### ISSUE TITLE
Client should remember what ids you use

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1]
if you frequently use an identity for a site, the UI should sort that id to the top of the list and perhaps tell you (id last used for this site 4 days ago)

the data to support this ui can be automatically gathered and need never leave the client.

**Comment by ghost** [comment]
I've verified this issue on Windows 7 with Firefox 7.0.1 and the current behavior is:
1. Load beta.myfavoritebeer.org in the browser.
2. Click on the Sign in button and log in to a BrowserID account with multiple email addresses associated to it (email1, email2, email3 etc).
3. Select email2 and log in.
4. Log out; select email 2 and log in.
5. Log out; select email 3 and log in.
6. Log out; click on the Sign in button and observe the emails list displayed on BrowserID dialog.

The last used email, not the more frequently used one is bolded. The order in the list has not changed. If the user logs out completely, then logs in again, no addresses are bolded.

Is this the desired behavior?

**Comment by shane-tomlinson** [comment]
@jbonacci - yes, this is the _last_ used email, not the most.  The order of the list should not change ever, as this will cause user confusion.  If the user logs out of BrowserID (a perceived corner case to begin with except for shared computers), we are wiping local data for the privacy of the user, otherwise anybody could come in and check out localStorage and see usernames->sites for other users.  There is no backend persistence at this time.
