### ISSUE TITLE
Feature request: Test Users for use in automated testing

### ISSUE THREAD

**Issue by AutomatedTester** [mozilla/persona#1012]
It would be great if we could have something like http://developers.facebook.com/docs/test_users/ where we can have automated tests create a test user and then use it when we are creating apps. Currently I am getting a number of regressions around my userflow after login and I cant automate my login since its all OSS on github.

**Comment by shane-tomlinson** [comment]
13:06
stomlinson
AutomatedTester - hey, thanks for filing that.  We spoke about it in our bug scrub yesterday - I was assigned the bug so I could ask you what the need was.  From reading over the facebook page, it looks like you need to have some test users and passwords set up so that you can use them.  Do you need to be able to create test users dynamically, or just be able to sign in to BrowserID with test users.

13:08
AutomatedTester
ideally have an API that creates them for us and returns them so we can use
or at  have a UI that allows us to create them and then use them
but API gets +10000000 from me 
what I am trying to get away from is creating throwaway accounts that, if someone decided to fubar my tests would still be ok
"throwaway accounts" === gmail account I dont care about
does that make sense?

**Comment by shane-tomlinson** [comment]
with personatestuser.org that @lloyd wrote, this can be closed.

**Comment by lloyd** [comment]
bullshit.  @jparsons wrote it :D
