### ISSUE TITLE
Move login to SRP

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#1014]
so that password is never even sent to the server.

**Comment by davidascher** [comment]
And by SRP he means; http://en.wikipedia.org/wiki/Secure_Remote_Password_protocol

**Comment by lloyd** [comment]
thanks davidascher.

**Comment by warner** [comment]
/me follows, this interacts-with/is-implemented-by the key-wrapping setup

**Comment by warner** [comment]
hrm, apparently I must say @warner to get this on my list?

**Comment by seanmonstar** [comment]
@warner theres a button at the bottom of this page: "Enable notifications for this issue"

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
