### ISSUE TITLE
IE8 Compatibility View: unsupported_dialog could give better guidance to user

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1050]
If you run IE8 in Compatibility View (Tools->Compatibility View), the sign_in dialog says:

  """We're sorry, but currently your browser isn't supported.
  BrowserID works with Firefox and other modern browsers."""

So yeah that's true. Not in compatibility mode, but that message could perhaps check for this mode on IE8 and let the user know that in this case, they can use IE8 if they switch out of Compatibility View.

**Comment by shane-tomlinson** [comment]
closely related to #803.

**Comment by shane-tomlinson** [comment]
@jrgm  - Excellent suggestion - here is an MSDN article on checking for compat mode in IE8

http://msdn.microsoft.com/en-us/library/cc288325%28VS.85%29.aspx#GetMode

**Comment by skinny97214** [comment]
I'm leery of saying anything using the words "compatibility view" in any user-facing strings. We can put that in the (read more) section for those that need it.

**Comment by shane-tomlinson** [comment]
Link to #1634

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
