### ISSUE TITLE
CSS should support RTL locales

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1066]
With Issue 1065, we have our first right to left (RTL) language 'he'.

Most languages are left to right (LTR) such as English. On RTL locales, we want the entire page design to be mirrored.

We put the following in the HTML to trigger the CSS:

```
<html lang='he' dir='rtl'>
```

To see how this works, compare https://addons.mozilla.org/en-US/firefox/ to https://addons.mozilla.org/h/firefox/

Notice the entire page layout is flipped. en-US has Secondary Navigation on the left, he has it on the right... etc.

We need additional CSS code to supports RTL layout.

@ozten is happy to mentor new contributors in fixing this issue.

**Comment by shane-tomlinson** [comment]
@skinny97214 - What do you think about removing the left to right arrow slide?  It really offers no benefit to the user besides a bit of eye candy.

**Comment by skinny97214** [comment]
I'd like to keep it, especially if we can use it in place of a spinner to indicate progress. Can we reverse it for RTL locales?

**Comment by shane-tomlinson** [comment]
@skinny97214 - we don't actually use it to indicate progress - it is only used to indicate "the process is done" - which delays the user signing in by a second or so.  The slide effect cannot be done during key generation (which is the slow part that comes before it, for which we show a wait screen) because key generation is synchronous and does give up any processing time to do any UI updates.

**Comment by zaach** [comment]
This is a more general case of #873

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
