### ISSUE TITLE
BrowserID should detect a stale include.js

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1089]
Spun off of Issue#226.

It's possible websites will deploy a copy of include.js instead of linking a script tag to browserid.org.

We should detect this situation and ...

**Comment by benadida** [comment]
I suggest waiting until early summer to do this kind of versioning support. At least until we've agreed on the events api :)

**Comment by zaach** [comment]
@benadida time to readdress this?

**Comment by benadida** [comment]
@zaach do you think we can easily address this? If so, great, but I'm wondering if that's a post-beta task.

**Comment by lloyd** [comment]
+1 to post-beta1

**Comment by shane-tomlinson** [comment]
@lloyd, @benadida - If we keep pushing this back, does it really deserve a 4_?  Would 3_s suffice?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
