### ISSUE TITLE
enable back button in the popup

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1091]
Users will click the back button, especially on mobile where we can't (and shouldn't) hide it in the chrome. Intercept the back and make it take the user to a useful previous step.

**Comment by shane-tomlinson** [comment]
I suggested this in #277 and got pushback.  I still think this is a good idea, though it is going to require some changes to the front end.

**Comment by sawyerh** [comment]
@shane-tomlinson / @skinny97214 - I see there are now cancel buttons in the design (http://d.pr/i/D0Ky), was this a proposed solution to the undo/back functionality you were looking for?

**Comment by skinny97214** [comment]
No, we want to support full back button so we can expose it in the browser frame. Currently it's hidden.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
