### ISSUE TITLE
The establishing relay error occurs every time the user restarts Firefox with the "Show my windows and tabs from last time" option set

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1121]
OS: Windows 7
Browser: Firefox 11.0

STR:
1. Launch Firefox.
2. Set the "When Firefox starts:" option in Tools->Options to "Show my windows and tabs from last time".
3. Load a BrowserID client in the browser.
4. Open the BID dialog from the client.
5. Close the browser window (don't close the dialog, it will close automatically with the main window).
6. Launch Firefox again.

The BID dialog is reopened when restarting Firefox but every time this happens, the establishing relay error message is displayed.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
