### ISSUE TITLE
The "This field must be an email address." error message is displayed when trying to sign up with and email address longer than 74 chars

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1172]
OS: Windows XP
Browser: Fx 11.0, Fx 13.0, IE8, Chrome 17.0.963.56

STR:
1. Load a BID sign in/up page in a browser (any dev, stage or prod server page or BID dialog).
2. Enter an email address longer than 74 chars.
3. Click on the button for signing in/up.

The "This field must be an email address." error message is displayed. If the user reduces the number of chars to 74, everything seems to work ok. 

Even if 74 chars would be the maximum allowed, the displayed message is erred since the entered string had the format of an email address. A more accurate message should be displayed (e.g. "Use an email address of at most X characters").

**Comment by shane-tomlinson** [comment]
@ioanab - the criteria for an email address are:

1) total address allowed to be 254 bytes long
2) local side only allowed to be 64 bytes long
3) domain side allowed to be up to 253 bytes long

The RegExp we use for validation is taken from http://blog.gerv.net/2011/05/html5_email_address_regexp/
with the addition change that there must be a ldh-str (.com, .net, .org, .cz, .uk, etc portion) because BrowserID addresses are for the moment required to be SMTP addressable.

**Comment by lloyd** [comment]
desired behavior!  not a bug, we're inline with the spec.
