### ISSUE TITLE
Login doesn't work in an iOS Home Screen web application

### ISSUE THREAD

**Issue by jalada** [mozilla/persona#1198]
If I make a website a home screen web app in iOS using:

```
<meta name="apple-mobile-web-app-capable" content="yes" />
```

When I go to log in with BrowserID on that web app, it appears to hang on 'Communicating with server'.

**Comment by zemirco** [comment]
I have the same issue. The popup window stays at **Connecting to Persona**.

Any news on this?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
