### ISSUE TITLE
The diresworb.org home page displayed both the Account Manager and "Connect with BrowserID..." sections when all the cookies are disabled

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1201]
OS: Windows 7
Browser: IE9, Firefox 11, Firefox 13

STR:
1. Disable all the cookies (the issue doesn't reproduce when only 3d party cookies are disabled).
2. Load https://diresworb.org/ in the browser.

The diresworb.org home page displayed both the Account Manager and "Connect with BrowserID..." sections. 

The issue reproduced with a fresh Firefox profile; the language settings were not changed from default. When re-enabling cookies and refreshing the page, it looks fine.

**Comment by lloyd** [comment]
fixed in stage. see GH-835

**Comment by aleksejrs** [comment]
With Firefox 10.0 and 11.0b6 for Linux x86_64, this happens if I set  Privacy → Use custom settings for history → Keep (cookies) until: to “ask me every time”. Firefox doesn’t ask anything. It works if I add an exception for diresworb.org.

When I enter an e-mail address on http://myfavoriteshow.org/, it says “verifying email address...”, but no pop-up window appears.

**Comment by shane-tomlinson** [comment]
@lloyd - I am trying to think of some solutions to this problem.

1) We could render the correct DOM on the backend avoiding the use of JS to show/hide content.
2) We could have a separate /manage page that the user is redirected to from "/" if the user is authenticated.  This may help with SEO of the initial content on the main site - search engines may currently be blocked from seeing any content that is displayed using JS.
3) We could ignore the "cookies disabled" check on the main page when checking the user's session_context status.

Thinking about #1, is there a way I can know whether the user is authenticated to BrowserID whenenver writing the initial server-side EJS  templates?  If I know the user's authentication status (including their email address), I can avoid the user seeing both the account manager and "connect with browserID" sections.  Writing the correct DOM on the server would help with the perceived speed of the initial page load because only the correct content would be visible.

Doing this would mean either not caching the "/" page for the user or updating the etag any time the user's status for this page changes.

#2 seems a slightly cleaner option, I've never liked having both the intro page and the manage page under the same URL, it goes against the idea of URLs.  If the user lands at "/" and is logged in, 302 them to "/manage"

#3 - ugh.  Just feels dirty.

**Comment by jrgm** [comment]
Verified for stage train-2012.04.11 with these notes: 
1. Load https://diresworb.org
2. Load https://diresworb.org/signin and begin typing in an email address
3. Try to submit the email address for /signin
4. Load https://diresworb.org/signup and begin typing in an email address
5. Try to submit the email address for /signup
6. Load https://diresworb.org/forgot and begin typing in an email address
7. Try to submit the email address for /forgot
8. Load http://beta.myfavoritebeer.org
9. Click 'sign in' to bring up the dialog.

Checked Ubuntu (Opera/11.62, Firefox/11.0, Chrome/18.0), Windows (IE8, IE9,
Opera/11.62, Firefox/11.0, Chrome/18.0, Safari/5.15), OSX (Opera/11.62,
Firefox/11.0, Chrome/18.0, Safari/5.15), Android ICS (Stock, FF11, Aurora),
Android 2.2 (Stock, FF11, Aurora).

Normally, I get this behaviour in most browsers
Works fine for 1,2. No duplicate/missing UI. 'Requires cookies' error message at 3.
Works fine for 4, 'Requires cookies' error message at 5.
Works fine for 6, 'Requires cookies' error message at 7.
Works fine for 8. Dialog shows 'requires cookies' at 9.                

The exceptions are:
0. GH-1418 already exists to not let the user use them when cookies are not enabled.
1. GH-1484 - Chrome throws exceptions at step 4 and step 6.
2. GH-1485 - IE8 WinXP: the error message is shown over a black (not just dimmed) background with IE8.
3. Safari 5.1.5 (Windows/OSX): At step 7, safari has an interesting bug/quirk. If you disable cookies
   in Safari but already have a cookie from diresworb.org, Safari will transmit that cookie with a
   request. So, if you have the cookie, but have now disabled cookies, the /signup page will
   successfully call /stage_user. But then with no new cookies accepted, the UI moves to the /signin
   page (?), and doesn't display the normal response to a successful call to /stage_user. If you don't
   already have a cookie from diresworb, and cookies are disabled, behaviour on the /update page is
   similar to other browsers (error message when you try to submit a user to /stage_user).
