### ISSUE TITLE
Duplicate strings in messages.po and client.po

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1208]
The following strings are located in both, messages.po and client.po files, which means localizers have to translate them twice. Is it possible to store them only in one file?
- Please close this window, <a %s>enable cookies</a> and try again
- BrowserID requires cookies

**Comment by ozten** [comment]
We cannot easily do this. The server side software uses the messages catalog, while the client side code uses the client catalog.

We have a few options, all of which require development work:
1) Re-write feature to only display strings via client code for this Cookies message
2) messages.json is available, add code so that the dialog adds it via a script tag, remove string from client side code

#2 is error prone and fragile.

Let's do #1, but we probably won't get to this for a few releases.

**Comment by mathjazz** [comment]
Thanks for clarifying. 

No need to proceed with this. If we have to translate twice for the next release, removing strings from one file afterwards doesn't make so much sense anymore.
