### ISSUE TITLE
build a mediawiki plugin to support BrowserID

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#1229]

**Comment by shane-tomlinson** [comment]
@benadida - I looked into doing this last year and ran into a roadblock that I had no obvious solution for - currently there is no way of retrieving a user account by email address.  To confirm this was a really a problem, I had a chat with a Wikipedia developer at MozFest - he confirmed my suspicion.  The reason, he explained, is because email addresses are optional in Wikimedia.  I did not pursue the plugin further due to time constraints. 

Any developers interested in writing this plugin - it'd be awesome!  Just be aware that as of Nov 2011 (not sure of the current state), a method is needed to retrieve accounts by email.

**Comment by shane-tomlinson** [comment]
Please see: https://github.com/stomlinson/browserid_mediawiki_extension

**Comment by seanmonstar** [comment]
closing this. if it's still a problem, please reopen.
