### ISSUE TITLE
improve feedback from frontend tests running under phantom

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1244]
this depends on pull request 1242 being merged.

Once merged, you'll notice that running frontend tests under phantom results in a longish pause (~2m), followed by a pile of test output.  it would be better to have incremental output for faster results.

**Comment by ozten** [comment]
Speaking of lots of output, I missed a test failure because the very end of my output says:

Tests completed in 65517 milliseconds.
983 tests of 983 passed, 0 failed.
· · · ✓ OK » 7 honored (70.575s)
npm ERR! browserid@0.0.1 test: `./scripts/test`
npm ERR! `sh "-c" "./scripts/test"` failed with 1
npm ERR! 
npm ERR! Failed at the browserid@0.0.1 test script.
npm ERR! This is most likely a problem with the browserid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/test
npm ERR! You can get their info via:
npm ERR!     npm owner ls browserid
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.32-34-generic-pae
npm ERR! command "node" "/usr/local/bin/npm" "test"
npm ERR! cwd /home/ozten/Projects/browserid
npm ERR! node -v v0.6.6
npm ERR! npm -v 1.1.0-beta-4
npm ERR! code ELIFECYCLE
npm ERR! message browserid@0.0.1 test: `./scripts/test`
npm ERR! message `sh "-c" "./scripts/test"` failed with 1
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ozten/Projects/browserid/npm-debug.log
npm not ok

I couldn't find any failures in scrollback, so I committed. Even now, I've fixed my two test breakages and think I'm green, but the `npm test` command ends with the same ouput :?

**Comment by shane-tomlinson** [comment]
closing as dup of #1326 which has been fixed.
