### ISSUE TITLE
undescriptive error when assertion is malformed

### ISSUE THREAD

**Issue by michielbdejong** [mozilla/persona#1250]
when posting a malformed assertion (i accidentally prepended the string 'undefined' to it) I got:

```
{"status":"failure","reason":"ReferenceError: InputException is not defined"}
```

back from browserid.org/verify. this looks like something from the bowels? maybe it should say "reason":"assertion is malformed", so that it's easier for RP devs to debug what happened

**Comment by lloyd** [comment]
what's an example malformed assertion?

**Comment by michielbdejong** [comment]
well, say the string 'ASSERTION' is what you're supposed to send, then i
was sending 'undefinedASSERTION'

On Thu, Mar 8, 2012 at 6:10 PM, Lloyd Hilaiel <
reply@reply.github.com

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
