### ISSUE TITLE
Ensure no client cache incompatibility with issue912

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1323]
This might be hard to reproduce....

1) Use branch of the site that is pre-issue912
2) Switch to issue912 branch
3) Using RP example page, click 'Get an Assertion'

Expected:
Normal dialog flow

Actual:
'BrowserID requires cookies' error screen

Workaround - Clearing my browsers cache via Aurora Preferences > Network > clear

This indicates some client caches may have the same name (cookies, localStorage, etc) and we have a migration issue to look for.

**Comment by ozten** [comment]
Closing - root cause will be fiex in Issue 1331

via IRC

9:37 AM <stomlinson> 1) checkout 1943fac9c284ff5a798229b206c648b59d641264

9:37 AM <stomlinson> 2) start server

9:38 AM <stomlinson> 3) open dialog

9:38 AM <stomlinson> (at this stage, everything acts as it should)

9:38 AM <stomlinson> 4) checkout issue912

9:38 AM <stomlinson> 5) restart server

9:38 AM <stomlinson> 6) open dialog

9:38 AM <stomlinson> (at this stage, the cookie error shows)

9:38 AM <stomlinson> to fix:

stomlinson> 7) edit resources/templates/dialog.ejs and add a space

9:38 AM <stomlinson> 8) restart server

9:39 AM <stomlinson> 9) open dialog

9:39 AM <stomlinson> (at this stage, everything works as it should)

**Comment by shane-tomlinson** [comment]
I believe this is a dup of 1331 because of the following series of steps:

1) checkout 1943fac9c284ff5a798229b206c648b59d641264
2) start server
3) open dialog
(at this stage, everything acts as it should)
4) checkout issue912
5) restart server
6) open dialog
(at this stage, the cookie error shows)
7) edit resources/templates/dialog.ejs and add a space
8) restart server
9) open dialog
(at this stage, everything works as it should)

By setting a breakpoint in network.cookiesEnabled in the catch portion of the try catch, after stage 6 I see the following error thrown:
`module constructor missing for is_this_your_computer`

This means the JS for the is_this_your_computer service is missing, meaning the resource is either not being requested or is unavailable.  Looking at the list of included resources, the file is not being requested.  The old HTML is used.  Etags are out of date.

Adding a space to dialog.ejs causes the etag to be updated and all resources to be included.

This does expose a problem with network.cookiesEnabled.

If the callback throws an exception when called when cookies are enabled, the callback will then be re-called with a false status.  Not nice.  See issue #1339
