### ISSUE TITLE
Scrollbar is not obvious in landscape mode; 'Sign in' button not visible

### ISSUE THREAD

**Issue by krupa** [mozilla/persona#1325]
Stock browser/ Android 2.2

Steps to reproduce:
1. Hold the phone in landscape mode (This is important since things work fine in Portrait mode).
2. Load https://marketplace-dev.allizom.org
3. Log in using a BrowserID account which has multiple email ids associated with it.
4. Select an email id with which you want to log in with.

expected behavior:
There is a 'Sign in' button for people to click

observed behavior:
In landscape mode, the 'Sign in' button is below the fold and users need to scroll to be able to view this. However, the scrollbar is not obvious and is shown only when people try to scroll.

**Comment by sawyerh** [comment]
@skinny97214: 

Proposed design solution:
- Currently: http://d.pr/i/4JvG and http://d.pr/i/jqnG
- Proposed solution: http://d.pr/i/WIWB (at least for landscape)

**Comment by skinny97214** [comment]
Can we shorten the input enough to slide in the [next] button to its right?

**Comment by sawyerh** [comment]
@skinny97214 Something more like this (http://d.pr/i/b13C)? Are you aware of any button labels that are longer than 4 characters (next, done, back)?

**Comment by skinny97214** [comment]
Yah, that's more of what I was thinking. We should check with Matej to see
what the worst case localization is. I do prefer this one if it can work in
all locales. Can it wrap to the line below if it exceed a certain width?
Need some schmancy detection I'm guessing.

**Comment by sawyerh** [comment]
@skinny97214 - If the problem we're trying to solve is the button not being immediately visible, the small button won't always work for screens that have multiple fields or screens that have a lot of text above the fields (example: http://d.pr/i/NExy). This is an alternative to the original solution I posted - http://d.pr/i/31ys

I'm not sure if the button being "below the fold" is a major issue though — people tend to know how to scroll the window. Plus, both solutions proposed won't work for screens in portrait mode when we only have 320px to work with. The button would have to flow below the fields again.

**Comment by skinny97214** [comment]
@sawyerh I agree the "below the fold" isn't the worst issue. I do think it's ideal if it's above in landscape, but not 100% required for every screen given all our other constraints. My prediction is that if it looks horrible in landscape, most users will rotate to portrait. Incidentally, I'm moving toward having only one password field, so that page will get better on mobile.

The blue arrow is promising but I'm not convinced it's actionable enough. I wouldn't be comfortable launching this without user testing it. It also doesn't support cancel.

So... what do? Make the font the _right_ size. Don't go to tiny crazy. I don't have a device on hand to test this out, so I'll have to rely on your good judgement here. Make the cancel and next buttons on the next line from the label because of the localization concerns. Even if the top button just peeks up above the fold, it'll help users know to scroll.

**Comment by sawyerh** [comment]
Hm, tweaked the sizes a bit (https://github.com/mozilla/browserid/pull/1949). Since there's now another line of text above the email label, the button still won't show in landscape (http://d.pr/i/yeUa). This isn't a big deal to me. Portrait looks fine (http://d.pr/i/xPUE), and I'd suspect this is the common orientation that people will be holding it.
