### ISSUE TITLE
add :response-time to format 'default_bid' in lib/custom-logger.js

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1327]
Followup from GH-1255. Somewhere along the way the intended addition of :response-time to 'default_bid' got dropped from the landing.

**Comment by ozten** [comment]
Fixed in http://git.io/glbmQg

Before:
browserid (11715): info: 192.168.186.1 - - "GET /wsapi/session_context HTTP/1.1" 200 193 "http://192.168.186.138:10002/sign_in" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:13.0) Gecko/20120329 Firefox/13.0a2"

After:
browserid (11753): info: 192.168.186.1 - - "GET /wsapi/session_context HTTP/1.1" 200 3 193 "http://192.168.186.138:10002/sign_in" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:13.0) Gecko/20120329 Firefox/13.0a2"

(3 milliseconds shows up right after http status code 200)

**Comment by jrgm** [comment]
Ugh. I'm regretting filiing this bug. I don't see this on either the webheads or the dbwriters. Is it some config bit that is not in production?

**Comment by zaach** [comment]
It looks like the bit is set correctly in production.json. Reopen if this is still a problem.

**Comment by jrgm** [comment]
So, um reopening. I cannot see production logs. But I can see stage logs (but not stage config which is annoying to me).

But a typical log line for browserid.log sez:

```
{"level":"info","message":"127.0.0.1 - - [Wed, 01 Aug 2012 05:26:42 GMT] \"GET /wsapi/session_context 
HTTP/1.1\" 200 214 \"-\" \"-\"","timestamp":"2012-08-01T05:26:42.427Z"}
```

214 is the response size.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
