### ISSUE TITLE
etag of sign_in does not correctly update in all circumstances

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1331]
Link to issue #403

On Stage, the etags of /sign_in only gets updated if dialog.ejs is updated.  If only dialog_layout.ejs or only the included JS are updated, the etags are not updated meaning the old content will be delivered to the user.

**Comment by lloyd** [comment]
re-opening this issue, because it is not yet fixed in dev, 5 star label still appropriate because it would block the wed. train from getting cut (@jbonacci - for reference, we hotfixed with a minimal patch, then rounded back in dev and are trying to do the right thing in pull request #1338)

@ozten will close this at PR merge time into dev, provided he doesn't find any more gaping holes in my fix :)
