### ISSUE TITLE
"BrowserID is the fast and secure way to sign in — learn more" is not translated in all the languages supported by BID

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1337]
OS: Windows 7
Browser: Firefox 13.0 Aurora
Language: Finnish, Italian

STR:
1. Load http://beta.myfavoritebeer.org/ in the browser.
2. Click on the Sign In button and sign into an account.
3. Observe the dialog footer.

"BrowserID is the fast and secure way to sign in — learn more" is not translated.

I checked and this issue doesn't reproduce in German, French and Swedish.

**Comment by mathjazz** [comment]
Finnish has a fuzzy string, which means localizers have to update their translation to match the original string. Until they are 100% complete, we're not shipping Finnish.

Italian looks ok, but it was only updated today. Perhaps server needs to refresh?
http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/locale/it/LC_MESSAGES/messages.po

@ozten, can I check the italian JSON language file on the beta server somewhere?

Also, should I start pointing localizers to http://beta.myfavoritebeer.org/ instead of http://temporary_preview.myfavoritebeer.org/?

**Comment by ozten** [comment]
No need to commit the JSON files. You can check them at:
- stage (beta.myfavoritebeer.org) is at https://diresworb.org/i18n/it/client.json for 'it'
- temporary_preview is at https://temporary_preview.hacksign.in/i18n/it/client.json

I apologize, the official l10n preview server has slipped again, hoping for building it out by end of this week.

We should continue to use temporary_preview.

**Comment by mathjazz** [comment]
Italian messages.json looks good:
https://temporary_preview.hacksign.in/i18n/it/messages.json

The string is in and translated.

Any idea why it doesn't show up on the server?

**Comment by ozten** [comment]
Please try again, I see BrowserID è un modo sicuro e veloce per identificarsi sui siti web — per saperne di più

**Comment by mathjazz** [comment]
Works for me in production.
