### ISSUE TITLE
optimize RP page load time with new APIs

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1351]
Given that the new APIs we're landing will include more resources at RP load time, we should spend some time optimizing page load times.  Concretely, the "communication iframe" will be placed in the user's dom at the time they interact with browserid's APIs, often around or before the DOM is loaded.

The two things we should explore are:
1. remove unused resources from vepbundle (~30% of cost)
2. remove our depenency on jquery (another ~30% of cost)

This work should be done before we start talking about the new APIs, probably before april 11th.

/cc @ozten @shane-tomlinson @benadida

**Comment by shane-tomlinson** [comment]
@jbonacci - this should be closed.  The main problem is the communication_iframe included jQuery, which was 135kb.  Within the communication_iframe, the only part of jQuery that we used was the ajax functionality.  Since we perform no DOM manipulation from the communication_iframe, the rest of jQuery was wasteful.  We have since removed jQuery from the communication iframe and added micrajax which saves a considerable number of KBs.  Closing as fixed.
