### ISSUE TITLE
Form does not always submit when hitting "enter" in password field in IE8

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1376]
STR

1) Load up myfavoritebeer.org in IE8
2) Open dialog, if signed in, sign out.
3) In email field, type in known email address, press enter
4) In password field, type in password, press enter.
5) try pressing enter again.

Nothin'

Expected - form is submitted.

**Comment by shane-tomlinson** [comment]
Took out the "fix" because it caused a double submit in Firefox and Chrome.  Grrr.

**Comment by seanmonstar** [comment]
We could add a timeout if the key is enter, and cancel the timeout in submit, so that the timeout makes the submit happen in IE, and good browsers cancel the timeout and submit once.

Yeck, I feel the need to sacrifice a few kittens after having written that sentence.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
