### ISSUE TITLE
SCL2 account deletion returns a 503

### ISSUE THREAD

**Issue by krupa** [mozilla/persona#1381]
steps to reproduce:
1. Go to https://browserid.org
2. Sign in using valid credentials
3. From the Account Manager, delete your account

expected behavior:
Account deletion is successful

actual behavior:
There is an error message and server returns a 503. See http://cl.ly/103j0Q2O0z0S2L271k0G

atoll, petef and jbonacci have more detailed info regarding this issue.

**Comment by floatingatoll** [comment]
Relevant dbwriter error log:

{"level":"error","message":"unexpected database failure: Error: Cannot delete or update a parent row: a foreign key constraint fails (`browserid`.`__old_email`, CONSTRAINT `__old_email_ibfk_1` FOREIGN KEY (`user`) REFERENCES `user` (`id`)) -- at reportErr (/opt/browserid/lib/db/mysql.js:526:38)","timestamp":"18 Mar 01:49:32"}

**Comment by fetep** [comment]
see https://etherpad.mozilla.org/8LOQ9q6fgb for full details.  basically, `__old_*` tables were lying around from the last schema change (2012-01-12) and had foreign keys into user.  when a user who had an older email in __old_email went to cancel their account, we delete emails from the live email table, then try to delete the row from user, which failed because of the foreign key constraints from __old_email.  we dropped the `__old_*` tables everywhere in prod, and updated our docs so this won't happen again after the next schema change.

leaving this bug open, need to go poke at stage databases to make sure they don't have any __old_\* tables lying around, too.

**Comment by fetep** [comment]
fixed in stage
