### ISSUE TITLE
Redirect /sign_in to /signin (or homepage)

### ISSUE THREAD

**Issue by krupa** [mozilla/persona#1382]
steps to reproduce:
1.  Load https://browserid.org/sign_in

expected behavior:
When users navigate to non-existent or obsolete pages, we show a 404 (with a link to homepage) or redirect to the newer page.

actual behavior:
We show an error message which is not very informative to the user. See http://cl.ly/0w3g1W132l2e2J2E010D

**Comment by floatingatoll** [comment]
krupa found the /sign_in url in Firefox Awesomebar, which led to discovering this issue. We don't publish direct links to /sign_in anywhere and normal user sign-in process works.

I checked and Google indexes browserid.org/sign_in, but does not return it in the results for "browserid sign in" that I can see. Had to search for "browserid.org/sign_in" to get it to show up.

**Comment by jrgm** [comment]
@jbonacci see also GH-1121

**Comment by csuciu** [comment]
Test case added https://moztrap.mozilla.org/manage/caseversion/23913/

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
