### ISSUE TITLE
log timestamp missing year

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/persona#1383]
```
{"level":"error","message":"unexpected database failure: Error: Cannot delete or update a parent row: a foreign key constraint fails (`browserid`.`__old_email`, CONSTRAINT `__old_email_ibfk_1` FOREIGN KEY (`user`) REFERENCES `user` (`id`)) -- at reportErr (/opt/browserid/lib/db/mysql.js:557:38)","timestamp":"31 Jan 10:35:48"}
```

the "timestamp" in the above log entry is missing the year, which isn't a problem yet, but will be in a few months.

**Comment by floatingatoll** [comment]
The above logline was from an on-disk logfile, if that matters for tracing the issue in winston.

**Comment by ozten** [comment]
Attempted fix in http://git.io/pxDJlg
I'm assuming this log line is from dbwriter.log and I see `"timestamp":"2012-04-19T01:23:01.412Z"` after this patch.

Please confirm in dev if you can. Thanks!

@anuragphadke - Heads up the timestamp in all metrics logs will be changing to have a full timestamp.

**Comment by jrgm** [comment]
Hmm, actually I was going to comment that I think that patch is wrong and has no effect. The main log files have been using ISO timestamp fields since 2012-03-15 in production. This patch was for metrics logs which still show as UTC strings. Shouldn't the 'timestamp' in the patch be an argument to the winston.transports.File constructor? But anyways, 
I think the right way to switch to ISO timestamps in the metrics.log is to change the line 'entry.at = new Date().toUTCString()' in lib/metrics.js and not add the redundant timestamp field.

**Comment by floatingatoll** [comment]
I confirmed that between 8 Mar and 15 Mar, staging BrowserID error logs switched to ISO formatted UTC strings.  So I'm happy as of March 15th, 2012, however that change was achieved.

**Comment by jrgm** [comment]
Oops, I said production but meant stage (since I can't see production anyways).
