### ISSUE TITLE
The "You must sign in with your email provider..." dialog hangs when loosing the internet connection

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1404]
OS: Ubuntu 11.10
Browser: Firefox 12.0 beta

STR:
1. Load http://beta.myfavoritebeer.org/ in the browser.
2. Click on the Sign In button.
3. Enter a primary email address and click on the Next button.
4. Loose your internet connection while on the "You must sign in with your email provider..." dialog.
5. Click on the Verify button.

The dialog from step 4 hangs until the user manually closes it. The status bar keeps displaying "Waiting for eyedee.me..." even after the internet connection has been restored.

**Comment by csuciu** [comment]
This issue still occurs on:
OS: Ubuntu 12.04
Browsers:  FF 14.0.1, Chrome 21.0.1180

**Comment by csuciu** [comment]
Test case added https://moztrap.mozilla.org/manage/caseversion/23912/

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
