### ISSUE TITLE
If "dom.storage.enabled = false" BrowserId claims browser not being Firefox

### ISSUE THREAD

**Issue by klebom** [mozilla/persona#1407]
I tried disabling local storage (dom.storage.enabled = false) to avoid tracking (I use cookie culler and allow all cookies).

This wasn't expected by the BrowserId code base...

"
We are sorry, but currently your browser is not supported.

BrowserID works with Firefox

and other modern browsers.

BrowserID is the fast and secure way to sign in — learn more
"

I'm using Firefox 11

**Comment by shane-tomlinson** [comment]
@klebom - Thanks for the feedback!  BrowserID is not checking for Firefox, but instead is checking for the availability of window.localStorage, window.postMessage, window.JSON.  Since you have localStorage disabled, BrowserID does not think that your browser meets the minimum technical requirements and is asking you to upgrade - as a generic message we suggest Firefox.

We did not include text about the minimum technical requirements because that would confuse non-technical users.

Closing as by-design.

**Comment by hotzeplotz** [comment]
i think the error message as is is confusing for power users, on the other hand - i suggest that detailed requirements and possible causes for failure should be at least documented somewhere, with documentation linked from the Persona error page. it's ok to avoid going into details on the error page, but just suggesting that the browser is unsupported (even if a user is using Firefox) seems quite unhelpful to me
