### ISSUE TITLE
code licensing

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#141]
I propose the moz tri-license for everything?  cause that's how we roll?

**Comment by shane-tomlinson** [comment]
I am reading over the license info now, one statement that may possibly concern us (from http://www.mozilla.org/foundation/licensing.html):

Website Code

You may use the HTML and CSS files on www.mozilla.org or other mozilla.org websites for your web site - as long as you don't use the visual design or style (the colors, gradients, fonts, etc.). In other words, you can use the HTML and/or CSS code, but your page should not look like you took Mozilla's page and dropped in your logo. This does not grant you any right to use the trademarks, trade names, service marks, or trade dress of the Mozilla Foundation.

So, the code/window they are calling is hosted from a Mozilla property, so perhaps this does not apply.  But the statement "but your page should not look like you took Mozilla's page and dropped in your logo" is particularly the one that gets me.  They aren't taking our page, they are "requesting to use" our page and we display their logo.  Is this a conflict?

**Comment by vthunder** [comment]
Definitely should tri-license all our code.

Shane, as for the website bits, I don't see a conflict. Our pages are hosted by us, and we display the RP's logo, not the way around. RPs do display the "sign in" button, but that is not a trademark, I think.

**Comment by Seldaek** [comment]
I'd have preferred a MIT-style license, for such open project it sounds like a much better approach than confusing the hell out of people with three licenses, two restrictive/semi-restrictive and one not so broadly spread, which means you have to read and try to understand it, and given the length of it, that's barely possible for a non-lawyer.

**Comment by lloyd** [comment]
Yo @seldaek,

I agree with you, I'm a minimalist and license my personal projects with [ISC](http://en.wikipedia.org/wiki/ISC_license), simply because it's the simplest possible license that preserves what I care about, and is easy to understand.

So I did some asking around for you and what I got as a response was basically acknowledgement of the problem (complexity!), and a proposed solution of the MPL 2.0 which is in progress right now.  Here's why MPL 2 will make this better:

"the MPL 2, soon to be completed and hopefully adopted by the Mozilla project, eliminates a large class of these
problems. It's a single license, 50% shorter than the current MPL, written in easily-understood language with easy-to-comply-with terms. That is our planned solution.

http://mpl.mozilla.org/ tracks progress."

As soon as MPL2 is complete and ready we should move to that instead of a MPL1.1/GPL/LGPL tri.

I hope this is a satisfying answer,
lloyd

**Comment by Seldaek** [comment]
Well, MPL2 is still way too long IMO, but I have low tolerance for lawyer speech :)

My main problem though is not that it's long, but rather that it's not very known. When I hear BSD, GPL or MIT, I know what it means, and I suspect most open-source engaged people would too. When I hear MPL, my brain is blank. Same goes for ISC, though that one is short enough that I can bother reading it.

Anyway, it's not a huge deal, as long as the MPL is a truly free (that excludes GPL class license in my books) license, I'd be happy. The thing is I still don't know if it is.

I just feel that something like BrowserID, if it were to become an essential building block of the web - and I sure hope it does - should be in the public domain, or at most MIT/BSD-licensed. Otherwise this is not much better than relying on Facebook Connect.
