### ISSUE TITLE
internal API needs updated for new API.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1416]
The internal API used by addons, pancake, OWA, etc needs to be updated to provide the same functionality given to RPs

**Comment by benadida** [comment]
yes, and it needs some key-wrapping love, too :)

**Comment by lloyd** [comment]
yes, and it needs some documentation love, too.  Also a sample usage, maybe a simple chrome extension would be useful?  Or maybe a cmd line program that can raise the prompt for you?

**Comment by lloyd** [comment]
let's figure out what the right internal API is for all the people it serves, and people it could.

**Comment by lloyd** [comment]
started fleshing out requirements for the internal API with anant: https://id.etherpad.mozilla.org/35

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
