### ISSUE TITLE
400 Bad Request: requires authentication response for POST /wsapi/cert_key                                                                  

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1445]
This one is hard to reproduce, but I've done it 6 or 7 times now. Following the STR below (I doubt it only happens this way,
but that's what I was doing). I get a 400 response if the requests to /wsapi/complete_email_addition, /wsap/email_addition_status, /wsapi/list_emails, /wsapi/cert_key are closely grouped in time.

  We are very sorry, there has been an error!
  Please close this window and try again.
    Action: Getting Assertion
    Network Info: POST: /wsapi/cert_key
    Response Code - 400
    Response Text: Bad Request: requires authentication
    Error Type: Bad Request: requires authentication

Steps to reproduce:
1. Go to http://beta.myfavoritebeer.org/ and click signin.
2. If already authenticated, click 'This is not me'.
3. Enter an @eyedee.me address you have never used before and complete the authentication.
4. Click logout on beer, and click signin again.
5. Enter a non-primary email address you have never used before, collect the email and load the add_email_address in the same browser. Enter a password twice for the user, but do not submit the form yet.
6. This is the hard part. I installed the HTTPFox addon so I could watch the requests for email_addition_status and time when I hit submit. If you time it right, you will get the 400. If not try again.    

Here's the sequence for hitting a 400 from HTTPFox (https://addons.mozilla.org/en-US/firefox/addon/httpfox).
(Columns are in order relative-timestamp, time-for-request, bytes-sent, bytes-received, method, result-code, mime-type, url)

00:06:56.515 0.039 916  248 GET  200 application/json https://diresworb.org/wsapi/email_addition_status?email=abcabdab%2Br27%40gmail.com
00:06:59.584 0.038 916  248 GET  200 application/json https://diresworb.org/wsapi/email_addition_status?email=abcabdab%2Br27%40gmail.com
00:07:02.640 0.048 916  248 GET  200 application/json https://diresworb.org/wsapi/email_addition_status?email=abcabdab%2Br27%40gmail.com
00:07:05.721 0.045 916  248 GET  200 application/json https://diresworb.org/wsapi/email_addition_status?email=abcabdab%2Br27%40gmail.com
00:07:08.324 0.073 997  299 GET  200 application/json https://diresworb.org/wsapi/email_for_token?token=lHeJdLLcKVTz2mqkQFICv9qza2EPzO3ER53g2PjtduAjaTH4
00:07:08.427 0.760 1126 258 POST 200 application/json https://diresworb.org/wsapi/complete_email_addition
00:07:08.799 0.047 916  272 GET  200 application/json https://diresworb.org/wsapi/email_addition_status?email=abcabdab%2Br27%40gmail.com
00:07:08.876 0.036 727  319 GET  200 application/json https://diresworb.org/wsapi/list_emails
00:07:08.977 0.036 1758 264 POST 400 text/plain       https://diresworb.org/wsapi/cert_key

**Comment by lloyd** [comment]
Here's a reworded sequence of events that explains what happens in the failure case (hypothesis):
1. you authenticate a session with browserid via assertion (with a primary address)
2. you add a secondary email address to your account
3. in the process of completing the email addition, you choose a password for your account
4. you pass the password and verification token up via the `complete_email_addition` call
5. on the server, the verification secret is used to find the secondary email and add it to your account
   AFTER THIS POINT, IF `email_addition_status` IT WILL SAY THE EMAIL IS VERIFIED
6. on the server if we detect that this is the first secondary email added to a primary account, we go oand bcrypt your password
7. on the server, after bcrypting your password, we send a response with an updated session cookie to `password` authenticate you
8. the client gets the response to the `complete_email_addition` call with the new cookie
9. in the dialog, we get an `email_addition_status` call that says the email is added
10. in the dialog we initiate a cert_key call to certify a public key for the secondary address, this requires password authentication

NOW!  if steps 9 & 10 in the dialog occur _before_ step 8 on the verification page, then you get a 400 response to the cert_key call - because you're trying to certify a key for a secondary address which requires `password` authentication, but your session is still `assertion` authenticated.

**Comment by lloyd** [comment]
I could move step 8 before step 6 and drastically reduce the likelyhood of the race condition with minimal risk.

**Comment by jrgm** [comment]
I can give you the exact sets of headers and bodies for a failing sequence if that would help you confirm your hypothesis. 

One thing I don't get in your steps is "if steps 9 & 10 in the dialog occur before step 8". I'm not seeing 9 happen before 8 has completed (see the above HTTP response sequence).

**Comment by lloyd** [comment]
I'm assuming the timing there is when requests _start_, not when they complete.  Is that wrong?

**Comment by lloyd** [comment]
this is similar to what's happening in GH-1440.

Also, the change that triggered this is GH-1293, which decreased the cost of key generation, shortened the delay between 9 & 10 above, and made it more likely that 10 would occur before 8.

**Comment by jrgm** [comment]
Let me cross check the timing with NSPR logging to see if it's start or end times.

**Comment by jrgm** [comment]
So, yes, those are start times (like duh the UI actual says).

**Comment by lloyd** [comment]
above commit is merged into train 2012.04.11 - should mitigate the race condition.  issue #1451 is against dev and we should have a more thorough fix in time for the next train.

**Comment by jrgm** [comment]
Working for me on stage train-2012.04.11-7. Continuing with some other browsers, etc.

**Comment by jrgm** [comment]
Oops, didn't previously mark as verified. Okay, now I am.
