### ISSUE TITLE
dev RP with dev IdP: User returned to authentication page if cancels authentication with IdP

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1459]
STR

1) Ensure an account exists with one secondary address, one address from the example.domain IdP.  If authenticated to BrowserID, sign out.
2) If authenticated on example.domain IdP, log out.
3) Open BrowserID dialog, for email address, enter secondary address and password.
4) When dialog closes, reopen dialog so the email picker is displayed.
5) Select @example.domain address.
6) Click "Verify" to redirect to IdP.
7) Once redirected to IdP, click cancel.

Expected Result:
User is redirected to email picker.

Actual Result
User is shown the "enter email" screen.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
