### ISSUE TITLE
move the cancel account feature to be inside the email section

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1462]
On the management page, move the text

"You may at any time cancel your account."

to be shown only when the user clicks edit email address.

http://cl.ly/3u080O0O440u261P1Y0Y

**Comment by shane-tomlinson** [comment]
@skinny97214 

Two concerns I have here while experimenting with this.  It does not feel like "cancel your account" has a tangible link to "edit your email addresses".  Visually, it looks nice.  The second is, one of the goals for the beta are to have swipe events in the manage page for mobile devices.  The cancel your account link would be hidden from users who remove email addresses using swipe events only.

Perhaps we could put the "cancel your account" link visually under the email addresses but always show it?

**Comment by skinny97214** [comment]
[Delete this email account] is pretty similar to [delete this whole profile].

As for swipe events, I'm not in favor. Let's not make uncommon, irreversible actions that easy.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
