### ISSUE TITLE
Follow on from GH-1123: gracefully deal with no-op remove of already deleted account

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1463]
1. Use an account that has only one user associated with it
2. Sign in to diresworb.org to get the management page. 
3. Open diresworb.org in a second tab of the browser.
4. Click 'Your email addresses'->edit on both pages
5. In the first tab, click remove and ok the popup. Account is removed.
6. Now in the second tab, click remove on the same account. 

Expected: 
  Could more gracefully handle the no-op remove of the account, similar to the approach in GH-1123

Actual:
  Error dialog
    We are very sorry, there has been an error!
    Please close this window and try again.
      Action: Syncing Email Addresses
      Network Info: GET: /wsapi/list_emails
      Response Code - 400
      Response Text: Bad Request: requires authentication
      Error Type: Bad Request: requires authentication

**Comment by jrgm** [comment]
Still valid STR, but demoting to 1-star (from 2-star).

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
