### ISSUE TITLE
Confusing behavior displayed when cancelling an email addition and retrying to add the same email

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1469]
OS: All
Browser: All

STR:
1. Launch http://beta.myfavoritebeer.org/ in the browser.
2. Sign in.
3. Log out of the client and click on the "Sign In" button.
4. Click on the "Add another email" link.
5. Enter an email address and click "add".
6. Click on the "use another email address" link. Leave the dialog open.
7. Sign into your email account and click on the BrowserID verification link.
8. Go back to the BID Sign In dialog.
9. Enter an email address and click "add".

The user is signed in with the email address he wanted to add. A new verification email is sent and, when the user tries to reconfirm his email address, he can do it without any issues. On the Android 2.3 native browser, I also saw the "Check you email!" dialog displayed for 1-2 seconds after step 9.

This behavior is quite confusing for the user. A notification about the email address already being added should be displayed both at step 9 and when the user tries to reconfirm the same email.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
