### ISSUE TITLE
reduce "normal" certificate duration to 6 hours

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1470]
http://groups.google.com/group/mozilla.dev.identity/browse_thread/thread/22c20d92282788f2#

Let's give this a bit of time to sit on the mailing list to let folks weigh in before implementing, but tracking it here.  (it's one or two lines of code and some doc, so the gating factor ain't implementation cost)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
