### ISSUE TITLE
forgot password flow: The user can set his current password as his new password

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1474]
OS: Win 7
Browser: Firefox 13.0

STR:
1. Load http://beta.myfavoritebeer.org/ in the browser.
2. Enter a non-primary email address associated to BrowserID and click on the "next" button.
3. Click on the "forgot your password?" link.
4. Click on the "reset password" button.
5. Confirm the reset from your email.
6. Set the current password as your new password.

Actual Results:
The user can set his current password as his new password. Considering that a password change splits your account into two accounts, this behavior might cause a lot of unhappy users.

This behavior is also not consistent with changing your password from the Account Manager.

Expected Results:
Display a message to let the user know that that is his current password.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
