### ISSUE TITLE
API leakage for window.location.href email return_url and other state

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1502]
When working on bigtent, I didn't carry through the query string parameters which were originally sent into my auth url.

Example:
/sign_in?email=eozten%40yahoo.com&return_to=http%3A%2F%2F192.168.186.138%3A10002%2Fsign_in%23CREATE_EMAIL%3Deozten%40yahoo.com

After a few redirects, I end up back on /sign_in.

BrowserID's authentication_api.js depends on those fields to:
1) Send email into the callback for beginAuthentication
2) Redirect the user back to the return url once completeAuthentication is finished

Without these query string parameters ...
a) Callback is invoked without an email address 
b) Calling raiseAuthenticationFailure the page ends up i an infinite loop, continuously changing window.location to ''.

This is confusing for developers implementing primaries, as they don't expect this state to leak into the public interface

Suggestion: Can we maintain state in local storage or somewhere besides the querysting / hash?

**Comment by shane-tomlinson** [comment]
@ozten, @lloyd - Lloyd and I talked about storing this data in localStorage a long time ago but decided against it because we have a leaky abstraction no matter how we look at it.  This leakiness is due to the fact that we need to be able to handle multiple BrowserID windows open from the same RP without causing collisions.

Originally, I wanted to store this data in localStorage keyed on the RP's hostname/origin.  This will fail if two BrowserID windows are open to the same RP and both have to redirect to an IdP.  If the first window is redirected to an IdP when the second window 
redirects to its IdP, the first window will have its state wiped out.

Then I thought "well, we need a unique token for each window".  I thought about passing a unique token like we do for WinChan/IE, this token used to key into localStorage, but this in the end seemed nearly as leaky as just sending the entire state and not using localStorage at all.

On the IdP side, they should be using the URL verbatim as we send it to them, whether we are sending only /sign_in or /sign_in with extra info.  Depending on redirecting directly back to /sign_in is reaching inside of our abstraction when we make no guarantees that /sign_in will always be the URL they can redirect back to.

I am very much open to suggestions on how we can clean this up in a way that we can avoid collisions when multiple windows to the same RP are open.

**Comment by ozten** [comment]
> On the IdP side, they should be using the URL verbatim as we send it to them, whether we are sending only /sign_in or /sign_in with extra info. Depending on redirecting directly back to /sign_in is reaching inside of our abstraction when we make no guarantees that /sign_in will always be the URL they can redirect back to.

Good point. I happened to name my url /sign_in, which adds to the confusion. If the API said, before using authenticate_api.js functions, you must have the window on the original URL you were sent too... then that would make sense.

Maybe this is too much work for the beta and we can fix this down the road, but I think you can handle this on the client side without introducing new server pieces.

A transaction can be implemented. This would add complexity and take a while to build before it was robust and could be trusted, but you have a synchronization problem. One window could obtain a lock and the other could wait. Or you could let both go forward inside of a transaction and committing one might rollback the other, etc.

**Comment by ozten** [comment]
This will affect Project Tapas, would be great if we could fix this before the beta.

**Comment by shane-tomlinson** [comment]
@ozten - Let's have a chat about this.  I'm not keen on implementing a transaction model in the dialog before beta.

**Comment by benadida** [comment]
here's an idea that could be really simple, and I'm happy to help implement it: we can use window.name, as follows:
- before redirecting to IdP, browserid.org stores some parameters in its localStorage, keyed on a new uuid we'll call primaryFlowId.
- still before redirecting to IdP, browserid.org stores primaryFlowId in window.name
- window.name is readable by other content in that dialog, including our own JS auth library, so primaryFlowId can be read by navigator.id shim and sent over postMessage.
- multiple active popups will have different windows, thus different window.name values, thus we're good.

Possible security consideration: window.name is writable by the IdP, can things go bad? I don't think so.

**Comment by lloyd** [comment]
benadida | stomlinson | ozten: how about using sessionStorage (rather than localStorage) ?  doesn't that do _exactly_ what we want?
