### ISSUE TITLE
statsd config host and port not used by lib/statsd.js

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1516]
The config for host and port at 
https://github.com/mozilla/browserid/blob/dev/lib/configuration.js#L113

Doesn't get used in our js lib at
https://github.com/mozilla/browserid/blob/dev/lib/statsd.js#L26

**Comment by shane-tomlinson** [comment]
This will be fixed by https://github.com/mozilla/browserid/pull/3909.

See https://github.com/mozilla/browserid/blob/6aec2c05a2bebfded68753aa2685e44773e6eba8/lib/logging/statsd.js#L26-L31

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
