### ISSUE TITLE
code cleanup: validate vs sanitize

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1526]
We have two code libraries for checking input parameters, one interfaced programmatically, one interfaced declaratively.

We should move all of our input validation into a single file, and make input validation clear and concise in each implemented API.  One way to go about this would be to change:

```
exports.args = ['oldpass','newpass'];
```

for instance, to 

```
exports.args = [
 { name: 'oldpass',
   type: 'password'
   required: true
 }, 
 { name: 'newpass',
   type: 'password', 
   required: true
 }
];
```

Basically I suggest we extend the parameter validation of the wsapi framework we've got to perform type specific validation (emails, passwords, origins, etc), and make the way that individual apis interface it declarative - moving validation out of `exports.process`.

/cc @ozten @shane-tomlinson @benadida @fmarier 

Now, if we were really in a mood to yak shave we could build wsapi.js into a reusable framework for restful api development.  But my razor is a little dull right now.

**Comment by lloyd** [comment]
how do you guys feel about depending on https://github.com/chriso/node-validator ?

/cc @ozten @shane-tomlinson @benadida @fmarier @warner @zaach

**Comment by benadida** [comment]
looks good on quick overview, your call!

**Comment by ozten** [comment]
Same feedback here. Maybe sanity test performance before adding it extensively. Has a good amount of followers and forks.

**Comment by lloyd** [comment]
good point, @ozten.

I expect this will be a really cheap change to make - and I need it for some UX changes.  I'll investigate in a branch, get some numbers on perf, and if that looks good, serve up a PR to you two.

**Comment by warner** [comment]
seems reasonable. What I always look for is annotation at a code boundary which tells the reader what assumptions are safe for them to make about the incoming data. So an `exports.args` isn't a bad way to go. The place where these schemes usually get hung up is on the type language: how to distingush between strings, strings that are really interpreted as email addresses, strings that are really interpreted as unconfined HTML, etc. But fundamentally it's all about correctly telling the programmer that it's safe to ignore what goes on outside the walls, because this type-checking will always be enforced.

**Comment by fmarier** [comment]
I like your approach. The lack of consistency in input validation / sanitization is one of the things I picked up in my review of the WSAPI code.

**Comment by lloyd** [comment]
I have started this work in the `api_param_validation` branch, I should be able to complete it today and then do a quick performance comparison...  please have a peek and criticize as I go !
