### ISSUE TITLE
show name and photo in email picker

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1589]
a.k.a. contact card

skinny owes a mock for this. 
#880 is the tracker

**Comment by shane-tomlinson** [comment]
Closing this until we actually decide whether we are going to tackle this. We can re-open then.

**Comment by pythonmobile** [comment]
Please open this. We would love to have image avatar / Name of the person returned on the backend.

**Comment by randomfactor** [comment]
I'm "piling on" to indicate my interest. I mistakenly tried to file this at https://bugzilla.mozilla.org/show_bug.cgi?id=906720.

Mozilla Persona is EXACTLY what the internet needs. It needs to catch on like an Idaho brushfire. To make it more valuable, please add a user icon or jpeg image that can be associated with the user's email address.

Persona is awesome for the developer. It offloads the burden of the secure login from my application and eliminates the need for users to always type in yet-another-email-address-and-password. But then, I have to include upload of image files in my app so that I can show a user icon along with the user's verified email address or handle? Please do this for me so that I don't have to.  I just want something like <img src="https://icon.persona.org/username@wherever.com"> to show the user's image file that Mozilla uploaded and sized so that I don't have to write that functionality into my app.

Someone mentioned that this might violate privacy, but those who need the privacy should either 1) upload an image that does not compromise privacy, or 2) don't upload an image at all.

**Comment by eldelacajita** [comment]
I would love to have this feature, too.
