### ISSUE TITLE
Need @ and . checking for new email addresses

### ISSUE THREAD

**Issue by tonychung** [mozilla/persona#159]
I was able to type in "sldfjsdlkfj" into add a new email, and it took me to the Email Confirmation window.   We should catch invalid email ascii chars upfront.

Repro:
1) goto http://beta.myfavoritebeer.org/
2) launch browserID, and add an email
3) type in something without @ and .
4) Verify popup takes user to confirmation dialog step

Expected:
- inline error checking for invalid email missing . and @ symbols

Actual:
- takes user to confirmation dialog

**Comment by lloyd** [comment]
fixed by @stomlinson, you can verify the fix on https://beta.myfavoritebeer.org now.

We should add a note somewhere to verify proper email validation in both the "create browserid" case and "add new email" case across all browsers we support, because afaik @stomlinson is using some fancy forms stuff that might not work on all browsers?

this specific issue, though, is fixed.
