### ISSUE TITLE
[ie6,ie7] redirect https://login.persona.org to https://login.anosrep.org/unsupported_dialog

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1618]
Follow on from GH-1529, IE6 is viewable now, but there is a second scrollbar on the right, and a thick black line below the header. 

But IE6 (IE7) don't really work for most of the rest of this site (they can't ever really work), and perhaps we should just redirect all pages (except /tos and /privacy) to a simple static "upgrade your browser" page (the same way we do with the dialog).

**Comment by jrgm** [comment]
Update summary to reflect what should really be done. Good first bug.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
