### ISSUE TITLE
wsapi_client.js location should not be in main lib

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#1628]
Code that supports production services (browserid, verifier, etc) should be directly under `lib` or a sub directory of lib.

Some code, such as `lib/wsapi_client.js` is only used by supporting tools, such as `bin/load_gen`, `scripts/create_account`, or vows tests.

It would be best to move these out of lib to reduce confusion when contributors are first learning the codebase.

Suggested location: `tests/lib` as load_gen is a kind of test or `lib/load_gen` but it's used beyond just load_gen.

Actually, `lib/load_gen` might make sense under `tests/lib` also.

**Comment by ozten** [comment]
`lib/tools/` as a parent directory would be another way to roll.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
