### ISSUE TITLE
Browser support detection can fail without giving much information

### ISSUE THREAD

**Issue by almet** [mozilla/persona#1634]
At least two users reported me that they were having troubles using BrowserID, even when using Firefox. It turned out that for whatever reason, they were having their "dom.storage.enabled" pref disabled.

I see that the code in "/resources/static/shared/browser-support.js" can tell what's going wrong, but it doesn't seem to use it to give actual input to the users, which could help them to solve their problems.

**Comment by shane-tomlinson** [comment]
Link to #1878

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
