### ISSUE TITLE
implement final property names in API

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1643]
on list we've agreed:

privacyURL -> privacyPolicy

and 

tosURL -> termsOfService

This is the final planned _change_ to the new Observer API which becomes "stable" this train...

**Comment by jrgm** [comment]
This was for PR in GH-1644 and was merged and in train-2012.05.25. Closing this issue. On the Changlog list to verify this train.

**Comment by jrgm** [comment]
Verified for stage train-2012.05.25. If both the deprecated 'privacyURL' and 'tosURL' are passed, links to those URL are shown in the dialog. If the new 'privacyPolicy' and 'termsOfService' are passed in, those URLs are shown. If all four are passed in, the deprecated form wins (i.e., the value of privacyURL is preferred to privacyPolicy). Small issue that I'll just put in separately (and wontfix-because-x is fine with me). Also this doc needs updating to the new params https://developer.mozilla.org/en/DOM/navigator.id.get
