### ISSUE TITLE
Implement HSTS

### ISSUE THREAD

**Issue by aaronsw** [mozilla/persona#166]
browserid.org should add an HSTS header to ensure it's always used securely. Indeed, it's so crucial for security, it should probably be preloaded with a pinned certificate:

http://www.chromium.org/sts
http://www.imperialviolet.org/2011/05/04/pinning.html

**Comment by benadida** [comment]
STS is already committed in the code (as well as secure-only cookies), undergoing beta testing this week and will be launched on Thursday.

Pinned certificates is probably not something we'll explore right now because (a) it covers only advanced and well timed attacks that probably won't be on our radar until we're bigger and (b) by the time we're bigger, we think the solution might look a bit different than pinning certs.
