### ISSUE TITLE
server timestamp no longer in KPI blob (with event_stream, lang, sample_rate, screen_size).

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1660]
The data uploaded to /wsapi/interaction_data on the wire consists of blobs like:

```
{
  "event_stream": [ event, ... ],
  "lang": "en-us",
  "sample_rate": 1,
  "screen_size": {
    "height": 1050,
    "width": 1680,
  },
}
```

Is it intentional that the server `timestamp` to have been stripped from that blob? (It is clearly not on the whitelist in the code, but the code for interaction_data looks like it's (optionally) expecting it).

**Comment by jrgm** [comment]
link to GH-1597 and GH-1613

**Comment by jedp** [comment]
Hmm...  I can't reproduce this.

To answer your question, it's not intentional that that would happen, no.  The timestamp should be added on the server-side in `lib/wsapi/interaction_data.js`.

Are you finding this is happening in the dev branch?  When I run browserid locally, I get the timestamps.  Also, they're being recorded in the blobs at https://kpiggybank.hacksign.in/

**Comment by jedp** [comment]
Ah!  Ok.  Reproduced.

We also lost `user_agent` somehow.  

I will fix.

**Comment by jrgm** [comment]
Verified in a dev env (feature not enabled in stage). The "data" portion of the payload sent contains only the keys
lang, timestamp, event_stream, sample_rate, screen_size
