### ISSUE TITLE
IE8/IE9: "Finishing sign in" screen intrudes on sliding arrow animation

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1705]
STR:
1. Be authenticated to dev.diresworb.org; use an RP to bring up the /sign_in dialog and click the sign in button.

Expected: (as seen with FF14/xp) after clicking signin, the arrow moves to right and the dialog closes when complete

Actual: (as seen with IE8 or IE9) after clicking sign in, a "Finishing sign in" screen is shown, then disappears to show the end of the arrow animation and then the dialog closes. 

It functionally is fine in either browser, but the FF experience is much nicer and probably the intended appearance

**Comment by jrgm** [comment]
Actually, this occurs on both IE8 and IE9 (but not FF). I'll note what other browsers do as I get to them.

**Comment by shane-tomlinson** [comment]
@jrgm - this is known and expected because I moved to CSS transitions because of a bug in jQuery with the box model that we are using.  See https://github.com/mozilla/browserid/pull/1656#discussion_r891602, https://github.com/mozilla/browserid/pull/1656#discussion_r891672 and https://github.com/mozilla/browserid/pull/1656#issuecomment-5983132.  Neither IE8 nor IE9 support CSS transitions, so there is no animation in these browsers yet.

There has to be a universal solution to this.  &lt;racks brain /&gt;

**Comment by jrgm** [comment]
closing as duplicate of GH-2618.
