### ISSUE TITLE
when adding a known secondary to a primary-only account, the user is prompted for a new password

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#1708]
I missed this in the previous release, even though I definitely did this (I think my eyes were glazing over). 

STR
1. From a clean state (clear profile/this is not me) go to 123done.org and signup in the dialog as a primary address (preferably a brand new email address, or you may bump into GH-1677).
2. Logout, pop the dialog again, and 'Add another email'
3. Enter a secondary email address that already exists and has a password with browserid.org

Expected: you are prompted for the password for the secondary and the two emails are joined together using that password

Actual: you are prompted for a new password twice

The rest of the flow can be completed from that point (modulo one other issue where you have to re-enter a third password; I think that issue is filed and I'll go look for it now).

**Comment by benadida** [comment]
/cc @callahad @shane-tomlinson 

we need to discuss the flow and the security implications, this is hard.

**Comment by benadida** [comment]
let's focus on this issue as just making it work with the current flow, that's Shane's job.
Broader discussion for later.

**Comment by callahad** [comment]
(The broader discussion, if we discuss allowing a Primary to unlock Secondaries, should consider users with a MockMyID account in their list of associated addresses.)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
