### ISSUE TITLE
Persona vs. Mozilla Persona

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#1737]
We use both, Persona and Mozilla Persona is our strings. What is the difference between them?

In some languages for instance, it's easier to use Mozilla Persona in a sentence than Persona. So localizers are asking me, whether they can decide for themselves when to use which one. Can they always use Mozilla Persona instead of Persona?

What about the other way around? They should probably never use Persona where Mozilla Persona is used.

/cc @ozten, @jbonacci

**Comment by callahad** [comment]
I believe they should be able to use whichever one they want.

@skinny97214 Can you confirm this?

**Comment by jrgm** [comment]
@mathjazz I see that an answer to your question wasn't posted here. Did it come by some other channel?

**Comment by mathjazz** [comment]
Not that I know of. I know it's been a long time, but I'd still love to get the answer.

**Comment by skinny97214** [comment]
I'd leave it up to localizers to make the most sense, since "persona" can be confusing in some languages. Definitely ping @ryanfeeley for any Persona design questions. He's your man now.

**Comment by ryanfeeley** [comment]
I think we should stick to Mozilla Persona for at least the first mention in a given block, if not every mention. Connecting Persona to Mozilla (and Mozilla less frequently to Firefox) is essential to establishing trust with prospective users. @jbonacci @skinny97214

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
