### ISSUE TITLE
Remove local embedded copies from include.js and provisioning_api.js

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#1749]
include.js embeds a copy of jschannel and winchan
provisioning_api.js embeds jschannel

caveat before shaving this yak - line 620 of include.js comments out a postMessage ping; this is to prevent the possibility of an error being raised if the ping is sent before the receiving frame is established.

@lloyd has written about this race condition here: http://lloyd.io/jschannel-taming-postmessage (see "Setup Race Conditions")

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
