### ISSUE TITLE
Expired identity displayed in list of possible identities for new account.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#175]
I have not logged in to my local dev machine in several days and saw some strangeness.  When I left last week, I had (I believe) an active BrowserID session open.  Today, when I first opened the BrowserID login dialog, instead of re-logging in with the same name as the expired user, I clicked on "I have never used BrowserID before."  I created a new session.  After verifying the email, I returned to the dialog where it displayed not only the new id that I just created, but the one that I believe I was logged in last week as well.  I then logged out and logged back in as the new user.  The extra ID was no longer there.

**Comment by lloyd** [comment]
A robust fix to this issue would be to fix the sync_identities logic in the client.  I believe we should:
1. always call sync_identities right when the dialog is rendered
2. use the returned JSON blob to understand what old identities should be purged, and which new ones should be added

This does add another call.  But there are many open issues related to multiple devices that this would solve.  An implementation tactic might be to call sync_identites rather than am_authed, because sync_identities will check the authentication status.  This way we don't add a new transaction.

sync_identities should also be called immediately after a successful login (I believe it already is).

**Comment by shane-tomlinson** [comment]
Fixed with pull request #180.
