### ISSUE TITLE
Windows install errors

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#1769]
Trying to install browserid locally onto a Windows machine causes some errors. These are what I've gathered so far, as I work around them, I'll add more that I find.
- ~~node-statsd specifically excludes Windows from the `os` property. - details in #1751~~
- ~~bcrypt fails to install (at version 0.4.1). There has been a lot of work on the repo to make it work in Windows, which seems to be getting close-ish: https://github.com/ncb000gt/node.bcrypt.js~~
- ~~jwcrypto fails - depedency on bigint, which uses old node-waf instead of node-gyp build system.~~
- ~~client-sessions fails - dependency on node-proxy. newest version of node-proxy would fix this.~~
- ~~postinstall script fails - if you get past the above issues, the browserid's postinstall script tries to execute `generate_ephemeral_keys.sh`, with shell not working on Windows, obviously.~~
- ~~process.on('SIGINT') throws~~
- ~~runDaemons overrides process.env.PATH~~
- ~~symlinks~~
- npm-lockdown doesn't work on Windows

**Comment by shane-tomlinson** [comment]
@seanmonstar - how are we lookin?

**Comment by seanmonstar** [comment]
I've been updating the list in the top description as things have been fixed. The only outstanding issue is that `lockdown` doesn't work right on Windows.

**Comment by shane-tomlinson** [comment]
@seanmonstar - do you still have problems installing on Windows?

**Comment by seanmonstar** [comment]
There's one last problem that: the current `scripts/lockdown.js` is an old version that doesn't work on Windows. There is an open pull request to fix the script in lockdown: https://github.com/mozilla/npm-lockdown/pull/24

Afterwards, the script would need to be copied to `scripts/lockdown.js`.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
