### ISSUE TITLE
Mobile VKB hides part of the signing in UI flow

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1779]
OS: Android 2.3.4
Browser: Firefox 14.0

STR:
1. Load http://beta.123done.org/ in the browser.
2. Tap on the "Sign in with Persona" button.
3. Enter an email address associated to BrowserID.
4. Tap on the "Go" button on the virtual keyboard.

Expected Results:
The next Sign In dialog is opened but the Password field is not focused until the user taps on it.

Actual Results:
What the user sees is that the virtual keyboard stays open and the email is removed from it. He needs to close the VKB to see what actually happened: the next Sign In dialog has been opened and the VKB has been opened to enter the password.

I don't have access to an iOS device, so I couldn't check to see if this issue also reproduces there.

**Comment by shane-tomlinson** [comment]
Same cause as #236

**Comment by shane-tomlinson** [comment]
This is a problem on iOS as well.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
