### ISSUE TITLE
The message that Persona requires cookies is displayed although cookies are enabled in the browser

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#1797]
OS: Windows 7
Browser: Firefox 14.0, Firefox 15.0, Opera 11.64

STR:
1. Load http://beta.123done.org in the browser.
2. Click on the Sign In button.

Although cookies are enabled in the browser (including 3rd party ones), the following message is displayed:

Persona requires cookies
Please close this window, enable cookies and try again

This issue is intermittent. I could only reproduce it once per 1-2 days of using Persona.

**Comment by seanmonstar** [comment]
@shane-tomlinson to try checking for cookies from JavaScript, we can just set a dummy cookie, and try to read it back out.

``` js
function hasCookies() {
  setCookie('__cookieCheck', true);
  var has = getCookie('__cookieCheck');
  unsetCookie('__cookieCheck');
  return has;
}
```

**Comment by shane-tomlinson** [comment]
@seanmonstar - that is exactly the approach I am taking in https://github.com/mozilla/browserid/blob/dev/resources/static/shared/network.js#L671-682.  Could it be because I am setting the max-age to 1 instead of using an expires?  

I just found on http://mrcoles.com/blog/cookies-max-age-vs-expires/ that IE8 does not support max-age.  This is enough of a reason to update the check.

**Comment by csuciu** [comment]
I got the 'Persona requires cookies....' message on https://login.anosrep.org/ when I tried to cancel an account. 
OS: Win 7
Browser: FF 13.0.1

**Comment by shane-tomlinson** [comment]
Closing as dup of #1903
