### ISSUE TITLE
Force BrowserID language

### ISSUE THREAD

**Issue by thom4parisot** [mozilla/persona#1798]
Hi guys,

we use BrowserID on a website where the customer can choose his preferred language, despite we initially detect the most suitable from his browser headers.

Anyway, in case I have an English preference for my browser, I've set the service in French.
_However_, BrowserID pops in English, so in a different locale than the UI.

It would be very cool if we could force the language by doing this `<script src="https://browserid.org/include.js?lang=fr-FR"></script>` or something like that.

Any plan for that?

**Comment by lloyd** [comment]
Hi!

We've discussed this at length on the mailing list.

We've discussed both having a user visible language picker in the dialog, and having an argument to navigator.id.request() that overrides defaults.

which would you favor?

**Comment by naholyr** [comment]
I'd favor both:
- default must be consistent with referer's → option in `request()`
- user should be always able to change its language → language picker in dialog
  - but if you add such a dialog, it should be optional, and most important it should talk back to opener (via the callback ?) to let main website know that user wanted to change language.

**Comment by DavidBruant** [comment]
In our (@naholyr, @oncletom and I work together) app, users have a favorite language. Since browserId is part of our user workflow, we'd like to make browserId consistent with the rest of our application and being able to impose a language to BrowserId (assuming the language is supported, of course).

More to the point, as far as our app is concerned, an argument in navigator.id.request() is what we need. A browserId "internal" language picker is beyond our use case and should probably be part of a different issue since it can be decided independently.

**Comment by DavidBruant** [comment]
Discussion with @oncletom led to the idea that instead of the browser language, browserId could decide which language to choose based on the html@lang attribute of the page it is opened from.
In this case, we would set the html@lang and BrowserId would choose a language consistent with this language.

**Comment by lloyd** [comment]
here's the thread on the mailing list where this was discussed.  I'll bump it for you.

https://groups.google.com/group/mozilla.dev.identity/browse_thread/thread/85d61589acec2201/1c2297a5edc64456?lnk=gst&q=dialog+language#1c2297a5edc64456

**Comment by shane-tomlinson** [comment]
@lloyd, @benadida, @vthunder - I thought we concluded we were _not_ going to add this functionality because it would override a user's browser settings.  If so, can we close this as "won't fix"?

**Comment by benadida** [comment]
This issue should go to @vthunder and @skinny97214, but I'm in favor of WONTFIX as I don't see a reason for our dialog to be in any language other than the user's browser's default.

**Comment by thom4parisot** [comment]
Maybe if a user selected a language on the website through a language picker (which can be different of the one of his browser), he would also like to keep his language experience the same?

If the app is monolingual, or if the user have not changed it, sure BrowserID could and must use the browser's default. It makes sense. However, if the user explicitely changed his language, the experience should pursue in the same language as far as possible.

**Comment by skinny97214** [comment]
@benadida I wish I could feel good about that as a solution, but after my work with the language issues on SUMO I realized it's not that simple. We know that the user's browser setting won't be correct 100% of the time. They could be checking in from a different computer than normal, i.e. an internet cafe. They could have an English distro even though they speak another language. 

The question for me is what percent of users does this effect and how should we prioritize figuring out the best solution. I expect it is a small percent but important enough that we will eventually have to address it.

**Comment by benadida** [comment]
@skinny97214 it might be hard to get good data on this. To me, the question is: if the browser is set to a certain language, is the user really inconvenienced if the Persona popup is in the same language? And how many folks would that really be a problem for?

Like I said, yours and @vthunder's call, but I'm having trouble seeing a high priority on this.

**Comment by thom4parisot** [comment]
> if the browser is set to a certain language, is the user really inconvenienced if the Persona popup is in the same language?

Absolutely not, IMHO it's the best thing to do.
Except when it comes to the next point.

> And how many folks would that really be a problem for?

For those who had **explicitely** chosen another **website language** (they provide language selector for purpose).

Yet it affets a small percentage, it would not be so hard to let the language to be set like this:

``` javascript
navigator.id.request({
  locale: "fr"
});
```
- If it's filled
  - Persona checks if the language is available
  - If it's available, it uses it
  - If it's not available, the default browser-detection happens  
- Otherwise, the default browser-detection happens.

PS: as someone noticed it earlier, the `html[lang]` attribute could be a good hint about the website language.

**Comment by naholyr** [comment]
Is Persona translated in **all** the existing languages ? Currently, even French is not fully supported :(

Until you don't support all languages, you cannot only rely on browser's header because: what will you do when none of those are supported by Persona ? Choose arbitrarily English ? You have to let user change this choice.
And when it's come to this, why not letting the opener pre-select this choice (as proposed by @oncletom for example) ? If user specifically defined a language, then chances are huge that opener is more accurate than  `Accept-Language`.

**Comment by fjanon** [comment]
Is there a change in this issue (having a way to pick the language on the client)?

We are developing a site that can be used everywhere in the world, including in public access internet place or internet cafes and mainly by tourists, Which means that the user is going to want to use a different language from the system language. Someone speaking arabic or mandaring is going to have a hard time going through Persona while in Holland.

It is a more than common use case. I am not sure why this is an issue.

Not having a way to change the language by program on the client is a blocker for us.

**Comment by seanmonstar** [comment]
At the moment, we don't have the resources to work on this (or any other issue, really).

**Comment by fjanon** [comment]
OK, thanks.

**Comment by vthunder** [comment]
:-(

**Comment by thom4parisot** [comment]
Too bad to read that, especially after the traction the project got (and the smart Yahoo! and Gmail bridges).

Any help needed to support the project?

**Comment by callahad** [comment]
@oncletom Yeah :) The paid contributors on Persona are currently focusing on Mozilla's Firefox Accounts and Sync services, which have more urgent needs.

We're still totally committed to maintaining Persona (if it needs a security fix or other critical bugs crop up), but we don't have the manpower to do new-feature work at the moment.

A really helpful place to start might be updating the Node dependencies and making sure the tests still run and pass. :) Otherwise, patches to close any bugs with the 4-star ("★★★★") label would be extremely welcome.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
