### ISSUE TITLE
check_primary_support does not check the content-type header

### ISSUE THREAD

**Issue by david-caro** [mozilla/persona#1836]
The check_primary_support script, does not check the HTTP header Content-Type as the browserid does (thus failing for the browserid but passing the check). I think that one of the two must be changed (the script should check for the header or the browserid server shouldn't).

David

**Comment by lloyd** [comment]
+1 the test should match the requirements of the server!

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
