### ISSUE TITLE
Please don't unfocus the email text field in the sign-in dialog

### ISSUE THREAD

**Issue by st3fan** [mozilla/persona#1840]
On iOS, when the email field loses its focus, the keyboard is dismissed. So you end up in a situation where:

1) BrowserID Dialog Appears
2) User taps in email field to fill it in
3) KEYBOARD APPEARS
4) User types email, hits next
5) KEYBOARD DISAPPEARS
6) User taps Password field to fill it in
7 KEYBOARD APPEARS
8) User enters password, hits next
9) KEYBOARD DISAPPEARS

Animations and keyboard going up and down. Too many things moving around on screen.

**Comment by shane-tomlinson** [comment]
Related to #236 and #1779. We need a sane approach to mobile keyboards.

**Comment by lloyd** [comment]
@sawyerh please take a look at this and advise

**Comment by sawyerh** [comment]
Here's a quick video demo of what @st3fan outlined, to help us visualize what the current interactions are: http://www.screenr.com/FYZ8

I don't believe we want to automatically focus the field for the user on mobile. There's a lot less friction with tapping than there is with clicking since it's a more natural interaction, so I don't mind making them tap into the fields on mobile (assuming these fields are easy to tap into). 

One big reason I would suggest this is that the sign in and register dialog will often times look a lot different than what the referring site does and the dialog is opening in a new window, so there will already be that change in environment that the user will need to adjust to and I feel that by having the Mozilla Persona branding and referring site name (http://d.pr/i/i79L) visible right away will help ease the user's mind a bit, rather than scrolling the page directly down to the field and hiding those sections. This is very true on the password page where it's saying that you're signing in with Persona and wouldn't mention the site name anywhere if the field is automatically focused (screenshot: http://d.pr/i/aBdd)

I'm interested in hearing everyone's thoughts on this + @skinny97214

**Comment by shane-tomlinson** [comment]
@sawyerh - I agree, it's sloppy on mobile and I've wanted to remove the auto focus for it for a long time.  I did a branch with it today, will test further next week and submit a pull request.

**Comment by lloyd** [comment]
@shane-tomlinson - still relevant?

**Comment by shane-tomlinson** [comment]
@lloyd - yes

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
