### ISSUE TITLE
Need a reasonable approach to Android "Cannot Establish Relay Frame" error

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#1854]
This error is displayed to users under several circumstances:

1) The user has multiple browsers and does not have a default browser selected when they open the BrowserID dialog
2) The user has a different browser set as default to the one they are browsing the RP with.
3) They use the MIUI ROM

For Android users, it would be nice if we had special instructions with a link to MDN helping them to set their default like we have for iOS and disabled cookies.

see also:
#1047
#1676
#1709

**Comment by lloyd** [comment]
4 star for better copy, and we go from there.

**Comment by jedp** [comment]
@shane-tomlinson , @lloyd , any thoughts on this?

It seems that most of the means of triggering the issue have been fixed (especially if #1047 cannot be repro'd on Android 2.x).  That might merit demoting this to three stars, but it still sounds like a priority.

**Comment by shane-tomlinson** [comment]
Link to #2034

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
