### ISSUE TITLE
alias en_UK et al to en_US

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#1863]

**Comment by lloyd** [comment]
talk to @lloyd for context!

**Comment by shane-tomlinson** [comment]
@lloyd, @seanmonstar, @ozten, @mathjazz Instead of aliasing en_UK to en_US, would it be better to rename our en_US locale just plain en and we let this be the fallback?

It seems kind of silly that if a user specifies en_UK as their default language and then es as their second, the user sees es - at least this was the case last time I checked.

Would this approach work for other languages as well, it looks like we have zn-CN and zn-TW,and nb-NO with no fallbacks to plain zn or nb?

**Comment by ozten** [comment]
This has been discussed previously (and i'll defer to l10n-drivers if I mispeak or the policy has changed but...)

1) I'm okay with changing en_US to en, because I don't think there are any en_\* locales which would be offended.

Aside: What % of our users have en_UK,es ?

2) We can get into real political trouble by doing this for other locales. I think it's even documented in the unit tests. 

**Please don't do this without the help of l10n-drivers.**

**Comment by shane-tomlinson** [comment]
@ozten, @mathjazz - who are the appropriate people to get in contact with on l10n-drivers?  My contact so far has been limited to @mathjazz.

**Comment by mathjazz** [comment]
Pascal (our web l10n driver): "on mozilla.org en-\* are aliased to en-US, if we need a specific page that really targets England (to announce an event for example), we can bypass the alias"

**Comment by milossh** [comment]
Aside from that, there's no and there should be no zh, as per community.

**Comment by seanmonstar** [comment]
That's fine with me. As long as someone who has `en_UK, cn` doesn't get
Chinese when we can clearly serve him English.

**Comment by jrgm** [comment]
verified in stage with the current set of localizations on train-2012.10.12

**Comment by jrgm** [comment]
Oh crap. Spoke too soon. If the browser does not send an Accept-Language header (e.g., in FF remove all the languages in the preferences UI, or in about:config set 'intl.accept_languages' to be '') then /sign_in loads content that has the HTML lang attribute set to 'en-US' and tries to load https://login.anosrep.org/production/en_US/dialog.js which is 404. The dialog is broken in this case.

Admittedly, not sending any Accept-Language header is unusual but not impossible. I'll open a five-star issue about this specific case.

**Comment by jrgm** [comment]
Okay, GH-2645 was a configuration issue in stage and fixed now.
