### ISSUE TITLE
add product tour to the popup

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1874]
Currently, if a user clicks the "learn more" link, they're directed out of the popup, to the "how it works" page on browserid.org. We should keep them in the popup and use the same content that's on the new /about page.

**Comment by sawyerh** [comment]
Not sure who to direct this towards (@lloyd / @shane-tomlinson?) — but could someone walk me through or point me in the right direction with setting up a view/route to implement the product tour in the dialog window? I'm thinking I only need one view and then can transition in the different tour info using JS. Just not sure where/how to get a view setup so I can start on this.

**Comment by sawyerh** [comment]
@seanmonstar Alright, I have this mostly working here: https://github.com/sawyerh/browserid/compare/issue-1874-tour

There's one thing not yet working and another that I totally hacked together because I was unsure how to do it otherwise.

Broken: The link in the dialog footer (http://d.pr/i/Thje) should point to the new /tour page and open in the current window. When you click it it's just closing the dialog window. Not sure what's going on there.

Hacked: I wasn't quite sure how to properly add a class to the `<body>` in Node so I hacked together a jQuery solution in tour.js

**Comment by seanmonstar** [comment]
@shane-tomlinson do you know what could be cause clicking links to close the dialog? Is it a `$.live()` call or something? I was looking for things like that, but there's so many things it could be, and I still don't know every single part of the system.

**Comment by seanmonstar** [comment]
I just thought of the window.onunload handler. Changing the page would trigger onunload, and winchan say cleans up at unload.

**Comment by shane-tomlinson** [comment]
@seanmonstar, @sawyerh - Sean, you are right, WinChan will close the dialog if the user changes pages from within the dialog.

What is the desired behavior once the tour is shown, can the user return to the dialog?

Is the tour accessible from the main site?  If so, perhaps a way to go is to make the tour into an EJS partial that we can use both on the main site and in the dialog.

**Comment by lloyd** [comment]
just given the magnitude of this change, we're moving it beta2. That said, if beta1 goes on for months, we might pull it in.

**Comment by seanmonstar** [comment]
@skinny97214 I've got the Tour inside the dialog, but feel the scrollbars seem out of place. See below:

![tour scrollbars](https://raw.github.com/gist/091dbf0a40d72b47b1a0/661cca88fff6e540a57ae99ae45a1e2ee98edc74/tour-scrollbars-1.png)

Does it make sense to be more of a slide show or something?

**Comment by skinny97214** [comment]
Yes, we can do a carousel with left and right arrows to navigate.

**Comment by seanmonstar** [comment]
Do we have arrow assets I can use?

**Comment by jaredhirsch** [comment]
Not happening before Beta 2. Bumping to Beta 3.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
