### ISSUE TITLE
Password strength standards?

### ISSUE THREAD

**Issue by sawyerh** [mozilla/persona#1880]
I'm working on a password strength indicator (#755) and have it basically working — the one thing that I need input on is what our standards are for a strong password and minimally secure password (length, what characters are included, etc.)?

**Comment by nmalkin** [comment]
The Dropbox tech blog recently had [a great article about realistic password strength estimation](http://tech.dropbox.com/?p=165). They looked at the current solutions, analyzed the threat model, and came up with their own [library for estimating password strength](https://github.com/lowe/zxcvbn) (in JavaScript, too!). It seems, at the very least, like a good starting point.

**Comment by lloyd** [comment]
currently the _only_ requirement on passwords is that they are 8 chars.  If we wanted to leave that constraint in for the first phase, then this would be the point which the button becomes clickable - minimal acceptance.

For an algorithm to generate a score from a password, I'd suggest something that considers a longer password with fewer distinct character classes present, as secure as a shorter one with more classes present.

My silly guess would be to count the number of char classes in the word, and use # of char classes and 
Char classes: 0-9, a-z, A-Z, Symbols

LENGTH \* CLASSES^0.625 = SCORE

and score:

good: >= 20
ok  : >= 12 < 20
weak: < 12

using that

l0nd0n - weak
goatsgrasslovewar - ok
Tr0ub4dor&3 - good
correcthorsebatterystable - good

Now, all this is just made up.  @warner, what's the real answer?

**Comment by lloyd** [comment]
oh, didn't see @nmalkin 's suggestions.  That looks like the _real_ answer, but adding 700k to our dialog load seems a non-starter...  Here's a tiny hack of what I mention above: https://gist.github.com/3022958

**Comment by warner** [comment]
That library does look pretty cool. I suspect the 700k (which only gets pulled down when you create an account or change your password, BTW) could be reduced a lot by using a Bloom Filter (finally! a use for a Bloom Filter!), but that'd involve a lot of code hacking.

Could we grab the zxcvbn code and just leave out the big dictionary?

The **real** real answer is to generate passwords for the user, from actual random numbers. Anything else is trying to guess which random distribution the human used by looking at a single sample, which is statistically goofy. (e.g. "password" is a perfectly legitimate output of an 8-character random letter generator, which would have an entropy of 37.6 bits, and there's no way to know whether their next password would have been "jwipltya" or "password2").

Also, most users are just going to type the minimum number of characters to make the darn thing work, which is why the most common Yahoo password (when it required a minimum of 6 characters) was 123456. The danger is that you get into a sort of adversarial game between the code and the user, where the user's goal is to get their job done (i.e. find a password that the thing will accept) and move on, while the code's job is to try to keep them safe by making them do more work than they're otherwise inclined to do. If users feel antagonized, they'll respond by trying to "outwit" the strength-meter (seeing it as the opponent, rather than as an ally), and may try to find the weakest possible password that will still get accepted: counterproductive.

That said, there's still some value to doing this sort of checking.. it can rule out the worst passwords, and can serve as a hint to what a good process should be. The blacklist is especially useful: if you could rule out the top one million passwords, things could be a lot better (at least for a few years, until the bad guys learn what the second million passwords are).

**Comment by sawyerh** [comment]
By the way, here's a demo of the updated UX — http://www.screenr.com/y7Z8 — we don't start the user off by displaying a red or yellow text field and wait until they have a strong password or backspace before applying a visual representation of the strength. Hopefully this can reduce the game between code and user as @warner mentioned (and not be as intimidating)

**Comment by sawyerh** [comment]
I have a working implementation of @lloyd's approach over here https://github.com/sawyerh/browserid/tree/password-strength-ux

This can be switched out with a more bulky approach like zxcvbn though if you feel that would be better and are okay with the size of it, just let me know.

**Comment by lloyd** [comment]
deployed and visible at http://strength.123done.org

**Comment by lloyd** [comment]
@warner do you mind hearding this conversation to a decision?

**Comment by skinny97214** [comment]
@warner I'd like to get this merged in before @sawyerh finishes up his internship next week. Can you take a look?

**Comment by warner** [comment]
Yeah, I'll take a look. I'm torn, because I don't really have a good answer for the "what criteria should we use" question. Next week I might, since there's a paper being presented on just this topic (https://www.usenix.org/conference/usenixsecurity12/how-does-your-password-measure-effect-strength-meters-password-creation), and the proceedings should become available in a few days.

Trunk is locked down to new features in preparation for beta, so even if we settle on the criteria, I'm not sure we can land it yet (I'll let @lloyd make that call). But for sure we can keep it lined up to land as soon as possible (i.e. I'll keep it from bitrotting).

Is is possible to use just the non-dictionary parts of the zxcvbn algorithm?

Also, is it possible to defer loading the strength-checking code until we hit the account-creating dialog? Ideally, we could split the zxcvbn code into two pieces (small rules, plus large dictionary), start loading the small part when the "please pick email/password" dialog appears, have it loaded by the time they type enough characters of the password to warrant showing anything, and then have the full dictionary loaded by the time they finish typing the confirmation password (at which point a "oh noes! lousy password!" interruption is probably ok). And if they type really fast and finish the process before the dictionary is loaded, we can decide whether to wait for the load or just skip the dictionary check.

What would that async-loading require.. a WebWorker? an iframe? A `<script async src=x>` element and something to discover when it's finished loading? I see a bunch of notes on http://css-tricks.com/thinking-async/ that seem relevant.

**Comment by shane-tomlinson** [comment]
This should be added to browserid-stories. Closing here.
