### ISSUE TITLE
demo siteLogo fails (not served over HTTPS)

### ISSUE THREAD

**Issue by warner** [mozilla/persona#1881]
When you use `npm start` to spin up a local test server, and use the "Supply Site Logo" button on the demo RP at `localhost:10001`, the resulting browserid login dialog gives an error, because the `siteLogo` URL is not being served over SSL. For real RPs this is the right thing to do, but for the local demo it just prevents use from exercising the `siteLogo` feature.

I think the test should actually be whether the "protocol" of the expanded siteLogo URL matches the protocol of the login dialog's URL. For real deployments this will be "https:" (because include.js points at https://persona.org), and for local test deployments this will be "http:".

**Comment by shane-tomlinson** [comment]
@warner - this is initially how I had it coded up. During code review @lloyd requested that I change it so that we could check whether the error message was displayed if using siteLogo from an http site.

Enabling siteLogo in development _is_ a pain, a developer has to manually edit code to do so. I think we should make this configurable somehow, though I am not sure through what mechanism. At the moment we have no way of surfacing configuration options to client code.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
