### ISSUE TITLE
use siteName rather than domain in emails

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1887]
When available (website using .watch() api and providing `siteName`), we could make our emails more human by including the name in the email.  

/cc @skinny97214 

This depends on issue #1526 - before we add more arguments to our API, we should clean up the validation of these arguments.  a worthwhile yak to shave.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
