### ISSUE TITLE
HTML mocks of emails

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#1890]
See issue #1070 for mocks and specs

**Comment by sawyerh** [comment]
@shane-tomlinson / @skinny97214 / @lloyd  - I have an HTML email template coded up (https://gist.github.com/3035638). I'm not familiar enough with Node to integrate it with what's currently there (or know how to test that) — if someone wants to walk me through that sometime. This template is also pulling a few assets from the static.dev.anosrep.org domain, since I couldn't find those assets on the persona.org domain yet. If there's somewhere in the repo you want me to add this to, just let me know.

**Comment by lloyd** [comment]
woohoo!  more awesomes!

I would love to work with you on this and give you context.  Or I could integrate one email, and then you could jump in and do the other two.  (currently we're sending out three distinct emails, that will change to more in the near future.

The soonest I could get to this is probably thurs or friday as I'm gettin all transatlantic tomorrow.

**Comment by sawyerh** [comment]
@lloyd I think if you're able to integrate one, I should be able to follow your lead. Or whatever is easiest for you.

**Comment by lloyd** [comment]
woo!  I've integrated your template into https://github.com/mozilla/browserid/tree/issue1890 and it looks super purdy.

To check it out, go to http://html.123done.org and sign yourself up as a new user.

All that seems to be left is to make templates for the other two cases, get your review and tweaks, and merge her in!

And looking at the raw email source it kinda looks like plaintext fallback is broke, I'll try to figure that out...

cheers!

**Comment by lloyd** [comment]
![Purdy](https://img.skitch.com/20120708-r5nge34dsasskh1tejgcmwkj9h.png)

**Comment by lloyd** [comment]
link to GH-1935, we should carefully think through the messaging and emphasis ^.  website you're logging into in subject?  

I think the _user_ is more concerned about "Complete login to foobar.com" than "Confirming email addresses for Persona"

**Comment by sawyerh** [comment]
Added the 2 other templates: https://github.com/sawyerh/browserid/tree/issue-1890-html-emails

**Comment by skinny97214** [comment]
agree, the site name has to have the biggest visual prominence.

**Comment by shane-tomlinson** [comment]
@lloyd - since 2173 was merged, can this be closed?
