### ISSUE TITLE
Falsely detects that cookies aren't enabled

### ISSUE THREAD

**Issue by gene1wood** [mozilla/persona#1903]
This may not be a problem with browserid, it could be with https://id.etherpad.mozilla.org/

Here's what happened.

I clicked this link in my irc client :

https://id.etherpad.mozilla.org/

which opened a new tab in Firefox (13.0.1)

etherpad said to sign in with browserid so I clicked the signin button.

A new browser window popped up and went through a sequence of redirects (too fast for me to record what they were) leaving me on a page saying :

BrowserID requires cookies
Please close this window, enabled cookies and try again

(see attached screenshot #1)

I don't have cookies disabled. I'm running adblock but not noscript.

So I closed the popup window, and clicked the "Sign in" button again. Nothing happened. Clicked it a few times and figured maybe firefox was noticing that I'd closed that popup and was blocking further popup attempts? Not sure.

So I pasted the URL https://id.etherpad.mozilla.org/ back into the browser and brought up the page again, this time without the message about browserid (see screenshot #2)

I clicked the "Sign in" button and it popped up the browserid window which went through some redirects I suspect and this time successfully brought me to the browserid login screen.

I'm not positive how to reproduce this. Maybe clear all cookies and start from scratch? Maybe related to etherpad changing auth methods since I last used it.

I can provide more info if it's needed. jbonacci suspects this relates to adblock

**Comment by gene1wood** [comment]
Here are the screenshots : http://imgur.com/a/PKqkZ

**Comment by shane-tomlinson** [comment]
@gene1wood - Thanks for the detailed description and screen shots, this is likely related to #1797.

**Comment by lloyd** [comment]
@jrgm can you work with @gene1wood to isolate this and understand affected users?

**Comment by frank-e** [comment]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=843493

**Comment by jaredhirsch** [comment]
@frank-e the bugzilla bug seems to indicate you're using FF 10. Is that correct?

**Comment by jaredhirsch** [comment]
I suspect he was using the extended support release of FF, based on the version number.

**Comment by frank-e** [comment]
FF 10.0.12esr in this case, yes. It's five days past its end-of-live, but there's no better browser when using Windows 2000.  I'm not aware of similar cookie oddities with Firefox on other sites.  Very vague ideas: 

(1) I used persona before for MDN (cf. https://bugzilla.mozilla.org/show_bug.cgi?id=629994), but [maybe] I never tried it for bugzilla.
(2) I can't tell if I used the same FF 10.0.12esr in the same OS when it worked for MDN, because I have a "portable" and an "ordinary" installation, both used under windows 7 (virtual hard disks) and windows 2000 (VM).

**Comment by jaredhirsch** [comment]
OK, is there any reason you can't use a newer browser in your windows 7? I want to unblock your using bugzilla, but have no clear steps to repro.

Moreover, this is an old bug, and you're using a browser that's past its EOL, in an OS that's past its EOL.

Leaving this bug open in case other reports surface, but not likely to tackle this right now.

**Comment by jedp** [comment]
I don't think this affects enough users to be kept as a four-star. Decrementing to three.  Please reassign if I am wrong.

Perhaps we can even close this?  @frank-e, are you still having problems?

**Comment by michielbdejong** [comment]
i'm using vanilla Firefox on a brand new Windows 8 laptop (only thing i changed was to install DuckDuckGo as my search engine). i can log in to voo.st using 'log in with facebook', but when i try the 'log in with your email address', after putting my email address and password into the popup, i get this error:

```
Error
Persona requires cookies to remember you.
Please close this window, enable cookies and try again 
```

this problem only occurs in Firefox, not in Explorer or Chrome.

from the fact that logging in with Facebook works, i know my firefox instance is not entirely misconfigured. something is going on that's specific to the combination of Firefox and Mozilla Persona (on Windows 8).

This problem is making me have to switch to Chrome whenever a website uses Persona.

attaching dev tools screenshots showing the 403 response to the POST:

![persona-cookie-problem](https://f.cloud.github.com/assets/408412/1644386/cade7750-58e2-11e3-8f16-4e94932d5aa1.png)
![persona-cookie-problem-console](https://f.cloud.github.com/assets/408412/1644387/cadecdfe-58e2-11e3-87d5-7e8a23b3c00a.png)

**Comment by michielbdejong** [comment]
i'm michielbdejong on irc btw, if you want me to test or try anything to investigate

**Comment by michielbdejong** [comment]
@shane-tomlinson do you know what could be causing the 403 there? as you can see, my browser is actually sending a cookie, including the string `can_set_cookies=1` :)

**Comment by shane-tomlinson** [comment]
@michielbdejong - Can you paste in the response both `/wsapi/session_context` and `/wsapi/authenticate_user`? Does either response say anything about cookies disabled? 

Is your Windows 8 32 bit or 64 bit?

**Comment by michielbdejong** [comment]
Windows 8 type:

> System type: 64-bit Operating System, x64-based processor

response body of `/wsapi/authenticate_user`:

> Forbidden: no cookie

i don't see a call to `/wsapi/session_context` but the response `/wsapi/addressinfo` is JSON:
- type: 'secondary',
- issuer: 'login.persona.org',
- disabled: false,
- normalizedEmail: 'michiel@unhosted.org',
- state: 'known'

**Comment by michielbdejong** [comment]
and here's the Cookie, in more detail:

![fullscreen capture 11-dec-13 151801](https://f.cloud.github.com/assets/408412/1724040/7cb555e2-6267-11e3-9927-91ecc2361095.jpg)

**Comment by shane-tomlinson** [comment]
@michielbdejong - the httpOnly is only for the browserid_state cookie, the cookie being checked for whether cookies are enabled is the can_set_cookies cookie. mmm.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
