### ISSUE TITLE
experiment with node-memwatch in browserid for memory stats

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1912]
@jedp and I built this: https://github.com/lloyd/node-memwatch

This tool could give us baseline memory numbers we could report via statsd, as well as events when heap growth is positive for a long time.

We might want to see if this could provides us a tool for monitoring of memory, by having it config'd on in stage for a loadgen run.

For integration, I'd suggest we simply start with emitting the base memory usage (on the `stats` event) via statsd... and go from there.

we could also give this a try on AWS first and see if the numbers are stable and useful.  Who knows, maybe we'll find some leaks?? 

/cc @zcarter @jedp @jrgm

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
