### ISSUE TITLE
Make KPI data_sample_rate adjustable on the fly

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#1930]
@jrgm has suggested it should be possible to adjust `data_sample_rate` without requiring a server restart.

**Comment by jrgm** [comment]
While ops has a pretty solid way to swing us out of one datacenter, bounce the servers, flip-flop datacenters, bounce the second datacenter, if there were a way of changing this value on the fly, that might be nicer and quicker (I'm thinking mostly of when we want to be a kill switch).

**Comment by jedp** [comment]
Since we've lived a year with the status quo, I'm going to decrement this to three stars.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
