### ISSUE TITLE
include.js should be generated

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#1971]
include.js has both JSChannel and WinChan as dependencies, but those are also include in common/js/lib. include.js received some patches that fixed a few things in WinChan (at the least), that never got upstream. To prevent this, the include.js should get generated from the lib files, ensuring that there is no source duplication (and divergence).

**Comment by shane-tomlinson** [comment]
We had another issue (#483) opened for this, but I closed it as "won't fix".  I still think there is a lot of value in this.

Also link to #1199

**Comment by shane-tomlinson** [comment]
link to #1749

**Comment by callahad** [comment]
FWIW, as of today, dev (ef06d2c2ffd0ffb8e44924a3257b511e2adb2579) has identical copies of jschannel in include.js and the resources folder, modulo differences in whitespace.

winchan slightly differs. digging in a little more...

**Comment by shane-tomlinson** [comment]
#3056 is merged, closing.

**Comment by callahad** [comment]
reopening so I can find it when I get home -- we haven't completely fixed the duplication yet, just made it fixable...

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
