### ISSUE TITLE
Be able to authenticate with BrowserID without selecting an email address.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#198]
Useful for the BrowserID page itself - if the user is not authenticated but on the manage/develope/etc pages, instead of showing the "manage" button, we could show a "Sign In" button.

**Comment by lloyd** [comment]
So with streamlined UX flows, do you think this matters?  Because we will dismiss the dialog immediately after authentication and use the email that the user uses to sign in, our new streamlined UX will satisfy precisely this feature.

agree?

**Comment by shane-tomlinson** [comment]
From my understanding, the streamlined UX flow that you are talking about is the initial signup flow, does this also apply to a standard login?  The location I am thinking of using this feature is on browserid.org/[users|developers|primaries|manage] - especially the manage - where we do not need an email address itself, but we would like the user to authenticate with BrowserID so that they can perform account operations.  Will the flow take care of this as well?  If so, I'm all for using it.

**Comment by lloyd** [comment]
I think in all cases, when the user provides an email address in the login dialog, we should automatically log the user in with that email address.  There are few rare edge cases where this will not be what they want, but the workaround is simple and user discoverable.

**Comment by shane-tomlinson** [comment]
@lloyd - I am still in disagreement with doing this, and I feel the workaround is neither simple nor discoverable (having to log out of BrowserID and then log back in using the email that the user wants).  My personal case is still the one I reference the most, and I think the case that many users are going to find since browsers perform form(and if forms are done correctly, password) completion.  To BrowserID I _always_ authenticate using my Mozilla address and then select the my Yahoo address to authenticate with my blog.

**Comment by lloyd** [comment]
oh darnit.

Well, for now can we at least change the second click from 'sign-in' to 'next'?  right now (as cce points out on IRC), it's 'next'. 'sign-in', 'sign-in' in terms of what the user clicks on.

I'll throw our handy dandy needs_ux label on this guy.

**Comment by shane-tomlinson** [comment]
@lloyd instead of changing it to "next" (as the first step uses "next" too), I changed it to "select email"

**Comment by skinny97214** [comment]
Can you attach some screenshots? I'm having trouble following what bits you're talking about.

**Comment by benadida** [comment]
I lean towards @lloyd on this: the email selector after signing in feels like a click too much.

@skinny97214, since my screenshot manipulation skillz are poor, a quick description:
- assume user has cleared cookies or not logged into BrowserID in a while, but has set up a few email addresses in the past.
- user visits myfavoritebeer, clicks sign in.
- BrowserID dialog prompts for an email address, cause BrowserID doesn't know the user.
- user types one of his email addresses.
- BrowserID prompts for password.
- CRUCIAL POINT: does BrowserID now just sign user in with email address user typed, or does BrowserID present the list of all email addresses and let the user select and go?

**Comment by skinny97214** [comment]
The best UX would be for the site to be able to _always_ know which email the user has used to make an account. I realize there are security problems for all the obvious ways of accomplishing that.

UI won't get us out of this problem, I'm afraid. Finding an elegant solution to this will be hard, but critical. We're in a situation similar to the one with cellphones and phone numbers. We let technology take over something that's beyond our cognitively capabilities (remembering >15 phone numbers) but now we are utterly beholden to the device to be our memory for us. 

BrowserID is in a similar position in that we're going to remove the burden on the user to remember which email address went with which site. Our users will be beholden to us. They'll have no clue which email they used. There's no immediate feedback on whether they used the right email since it will just create a new account on the site. The undo process (logging out, logging back in with another guess of which email is correct) is painful.

I hope we can chat next week while I'm there about technical solutions we can come up with for this.

**Comment by shane-tomlinson** [comment]
@skinny97214, @benadida, @lloyd - So far, I have been giving the most pushback against signing a user in directly to the RP as Ben outlined above in https://github.com/mozilla/browserid/issues/198#issuecomment-2944790.  My personal use case is that I ALWAYS sign in to BrowserID using the same username/password combo - and then I select the email address that I want to use.  With my personal blog for instance, I sign in to BrowserID using my mozilla email address, and then sign in to my blog using my yahoo address.  I have no numbers to back up my claim that a substantial portion of users will have this behavior, especially with browsers doing form auto-completion on the username.

Optimizing a single click by removing the email picker when the user is forced to enter their username/password in BrowserID will break this flow and will give users an inconsistent behavior.  If the user enters their username/password and is not presented with an email picker, and the next time they use BrowserID they are presented with an email picker, they are going to ask themselves "Why do I get a choice sometimes but not others?"  People with my use case are gong to have to be trained to authenticate to BrowserID using the email address they want to use on the RP - if a user needs training for something as simple as entering the correct email address, this screams to me of failure on our part.

By remembering the email address a user used the last time they signed in to the site, I feel we have done a lot to ease the mental burden on the user, it is one less click they have to make, but removing the choice altogether and assuming that the email they signed into BrowserID is the one they want to use for the RP is going to cause confusion.

**Comment by benadida** [comment]
@shane-tomlinson - I don't quite buy this: I think your use case is a consequence of you knowing too much about BrowserID. My guess is that users won't think of "logging into BrowserID". They'll only think about logging into the web site. So why would they enter an email _other_ than the one they want to use to log in to the actual RP?

**Comment by shane-tomlinson** [comment]
@benadida - You have a valid point, especially once BrowserID is baked in to the browser.  In the mean time, BrowserID is a site, and users have been trained for years to sign in to a site using a single username/password combination.  

Could we ask Mary to user test various login flows?  I had a line in the code for months that I just took out to be able to easily add the proposed behavior and I think it would be good to see what users think, otherwise I'm going to be holding on to my belief without any evidence.  :/

**Comment by benadida** [comment]
@shane-tomlinson - we could ask Mary, but would you be comfortable with us trying this and seeing how users react? We can always revert :) Our user-testing bandwidth is fairly limited and there are a bunch of things we'll probably want to test first (e.g. profile)

**Comment by skinny97214** [comment]
I'm available for user testing. Mary can advise on it if she has time. 

@shane-tomlinson Since you have snazzy screencasting skillz, can you make one for me that shows this flow. I'm not 100% sure I understand your concern.

**Comment by jrgm** [comment]
verified. The new flow on stage when a user is not logged into browserid is enter email, click next, enter password, click
sign in, user is immediately signed in to the RP with no email picker shown. 

Note: GH-1241 - The option to check 'Always keep me signed in' is missing in the simplified sign-in flow for a returning user
