### ISSUE TITLE
eliminate redundancy in unit tests

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#1983]
our backend unit tests have lots of duplicated code.  For example, several tests set up new accounts with several emails as a startup step.

The way these tests typically evolve is by copying and pasting from another test.

This is lame, because we end up with several tests that duplicate the same code. They are hard to understand, hard to maintain, and most importantly the intention of the test is lost in all of the setup code.

I think we should break down the commonality into a library.  so if you wanted to test email you would say "give me an account with three email addresses" as a setup step, then explicitly invoke `remove_email`.

**Comment by benadida** [comment]
yes! And also simplify some of the setup, I'd like to see more true unit tests, less setting up of the servers, etc.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
