### ISSUE TITLE
add IdP protocol support for account provisioning flow and constrained RPs

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#1985]
as per needs for B2G, though provisioning flow will serve us well, too.

Specifically, account provisioning means that at the time of auth, the exact username is unknown, but the domain is known. e.g. "create a new account with this IdP." beginAuthentication callback thus takes a null identity. The selected identity is delivered in the completeAuthentication() call.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
