### ISSUE TITLE
deprecate getVerifiedEmail

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#1990]
We should begin the deprecation process for it with the beta launch.

**Comment by warner** [comment]
ben's comment suggests this is beta1-req, not sure if we still feel that way, tagging to solicit discussion

**Comment by callahad** [comment]
I like beginning the deprecation process for `getVerifiedEmail()` with beta1 since it affords us the opportunity to walk through deprecation, monitor for usage, add console alerts, etc. in anticipation of real, future deprecations.

The only place I'm aware our thinking has changed is with regard to `get()`, which we'll be keeping around for a little while longer.

**Comment by jrgm** [comment]
deprecation warning added in PR-2267. Verified in train-2012.08.17
