### ISSUE TITLE
Internal userid should not be exposed

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#1993]
(This is a very low priority bug because it doesn't have any security implications as far as @warner and I can see.)

These WSAPI operations all expose the internal userid we use in the database:
- user_creation_status
- authenticate_user
- auth_with_assertion

If it's not necessary, we should remove it.

**Comment by shane-tomlinson** [comment]
@fmarier, looping in @lloyd - Lloyd exposed the userid to the front end so that we could keep a table of which user's answers to the "is this your computer" question.  Since the user's emails can change but the user's ids do not, he chose to expose the userids.

We could do an alternate approach using email only.  Any time an email is added to the account, if another email associated with the account already has a flag set, then set the same flag.

**Comment by fmarier** [comment]
@shane-tomlinson I guess we could use emails like you suggest, but it also sounds a good reason to keep using userids. Thanks for the clarifications.

If we really wanted to get rid of the userid without impacting the front-end, then maybe the backend could simply return a hash of the userid... Anyways, low-priority :)

**Comment by fmarier** [comment]
This depends on https://github.com/mozilla/persona/issues/4079

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
