### ISSUE TITLE
Refactor domainFromEmail code

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#1994]
We currently extract the domain from an email using a regexp in a couple of places.

This should be refactored so that the regexp is in a single place (i.e. every part of the code is guaranteed to extract the domain in the exact same way).

I also propose that we validate (using the new regexp from GH-1981) the domain once it has been extracted. This should normally not be necessary given that we now validate any emails coming in, but this extra validation could help find bugs / discrepancies between our email and hostname regexps.

**Comment by fmarier** [comment]
https://github.com/mozilla/browserid/pull/2797/files introduced a helpers.getDomainFromEmail() function

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
