### ISSUE TITLE
[API] Need logo on IdP

### ISSUE THREAD

**Issue by ringe** [mozilla/persona#2002]
See #1908 for the idea.

The `.well-known/browserid` path could provide siteName and siteLogo parameters as well, to make it more user friendly.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
