### ISSUE TITLE
redirect timeout is sometimes first displayed with < 5 seconds.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2007]
This can happen if the CPU is busy and the fade in of the redirection text takes a long time.  Zac from automated testing even has a video where it first displays with 1 second.

**Comment by stephendonner** [comment]
Is it this video: https://saucelabs.com/jobs/a7c57aabbab84aef95a961a45cb254fa# ?  It's from this report, if so: http://qa-selenium.mv.mozilla.com:8080/job/browserid.dev.123done.linux.firefox.10/312/HTML_Report/

**Comment by stephendonner** [comment]
Confirmed with @zacc that this is responsible for our dev.123done build failures -- can we get this bumped up in stars/priority?  Realize you guys are slammed with regressions and prod rollouts, but want to ensure that our automation is kept humming along, to help!  Thanks.

**Comment by zacc** [comment]
Video, starts at 0:28: http://qa-selenium.mv.mozilla.com:8080/job/browserid.dev.123done.windows.7.firefox.11/290/HTML_Report/?

**Comment by stephendonner** [comment]
Or, for those output the VPN, and more directly: https://saucelabs.com/jobs/386925d6baa042a3ac864586d9be4ac0

**Comment by seanmonstar** [comment]
@shane-tomlinson I wonder if it's because of a possible network call also.

At https://github.com/mozilla/browserid/blob/dev/resources/static/pages/js/verify_secondary_address.js#L104, the `updateRedirectTimeout` countdown gets setup, and if `mustAuth` is false because it's the same browser, then `submit` is called.

In submit, at L55, is a call to `user[verifyFunction]()`, and only once that returns, is the confirmation page shown, at L61.

It could be that the animation doesn't fade it in, but it could also be that the network request is taking a moment. I'll see about making them start at the same time.
