### ISSUE TITLE
add different callback and discourage onready()

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#2017]
new callback should be something like onstatusquo(), which gets called if neither onlogin nor onlogout are about to be called. We should then phase out onready().

**Comment by callahad** [comment]
How certain are we of this change? Should I discourage use of onready in MDN now*, while we work on finalizing its deprecation plan and the exact details of onstatusquo?

\* Where now means as soon as MDN comes back up for edits.

**Comment by callahad** [comment]
I believe the decision is to go with `onvalidsession`, but awaiting further discussion from @lloyd and co.

**Comment by warner** [comment]
this sounds like it needs to be nailed down soon (to allow onready() to be phased out in a reasonable timeframe), but not necessarily before beta1

**Comment by callahad** [comment]
As per discussion with @lloyd, we're confident that we want to do this, but the details are still up in the air. Since many sites are using the Observer API without using onready, I'm going ahead and pulling this from the docs but without formally deprecating it.

**We have not yet announced this deprecation!** Do NOT modify / remove `onready` without discussing a deprecation plan with @fmarier or me.

**Comment by callahad** [comment]
To be implemented in #2648 as `onmatch`.
