### ISSUE TITLE
Consistent "this request is taking a looooong time" message when port 443 is filtered on the domain

### ISSUE THREAD

**Issue by potch** [mozilla/persona#2018]
I use an email address at `potch.me` to sign into various sites using browser id. The email for this domain is provided by Google Apps via Dreamhost. When prompted for my email address, the sign in process consistently stalls at the "gathering information about your email provider" step, resulting in the slow request message. That step can take as long as 8-10 seconds.

**Comment by ozten** [comment]
time curl 'https://potch.me/.well-known/browserid'

```
curl: (7) couldn't connect to host

real    1m15.574s
user    0m0.008s
sys 0m0.011s
```

Note HTTP version fails fast: time curl 'http://potch.me/.well-known/browserid'

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> 
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /.well-known/browserid was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

real    0m0.089s
user    0m0.005s
sys 0m0.004s
```

**Comment by fmarier** [comment]
potch.me is very slow to return:

```
$ time curl -i https://potch.me/.well-known/browserid
curl: (7) couldn't connect to host

real    1m3.146s
user    0m0.000s
sys 0m0.004s
```

whereas fmarier.org is fast:

```
$ time curl -i https://fmarier.org/.well-known/browserid
curl: (7) couldn't connect to host

real    0m1.175s
user    0m0.004s
sys 0m0.004s
```

It looks like the difference is at the firewall level where fmarier.org is REJECTing packets:

```
$ nmap -p 443 fmarier.org

Starting Nmap 5.21 ( http://nmap.org ) at 2012-07-13 11:35 NZST
Nmap scan report for fmarier.org (50.57.132.130)
Host is up (0.23s latency).
rDNS record for 50.57.132.130: kopavogur.fmarier.org
PORT    STATE  SERVICE
443/tcp closed https

Nmap done: 1 IP address (1 host up) scanned in 1.01 seconds
```

and potch.me is DROPing them:

```
$ nmap -p 443 potch.me

Starting Nmap 5.21 ( http://nmap.org ) at 2012-07-13 11:36 NZST
Nmap scan report for potch.me (69.163.165.176)
Host is up (0.14s latency).
rDNS record for 69.163.165.176: apache2-noxim.reds.dreamhost.com
PORT    STATE    SERVICE
443/tcp filtered https

Nmap done: 1 IP address (1 host up) scanned in 3.80 seconds
```

In any case, we probably need to adjust our internal timeouts...

**Comment by skinny97214** [comment]
+11

**Comment by lloyd** [comment]
+1 
This one drives me crazy too.

**Comment by warner** [comment]
Firewalls that silently DROP packets instead of explicitly REJECTing them are super annoying. The only way to deal with it is an application-level timeout, which will most likely cause false-failures for servers that are merely slow.

The best approach I can think of is to have a pacifier message: if the primary request hasn't come back within two seconds, leave it running but put up a notice that says "we're still waiting for a response from DOMAIN". Then establish a hard upper limit on how long it's allowed to wait (which sounds like it's about 9 seconds, seems reasonable).

**Comment by shane-tomlinson** [comment]
@warner - Somebody proposed adding an application level timeout a while back. Would you make this a server side timeout or a client side timeout?  @lloyd pointed out that while at a former employer, users in far flung reaches of the globe would frequently encounter 20 to 30 seconds or more of latency, making client side timeouts risky.

**Comment by warner** [comment]
what's the client/server split in this case? I can imagine the user's browser doing one fetch to the purported IdP's `.well-known` (from the dialog), then if that fails and it talks to the secondary, there could be another fetch by the server (i.e. secondary) to confirm that it really should be creating certs for this domain. So, um, "both"? Unfortunately, that will double the amount of time it takes to get a cert.

And yeah, we shouldn't assume a 30s delay means failure. The internet used to tolerate _hours_ of delay.

Yeah, timeouts indicate a can't-win situation. My best generic advice is to move any timeouts to as high a level as possible, preferably the human, and to provide full information between layers (instead of reporting failure due to timeout, report "I'm getting impatient" events followed maybe by success).

**Comment by jrgm** [comment]
The dialog does not make requests to <domain>/.well-known/browserid for the STR in this issue. It makes one xhr
to https://login.dev.anosrep.org/wsapi/address_info?email=someemailaddr%40potch.me which times out in 15 seconds
(with the "this is taking a long time" shown 10 seconds into that).

**Comment by abourget** [comment]
If that request times out.. can't we just assume the server will never give us a support document, and go on with a "persona.org"-backed authentication ?

I understand the "longer than normal" thing.. but then why would it just stop there, leaving no options.  We could start off with a persona-backed auth, and then later one, upon next sign-ins, verify if the remote party popped into existence, and then proceed with the delegation or someting.

I'm new to this, I might not have a thorough understanding, so just questioning.

**Comment by pthulin** [comment]
Having the same problem with "@youtify.com" addresses.

**Comment by shane-tomlinson** [comment]
Can this be solved by #1523?

**Comment by jaredhirsch** [comment]
Keeping this open to track further IdP complaints, but bumping down to 3 stars.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
