### ISSUE TITLE
load_gen: 'certificates must be a non-empty array' exception thrown

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2041]
I was running load_gen at 250000 ADU and a few hours in it threw an (uncaught) exception: 'certificates must be a non-empty array'. There was no stack shown but I figure it was thrown from here: https://github.com/mozilla/browserid/blob/dev/lib/load_gen/crypto.js#L65

Which is, heh, the line I added to fix GH-1770. Now obj.cert shouldn't be empty or falsy at this point. I'll look at a fix, but for now I'm just going to just use process.on('uncaughtException',...)

**Comment by jrgm** [comment]
I think obj.cert was empty here due to an error talking to zeus when trying to certify a key about 40 minutes before this crash.

**Comment by jrgm** [comment]
There was a major interruption of some kind for zeus on stage today about 15:00 PDT. About 30 minutes after that, the uncaughtException handler that I put in started chirping about this 'non-empty array'. So, yeah this is indeed happening to load_gen in the face of network errors.

**Comment by shane-tomlinson** [comment]
@lloyd - I am assigning this to you for investigation.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
