### ISSUE TITLE
load_gen does not renew expired certicates

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2063]
Sorry, noticed this a couple of weeks ago, but didn't file an issue. This wasn't visible before GH-1770 was fixed. So load_gen starts with an initial set of users and adds more all the time. These users get certs with 24 expiry. So after 24 hours the population begins to have expired certificates. 

Easy workaround for an extended duration test has been to restart load_gen after 24 hours, but it would be good to do the regeneration automatically. 

(This may also explain some (but not all) of the decline in rps by load_gen over time).

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
