### ISSUE TITLE
dynamic well-known

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#2078]
To support BigTent and generally provide a bit more flexibility, we should tweak the protocol such that, when a well-known file is requested at a URL whose domain does NOT match the email for which the request is made, a domain GET parameter is added to the well-known request.

**Comment by warner** [comment]
does this need to be nailed down before the beta1 release? Or are you comfortable making protocol changes after it?

**Comment by ozten** [comment]
I think this is after Beta 1.

**Comment by warner** [comment]
righto

**Comment by lloyd** [comment]
GET parameter?  Or HTTP header?

Remind me, _why_ does bigtent require this?  (Ideally this context would be in the issue description for forgetful people like me)

**Comment by benadida** [comment]
BigTent could be implemented in a number of ways:

(a) sharing the secret key (uggh)

(b) cert chaining (really complicated)

(c) GET parameter on well-known

In general, during the meeting we had about this where we discussed various ways in which a domain could logistically deploy different keys for different sets of users, we agreed (and I think you were enthusiastic) about (c) as the simplest way.

HTTP header is a no-go, that would break REST / caching / web arch in a serious way. It should be a diff URL.

**Comment by callahad** [comment]
@lloyd Our fallback needs a way to optionally route requests to BigTent. BigTent is designed to function just like a normal IdP.

The safest and simplest option on the table involved querying the well-known file with the user's domain as a GET parameter, so that we could use standard authority delegation to hand control over to BigTent.

As Ben mentioned, we're trying to avoid cert chaining or sharing the secret key. We'd also like to be able to easily add or remove BigTent for certain domains / addresses, so that B2G and the native Firefox implementation can use it _without_ having explicit knowledge of BigTent and its supported domains.

Unfortunately, it turns out that we can't actually support all Yahoo addresses with BigTent, and thus domain-based partitioning won't work for all currently-supported Yahoo addresses. This is thanks to a "disposable address" (pseudonymous alias) feature in Yahoo! Mail Plus. Which sucks a lot.

I _really_ need design help in figuring out a good way to make this thing work. @lloyd, here's your opportunity for a re-think of this thing. :)

**Comment by benadida** [comment]
@callahad fascinating! Those addresses are at the same domain? yahoo.com?

**Comment by callahad** [comment]
@benadida Yep! More info in mozilla/browserid-bigtent/issues/12, but the way you can tell a real Yahoo address from a disposable one is the presence of a hyphen in the address. Normal accounts can't have one, disposable aliases must have one.

**Comment by callahad** [comment]
@ozten Do we have a tracking bug for adding dynamic well-known lookup to our verifier?

**Comment by ozten** [comment]
@warner is working on this in mozilla/browserid/pull/2623

Brian, any other bug #s to mention?

**Comment by callahad** [comment]
I'm under the impression that this is in, and is how BigTent is currently working. Could someone verify, and I'll take care of the spec side?

**Comment by jaredhirsch** [comment]
@callahad yah, looks like #2623 is the dynamic well-known implementation in browserid, and was merged in.

**Comment by ozten** [comment]
Yes it is in the implementation, but probably not in the spec.
Here is the [open pull request](https://github.com/mozilla/id-specs/pull/28)

**Comment by ozten** [comment]
Relevant [mailing list thread](https://groups.google.com/forum/?fromgroups=#!searchin/mozilla.dev.identity/dynamic$20well$20known/mozilla.dev.identity/NbNybEEB8O4/4CBuM0_Oo7MJ).

**Comment by callahad** [comment]
Awesome. Feel free to leave the spec to me -- it'll be my main focus after I give my talk.

**Comment by jaredhirsch** [comment]
@callahad ping :-)

**Comment by callahad** [comment]
We're like, 99% there.

**Comment by jaredhirsch** [comment]
\o/ :beers:

**Comment by sesam** [comment]
Since Beta 2 has been launched, is this issue done?

**Comment by jaredhirsch** [comment]
I don't think so, since the specs repo hasn't been updated recently:
https://github.com/mozilla/id-specs

**Comment by callahad** [comment]
Taking this. Sleeping in tomorrow, will tackle that evening.

**Comment by seanmonstar** [comment]
This is done. If specs need updating, file a bug of there.
