### ISSUE TITLE
Cookies disabled: error message points to Firefox-only documentation

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2079]
When cookies are disabled, we show users an error message which ultimately points to this SUMO page:

  https://support.mozilla.org/en-US/kb/websites-say-cookies-are-blocked-unblock-them

Since Persona is not Firefox-specific, we should give instructions for other browsers too.

**Comment by shane-tomlinson** [comment]
+1.  This is a dup of the closed #1302.

From https://github.com/mozilla/browserid/issues/1302#issuecomment-4751065:

```
Docs found so far:

Desktop:
Firefox: http://support.mozilla.org/en-US/kb/Websites%20say%20cookies%20are%20blocked
Opera: http://www.opera.com/browser/tutorials/security/privacy/
Safari: http://docs.info.apple.com/article.html?path=Safari/5.0/en/ibr1074.html - Could use a better doc
Chrome: http://support.google.com/chrome/bin/answer.py?hl=en&answer=95647

Mobile:
Safari: https://support.mozilla.org/en-US/kb/how-enable-cookies-iphone
Fennec: Cannot find
Chrome: Cannot find
Android: http://support.google.com/mobile/bin/answer.py?hl=en&answer=169022

```

**Comment by lloyd** [comment]
+1

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
