### ISSUE TITLE
siteName and siteLogo not scrubbed from id.get()

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#2086]
User @oncletom reports that siteName and siteLogo are working for him using the old API. Should they be? We never tested those features with that API.

We should probably also check on returnTo.

**Comment by thom4parisot** [comment]
Too bad, it was a cool stuff :-(

**Comment by lloyd** [comment]
@oncletom why not use the .watch() api?

**Comment by thom4parisot** [comment]
The short way: because it was really easy with `navigator.id.get` and there was no point for us to evolve towards `watch` API.

The detailed reason:
- we don't want/need to have Persona script on every page: we use it only for login;
- our app already handles the session, we don't need another tool doing the same thing
- if we don't provide the user email to the watch API, the behavior is a total nonsense – the `onlogin` is called for every page (yet we expected to have this called only after a login)
- I find it quite weird to provide the user email on every page, just for the sake of Persona
- and finally, it's a matter of taste, the watch API is weird. Why not sticking to usual libs? `navigator.id.watch('login', function(}{ … })` etc.

**Comment by lloyd** [comment]
@oncletom Thanks for taking the time to lay out your concerns.  I really appreciate it.  Our thinking right now is that it's so important that we help users log out of a machine more easily, and so important that we streamline user experience for first time login, that we make some sacrifices - those that you describe.

As far as the resource hit (more resources on every page), the best thing I can think of doing is to focus on optimizing delivery of this content (size and latency).

As far as the api requirements (complex semantics, and needing to provide email address on every page), I'm trying to dream up how we might find a compromise and make this better.  The first part of the compromise I'm trying to find is in a new utility library that @callahad and I wrote:

https://github.com/lloyd/persona.js

I'd love your thoughts on this.  Does this _feel_ better?  Make more sense?  Fit your application better?

The second part of the compromise is challenging whether we really need email on every page.  I think it might be complex to pull off (and haven't finished thinking through fully how it would work), but what if we explore on the email list the possibility of relaxing this requirement?  What if instead of providing the email of who is logged in, you just tell us that _someone_ is logged in?

Anyhow, I take your objections seriously (I know other people will have them too), and am really curious how we can make this work better for you.

**Comment by thom4parisot** [comment]
Well, telling the user is authenticated within the page could be a good thing. Anyway technically it also remains the same stuff: JS are compiled statically wether this information is _dynamic_, according to the page (so we have to store somewhere – `data-*` or anything else) the information telling the user is logged in, and reading it from the script calling Observer API).

However, this leads to a point where anyone reading the JS code could find, and alter the DOM to make believe the user is already logged in in Persona. The security still have to be done by the app (so providing that to Persona is just a way to save resources, not solving any problem).

It would be also good to have that for functional testing.
We do functional testing (with PhantomJS and CasperJS) and at the moment, the `window.open` is hardly manageable.

Finally, if an app provides a **Login with Persona** button to a user, that's also means the user is already logged out from the app… and so, it silently says the user has to approve again the signin.
That's currently the behavior of `navigator.id.get`, which is again, simple and effective.

I'm more and more thinking having a `navigator.id.signin` and `navigator.id.signout` would do the same thing, and calling a signin (while logged in for Persona) is an implicit call to signout + signin.

**Comment by jrgm** [comment]
verified train-2012.07.30 - siteName and siteLogo have no effect in dialog when called through n.id.get() and returnTo has no effect, (although it didn't prior to this patch).
