### ISSUE TITLE
Dialog buttons not disabled during auth with primary

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2102]
Log into an RP (or login.persona.org itself) using a new eyedee.me address.

While Persona is "checking with your provider", the "next" (or "add") button becomes clickable at times (when really, you should just be waiting for this to finish).

Also, when you come back to the dialog (after successfully logging into eyedee.me with the right password), you are back on a dialog screen which momentarily has a clickable "Verify" button. Again, you should be waiting for things to finish here, not click on that button.

(Tested on Opera Mobile for Android tablets.)

**Comment by lloyd** [comment]
please re-confirm against dev?

**Comment by fmarier** [comment]
Confirmed against dev.

Steps:
1. clear all cookies
2. go to `dev.myfavoritebeer.org`
3. login using an eyedee.me address

After clicking "next" and before the screen with the "sign in with eyedee.me" button becomes visible, the next button becomes clickable again.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
