### ISSUE TITLE
Set up test case for native embedding

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#2108]
For testing native apps such as Pancake, Firefox, etc.

**Comment by lloyd** [comment]
roll into high level Q3 goal?  "Native App Integration"

**Comment by jedp** [comment]
@benadida what's the status of this bug in your mind?  What can/should I do?

**Comment by benadida** [comment]
@jedp I was thinking we would have some kind of server-side fake client that would mimick the actions of a native Firefox / FXOS client. Maybe some PhantomJS/Node thing. But really, prioritization is up to you.

**Comment by shane-tomlinson** [comment]
@jedp - is the request here integration testing of the internal API?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
