### ISSUE TITLE
Minor layout problem on Opera Mobile for Android tablets

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2119]
Just before being redirected for auth with a primary, the buttons are misaligned on Opera Mobile (Android tablet):

![Layout problem](https://raw.github.com/gist/3330829/0427fb680207c3fbf86429382907bd80d51b0daf/opera_android_tablet.jpg)

Image also available here: https://gist.github.com/3330829

**Comment by lloyd** [comment]
"the file you are looking for is moved or deleted" - lost the image!

**Comment by fmarier** [comment]
Instead of trusting cloud storage services, I should have followed [my own advice](http://feeding.cloud.geek.nz/2012/06/attaching-files-to-github-issues.html)!

Should be back now :)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
