### ISSUE TITLE
CSS Sign In buttons

### ISSUE THREAD

**Issue by tmickel** [mozilla/persona#2143]
The only available sign-in buttons for developers are PNGs.

A non-image version would be great!

**Comment by fmarier** [comment]
Indeed. It would help a lot for localization as well.

**Comment by sawyerh** [comment]
Working on this

**Comment by sawyerh** [comment]
You can preview the CSS buttons here (http://dev.sawyerhollenshead.com/mozilla/buttons/buttons.html). I wasn't sure where to upload these to.

The HTML is simply `<a href="#" class="persona-button"><span>Sign in with Persona</span></a>` and the only image used is the dark user icon. The span is used for some of the styling. Everything else, including the arrow, is CSS. This degrades gracefully in IE8, and degrades to a simple link with solid background in older versions. The unprefixed gradient syntax is reversed for the triangle so that it appears correctly in Firefox 16 (tested in Nightly)

**Comment by callahad** [comment]
Moving to MDN

**Comment by callahad** [comment]
...when Sawyer tells me he's happy with it. @sawyerh

**Comment by skinny97214** [comment]
@callahad It's ready to go.

**Comment by callahad** [comment]
Hooray! Thanks @skinny97214

**Comment by callahad** [comment]
@sawyerh Before I add those to MDN... is it just me, or is the text a little too high in the button? Adding a 1px margin-top and a corresponding negative margin-bottom to the span seems to make it look a little closer to me (2px seems like too much).

Do you agree, or should I go with it as-is?

**Comment by sawyerh** [comment]
@callahad I'd love to speak to a Firefox developer about that. Firefox does something weird with Helvetica and it's line height, causing this weird 1px discrepancy. Feel free to just change the font stack of the button to `Arial, Helvetica, sans-serif` instead

**Comment by callahad** [comment]
Done! I compressed the png down to <300 bytes and included it inline as a data URI. See: https://developer.mozilla.org/en-US/docs/persona/branding
