### ISSUE TITLE
Add support for IdP dynamic identifiers

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2156]
Using [Spec change 18](https://github.com/mozilla/id-specs/issues/18) as a guide, implement all the pieces to support dynamic identifiers.

**Comment by callahad** [comment]
This is also important for https://github.com/mozilla/browserid-bigtent/issues/66

**Comment by lloyd** [comment]
things have changed?  when is this required by now and what's the driver?

**Comment by callahad** [comment]
We have a really easy failure mode for users with multiple Gmail/Hotmail/Yahoo addresses:
1. User types `foo@gmail.com` into the Persona dialog.
2. BigTent redicts the user to Google for OpenID authentication.
3. User actually authenticates as `bar@gmail.com`, since that's what they were signed into Google as at the time.

We can't prevent this, so our only option right now is to throw up a hard failure in the user's face: "You authenticated as the wrong address."

With dynamic identifiers, we could give the user the option of continuing as `bar@gmail.com`, so it's a soft failure rather than a hard failure.

**Comment by callahad** [comment]
As for priority, this is an enhancement for BigTent, but not a blocker.

As I understand it, this _is_ a blocker for BlueVia.

**Comment by ozten** [comment]
Spec proposal is won't fix.

This should be re-visited from scratch for Bigtent.

Won't fix.
