### ISSUE TITLE
Pinning the CA for our TLS certs

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2158]
Given that Firefox 17 [will be getting CA pinning](https://wiki.mozilla.org/Security/Features/CA_pinning_functionality), we should reconsider the position we stated in GH-166 and look at getting added to the relevant Firefox and Chrome lists or providing the necessary headers.

**Comment by lloyd** [comment]
four star?

**Comment by fmarier** [comment]
So getting added to the Chromium list is easy: we just need to talk to agl. I'm guessing the Firefox preloaded list is likely to be based on the Chromium one, so should we just do it?

CCing @gene1wood because this will make certificate transitions potentially more complicated for ops.

**Comment by jaredhirsch** [comment]
@fmarier bump. any plans to handle this in the near term?

**Comment by gene1wood** [comment]
This'll depend on the web ops team (the team that issues certs for us) being open to committing to a fixed set of CAs that they'll be buying certs from. Assuming that's ok this should be pretty straight forward. The only added operational complexity is if they commit to a set of CAs and then for some reason we have to use a different one.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
