### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2160]
We don't appear to have a bug to track IPv6 support in Persona. We currently don't expose AAAA records on any of the Persona services.

I believe that this is a big deal in the developing world where IPv4 addresses are in short supply (or no longer available).

**Comment by fmarier** [comment]
The new regexp that was introduced to fix #1981 will need to be extended to support IPv6 numerical addresses.

**Comment by warner** [comment]
Other places that will need fixes (accepting ":", "[", and "]" in numeric hostnames):
- frontend validation of postMessage parameters: resources/status/common/js/user.js in the "setHostname" function (added in 780267-fixup-origin)
- the other frontend-validator in resources/static/dialog/js/modules/dialog.js (extractValidHostname)
- new tests to exercise this in resources/static/test/cases/dialog/js/modules/dialog.js (the tests only currently exercise names in URLs, not v4 or v6 addresses)

**Comment by fmarier** [comment]
As far as ops go, the first step there is to build a case (e.g. stats and numbers on Internet users in various countries that don't have IPv4 access) and then send it to Mark Mayo.

**Comment by fmarier** [comment]
http://www.ipv6.org.nz/2012/10/17/arin-scrapes-bottom-of-ipv4-barrel/

**Comment by fmarier** [comment]
This issue is blocked until Amazon adds IPv6 to ELB.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
