### ISSUE TITLE
Nitpicking on the browserid.org redirects

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2170]
I'm just nitpicking here, so please adjust the priority accordingly :)

We currently have the following redirects:

```
$ curl --head http://browserid.org
HTTP/1.1 301 Moved Permanently
Content-Type: text/html
Date: Fri, 27 Jul 2012 04:53:20 GMT
Location: https://browserid.org/
Connection: Keep-Alive
Content-Length: 0

$ curl --head https://browserid.org
HTTP/1.1 302 Moved Temporarily
Content-Type: text/html
Date: Fri, 27 Jul 2012 04:53:29 GMT
Location: https://login.persona.org/
Connection: Keep-Alive
Content-Length: 0
```

Ideally, I think that:
1. `http://browserid.org` should redirect to `https://login.persona.org` directly
2. `https://browserid.org` should have HSTS headers just like `https://login.persona.org`

**Comment by benadida** [comment]
the first point is a nitpick.

The second is not! We should retain the HSTS header for https://browserid.org since it is still being used by many web sites. @fmarier can you follow up with ops to make sure this happens? This is where we need those security regression tests.... @fmarier might you be interested in helping with this?

**Comment by fmarier** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=779710
