### ISSUE TITLE
going from /signin to /forgot via the "is this your address?" link redirects the user back to /signin

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2179]
regressions are bad.

**Comment by jrgm** [comment]
To flesh out STR (as I understand them)
1. Go to main site and click sign in. Enter the email of a known secondary email address and click sign in button.
2. Instead of entering a password, click on "forgot your password?"
3. Enter a new password twice and click 'reset password'
4. Go to email and click on the reset_password link to open in a new browser window (but same browser as the one you started in). 

Expected: window 2 shows "Your address has been verified". Window 1 should transition to show the management UI.

Actual: window 2 does as expected, but window 1 transitions to show the original /signin page with a prompt to enter email

Note: however with window 1 if you click on 'Mozilla Persona' you will see that you are in fact already signed-in.

**Comment by shane-tomlinson** [comment]
@jrgm - you STRs are the STRs for #1682 and PR #2163.

The STRs for this particular bug are:

1) Go to main site /signin
2) Enter a known secondary
3) Click "Forgot your password?"
4) It redirects to the /forgot page, then redirects back to the /signin page.

**Comment by jrgm** [comment]
@shane-tomlinson Ah sorry. Hmm. I cannot reproduce this with 07.20 or 07.30 or current dev with osx/chrome. What am I missing?

**Comment by lloyd** [comment]
@shane-tomlinson

I cannot reproduce on ansorep.org (train-2012.07.20)
I cannot reproduce on login.dev.anosrep.org right now

what am I doing wrong?

**Comment by lloyd** [comment]
cannot reproduce in our development environment anymore, nor can shane.  WFM, please re-open if you can figure out whether this is still relevant?

```
14:25 < stomlinson> lloyd: 2179 only affected dev (the current dev), it was never a problem in 7/20.
14:25 < stomlinson> and now I'm not getting it to reproduce.  grrr...
```

**Comment by jrgm** [comment]
verified not a bug now
