### ISSUE TITLE
Avoid using special characters in key names for BrowserID protocol JSON messages

### ISSUE THREAD

**Issue by magnusart** [mozilla/persona#2193]
I'm using a 3rd party library in Scala, that will generate a JSON message given an case class instance. 

However the dash in the key "public-key" is an operator and illegal to use as a type name in Scala/Java (and most other languages), so I can't easily generate my JSON messages, but will have to manually map to and from JSON in these cases. 

I suggest a change where the BrowserID protocol JSON messages refrains from having keys with dashes or other characters commonly used as operatiors in programming languages. 

Example: "public_key" or "key" instead of "public-key".

**Comment by nmalkin** [comment]
(For reference:) see the mailing list for [additional discussion](http://groups.google.com/group/mozilla.dev.identity/browse_thread/thread/a395304dbd0c6d32#)

**Comment by magnusart** [comment]
The mailing list discussion is good and a summary of my intentions boils down to this: 
1. I respect that his have a large impact therefore might not be feasable
2. To work around this is not a very hard technical challenge for the implementor and only applies to certain implementors.
3. It is more of an usability issue for implementors (avoiding surprises), it is in this - still important - light I would like it to be considered. 

Also noting that changing the wording to be "not use any special characters in the BrowserId protocol message keys" covers all cases.

**Comment by warner** [comment]
In the long run, we're changing `public-key` to `publicKey`: see https://github.com/mozilla/jwcrypto/blob/10714d9410f30cd37bfb25400d61f04b725891ff/lib/cert.js#L20 . Since this (and the other handful of format changes that it travels with) is an incompatible change, we have to move carefully. We're working on a plan this week, see https://id.etherpad.mozilla.org/format-upgrade-rollout for some working notes. Basically it involves versioned serialization formats, liberal-in-what-you-accept-conservative-in-what-you-emit handler functions, and updating all the verifiers and browser implementations before allowing the IdPs to start publishing new-format keys. It may take a year to finish rolling out, but it'll happen eventually. It might also get done before the Beta 1 milestone.

(using `public-key` is a hassle for our native Javascript too, as it forces code to use `cert['public-key']` instead of the more-natural `cert.publicKey`, so know that it's not just Scala that's feeling the pain :smile: )

In the short-term, I guess the best fix would be to use a different JSON library: I see that Jared suggested https://github.com/lift/lift/tree/master/framework/lift-base/lift-json/ (not knowing Scala I can't comment on its suitability).

I'm going to close this one out. Please feel free to re-open it or file a new one if you find other issues like this. Also, I'm told that we should file specification change requests on the https://github.com/mozilla/id-specs/ repo (i.e. treating "id-specs" as the protocol definition, and "browserid" as the flagship implementation), so feel free to file Issues over there too.
