### ISSUE TITLE
[ie8] javascript exception signing up a new user via /sign_in dialog 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2206]
I was using train-2012.07.30 to reproduce this. Does not happen with train-2012.07.06. Haven't checked dev.

STR
1) Load &lt;ephemeral&gt;.123done.org or http://127.0.0.1:10001 and bring up the /sign_in dialog
2) Enter a secondary email address that is not known 
3) Enter password twice and submit
4) Open the verify_email_address in a new browser window (same browser you started with).

Expected: normal sign-in completes
Actual: javascript exception:

```
Using <ephemeral>.123done.org:
    Line: 9
    Error: Exception thrown and not caught
    dialog.js

Using local dev environment:
    Line: 326 character 9 
    Error: Exception thrown and not caught
    state.js
```

It's easy to reproduce this so I won't transcribe the call stack from the IE8 debugger here.

Likely related to GH-2183. The exception only appears on IE8. However, with IE9 the verify_email_address window does not show a logged-into-123done state when complete. The initiating window shows logged-in UI but clicking logout does nothing and a reload shows you are logged out.

**Comment by jrgm** [comment]
Obviously 5 etoile

**Comment by shane-tomlinson** [comment]
This occurs on beta.123done.org as well.  This does NOT occur if you verify in a second browser.

@lloyd, @jrgm - This is our old localStorage in IE8 sync friend.  If I add a "setDefaultValues" to storage.js to one area, the problem goes away.

Why do I think this is the same cause as #1638?

1) The STRs for the localStorage problem previously involved two windows.  Necessary conditions for problem to manifest:

a) more than one context on the same domain, call them context A and context B
b) context A & B both want to read/write to the same field in localStorage, called localStorage.field.
c) context B writes a value into localStorage.field where the previous value was undefined.
d) context A tries to read from localStorage.field AFTER context B has written to it.  Context A still sees localStorage.field's value as being undefined.

To get around this, we found that:
a) If context A had a value defined for localStorage.field whenever context B wrote to localStorage.field, context A saw the updated value.

Our fix was to:
a) context A sets default values for _all_ fields.
b) context B does not set any default values.

2) We now have 3 contexts. The original RP (context A), the dialog (context B), and the verification window(context C).  Changes to context C effectively block localStorage sync in context B(the dialog).

The current order of ops:
1) Context A writes its default values to localStorage. Context B (the dialog) does not set any default values and in fact calls storage.js->clear because the user is not authenticated when they load the dialog.  storage.js->clear calls storage.removeItem on emails, siteInfo and managePage.  This means localStorage.emails, localStorage.siteInfo and localStorage.managePage are all "undefined" as viewed by Context B.
2) User opens Context C to verify.  localStorage.emails is written to localStorage with the email that was just verified.
3) In Context B, the new email is also written to localStorage, but localStorage returns "undefined" when querying localStorage.emails  This is identical behavior to our original STRs for a two window situation.

Why has 07.20 uncovered this bug?

user.js, line 137.  Before this commit, we were not writing the email address to localStorage in the verification page (Context C).  We were relying on the dialog to add the email to localStorage.  Since the verification page was not writing into localStorage.emails, the dialog could write to and then read from localStorage.emails without a problem.  

The new addition writes localStorage.emails in the verification page while Context B (the dialog) thinks that localStorage.emails is "undefined".  Since localStorage.emails was undefined in Context B when Context C wrote to it, Context B is shielded from writing to or reading from localStorage.emails, the same problem we had before.

Workarounds:

1) remove markAddressVerified from line 137 and depend on the dialog marking the address as verified.  I added markAddressVerified to the verification page so that their was not an implicit dependency on the dialog to perform this job.  The user may have closed the dialog, in which case an address would not be marked as verified until a sync with the backend occurs. 

For an assertion to be generated, an address must be marked as verified.  Removing markAddressVerified from line 137 still allows assertions to be generated when the user returns to the RP, but this depends on sync_emails being called whenever the user loads the RP.  @lloyd's stated goal from the comment above user.js->getSilentAssertion is to remove this sync.  Removing this sync makes it so that assertions are not generated for newly verified emails if the verification occurred with the dialog closed.  This can be verified by removing the AndSync from user.checkAuthenticationAndSync on line 1228.

2) in storage.js->storeEmails, change "storage.emails = .." to storage.setItem("emails", …);

This surprisingly works in IE8 just fine, but this is an incomplete solution in that it only takes care of the emails field.  We could use .setItem for _all_ access, but doing so requires a larger patch.

3) In storage.clear(), change all "removeItem" declarations to set the default value for those fields instead.  This would duplicate logic with setDefaultValues.

4) In storage.clear(), add setDefaultValues() after all the "storage.removeItem" declarations.  This makes sure that emails has a default value when the Verification page is loaded.

I prefer method 4 because it is the most robust and smallest change.

As a further addition, I would like to make sure that _all_ contexts run storage.setDefaultValues just to make sure no context has unset localStorage values if a new context is opened.

**Comment by jrgm** [comment]
This was never on train-2012.07.30 and is a problem there. But we're gonna pickup dev as the next shipping train on stage. This works in dev now, so will pick up the verify in stage.

**Comment by jrgm** [comment]
verified train-2012.08.17
