### ISSUE TITLE
Sometimes, a blank Persona screen loads during login on Fennec nightly

### ISSUE THREAD

**Issue by krupa** [mozilla/persona#2241]
## Environment:
- Android 4.0.1/Galaxy Nexus
- Fennec Nightly
- Persona prod
## Steps to reproduce:
1. Go to https://marketplace-dev.allizom.org
2. Click on Login link in the footer
## Expected behavior:

Persona screen opens with a way for the user to enter their login credentials.
## Actual behavior:

A blank Persona screen loads. User cannot proceed ahead with logging in.
## Reproducible?

Sometimes.
## Screenshot

http://cl.ly/image/2t0O1r1n371A

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
