### ISSUE TITLE
Weird ghost text prefilled in password field with HTC Incredible S Android 2.3.4 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2242]
I was going through GH-2088 on multiples browsers/os and borrowed a 2.3 Android device from tchung, and came across this oddity

![img](https://img.skitch.com/20120808-3yumbf3tadc2cnkw5m18ir91a.png)

You'll notice that email address is shown in the 'enter password' field. But that's not actual editable text as I couldn't change it in any way; I could only type over it, which would make it disappear. If I set focus elsewhere, it changed to the expected 'enter password' placeholder text. It's just weird. Why is it monospace? Why is it not the complete email address?

This was with this phone: 2.3.4, Stock browser webkit/533.1, HTC Incredible S S710e, HTC Sense 2.1

I tried with a second similar phone: 2.3.4, Stock browser webkit/533.1, HTC Sensation 4G, HTC Sense 3.0, but could not reproduce this on that phone.

**Comment by shane-tomlinson** [comment]
@jrgm - I have seen this on an HTC Desire HD running Android 2.3.5

**Comment by csuciu** [comment]
Still an issue on HTC Desire (2.2.2) - stock browser

**Comment by shane-tomlinson** [comment]
This is an upstream bug with the Android 2.x browser. I'm trying to find the relevant links.

**Comment by shane-tomlinson** [comment]
https://code.google.com/p/android/issues/detail?id=30964
http://stackoverflow.com/questions/6828263/how-to-get-rid-of-placeholder-on-password-field-taken-over-from-label
http://stackoverflow.com/questions/12035895/absolute-positioning-with-inputs-in-android-2-2-web-browser

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
