### ISSUE TITLE
[ARMv6] Strange appearance and behavior for log in with Persona (BrowserID) 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/persona#2283]
Build ID: 17.0a1 (2012-08-14) Nightly Channel
Device: LG Optimus One P500
OS: Android 2.2

Steps to reproduce:
1. Open Fennec -> Go to www.moztrap.mozilla.org
2. Press Sign in - upper right corner
3. Press Mozilla Persona text/link

Expected result:
- Persona (BrowserId ) should be loaded - you should be able to log in

Actual result: 
- The Persona (BrowserID )is loaded but there is no background image display, only white pages and link to different secondary pages

**Comment by ioana-chiorean** [comment]
screenshot : https://bug782631.bugzilla.mozilla.org/attachment.cgi?id=651747

**Comment by lloyd** [comment]
let's determine whether this is an upstream bug or not.  does this occur in any other environment?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
