### ISSUE TITLE
IE8: Tooltip causes form field to lose focus

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2294]
STR

1) Load up either the dialog or main site in IE8
2) Enter incorrect data into a form field.
3) Press enter.
4) The form field has lost focus.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
