### ISSUE TITLE
IE8: If page is scrolled, tooltip shows up in wrong position

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2295]
STR

1) Load up the account manager in IE8 for an account with at least one secondary
2) Scroll down the page
3) Try to change the password but enter an incorrect old password
4) Press enter
5) The tooltip is displayed somewhere over the email addresses

![Clip showing tooltip](https://img.skitch.com/20120815-qkg1uha7amw5sradn1chfqd3nf.jpg)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
