### ISSUE TITLE
tablet: difficult to click on Persona tos link in landscape mode

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2299]
STR

1) On a tablet, load up dev.123done.org
2) Clear localStorage
3) Open the Persona dialog
4) Try clicking on the Persona's Terms link.   It took me 5 tries.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
