### ISSUE TITLE
Android 4.0 - Confirm your email address screen still shows password input field

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2301]
STR

1) On Android 4.0 Tablet (I am using an Asus EE Transformer), open dev.123done.org
2) Open Persona dialog using a primary only account
3) Click on "Add an email address"
4) Enter secondary email address
5) Fill out password
6) Click "Sign In"

![Android Password shows through](https://img.skitch.com/20120815-mpbb41j8bjnf5msespt5rqxwf.png)

**Comment by shane-tomlinson** [comment]
Link to #1837, these may have the same root cause.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
