### ISSUE TITLE
with Javascript disabled, footer partially obscures TOS/Privacy pages when user scrolls

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2302]
STR

1) In Firefox disable Javascript
2) Go to https://login.dev.anosrep.org/privacy
3) Scroll the page

![footer obscures content](https://img.skitch.com/20120815-m3c5mtu3fe63t9xweahhkdqyi8.jpg)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
