### ISSUE TITLE
IE8: Main Site Headers incorrect if Javascript is disabled

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2304]
STR

1) Load up IE8, disable Javascript (Tools->Internet Options->Security->Custom Level->Scripting->Active Scripting->Disable)
2) visit https://login.dev.anosrep.org/signin

![IE8 header incorrect if Javascript is disabled](https://img.skitch.com/20120815-827tjake11rmx6kwyxrh4w1pkt.jpg)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
