### ISSUE TITLE
Upgrade to jQuery 1.8 and use only components that are necessary

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2306]
From http://blog.jquery.com/2012/08/09/jquery-1-8-released/

```
Modularity: If you know your project’s jQuery dependencies well, you can use 
the new grunt-based build system to strip out parts of jQuery that you know you 
don’t need. What we’ve done here for 1.8 is really just a beginning, you’ll see 
even more flexibility as we move to later versions.
```

**Comment by pdehaan** [comment]
FWIW, the current latest jQuery 1.x branch version is 1.10.2: http://code.jquery.com/jquery/
Shane was mentioning that we should stick w/ the 1.x branch since it has the most backwards compatibility w/ IE8+/-.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
