### ISSUE TITLE
Confirm email addition in 2nd browser causes email_addition_status to return 400 "Bad Request"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2307]
STR

Requires two browsers.

1) In Browser A, Open dev.123done.org.
2) Open dialog, sign in with primary only account
3) Sign out of dev.123done.org, open dialog.
4) Click "Add new email address"
5) Enter account's first secondary address
6) Enter password
7) Submit form
8) In Browser B, Open email provider
9) Click verification link in email
10) Watch Browser A blow up.

Exact error in Browser A:

```
Action: Registration Failed
Network Info: GET: /wsapi/email_addition_status?email=set117%40gmail.com

Response Code - 400

Response Text: Bad Request: requires authentication

Error Type: Bad Request: requires authentication
```

![email_addition_status returns 400, Bad Request: requires authentication](https://img.skitch.com/20120815-d6er2wgbbuw8u6qwh7f6wugcic.png)

**Comment by zaach** [comment]
This appears to have been introduced with the new password change, session reset feature. The session is being reset [here](https://github.com/mozilla/browserid/blob/dev/lib/wsapi.js#L154).

/cc @warner

**Comment by warner** [comment]
@zaach and I are looking at this. We're looking suspiciously at [db.completeConfirmEmail](https://github.com/mozilla/browserid/blob/dev/lib/db/mysql.js#L400) which calls db.updatePassword with the "please update `lastPasswordReset`" flag set to "true". We think that if it were given "false", then the session would not be clobbered, and browser A would not get an error.

Why is `completeConfirmEmail` trying to (sometimes) reset the password hash? I can't figure out which code paths would lead into this method, so I don't know where to look for `o.passwd` being set or not. Is it possible that this whole clause is unused, and `o.passwd` will always be undefined?

Anyways, setting that "true" to "false" is probably the immediate fix, but we don't yet know what that might break.

Also, it would be nice if browser A's code that is polling `email_addition_status` could respond to a 400 Unauthorized by jumping back to the login page, instead of exploding like this. Fixing this bug should avoid creating the 400, but in the long run we should fix both.

**Comment by jrgm** [comment]
verified train-2012.08.17 on ephemeral https://train0817.personatest.org for original STR and also reviewing db state.
