### ISSUE TITLE
"New to Mozilla Persona" banner shown every time the user logs out and logs back in

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2311]
STR

1) Visit /signin
2) sign in with already existing account
3) visit manage page, look at yellow banner
4) sign out
5) go to step #1

Maybe do something like the "Is this your computer".

**Comment by jrgm** [comment]
We seem to resetting managePage to {} at signout. (It is set and even persisted to disk, but is gone again after logout).

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
