### ISSUE TITLE
IE6/IE7: exceptions thrown on main site /

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2313]
STR

1) Load up IE7
2) visit https://login.dev.anosrep.org

```
Line: 9
Char: 14861
Error: 'JSON' is undefined
Code: 0
URL: https://login.dev.anosrep.org/
```

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
