### ISSUE TITLE
Android Chrome Beta on tablet: Intermittent inability to scroll manage page in landscape mode

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2325]
STR

1) In Chrome Beta for Android, sign in to a Persona account from dev.123done.org
2) Place the tablet in landscape mode and browse to login.dev.anosrep.org
3) Try to scroll - sometimes it works, sometimes it doesn't.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
