### ISSUE TITLE
Mobile: /verify too much space to the right of the form

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2326]
STR

1) Add a new email to an existing account
2) Open the verification email in portrait mode on a mobile device

![Too much space to the right of the form](https://img.skitch.com/20120816-pt1fxm4epfr2cuds84pk3ckqk4.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
