### ISSUE TITLE
Android Native/Fennec: ugly line across screen

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2327]
STR

1) Visit the main site using the Android Native or Fennec Mobile browsers on Android 2.3
2) Check out the ugly line
### Android Default

![Android Default Browser Line](https://img.skitch.com/20120816-mx5p7hhrwuwriah151uw9drnqx.png)
### Fennec

![Fennec Line](https://img.skitch.com/20120816-r9cc7x4jry49hx29qfjq8w7a3y.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
