### ISSUE TITLE
Android 2.3 native: main site footer alignment issues

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2328]
STR

1) With Android 2.3 native browser, visit the main site
2) Check out the footer

![Android Footer Alignment Issues](https://img.skitch.com/20120816-qpxi97ue1e32tpubfc7j93ic54.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
