### ISSUE TITLE
Mobile: /about page inconsistent margins around "Real Privacy."

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2329]
STR

1) Load up https://login.dev.anosrep.org/about on a mobile device
2) Scroll to "Real Privacy."
3) Margin above and below is inconsistent.

NOTE: This affects desktop browsers too.

![Inconsistent Margins around "Real Privacy"](https://img.skitch.com/20120816-ridny94kcgmqkibhsatcbmmdxa.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
