### ISSUE TITLE
Mobile: Too much margin around TOS/Privacy in landscape mode

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2330]
STR
1) Load up https://login.dev.anosrep.org/tos or https://login.dev.anosrep.org/privacy on a mobile device.
2) Turn the device to landscape mode
3) Check out those margins

![Large margins in landscape mode on a mobile device](https://img.skitch.com/20120816-nf12nj6geumgr79tkbfjw3kg36.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
