### ISSUE TITLE
Mobile: Change password section on manage page has very narrow form fields

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2331]
STR

1) On a mobile phone in portrait mode, visit https://login.dev.anosrep.org/signin and sign in with a secondary account.
2) Visit manage page.
3) Under the "Password" section, click "edit"
4) Check out how narrow those fields are.

![Narrow fields on mobile](https://img.skitch.com/20120816-kwum68ge14d694e658ji3bwibr.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
