### ISSUE TITLE
iOS 4.3 iPod/iPhone: Dialog rendered for desktop browser.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2332]
STR

1) On iOS 4.3 iPhone (or simulator), open up dev.123done.org
2) Open the dialog.
3) Check out how it renders

I realize iOS 4.3 is not on our [official supported browser list](https://developer.mozilla.org/docs/persona/Browser_compatibility), but everything works fine except this.

![iOS4.3 dialog screenshot](https://img.skitch.com/20120816-jab9msq5x1rfa419be36xrhip2.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
