### ISSUE TITLE
keyboard accessibility: manage page "password" done button not clickable using the keyboard

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2344]
STR

1) Load up login.dev.anosrep.org and sign in
2) Go to /
3) Using the keyboard, tab to the password "edit" field
4) tab to the "done" button
5) click "enter"

Specific bug for #869

**Comment by shane-tomlinson** [comment]
Link to #2981

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
