### ISSUE TITLE
[iphone safari] 123done: logged in state not always reflected between two windows

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2357]
Sorry, I don't have 100% STR. Some times it works some times not. 

1) Use safari on the iphone. Open dev.123done.org and auth as a secondary.
2) Open a second window and load dev.123done.org, which will show you as logged in. 
3) Repeatedly log out of one window, check that the other window reflects the logout. Then login in one window, and check that the other window is logged in. Sometimes use the left window as "the other window" and sometimes use the right window. 

Not always, but sometimes, despite being logged in to one window, the other window does not show that. (And to be clear this is after setting focus on the second window, not just checking the preview display).

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
