### ISSUE TITLE
Example RP has redirect error on Windows

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2367]
Opening `http://localhost:10001` in a browser while running browserid on a Windows machine will server a `301 /` response.

Current workaround is to remember to go to `http://localhost:10001/index.html`.

This was fixed in `connect.static()` in [connect@2.0.2](https://github.com/senchalabs/connect/commit/a9f20e450b8c197e22da41d3d1d610685878489d), and we're currently using `connect@1.7`, because of `express@2.5`.

**Comment by shane-tomlinson** [comment]
@seanmonstar - We are on express 2.5.0 right now, does this problem still exist? If not, can you close it down?

**Comment by seanmonstar** [comment]
I believe so, but I can't currently test since `toobusy` fails on Windows.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
