### ISSUE TITLE
clear 'usersComputer', etc., when user says 'This is not me'

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2387]
It seems to me that when the user clicks 'This is not me' **all** information in localStorage should be cleared. Currently the emails key is cleared, but   'emailToUserID', 'usersComputer', and others are left behind.

**Comment by jrgm** [comment]
Related to GH-2335, or perhaps the same thing?

**Comment by shane-tomlinson** [comment]
@jrgm, @lloyd - this is by design to keep track of which users have answered the "is this your computer" screen. A field that should be removed when a user signs out is loggedInEmails. Once the user's site->email list is cleared on logout, there is no value in this information hanging around. I'll file a separate issue for that, I have the fix in a branch already.

Shane
