### ISSUE TITLE
[ie8] leftover from GH-2087 - main site confirm screen - password field not automatically focused

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2395]
Doesn't work on ie8/winxp. What a surprising thing.

STR

1) In Browser A, open dialog to email picker
2) In Browser A, add a new secondary email
3) In Browser B, make sure user is logged out.
4) In Browser B, open verification email
5) In Browser B, password field should be focused.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
