### ISSUE TITLE
 on a samsung galaxy tablet, I can't click the 'forgot password' link

### ISSUE THREAD

**Issue by jmaher** [mozilla/persona#2397]
I cannot click on 'forgot password' as the 4 times I tried it did nothing.

**Comment by jmaher** [comment]
this was found on Firefox Mobile Aurora during a testday for marketplace and webapps.

**Comment by jmaher** [comment]
originally filed as https://bugzilla.mozilla.org/show_bug.cgi?id=785419

**Comment by shane-tomlinson** [comment]
Is this a dup of #697?

**Comment by shane-tomlinson** [comment]
Link to #2299

**Comment by seanmonstar** [comment]
@jmaher Did anything happen at all? As I use Nightly for Android regularly, I find on many sites, sometimes tapping on links does nothing at all.

Possibly related: https://bugzilla.mozilla.org/show_bug.cgi?id=787540

If this is only in Firefox for Android, and not on stock browser or Chrome, I'd say mark this upstream.

**Comment by jmaher** [comment]
Nothing happened at all.  It seemed to be a dead link.  I just tested with
the stock browser and I am unable to click on the forgot your password link
as well.

**Comment by seanmonstar** [comment]
Interesting. The link works correctly on my tablet, in both Browser and Firefox 18.

I've got a Galaxy Tab 10.1, running Android 4.1.1.

**Comment by jmaher** [comment]
I have a Galaxy Tab 10.1 running Android 3.1, I am going to upgrade it and
try again.

**Comment by seanmonstar** [comment]
Well, it's not an official upgrade. I believe the Tab is officially at 3.2.

**Comment by shane-tomlinson** [comment]
Link to #2473

**Comment by jedp** [comment]
This is ten months old; still a four-star?

**Comment by shane-tomlinson** [comment]
@jmaher - are you still able to reproduce this?

**Comment by edwindotcom** [comment]
I have a galaxy nexus in office, i'll test then.

**Comment by pdehaan** [comment]
I'm UTR on my Nexus 7/Android 4.3 w/ 123done.org and Firefox Nightly 27.0a1.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
