### ISSUE TITLE
Adding existing primary email account to secondary email account does not expire session

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2405]
In looking at GH-2026 and going through permutations, I came up with this quirk. I can see a possible argument that this is correct behaviour and it may be already accounted for in the code (haven't checked). Anyways:
1. In browser-1 use 123done to signup a primary email address. (That user will have a password of NULL and a lastPasswordReset of NOW()). Leave that browser signed in to 123done.
2. In browser-2 user 123done to signup a secondary email address (passwd NOT NULL, lastPasswordReset NOW()).
3. In browser-2 add the primary email address from (1). (primary email id is recreated and linked to the user account from (2)).
4. In browser-1 reload the page. 

In a sense, the primary email's password has changed, but their session is not invalidated.

**Comment by callahad** [comment]
Potentially not-a-bug. @lloyd to review.

**Comment by jaredhirsch** [comment]
@lloyd, thoughts here? bumping to Beta 3

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
