### ISSUE TITLE
https://persona.org/include.js redirects to https://login.persona.org/include.js

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2419]
This issue is similar to GH-2097. It's possible that RPs will start using the wrong URL and limit our ability to change what we do with https://persona.org (top level domain).

I'd like to propose that this redirect shouldn't exist:

```
https://persona.org/include.js => https://login.persona.org/include.js
```

Instead, it should return a 404.

Note: before we do this, we should look at our access logs to see if persona.org/include.js is used by anyone. Then, we probably need to send a note to persona-notices.

**Comment by callahad** [comment]
Yeah, having persona.org work is crazytalk. Nuke that. (Well, see if anyone is hitting it, then nuke it)

**Comment by callahad** [comment]
Assigning to @gene1wood to check the logs.

**Comment by jaredhirsch** [comment]
Valid but too big to get done before Beta 2. Bumping to Beta 3.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
