### ISSUE TITLE
http://login.persona.org/include.js redirects to the right script

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2420]
Related to (but slightly different from) GH-2419.

Currently we have the following redirect:

```
http://login.persona.org/include.js => https://login.persona.org/include.js
```

I would argue that while it's good to have a general HTTP to HTTPS redirection:

```
http://login.persona.org/* => https://login.persona.org/*
```

in this specific case, it means that if an RP makes the mistake of using a script tag like this:

```
<script src="http://login.persona.org/include.js"></script>
```

then it will work but users will be vulnerable to SSL stripping attacks.

I'd like to propose these rules instead:

```
http://login.persona.org/include.js => 404
http://login.persona.org/* => https://login.persona.org/*  (as long as it's not "include.js")
```

Note: before we do this, we should look at our access logs to see if http://login.persona.org/include.js is used by anyone. Then, we probably need to send a note to persona-notices.

**Comment by callahad** [comment]
+1 for checking usage then nuking.

**Comment by callahad** [comment]
Assigning to @gene1wood to do the log scraping

**Comment by jaredhirsch** [comment]
doesn't seem beta-2 necessary to me. bumping to beta-3

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
