### ISSUE TITLE
navigator.id.logout() callback needs deprecation warning

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2427]
The callback argument for `navigator.id.logout()` has an inline comment about deprecation, but should also log a warning letting developers know.

**Comment by graue** [comment]
Why is the callback argument deprecated? How else are you supposed to know that the logout has completed and it's safe to redirect to a different page?

This issue is the only relevant search result I could find — [MDN docs don't mention the callback](https://developer.mozilla.org/en-US/docs/Web/API/navigator.id.logout) or explain what to do instead.

Edit: Sorry, I'm a moron. 30 more seconds spent looking at the MDN docs would've shown me the new preferred way is to provide a callback to `navigator.id.watch`. Disregard this, please. (Or mention `navigator.id.watch` in the deprecation warning, if you want to be really moron-proof.)

**Comment by fmarier** [comment]
@graue the callback has been moved to [navigator.id.watch()](https://developer.mozilla.org/en-US/docs/Web/API/navigator.id.watch).

See https://developer.mozilla.org/en-US/Persona/Quick_Setup for how everything fits together.

**Comment by graue** [comment]
Thanks, Francois — I'd sort of figured it out, but this will be useful because `navigator.id.watch` seems to require a different architecture from what I've got now.
