### ISSUE TITLE
Password reset: landing page says "Your address has been verified!"

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2471]
Steps:
1. clear cookies
2. go to https://login.anosrep.org
3. type in a (secondary) email address
4. click the "forgot password" link
5. type in a new password
6. check your email and click on the link

The landing page you get after successfully resetting your password is:  "Your address has been verified! "

**Comment by jrgm** [comment]
Actually this is fixed in current login.dev.anosrep.org, no? See GH-2424

**Comment by fmarier** [comment]
Here's the landing page I get from `login.dev.anosrep.org`:

![Password reset confirmation page](https://raw.github.com/gist/3719384/0ac9ee774fbaed672ff1aa95159c1bb984b0fecc/confirm_password_change.png)

It does redirect correctly to the management page after 5 seconds, but the first page you see does talk about email verification, not password reset.

Maybe that's a 1-star or 2-star issue?

**Comment by jrgm** [comment]
Ah, sorry. I forgot this was about the language ('address has been verified' vs. 'password has been reset'). Thanks for reopening and fixing my mistake.

**Comment by jrgm** [comment]
And this is still 3-star. I just confused this issue with some others.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - What do you think about this post-password reset text, can it be made more intelligible? 

![password-reset-text](https://f.cloud.github.com/assets/848085/1114338/8c9f7a66-1a17-11e3-88ae-7e52b962ccd4.png)

**Comment by ryanfeeley** [comment]
I just reset my password and went through this experience. I don't understand the need for the redirect screen. Why can't it just go to something like:
![screen shot 2013-09-10 at 11 03 54 am](https://f.cloud.github.com/assets/68213/1115385/4759c7be-1a2a-11e3-9ad2-a534c3c684fb.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
