### ISSUE TITLE
Unable to lazy load include.js file

### ISSUE THREAD

**Issue by jmathai** [mozilla/persona#2472]
Ideally you could lazy load the include.js file once a user clicks to log in. Doing so triggers the popup blocker in Firefox.

It's sort of a known issue but having a solution would be nice. One idea is to create the popup and then pass a reference to it into the `getVerifiedEmail` function. I'm not terribly happy with that proposal but thought I'd at least open an issue to track it.
- [JSFiddle of working implementation](http://jsfiddle.net/KRtZ4/)
- [JSFiddle of broken implementation](http://jsfiddle.net/vRW75/)

**Comment by lloyd** [comment]
include.js is 5k compressed.  Why bother lazy loading?

**Comment by jmathai** [comment]
@lloyd Seems like I should still have the option to lazy load it. A couple thoughts though...
1. There are workarounds
2. 5k isn't large but it's also non-zero
3. The reason for the existing behavior exists at the browser level for security reasons (unwanted popups)

Number 3 alone might make this a WONTFIX. Perhaps a nice to have but still valuable to keep page weight as low as possible.

**Comment by shane-tomlinson** [comment]
@jmathai - lazy loading implies that you are using navigator.id.get and not the navigator.id.watch/request API? I have not tested lazy loading in any form, but have you tried adding include.js asynchronously just after DOMContentLoaded/onload but before the user clicks on the login button? 

You could do something like wait for DOMContentLoaded, add include.js asynchronously, as soon as include.js is ready, show your login button.

**Comment by jmathai** [comment]
@shane-tomlinson I was just trying that. I imagine that will work. Stay tuned...

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
