### ISSUE TITLE
Chrome for Android Tablets: hard to tap the next button -- "Terms" link too close

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2473]
The button looks like it's large enough, but during my testing, I only had a 50% success rate in tapping the button instead of the "Terms" link. It was not a big deal, but definitely irritating.

![Button and links](https://gist.github.com/raw/3704774/22ff94d25003724d4faa691383bda6ec253538dd/Screenshot_2012-09-12-17-56-45.jpg)

Perhaps we could add a bit of whitespace to move the TOS/PP links away from the buttons?

**Comment by shane-tomlinson** [comment]
Linking to #2299

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
