### ISSUE TITLE
npm test doesn't work on Windows

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2490]
A couple of things prevent the full test suite from running on Windows with the command `npm test`.
- needs to be `node ./scripts/test`
- `test_backend` is in bash
- `start-stop` relies on Signals, which don't work in node <=0.8.x on Windows

Possibly others...

**Comment by shane-tomlinson** [comment]
@seanmonstar - does this now work for you?

**Comment by seanmonstar** [comment]
Nope, `test_backend` is still bash, and the `start-stop` still relies on `signals` that don't exist on Windows.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
