### ISSUE TITLE
Rarely used email addresses should be reconfirmed periodically in the fallback IdP

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2494]
Given the following scenario:
1. Alice creates Persona account.
2. Alice adds `alice@isp.net` and `alice@vanitydomain.com` to her account.
3. Alice stops paying for `vanitydomain.com` and lets the domain expire.
4. Bob buys `vanitydomain.com` and gives `alice@vanitydomain.com` to his wife.

The new owner of `alice@vanitydomain.com` is Bob's wife, but the original Alice still has it in her Persona account and therefore could login as Bob's wife on certain sites (especially the ones that support more than one authentication system).

The problem (which is very common all over the web) is that the fallback IdP claims that Alice owns the email address whereas it only knows that Alice **has owned that email address in the past**.

There are two ways to fully resolve this discrepancy:
1. `vanitydomain.com` becomes a primary IdP
2. the fallback IdP asks users to confirm their email every time they login

Of course, #2 is unrealistic from a UX point of view. However, perhaps it wouldn't be too much to ask users to reconfirm addresses they rarely use.

For example, we could ask users to reconfirm any email address they haven't used in 1 year, the next time they try to use it to login somewhere. (This "1 year" period is completely arbitrary, maybe it could be shorter, I'm not sure.)

**Comment by warner** [comment]
Yeah, I think that's a good idea. I need to think a bit about what's being bound to what (clearly Bob's wife shouldn't get control over the rest of Alice's account), but I think periodic reconfirmation is appropriate.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
