### ISSUE TITLE
Forgot password UX is confusing

### ISSUE THREAD

**Issue by sprice** [mozilla/persona#2499]
Presently, if a user forgets their Persona password they click "forgot your password?", enter a new password and click "reset password". This sends an email to the Persona account holder with an activation email link.

Any random user can enter any Persona account they want and choose a new password. They only need the account holder to click the activation link to have control of the Persona account. The activation link does say something along the lines of "Only click this if you asked to reset your password" but not all users will see this.

To retrieve a forgotten password, an account holder should click "forgot your password" and then click "reset password". They should receive an activation link which then prompts them to enter a new password.

Edit:// updated title. see my next comment below

**Comment by callahad** [comment]
Related: #1629, #1913

**Comment by shane-tomlinson** [comment]
@sprice - You can try our defenses of this case for yourself.

1) Open two distinct browsers. Browser A will simulate malicious user, Browser B innocent victim.
2) In Browser A (acting as the malicious user), go through the "forgot your password flow" and set a new password.
3) In Browser B (acting as the victim), open up the email.

Persona recognizes that Browser B is not the same as Browser A and forces the user to enter _the same password_ that malicious user entered. The victim's password is only reset when he/she enters the same password as the malicious user.

The user of Browser A will only ever gain access to the victim's account if they can successfully guess what password the victim will enter, otherwise they are blocked. The worst the malicious user can do is spam the victim's email account with password reset verification emails.

**Comment by callahad** [comment]
Oh, wow, we're doing that? I totally need to spend more time in core. That's awesome.

**Comment by sprice** [comment]
Ok this is a good thing. I've updated the issue title.

Based on this workflow I assumed that my account had been compromised (it was a co-worker who tried to hijack my account). After I clicked on the verification email I was asked to enter my password. As stated above the password didn't match so the error message was something along the lines of "password does not match". I took this to mean I could not log into my account.

It might be helpful if the error message was "Password does not match. Account reset has not occurred and your old password still works" Only with better wording :)

**Comment by lloyd** [comment]
@skinny97214  , see the last comment, any ideas on better language?

**Comment by skinny97214** [comment]
Fixing GH-1232 will address the confusing UX issue. @lloyd should we close as dupe?

**Comment by shane-tomlinson** [comment]
Closing as dup of #1232
