### ISSUE TITLE
Monitor requests in the router

### ISSUE THREAD

**Issue by zaach** [mozilla/persona#2508]
This is a blocker for #1744

We'll need to monitor requests in order to determine when to show captchas.

It will required a new database server for persisting request data (likely redis).

**Comment by jaredhirsch** [comment]
Valid but too big to get done before Beta 2. Bumping to Beta 3.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
