### ISSUE TITLE
Identity Certificate seems to now require an "iat" claim

### ISSUE THREAD

**Issue by mook** [mozilla/persona#2509]
https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/user.js#L44 checks for an "iat" property ("issued at", apparently) on the cert.  This was not previously required, and broke my custom IdP.  (My change to fix it is https://github.com/mook/browseridp/commit/23c745c9a342f3cc0c4379b97bb466b956b8810a .)

This may have broken other IdPs; I don't know.  It would be nice to 1) make sure this is intentional, and 2) document that if so.

The fix for IdPs isn't that hard, but it was difficult to track down; the user-visible behaviour is that the Persona login dialog (the blue/grey thing) says "email verified", and gets stuck (the wedge thing doesn't slide to the right), until it gives up and fails.  In the mean time, it sends over traffic that looks pretty much exactly like the case when the login succeeds.

**Comment by shane-tomlinson** [comment]
@mook - looking at GitBlame, this line was added on November 18th of 2011, so it is nearly a year old. 

@lloyd, @warner - does iat need to be added to the IdP docs?

**Comment by shane-tomlinson** [comment]
@mook - my mistake, my GitBlame line numbers were not lining up. This chyange was made on May 3rd, 2012 by @benadida. @benadida, the same comment applies, does this need to be added to the IdP docs?

**Comment by jrgm** [comment]
Is this issue still relevant?

**Comment by mook** [comment]
Sort of; I'm having issues figuring out which spec I should be looking at.  [prod](https://github.com/mozilla/id-specs/blob/prod/browserid/index.md#identity-certificate) is missing `iat`; [beta1](https://github.com/mozilla/id-specs/blob/beta1/browserid/index.md#identity-certificate) is more complete and has it documented.  The default branch seems to be `prod` (which means that won't actually work in production, I think).

**Comment by callahad** [comment]
We need help finishing the spec update. Any takers?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
