### ISSUE TITLE
Running the verifier on a separate IP address to avoid relying on SNI

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2527]
To avoid [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication)-related problems for people that [run sites on old servers](https://groups.google.com/forum/?fromgroups=#!topic/mozilla.dev.identity/vwS9ERSyn4A), I think we should have the verifier be on a separate IP address.

This separate IP address would have a single vhost and therefore always offer the same SSL cert.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
