### ISSUE TITLE
New cert code and BrowserID Addon are incompatible with each other.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#253]

**Comment by benadida** [comment]
incompatible, or is it that the add-on doesn't support the additional calls?

**Comment by shane-tomlinson** [comment]
@benadida - include.js checks for the existence of navigator.id, and if it exists, it bails completely.  Since the addon provides navigator.id, the functions regarding the certs never get added to navigator.id.  What would the repercussions be if include.js was modified to provide any functions that are missing from navigator.id - ie, getVerifiedEmail may be provided by the addon, but generateKey, registerVerifiedEmailCertificate and checkVerifiedEmail are still added by include.js

**Comment by benadida** [comment]
@shane-tomlinson I wouldn't recommend that, because, if the browser implements some of navigator.id._, you can't quite assume *how_ it's implementing it, so how would you implement the other calls? I would say the way include.js currently works is probably right. The browser should implement all the calls, or none.

**Comment by lloyd** [comment]
I'd suggest we keep the addon and web implementations decoupled.  I don't think this should block certs from going into beta next thursday.

**Comment by benadida** [comment]
oh yes, I don't mean to couple them, but they do have to support the same API :)

**Comment by lloyd** [comment]
this issue is moved to browserid-addon: https://github.com/mozilla/browserid_addon/issues/84
