### ISSUE TITLE
Dialog doesn't make it clear what password it's asking for

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2539]
From a [hacker news thread](https://news.ycombinator.com/item?id=4581926):

"It does seem a pretty elegant way to log in, the only concern i have is that it's kind of unclear what password i needed to use to login. I had already created a browserID password at some point in the past, so when i went to the times crossword and clicked sign in, i was prompted for a password. my first thought was maybe i had already signed up for the times crossword, so i tried the password i probably would have used to sign up for a site like that. nope, but it said "authenticating with your email provider". So then i tried my email password, thinking maybe it was integrating with my google account. nope. Third try was the password i had used to sign up for persona.

Maybe in the future, if this sees wide adoption, they can get away with just putting some mozilla branding in the corner, but for now there should really be some explanatory text on the login window telling you that you need to enter the password you created for mozilla persona, or this is just going to confuse users."

**Comment by Flimm** [comment]
My suggestion would be to make the placeholder text "your Persona password", instead of just "password".

Another suggestion would be to change the instructions to say: "Now enter the password associated with your Persona". This would replace the stale instructions: "To sign in with Persona, please enter your email address."

**Comment by seanmonstar** [comment]
I like both of those suggestions, personally.

**Comment by sergiotapia** [comment]
I agree, as it stands the prompt confused me for a bit. We should try to avoid mental gymnastics on our users.

Something like, "Enter your Persona password." would be simple and poignant enough.

**Comment by lloyd** [comment]
+1

**Comment by ozten** [comment]
Having a Persona Glyph in the password field would be splendid. +1

**Comment by skinny97214** [comment]
Ack! This screen got missed in the copy revamp. Here's the relevant page that specifies the copy should read:

"Enter your Persona password"

*note: not "PersonaID"

http://cl.ly/image/3N043y2I1x3O

**Comment by lloyd** [comment]
+1 from me too.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
