### ISSUE TITLE
Convert scripts to use ShellJS

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2544]
In #2537, @mathewp pointed out we can use https://github.com/arturadib/shelljs for our scripts. Other Mozilla projects already use it, and it looks awesome. This would be a huge win for Windows (!).

**Comment by shane-tomlinson** [comment]
@seanmonstar - is this still applicable since we use .js scripts for just about everything?

**Comment by seanmonstar** [comment]
It was simply easier to read and program than plain nodejs code.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
