### ISSUE TITLE
escape key binding for popup window

### ISSUE THREAD

**Issue by bryandonnovan** [mozilla/persona#2554]
please consider adding an escape key binding to dismiss the popup window

**Comment by seanmonstar** [comment]
The default to close tabs/windows is Ctrl + W

**Comment by lloyd** [comment]
if there were a pull request for this, I'd merge it!

**Comment by bryandonnovan** [comment]
The persona popup is a Dialog Box, not a top level window or tab.

According to Microsoft's UX guidelines,
http://msdn.microsoft.com/en-us/library/aa511268.aspx#modelessDialogBoxes,
Pressing
the Esc key always closes an active dialog box.

**Comment by shane-tomlinson** [comment]
I second @seanmonstar's opinion here - ctrl-w is the known and accepted standard for closing tabs/windows within web browsers. Closing the window on escape adds a non-standard behavior that would break user expectations about what they can and can't do within a browser tab/window.

@skinny97214 - can you weigh in here?

**Comment by jrgm** [comment]
Actually, I think being able to dismiss the popup with ESC would be be a valuable improvement. (Compare to bringing up preferences in FF and dismissing that with ESC; yeah not quite the same thing, but anyways).

**Comment by jaredhirsch** [comment]
+1 for closing this as wontfix.

I'd agree that ESC should close the dialog, if it were a dialog lightboxed inside the existing window. It isn't. It's a popup window.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
