### ISSUE TITLE
enforce version dependencies during rpm building and installation

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2586]
`browserid.spec` can express more specific version dependencies on build-time and run-time required software.  This would help us perform better checking of applications assumptions and help us find issues sooner.

The catch is, we should not represent node version in multiple places - it's already present in `package.json`

**Comment by ozten** [comment]
Editing package.json and browserid.spec doesn't seem horrible. We could add a vows test to make sure they have the same value.

Otherwise... we could make one of them an artifact that a build step creates.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
