### ISSUE TITLE
Monitoring points to the wrong domain ?

### ISSUE THREAD

**Issue by Lennie** [mozilla/persona#2598]
Could it be http://status.mozilla.com/ still watches the old domains/urls ?:

http://status.mozilla.com/11627/216654/browserid.org
http://status.mozilla.com/11627/217458/browserid.org/include-js

**Comment by fmarier** [comment]
My guess is that it's monitoring `browserid.org` to ensure that:
1. the redirects are working
2. the service is up

but I could be wrong and it could just be something we forgot to update...

**Comment by Lennie** [comment]
I did consider that and I don't know how the monitoring is handled, but if you monitor one domain and expect it to redirect and monitor the second that way. You'll have a nasty surprise if the redirect is removed by accident and the second does not work anymore.

So I thought, probably better to report it before it goes live :-)

**Comment by lloyd** [comment]
let's resolve this when we launch status.persona.org very soon.  we should probably redirect from status.mozilla.org.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
