### ISSUE TITLE
logged-in state not properly updated in second window with 123done

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2609]
STR
1. Start with a new browser profile with Firefox 16.01
2. In window-1, load http://123done.org/
3. Click signin and enter an existing secondary username/password to complete the login
4. Open a second window, window-2 and load http://123done.org/. This window will automagically show you as logged in.
5. In window-1, click Logout. Both windows should show a logged out state.
6. In window-2, click sign in with the dialog.

Expected: both windows transition to show the logged-in state.
Actual: window-2 shows as logged-in, but window-1 does not.

The same STR can be used on stage (beta.123done.org) with the same actual result.

NOTE: if you reload window-1, it will now show the logged-in state.

**Comment by jrgm** [comment]
This also can be done in Chrome/osx, but not on IE9/win7 or IE8/winxp.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
