### ISSUE TITLE
login.persona.org doesn't support RFC 5746

### ISSUE THREAD

**Issue by djc** [mozilla/persona#2612]
When using login.persona.org, I see messages like this in the error console:

"login.persona.org : server does not support [RFC 5746](https://tools.ietf.org/html/rfc5746), see [CVE-2009-3555](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2009-3555)"

**Comment by fmarier** [comment]
This page explains the console warning: https://wiki.mozilla.org/Security:Renegotiation

It looks like our server [supports client-initiated renegociation](https://www.ssllabs.com/ssltest/analyze.html?d=login.persona.org&hideResults=on) which could make it [vulnerable to DoS attacks](https://community.qualys.com/blogs/securitylabs/2011/10/31/tls-renegotiation-and-denial-of-service-attacks).

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
