### ISSUE TITLE
Show error message instead of silently returning to homepage

### ISSUE THREAD

**Issue by djc** [mozilla/persona#2613]
While implementing my IdP, I'm running into the following error from /wsapi/auth_with_assertion:

{"success":false,"reason":"bad signature in chain"}

When the login fails this way, login.persona.org reloads the homepage instead of showing some error message UI.

**Comment by jrgm** [comment]
@djc can you add more on what you think should be done to fix this? Is it applicable in the same way now, given changes in UI?

**Comment by djc** [comment]
@jrgm I have no reason to think this has changed, but I also don't have an easy way to reproduce this error.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
