### ISSUE TITLE
Optional separate popups for login and signup

### ISSUE THREAD

**Issue by max-mapper** [mozilla/persona#262]
I've observed some confusion amongst people signing up for the first time (they've never heard of BrowserID before). When they open up the BrowserID sign in popup and are immediately asked to enter their email address they aren't sure if they should be entering their (for instance) GMail username and password. After a moment or two of confusion most eventually notice the small 'sign up' text at the bottom of the popup.

A separate API call that opened up the registration page directly would help in that I could have separate buttons for first time users and existing users.

```
navigator.id.getVerifiedEmail(callback, {signUp: true})
```

**Comment by shane-tomlinson** [comment]
@maxogden - We have noticed the same through our user testing and have changed the entire flow because of it.  With the coming rendition of BrowserID, a user will see only one input field (email) whenever the popup is first opened.  BrowserID will then check for whether the person signing in is currently a user, if so, a password field will be presented.  If the person is not a user, they are asked if they would like to become one, and sent a verification email.  Only after they click on the verification link in the email are they ever asked for their password in this flow, and it is made clear that we are asking for a password for BrowserID instead of for the site that they are signing in to.

The work is not yet complete, but if you check out the "design" branch, you can see the progress that we made last week.  I am hoping for the majority of this to be completed this week.  

With a flow like this, would that eliminate the need for a "signUp" option?

If you have any more feedback, please let me know, we love getting suggestions!

**Comment by shane-tomlinson** [comment]
Closing this issue as taken care of in the UX redesign.

**Comment by jamesgecko** [comment]
The current UX instructs the user to enter their email address to "sign in" to the page. The first time I saw that, I closed the popup window and went back to the website to see if I'd missed a "sign up" link.
