### ISSUE TITLE
lots of emails causes signin button to be hidden

### ISSUE THREAD

**Issue by lookfirst** [mozilla/persona#2622]
This is a re-open of two issues: #1325 and #2144. screenshot coming after I submit this issue.

**Comment by lookfirst** [comment]
http://www.evernote.com/shard/s178/sh/abd20884-b458-4194-a324-acb8af25a324/1edf9587f7291de9fca58741a1ea3b8c

**Comment by lookfirst** [comment]
It used to be that I could scroll in that dialog, which was kind of wrong too. Now there isn't even scrolling available.

**Comment by shane-tomlinson** [comment]
This was fixed with checkin 42182387d012dd354d3759b0ce102589d11e772c which is currently in beta.

![Email scroll bar](https://lh4.googleusercontent.com/-VO7N9dg0UaY/UIUkB0WrxjI/AAAAAAAAAHw/u79OPeZ3w5Y/s703/email_scrolling.png)

Closing as fixed.

**Comment by lookfirst** [comment]
@shane-tomlinson 

I still think this design could be improved in other ways.
1. Hiding the signin button below the other two buttons and a scrolling UX is confusing.
2. The email addresses could be clickable buttons. That would avoid the two clicks to sign in and the whole signin button. Remembering the last signin address could be done with icons in the button.

**Comment by shane-tomlinson** [comment]
@lookfirst - Thanks for your feedback. Regarding point 1 - this decision was not made lightly. On a mobile device in landscape mode, if the submit buttons are always shown there is room for approximately 1 email address, which looked terrible on top of being totally unusable. Since the average number of email addresses our users have is ~ 2.7, we optimized for this case. Users with > 8 email addresses is a very small minority.

Point 2 was considered as well. Unfortunately I forget the reasons why this was decided against.

**Comment by lookfirst** [comment]
@shane-tomlinson On a mobile device, you could just have a dropdown box. The most recently used account is selected. At least on iOS, a dropdown box is also rendered nicely in the UI when engaged.

**Comment by shane-tomlinson** [comment]
Re-opened because this request is made often.

**Comment by cyberdees** [comment]
I don't have a proposed solution (yet) — but just wanted to highlight that I often choose an associated email address and just wait, forgetting that the sign-in button is a scroll or two away. 

Could it perhaps be somewhere else in the UI always visible but grayed out until an email is selected? Changing from gray to blue with immediately highlight it for me too. 

I don't mind the scrolling (too much) to find an associated email address that much, although you could possibly uplift the ones that are used more often rather than have them in the standard when created order.

**Comment by lookfirst** [comment]
So glad this is re-opened.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
