### ISSUE TITLE
DOM contains duplicate IDs

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2641]
With the introduction of #2556, the authentication form is now always in the DOM. As shown in #2632, this has caused some problems. 

The problem described in #2632 was fixed with #2634 but the larger problem of elements with duplicate IDs is not yet fully handled. The IDs of the tooltips relating to the email address and password are duplicated in add_email.ejs and set_password.ejs. I tested across several browsers (Firefox OSX, Chrome OSX, Fennec, Android Native browser, IE8 on WinXP) to see if this would cause a problem, so far all the tooltips show when expected.

**Comment by shane-tomlinson** [comment]
Demoting to 2\* since there has been no action on this and it is unlikely to change in the near future.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
