### ISSUE TITLE
l18n module should check that default_lang exists

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2649]
On server startup, the i18n.js module should ensure that the files needed to support the default lang exist.

This would have caught Issue #2645 being an invalid default_lang setting.

I'm pretty sure the old code enforced this by checking for the existence of default_lang .mo files.

**Comment by lloyd** [comment]
yeah, hard error and process exits would make it really hard for this bite us again.  +1

**Comment by callahad** [comment]
Likely resolved as of current state of dev? To verify....

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
