### ISSUE TITLE
perform the 'We just sent an email...' check earlier in dialog signup flow

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2652]
STR
1. With FF, load http://beta.123done.org and click sign in.
2. Enter a secondary email address not previously known.
3. Enter and confirm password.
4. Dismiss the /sign_in dialog.
5. Click sign in again.
6. Enter the same secondary email address again.
7. Enter and confirm password.
8. Dialog shows red tooltip 'We just sent an email...'

The UX would be a bit nicer if it informed the user about the duplicate submission when on the email prompt (step 6). As it is now the user is not warned until they are on the password prompt (step 8). Perhaps if /wsapi/address_info were changed to optionally return a staged boolean, e.g., '{"type":"secondary","known":false,"staged":true}'.

But I realize these are UI nits and they are bigger fish to fry.

**Comment by callahad** [comment]
@skinny97214 Thoughts / Insight?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
