### ISSUE TITLE
Create test instances of eyedee.me (or mockmyid.com) with broken TLS certs

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2665]
This will allow us to test that primaries with broken TLS certificates are correctly ignored:
- `wrong.eyedee.me`: valid cert for a different domain
- `untrusted.eyedee.me`: self-signed cert
- `expired.eyedee.me`: expired but otherwise valid cert

**Comment by callahad** [comment]
https://bogus.mockmyid.com/ covers your first case.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
