### ISSUE TITLE
123done /api/logout is called when cancelling out of dialog (the first time after previously signed in) 

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2667]
STR
1. Log into https://login.persona.org 
2. Go to http://123done.org/. Bring up Chrome DevTools or Firebug and enable the Network panel.
3. Bring up the dialog and signin.
4. Logout of 123done.
5. Bring up the dialog again and then close that window without signing in.

Two GET's for /wsapi/{session_context,list_emails} are made and then a POST to http://123done.org/api/logout is made which returns '401 Unauthorized'.

If you repeat step 5 after the initial error, there is no attempt to call /api/logout.

If you complete signin with 123done again, and then try Step 5, the POST /api/logout happens again on the first cancel of the dialog.

This is reproducible with OSX Chrome and Firefox, and can be done in production or on stage.

**Comment by callahad** [comment]
Logout shouldn't get called at all... sean, can you look into this?

**Comment by seanmonstar** [comment]
Probably not soon. I'm deep in the b2g/bigtent woods, and see no way out.

**Comment by callahad** [comment]
Reassigning to @shane-tomlinson for looking into later.

**Comment by jrgm** [comment]
Bumped into this 401 in train-2012.12.07, and was reminded of this open bug.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
