### ISSUE TITLE
Split the "need assertion and audience" error message (verifier)

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2672]
Currently if the assertion or the audience field is missing in a request to the verifier, you get the same error message.

To make debugging (both for RPs and for us), it would be good to split these into three error message:
- assertion missing
- audience missing
- assertion and audience missing

In addition, if we could include print the audience to `verifier.log` in the case of a missing assertion, it could help us identify RPs or applications that have broken implementations and reach out to them.

**Comment by fmarier** [comment]
@warner: can you think of security problems with exposing which of the two parameters was missing?

**Comment by fmarier** [comment]
Keeping a copy of the audience might have privacy implications.

**Comment by jrgm** [comment]
Actually, the audience is already contained in metrics, so this has been privacy reviewed (presumably).

**Comment by lloyd** [comment]
related to mozilla/jwcrypto#54

+1

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
