### ISSUE TITLE
signup flow sometimes leads to 'aw snap' chrome problems

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2691]
First noticed this via selenium tests, interestingly.

Basically, go through the flow of the remove-email automation test:
1. go to 123done, use the dialog to add an unverified secondary email. don't close the dialog.
2. pull the link out of the email and paste it into the 123done main window
3. aw, snap!

Something to do with reusing that window, instead of opening a new tab, causes trouble.

Seen repeatedly in vista/chrome via sauce, for example: https://saucelabs.com/tests/7f0fb60aa7c54f26b35dc30e1731b972

Repro'd manually on mac/chrome stable.

EDITED to add simpler repro steps.

**Comment by jaredhirsch** [comment]
forgot to mention - this happens on dev

**Comment by jaredhirsch** [comment]
NOT occurring on prod

**Comment by jaredhirsch** [comment]
NOT occurring on stage

**Comment by jrgm** [comment]
Five star.

**Comment by jaredhirsch** [comment]
ONLY happens if the dialog is open. If the dialog is closed before loading the link, no error.

**Comment by jaredhirsch** [comment]
not reproducible on mac/ff16

**Comment by jaredhirsch** [comment]
not broken on safari 6 either

**Comment by lloyd** [comment]
alternate STR which are interesting
1. go to dev.123done.org, use the dialog to add an unverified secondary email. don't close the dialog.
2. _type https://login.dev.anosrep.org_ into the 123done main window
3. aw, snap!

**Comment by jrgm** [comment]
So:

1)  I have chrome 21 and 22 on osx and _can_ repro with both.

2) Stage does not reproduce we know that. But the same branch on an awsbox does. So what's up with that?

**Comment by jrgm** [comment]
Also on my awsbox, I set options "kpi_backend_sample_rate": 0.0, "enable_development_menu": false which otherwise would alter client behaviour. These are set this way on stage. Any others? (I'd really like to see show_config from stage).

**Comment by jaredhirsch** [comment]
cc @gene1wood, any pointers on config differences?

**Comment by jrgm** [comment]
I had noticed that the 21 and 22 .app's had been updated sometime in the 3 hours between when I restored these from Time Machine and when I noticed they had changed. So I disabled automatic updating and used a clean unupdated chrome 22, and can repro with that. I used `sudo lsof -P -n` to confirm that there was no version 23 bits loaded anywhere. 

So this issue with Chrome may have been around for this flow for quite some time. But for reasons that are unclear, the bug is not reproducible in the stage or production environments which have slight differences in packaging and configuration, and also have a full set of translations.

**Comment by jaredhirsch** [comment]
5-star unassigned, I call shenanigans.

Either this isn't really that important, and we should change our sauce tests to do something different, or it is important, just not 5-star important, or it really is 5-star important, yet it's unassigned and hanging around.

@lloyd, @jrgm, which is it?

**Comment by gene1wood** [comment]
@6a68 production.json ( https://github.com/mozilla/browserid/blob/1173c2d7c173e9deabe9209b4136006935f1bfaa/config/production.json ) differs from what's in stage in these ways :
- dev has no public_url
- dev defines a "user" value under "database"
- dev has create_schema true under "database"
- dev has a "kpi_backend_sample_rate" value
- dev has no "smtp" value
- dev has a "supported languages" value
- dev has a express_log_format of default_bid instead of default
- dev binds the keysigner to 62600 instead of 62700
- dev has a different verifier url keysigner url and dbwriter url (understandably)
- dev has a enable_development_menu value

**Comment by jrgm** [comment]
Thanks @gene1wood. The differences for database, smtp, port, express_log_format, {keysigner,dbwriter} url should not matter as this happens on client side. I've set kpi_backend_sample_rate and enable_development_menu  to the values they should have in stage (0.0, false) and cannot repro on an awsbox (which is like dev without those two config changes).

I guess what I really need is a run of a command on stage that we can talk about tomorrow.

**Comment by jaredhirsch** [comment]
should we reduce the star count, since this only seems to affect dev?

**Comment by jrgm** [comment]
Lowering to 4-star. What @6a68 said.

**Comment by jaredhirsch** [comment]
hasn't recurred in a while, I'm guessing it was a chrome bug. If not, we'll reopen.
