### ISSUE TITLE
/about doesn't mention the words "cross-browser"

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2695]
We need to make it explicit that this is not a Firefox-only feature.

**Comment by lloyd** [comment]
@callahad - what's the status of our new language for the site?  If we're far away, maybe it's best to incrementally improve this language?

**Comment by jrgm** [comment]
Do we have some new text for this page? Yes, we should be clear that this is cross-browser, so let's make it clear with text changes.

**Comment by callahad** [comment]
We've had new language for 6 months or more ( https://github.com/callahad/browserid/commit/e9670de0a10a322217bd0939cafe3d2ad5966fdc ), but things stalled on design for that page. Maybe something to revive with John joining the team and Rob pushing for a more marketing-centric landing page?

**Comment by fmarier** [comment]
@callahad I love the fact that the word "wall" is gone from that new page :)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
