### ISSUE TITLE
Absolute URI's for Icons in the dialog

### ISSUE THREAD

**Issue by ForbesLindesay** [mozilla/persona#2696]
Some of the websites I manage use free hosting that doesn't support https, so I really need to be able to host the image for the dialogue somewhere different.  I think adding a logo to those dialogues would be a huge enhancement in terms of user confidence in the system, so I'm really keen to add the icon to that dialogue.

**Comment by lloyd** [comment]
@warner, what do you think about loosening this constraint?

**Comment by ForbesLindesay** [comment]
Has any more thought been given to this?

**Comment by ForbesLindesay** [comment]
This is now a blocking issue for me adopting browserid

**Comment by shane-tomlinson** [comment]
@ForbesLindesay - instead of an absolute URI, would data-URI be a viable alternative?

**Comment by ForbesLindesay** [comment]
Yes, that would be equally good

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
