### ISSUE TITLE
allow an IdP to explicitly state they do not support persona in their support document

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#2697]
proposal is a `.well-known/browserid` of 

```
{ 
    "support": false
}
```

is a way that a domain may explicitly indicate that they do not wish to support persona.  The problem this solves is it gives IdP's a hook to rapidly turn off persona support and indicate to us and verifiers that they are not temporarily broken, but actually want to stop being an IdP.

**Comment by seanmonstar** [comment]
Could it be even simpler, such as with a http status code?

**Comment by lloyd** [comment]
that could would work just fine.  @callahad, as the keeper of our public APIs, got a thought?

**Comment by callahad** [comment]
Whatever you decide, open an issue / pull request against mozilla/id-specs!

I could see either way -- it feels weird to require that a domain maintains a file just for us, just to tell us it wants nothing to do with us.

Since this only matters when a domain is going from IdP to non-IdP (basically giving it a fast fail back to the default case), then they already have and are serving a well-known file.

They just want to stop doing that.

And we want to make sure that signal is up for as long as we need for our caches to expire, right? So can we say something like "Change your well-known file to X, and keep it available for at least 2 weeks."

A 410 Gone response feels like the right one if we went the header route.

How easy is it to configure Apache, IIS, and nginx to send a custom header like that?

**Comment by callahad** [comment]
I'm feeling a bit weird about how the spec would document the well-known file.

"First, look for this key. If it's there and is of this value, then abort. Then {normal stuff}"

**Comment by seanmonstar** [comment]
I had the same thought, @callahad. It feels odd to suggest maintaining file explicitly to tell us they don't support us. A `410` response sounds appropriate from my side.

**Comment by ozten** [comment]
Many IdPs will support the `/.well-known/browserid` with a static file and their existing web server.

I think removing parts of the document and adding a property is a very simple opt out.

Adding a status code is possible, but would be a new step - different than what they did to opt in. They would have to add an `.htaccess` file or figure out some way to set the status code.

A few weeks later, it's easier to remember to remove the static file than to remove a line from an .htaccess file (or whatever config / code that does the `410`.

Either will work, but I'd vote for an updated well known.

**Comment by lloyd** [comment]
The way I might explain is thus:

Your support document may do one of three things:
1. explicitly disable browserid support, requiring that the secondary authority is used
2. delegate authority for this domain to a different one.
3. express support for the browserid protocol by providing a public key and paths to required html resources.

These are listed in precedence order.  If `support`: false is found, then support is disabled.  If not and `authority: <domain>` is found, then authority is delegated.  If neither of these are true, then a domain acting as a browserid primary must provide `auth`, `prov`, and `public-key` properties.

Suck?  Rock?

**Comment by callahad** [comment]
+1. Let's go with the document option.

I'd like to say something (in an appendix?) regarding transitioning from support to no support. Keeping an eye on #2608 for that.

**Comment by lloyd** [comment]
I'll have a proposal about wording and strategies for turning on or off support shortly.  Hope is that there's a simple and patterned way you can turn on or off support as a primary with minimal / zero user impact.

**Comment by lloyd** [comment]
we changed this to `disabled: true` and it's landed in 781184b5f2b6372c0ce44fff046f1719a78553f9
