### ISSUE TITLE
clear out username and password on "this is not me" click

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#27]

**Comment by lloyd** [comment]
as well as all local keying material, right?

**Comment by lloyd** [comment]
ok, to clarify, here are steps to reproduce what I think this issue is:
1. log into browserid and set up emails
2. raise dialog
3. notice the sign in page preloaded with your identities
4. click "this is not me"
5. click cancel
6. raise the dialog again
7. notice you're now signed in again!  you shouldn't be!
