### ISSUE TITLE
No confirmation that your password has been changed successfully

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2729]
Steps:
1. go to https://login.persona.org and login
2. click "Edit" next to your password
3. change your password
4. nothing tells you that it worked

This was especially confusing when I tested that functionality with a blind user. He wasn't sure that it had worked and spent a bit of time looking through the page elements for some kind of confirmation text.

**Comment by gene1wood** [comment]
Ya, just encountered this. Confusing. I did the same thing.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
