### ISSUE TITLE
"Bad password" red overlay is invisible to screen readers

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2730]
Steps:
1. click the sign-in button on 123done.org
2. enter your email address
3. enter the wrong password

A red overlay pops up to tell you that the password is wrong but it disappears while a blind user tries to look through the page elements to find out what is going on.

That error message is dismissed after a short timeout. It's not long enough to enable a screen reader to really pick it up.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
