### ISSUE TITLE
"Check your email" screen needs to focus the first text element

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2731]
Steps (using a screen reader):
1. click the sign in button on 123done.org
2. use a new email address to sign into the dialog and click "next"
3. type your password twice and click "done"

At this point, you get the "check your email" screen . On a screen reader though, it's not clear that anything happened at all because we're still on the same page.

According to the blind user I tested this with, if we gave focus to the first text element of that page (I guess the "Check your email" heading), then the screen reader would pick up on that focus change and allow the user to easily read the rest.

That same screen shows up in the password reset flow.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
