### ISSUE TITLE
"Is this your computer?" screen is very confusing when using a screen reader

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#2732]
The "Is this your computer?" screen in the dialog has two buttons:
1. One month
2. This session only

Unfortunately, on a screen reader, it looks like this:
1. One month [button]
2. I trust this computer This session only [button]
3. This is not my computer [text]

In other words, the labels on the right of the buttons are not connected properly to the matching button.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
