### ISSUE TITLE
add logging to run-all to isolate non-zero exit codes

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2737]
Many recent test failures (for example, FF 16 run [2064](https://ci.mozilla.org/view/Persona/job/identity.browserid.dev.windows.7.firefox.16/2064/)) don't show much output useful in diagnosis.

Some options:
- in xunit mode, if exits non-zero, give the name of the test that exited non-zero
- add verbose option to run-all to dump lots of info to the console

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
