### ISSUE TITLE
enable/disable buttons uniformly

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2739]
To ensure our automated tests don't try to click buttons when they're in the DOM but not wired up, ensure we're always using the same classname/attribute combination.

**Comment by shane-tomlinson** [comment]
@6a68, @lloyd - This needs to be re-considered. Right now, the submit_disabled class is added to the body when an XHR request is out. This has worked well for us and after further digging into the code, I am hesitant to change it because the scheme works very well for screen transitions.

1) If buttons are disabled when screen transitions to another, buttons are still automatically disabled after the new screen appears. 
2) If buttons are not disabled at the screen transition, they are not disabled when the new screen appears.

We cannot assume that buttons are disabled during screen transition because we need a trigger to remove the "disabled" attribute from the submit buttons.  Some screens are transitioned without an XHR request, meaning there would be no trigger.

Similarly, waiting until the new screen is shown and JS is run to disable buttons may be risky because there is the chance that there is button flicker while JS is being run or state is being checked.

If we have to do either of these, the second is preferable.

Since we have to update the tests to check whether a button is disabled before clicking it, we can just as easily check the body element for the "submit_disabled" class and not change any existing code.

**Comment by shane-tomlinson** [comment]
Closing this as won't fix. We are going to keep the current scheme because it is working for us, and modify the tests instead. See issue #2740

**Comment by lloyd** [comment]
Fair 'nuff.

-- lloyd (thumb-typing)
