### ISSUE TITLE
browserid.org's SSL certificates not trusted by Android 2.2 default browser

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#274]
I have seen this in the Android 2.2 emulator's default browser and there have been community reports of this as well.

**Comment by jrgm** [comment]
I was working with a factory-reset Verizon Motorola Droid with Android 2.2,
and only stock browser.
- Start stock browser.
- Load http://myfavoritebeer.org
- Android displays 'Security warning: There are problems with the security
  certificate for this site. This certificate is not from a trusted authority'
- Click on 'View certificate' shows it the cert for browserid.org is issued by
  Geotrust.

The problem is that Android 2.2 and below do not trust all GeoTrust certificates.
Described better here, with links to follow, and maybe server workarounds.
https://knowledge.geotrust.com/support/knowledge-base/index?page=content&id=SO15937&actp=RSS&viewlocale=en_US

I think we should re-triage this issue.

**Comment by jrgm** [comment]
I asked jvier about this today, and he indicated that ops will be working on a fix for this real soon now.

**Comment by shane-tomlinson** [comment]
Closing since we moved to persona.org.  @jrgm is going to verify on persona.org

**Comment by jrgm** [comment]
I used a 2.2 Droid device with stock browser, FF14 and FFBeta. None of them have a problem with the SSL cert we provide at login.persona.org.
