### ISSUE TITLE
Intermittent spinner while provisioning from primary IdP

### ISSUE THREAD

**Issue by djc** [mozilla/persona#2785]
In the Persona dialog, while provisioning (e.g. no need to be authenticated with the IdP, clicking the button to "sign in"), the spinner will sometimes disappear for a while (e.g. between 300ms and 1.5s?) while the provisioning is happening. I think the spinner appears twice, while in between there's no visible sign of progress. This is slightly crappy UX, since it seems like something's breaking (since there's no visual cue about what's happening).

IMO, it would be better to make the spinner appear after clicking the "sign in" button and leave it on until the dialog disappears, unless any errors happen.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
