### ISSUE TITLE
Hidden files ending in .ejs can crash template engine

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#2788]
Sometimes my editor leaves working files like `.#foo.ejs` in the directory while I'm editing foo.ejs.

I have to remove these before each server restart, or else the templating engine gets confused.

This will cause the qunit tests to fail 'Cannot find Template', etc.

We should not put hidden files into the list of ejs templates on startup.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
