### ISSUE TITLE
install Open Sans semi-bold

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#2802]
http://www.google.com/webfonts/specimen/Open+Sans

Sandstone specifies semi bold. I'd like to use it in the RP name.

**Comment by seanmonstar** [comment]
Is using it there worth the extra download time? Especially on slower connections (EDGE)?

**Comment by skinny97214** [comment]
I'd be willing to trade out semi-bold for bold as that's what Sandstone specifies.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
