### ISSUE TITLE
Set up Sauce Labs overflow account & API management code

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2806]
It turns out that we can add a backup account with up to 50 concurrent VMs to handle overflow from our new Sauce account, but we have to use a different API key for that account.

I'm thinking we can fail over by using the Sauce REST API to check how many tests are in the queue, and dynamically jump over to the backup account if the queue gets long enough.

We'll also need to make sure we wouldn't be saving money by adding more VMs to our contract vs paying by the minute for overage, that'll be an ongoing item to monitor.

**Comment by shane-tomlinson** [comment]
@6a68 - is this still the case?

**Comment by jaredhirsch** [comment]
@shane-tomlinson no movement on this since end of last year, so we could do it but haven't.

**Comment by edwindotcom** [comment]
our automation hasn't been stable enough on jenkins/saucelabs to run at 50 concurrent runs.  I vote to downgrade or just close for now.

**Comment by jaredhirsch** [comment]
@edmoz the motivation here isn't to make jenkins even more parallelizable, it's to support jenkins AND one or two developers working on the tests independently. In the current system, our account gets maxed out and we simply see a ton of tests failing because they timed out waiting to start.

that said, if you want to change the starrage, go for it.

**Comment by jrgm** [comment]
lowering to 3-star.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
