### ISSUE TITLE
Account Manager - headings no longer look like headings

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#2813]
![Screenshot of Persona account page](http://f.cl.ly/items/0u351i0b3l0K0P2m0N2G/Screen%20Shot%202012-12-03%20at%2011.29.43%20AM.png)
The headings "Your email addresses" and "Password" should be font-weight: 600.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
