### ISSUE TITLE
tests/cookie-session-security-test.js has something that doesn't make sense (to me)

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2833]
In doing GH-2832 test for /wsapi/logout.js, I noticed /wsapi/logout was being called here:

 https://github.com/mozilla/browserid/blob/dev/tests/cookie-session-security-test.js#L41-46

So, 1) GET is not allowed for /wsapi/logout, and 2) logout while not authenticated doesn't make much sense anyways.

From the line '"and then session context again"', and then calling /wsapi/logout, is this a typo?

The test passes with either /wsapi/logout or /wsapi/session_context, but I don't have the history on the intent of this test.

**Comment by shane-tomlinson** [comment]
@benadida - looking at the logs, yourself and @lloyd wrote this section of code. @jrgm is asking for a clarification as to why session context is called.

**Comment by benadida** [comment]
yeah, probably a typo in the test description. I can't say I remember exactly what the point of this is, it looks like it's checking to make sure no additional cookie is set, but not sure why /logout is the call being made here. @lloyd, any idea?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
