### ISSUE TITLE
static server must check for a file name that exceeds NAME_MAX

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2901]
Trying to access a filename > NAME_MAX is pointless since it will return ENAMETOOLONG  (where NAME_MAX is 255 for our kernel).

So check the maximum filename/dirname length in the url before trying/failing to pass that along. Log an error message if too long and return, hmm, I guess 404).

gifting this to @zaach because it's the holiday season. /cc @gene1wood and @fmarier  since my googling found him reporting this same thing against `npm`.

**Comment by jrgm** [comment]
> So check the maximum filename/dirname ...

To be clear, I meant something like check all parts in `somepath.split(path.sep)`.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
