### ISSUE TITLE
unverified-email assertions should use a different issuer

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#2908]
For example, `unverified.login.native-persona.org`.

@lloyd or @ozten: I'm not sure how we would set this up for b2g. Would it be another browserid instance setup at the different domain? If so, then it can have it's own secret key as normal, but I don't know how I would setup tests that make sure the other issuer (and key) is used in vows...

**Comment by seanmonstar** [comment]
@jedp do you know what the deadline is for this? i'll be on vacation for the next 2 weeks, does this need to be done during then?

**Comment by jedp** [comment]
As @benadida commented on https://github.com/mozilla/browserid/pull/3307#discussion_r4023206, longer-term, we will want a different issuer, but for the near-term, as b2g launches, this will be ok.

**Comment by jedp** [comment]
... therefore I have reassigned it from four stars to three.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
