### ISSUE TITLE
[b2g] login state not shared between tabs in phone browser for the same Idp domain

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2914]
STR
1. Go to http://notoriousb2g.123done.org and auth with an existing secondary user (only one email on the account).
2. Create a new tab in the phone browser, and load https://notoriousb2g.personatest.org

Expected: you should be logged in to the main site.
Actual: non-authenticate UI is shown, with a 'Sign in' button shown.

I can see with https://etherpad.mozilla.org/http-logging-for-b2g that different cookies are sent for /wsapi requests in the two different contexts (trusted UI on /sign_in vs. regular browser window to /signin on the notoriousb2g.personatest.org domain).

One can actually complete 'sign in' with the main site, and a cookie for /wsapi on that domain is issued that is different from the cookie used in the trusted UI).

This may be expected in the current state. Dunno.

**Comment by jedp** [comment]
I think what's happening here is that the persona login form is setting cookies and all, but because it's not glomming onto the native implementation, it's not setting them in the same context.

On b2g, each tab and each app has a separate cookie jar; the native navigator.id implementation works around this by causing all browserid state to be stored in the system app's cookie jar.  But this login form doesn't have anything to do with the system app.

Maybe there's a way we can fix this without ever touching b2g code?  A way to trigger cookie setting in the internal api?

@seanmonstar and @shane-tomlinson, do you have any thoughts (I know you're doing a big spring-cleaning of the front-end code now ... :)

**Comment by shane-tomlinson** [comment]
Mmmm...  I have no good thoughts on this, all the cookies are HttpOnly so we can't set them using JS in the internal API.

Am I wrong in wondering if this is a broken feature in B2G? Shouldn't different tabs of the same browser share cookies?

I'm trying to think if there is a solution to work around this. Nothing is coming to mind at the moment. At one point I thought @benadida was considering doing away with cookies altogether and using some other mechanism? But this may be a dream I had one day after too many hours of coding.

**Comment by seanmonstar** [comment]
I was going to say the same: I don't see how we can affect the cookies of another context. Is that not a B2G bug?

**Comment by shane-tomlinson** [comment]
@jedp, @jrgm - is this still the case?

**Comment by jedp** [comment]
I will verify.  Having trouble building latest b2g, but will check as soon as I have a build.

**Comment by jedp** [comment]
FWIW, this is still the case.  You're not signed into the persona main site by signing into 123done (today as I test, that's `firefoxos.123done.org` and `firefoxos.persona.org`.)

**Comment by jedp** [comment]
The same-domain across multiple tabs issue has been fixed for some time, but the persona.org dashboard issue has not.

I'll close this and refer questions about the dashboard to Issues #3624 and #3558.

**Comment by jedp** [comment]
I've opened  [Bug 892050](https://bugzilla.mozilla.org/show_bug.cgi?id=892050) for an Account Manager on FirefoxOS
