### ISSUE TITLE
Dialog transitions to wrong screen while polling user_creation_status, etc., on a flaky network.

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#2927]
This comes originally from seeing this when using a flaky network with flaky phone. But I can reproduce on desktop with a little ipfw trick that's make this easier to debug.

STR
1. Load dev.123done.org and bring up the dialog
2. Enter a new secondary email address, the password twice and submit.
3. The new user is staged, and the dialog switches to show the "Check your email..." screen. Polling for /wsapi/user_creation_status continues in the dialog.
4. Now fake a little network issue: On osx do `sudo ipfw add drop tcp from any to any 443 out; sleep 15; sudo ipfw -q flush`. The dialog switches to 'we are sorry this is taking longer...' screen at 10 seconds. At 15 seconds, when we reopen traffic with the `flush`, the dialog switches to show the password entry screen, not the 'check your email...' screen. 

I've also seen it then transition to show 'Persona requires cookies...` with "Action: Registration failed, POST /wsapi/authenticated_user, 403, Forbidden: no cookie". I didn't see that on the phone. Not sure what's up with that.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
