### ISSUE TITLE
reduce noise level in selenium prod-monitor.

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#2935]
once again, saw a lot of alerts over the weekend.

Could be a bug in health-check tests, problems with the git-mirror (this caused the previous weekend's failures), or problems with npm or sauce.

Need to analyze some of the hundreds of recent failures, find the top problem, and fix it.

I'm happy to take this, but curious what level of starrage it'll merit in triage.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
