### ISSUE TITLE
transitionNoPassword sends the reset password email instead of a more appropriate email

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2937]
This will cause user confusion when they get an email that says:

"Forgot your password for Persona? It happens to the best of us."

**Comment by shane-tomlinson** [comment]
Hey @skinny97214 - When a user who has an account with only primary email addresses and one of their addresses converts from a primary to a secondary, currently the password reset email is sent out.  While it is an edge case that we hope does not happen often, it is an area that will cause confusion when it does. Whatcha think about sending a new email?

**Comment by lloyd** [comment]
+1 - this will be confusing.  This case occurs only when a primary transitions to a secondary, which is thought to be rare.  We did not bother optimizing the email text for this case as part of the initial merge because the patch was HUGE, we thought time was tight, and this seemed like something we could safely get to later.

**Comment by skinny97214** [comment]
We do need a new email with custom copy. @callahad can you help draft the copy?

**Comment by callahad** [comment]
@skinny97214 / @shane-tomlinson Do we need to expose the user to the fact that their email provider isn't supporting Persona? If we do, how about:

> It looks like your email provider is having trouble with their Persona support.
> 
> To continue, you need to re-confirm this email address and set up a new, Persona-specific password.
> 
> Click the link below to get started: 
> {link}
> 
> Thank you,
> The Persona Team

I'm intentionally ignoring the fact that a domain might intentionally disable Persona, and instead referring to everything as "trouble with their Persona support." Because I can't think of a better way to put it, and because the verbiage above is more likely to be the common case. And it will hopefully inspire user inquiries to the provider. :)

**Comment by skinny97214** [comment]
This is a weird enough thing that it seems like there needs to be a support article with more detail that we could link to. 

Other than that it looks great. I tweaked the link copy a teeny bit.

```
It looks like your email provider is having trouble with their Persona support.

To continue, you need to re-confirm this email address and set up a new, Persona-specific password.

{Click here to set your new password}

Thank you,
The Persona Team
```

**Comment by zaach** [comment]
@callahad @skinny97214 Any ideas for the subject of the email?

**Comment by callahad** [comment]
Current email subject lines:

<dl>
<dt>confirm</dt>
<dd>Confirm email address for Persona</dd>
<dt>new</dt>
<dd>Confirm email address for Persona</dd>
<dt>reset</dt>
<dd>Reset Persona password</dd>
</dl>

For this case, re-using "Confirm email address for Persona" seems reasonable.

**Comment by zaach** [comment]
Yes, that does seem reasonable. I'll also reuse the confirm email landing page unless we want different copy there too.

**Comment by shane-tomlinson** [comment]
@lloyd - did you fix this already? If you did, can you close this?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
