### ISSUE TITLE
Error thrown when staging a user when site parameter contains an underscore '_'

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#2948]
STR

1) Create an ephemeral instance with an `_` in the name "has_underscore" for instance.
2) Visit "has_underscore.123done.org"
3) Try staging a user.
4) Check out the error screen.

![invalid_origin_dialog](https://f.cloud.github.com/assets/848085/74551/2493f4f8-6098-11e2-9911-fae10c627f53.png)

5) Visit "has_underscore.personatest.org/signin"
6) Try staging a user.
7) Check out the error screen.

![invalid_origin_main_site](https://f.cloud.github.com/assets/848085/74550/210433a2-6098-11e2-81a0-c4e6b9ed88bc.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
