### ISSUE TITLE
Identity screens within the trustedUI have UX issues with the keyboard open

### ISSUE THREAD

**Issue by jds2501** [mozilla/persona#2970]
NOTE: The STR I have specified are more detailed than they need to be since I am trying to tie the IdentityFlow with payments to warrant a higher priority.

steps to reproduce:
1. Get marketplace-dev app from http://people.mozilla.org/~kmcmillan/mktdev.html
2. Launch the marketplace app on your unagi device
3. Search for 'Private Yacht'
4. Click on the purchase button
5. Identity Flow launches within the trustedUI
6. Try to log in as a new Persona user with an unverified email id

observed behavior:
- while entering the email id, the submit button is not visible. User has to hit enter to proceed to the next step. (See screenshot 1)
- While setting up the password, the verify password form field is not visible nor is the submit button. ( See screenshot 2)
- The identity screens are twitchy and get redrawn quite often which is jarring (probably a gaia issue)

**Comment by jds2501** [comment]
Read the rationale on https://bugzilla.mozilla.org/show_bug.cgi?id=834507#c2 on why this is a server-side persona bug. In short - this is a responsive design problem.

**Comment by jedp** [comment]
The twitchiness would be a gaia issue

I think for the password dialog here, we should consider making "enter" on the first password field cause the dialog to focus on the second password field, and keep "enter" on the second password field as it is (submitting the form).  Focusing on the second password field will bring the field into view.  It is currently hidden behind the keyboard.

I think this would work well on desktop (where one could hit enter instead of tab because other applications sometimes work that way to transition between fields), and it's crucial on the phone, where there's no tab key, and no way apart from tapping and dragging to bring the second password field into view/focus from behind the keyboard.

Faster STR: using an eng build (device) or DEBUG=1 gaia build (desktop), launch the UI Tests app; go to navigator.mozId tests.  On the test page, click "unverified ok" and then press the Request unverified email button.

**Comment by seanmonstar** [comment]
@skinny97214 do you have suggestions on how to make this UX better? There is a confirm password field hidden by the keyboard, so the user doesn't really know it's there.

![attachment](https://f.cloud.github.com/assets/51479/133412/a57095d2-70aa-11e2-8931-203cca796908.png)

**Comment by skinny97214** [comment]
We will need to do some trickery with mobile, I suspect. What it should do here is transition to a new screen that only has the password, repeat password fields and the submit button. 

Just double checking... does the enter key work to submit the form?

**Comment by seanmonstar** [comment]
Yea, currently pressing the enter key after entering your password in the first field will submit the form, and give you a red tooltip.

We were wondering if there's a way to tell the B2G keyboard to provide a sort of "next" button instead.

**Comment by skinny97214** [comment]
We have visual designs for the FxOS-specific skin from Maureen and Michael. Sean - want to review these with me out of band?

![ID_Payments_VisualDesign](https://f.cloud.github.com/assets/41135/137259/0484e43e-7168-11e2-9467-4e07a56aed8f.jpg)

**Comment by jedp** [comment]
I've created https://github.com/mozilla/browserid/issues/3502 to track the issue @seanmonstar mentions in [his comment above](https://github.com/mozilla/browserid/issues/2970#issuecomment-13216611).  My bad - I thought we already had an issue for that.

**Comment by jedp** [comment]
By now, the UI and event handlers have changed substantially, and I believe we match the designs by Maureen et al.  Closing this as fixed.  Please reopen if I am mistaken.
