### ISSUE TITLE
 [persona] allowed to enter space in email address in persona login screen

### ISSUE THREAD

**Issue by jds2501** [mozilla/persona#2971]
Migrating this from https://bugzilla.mozilla.org/show_bug.cgi?id=834538.

**Comment by jrgm** [comment]
So Dietrich said "summary says it all", but it doesn't. 

If I enter a space character in either the local part or the domain name of the email address and try to use that, I get a tooltip warning that "that is not a valid email address". 

But yeah, a restriction on the front-end that just doesn't allow the user to type a space at all when entering an email address would be a UX improvement. 

Or did he mean something else?

**Comment by autonome** [comment]
Yep, just disallowing spaces altogether. IIRC I was allowed to enter multiple strings, and saw no tooltips.

Hm, actually... do the tooltips show up at all on Firefox OS web content?

**Comment by jrgm** [comment]
Thanks @autonome.

I'm using platform 18.0, build identifer 20130123070202, update channel nightly, and I get a tooltip when I rry to use an email with a space in either the local part or the domain name of an email address (which is a client side filtter).

**Comment by lloyd** [comment]
Is space filtering common on other high profile sites?  links?

**Comment by autonome** [comment]
Lol. The only valid input is an email address.

Feel free to wontfix this. I'd rather y'all focus on other things in Persona instead of doing an audit of high profile sites that allow spaces into email fields.

**Comment by jaredhirsch** [comment]
I'd prefer to use tooltips to inform users of restrictions, not silently
deactivate keys.

Suggest closing as wontfix

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
