### ISSUE TITLE
An invalid email pattern that is not invalid on the frontend, but is invalid on the backend

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3000]
Wasn't actively looking for this, but typo-ed on a mobile device, and then repro'd more simply on osx/chrome.

STR
1. Load https://login.anosrep.org/signin
2. Enter the email '.foobar@example.com'

Actual: That email address is not detected as a bad pattern on the frontend, but the backend returns '{"success":false,"reason":"email: Error: Invalid email"}'

Side-effect: at least on Chrome/osx, that email is autofilled on reload on /signin, which returns the error again, and leaves the user in a generally difficult-to-recover-from position.

Note: the same error for invalid email is returned when using the /sign_in dialog. But the invalid address is not sticky in the email address field there, so the user can more easily correct this (unusual) typo.

**Comment by jaredhirsch** [comment]
I suspect this'll get fixed by #2891

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
