### ISSUE TITLE
Port scripts/extract_po.sh to i18n-abide

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#3002]
Currently we have a shell script `scripts/extract_po.sh` which uses the GNU Gettext tool `xgettext` to extract strings and put them into POT files.

In Issue #1322 we've switched to i18n-abide which provides `bin/extract-pot`.

This is a purely node solution, so xgettext is no longer required.

We should work closely with mathjazz to make sure there are no bugs. We should closely compare the .pot and .po files generated to make sure no strings are missing or changed.

We won't do this work with the work involved in closing Issue #1322.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
