### ISSUE TITLE
audit and update pencil for new wsapi.

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3009]
Quick placeholder for @jrgm

**Comment by jrgm** [comment]
To flesh this out a bit more:
1. There are some wsapi/*.js api calls that are not tracked/shown
2. Check that all (as best can be determined) have data. Some are clearly not showing anything.
3. Check that the data values are reasonable (e.g., the %CPU is the sum of percentages from the 3 webheads, which is wrong).

**Comment by jrgm** [comment]
We're not using pencil with AWS deployments now, but I'd really like to get something equivalent (or just use pencil) back in place. Leaving this open for now.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
