### ISSUE TITLE
include.js cannot be cached (Cache-Control: public, max-age=0)

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3035]
`include.js` is currently exposing a `Cache-Control` header with `max-age=0` which means that sites that include from every page will cause browsers to do an extra HTTPS request every time.

```
$ curl --head https://login.persona.org/include.js
HTTP/1.1 200 OK
Vary: Accept-Encoding,Accept-Language
Cache-Control: public, max-age=0
Content-Type: application/javascript
Strict-Transport-Security: max-age=2592000; includeSubdomains
Date: Fri, 22 Feb 2013 05:38:42 GMT
Access-Control-Allow-Origin: https://login.persona.org
ETag: "15578-1360955616000"
Connection: keep-alive
X-Frame-Options: DENY
Content-Length: 15578
```

Letting browsers cache this file makes deploying a new version trickier, but it's really worth it from a performance point of view.

**Comment by callahad** [comment]
To discuss on list....

**Comment by jrgm** [comment]
Also noted in GH-2549

**Comment by fmarier** [comment]
Posted the 10 min proposal to the list: https://groups.google.com/d/topic/mozilla.dev.identity/jXhDsQsO-fQ/discussion

**Comment by fmarier** [comment]
Also related: https://github.com/mozilla/browserid/issues/3119

**Comment by deepak1556** [comment]
can the application cache file be of use here ? u can add an additional script to look for push changes to ur repo and on the respone download the new manifest file ,which wld download the updated include.js on the next run. still cant figure a way make it async..

**Comment by djc** [comment]
If we have ETags, why is deployment trickier after unblocking caching?

**Comment by jaredhirsch** [comment]
@djc if we use time-based expires/cache-control headers, and the time period hasn't elapsed, then the browser will not check the ETag, it'll just use the locally-cached version of the file. check out the dev-identity conversation francois linked for more discussion.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
