### ISSUE TITLE
Support for 2-factor auth like Google Authenticator

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3045]
It doesn't look like we have a bug for adding 2-factor auth (using Google Authenticator maybe?) support in the fallback IdP.

I guess it will be less important once BigTent is fully deployed, but still it would be nice to have.

**Comment by shane-tomlinson** [comment]
sendmypin.org was an exploration to see how a simple 2 factor auth could work. Authenticator is far more sophisticated.

**Comment by appsforartists** [comment]
How hard would it be to use this:

https://github.com/guyht/notp

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
