### ISSUE TITLE
(Technical) Elevator Pitch

### ISSUE THREAD

**Issue by digitarald** [mozilla/persona#3047]
Scenario: Pitching to technically minded folks in person or just by sending them a link.

I'd like a short, concise and high-level overview. This should fit on one page or a flyer.

Maybe a melange of 3 short sentences, bullet points and a nice visualization, as a picture is worth a thousand words.

This could also be one of those whiteboard style videos. Anything to make the pitch more accessible.

**Comment by fmarier** [comment]
One thing that @digitarald suggested on IRC was to add a diagram of how Persona works to https://login.persona.org/about/

Not a technical/detailed diagram like the ones on http://lloyd.io/how-browserid-works thoug. Something simpler.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
