### ISSUE TITLE
[webdriver] Opera driver does not implement 'POST accept_alert'

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3049]
See http://code.google.com/p/selenium/wiki/OperaDriver where it notes (badly formatted): "No support for JavaScript alert/popup dialogues", and the source at https://github.com/operasoftware/operadriver/blob/master/src/com/opera/core/systems/OperaDriver.java#L738

This dooms the remove-email test to failure on Opera.

Maybe we need a way to ignore tests on certain platforms.

**Comment by jaredhirsch** [comment]
le sigh.

What's the future of OperaDriver, now that Opera's moving to Webkit?

**Comment by jrgm** [comment]
I think this also applies to Safari as well. I had the references links, but didn't write them down. But google 'selenium safari alert'.

**Comment by shane-tomlinson** [comment]
Relate to #3202

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
