### ISSUE TITLE
There needs to be a way to tell include.js that verification failed

### ISSUE THREAD

**Issue by ethernomad** [mozilla/persona#3051]
If verification during onlogin fails it seems the only way to report this is to call navigator.id.logout, but then the onlogout handler is called. This is unnecessary because site login has not occurred.

In the Drupal module we do this to mitigate the problem: http://drupalcode.org/project/persona.git/commitdiff/11c208a

It would be nice if an exception could be thrown in the onlogin handler to say that verification failed.

**Comment by callahad** [comment]
+1. It needs to be easier to make this API function as expected. The django-browserid folks do something similar by redirecting the user to a page with `?bid_login_failed=1` appended to the URL, and using that as a signal.

(I am curious about how you're getting invalid / expired assertions, though. Other than an `audience` mismatch on your verification code, it shouldn't be possible to receive a bad assertion from a good browser.)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
