### ISSUE TITLE
Persona assets need to be reduced for FX Marketplace

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3060]
Persona is way too heavy on bandwidth right now and is contributing to some serious performance issues in Marketplace. Some issues that need to be addressed:
- A full copy of underscore.js is being included in communication_iframe.js. It's only used 34 times, and most of those are `_.extend` and `_.defer` (which could be provided standalone).
- There's a second full copy of underscore.js that's included in communication_iframe.js because you mark it as a dependency with require.js.
- Lots of uncompressable function names (e.g.: `cancelWaitForPasswordResetComplete`, `_LEGACY_extractAssertionParamsFrom`, `_20120815_serializeCertParamsInto`, etc.) which are only used less than four times (gzip doesn't save you any/many bytes) and many used only once or not at all.
- Multiple copies of printable ASCII bytes (`ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/`) in various permutations (capital/lowercase/numbers/symbols, lowercase/capital/numbers, capital/lowercase/numbers/different symbols, etc.) in communication_iframe.js. This hurts gzip and means that the code is not DRY.
- include.js is mostly composed of workarounds for IE. A separate (IE-free) version would be appreciated for folks that don't support <IE9 (or to allow for conditional comments to use the faster version for non-IE users).

There are a lot more optimizations that could be made, but this is pretty critical right now for the performance of Marketplace (and apps that use Persona in general). This is something that we hope can be resolved before June.

**Comment by jaredhirsch** [comment]
Rather than suggest specific optimizations, I'd prefer we take a more holistic view. What's the current page load time delay due to include.js? How can we measure that in a repeatable, rigorous way (maybe webpagetest.org)? Once we know the delta, I'd propose the front-end folks will figure out how best to reduce the page load impact--again, by choosing optimizations and measuring them rigorously. Sound good?

**Comment by jedp** [comment]
Hi, Matt, we completely agree; the current situation is not acceptable on b2g device.  We've been working hard to make persona slimmer and faster, and we're not there yet for b2g.

Here is a list of improvements (which goes beyond asset reduction) that we are currently working on: https://id.etherpad.mozilla.org/b2g-persona-performance

The end of that document gives gives a holistic description of the main issues that we face, with analyses by @fmarier and @shane-tomlinson, both of whom have put a lot of thought and work into this problem.  We do need to measure and track key performance indicators over time, as @6a68 notes, and we have a system for doing this.

The good news is that fixes have already begun landing in the persona dev (effectively our master) branch, which we are now working to merge with the b2g branch.  When that happens (and I can't say exactly when it will other than that it looks like it will be soon), we will be able to bring these changes back into b2g.  We are focusing our efforts now on reconciling those two branches, which will give us all the biggest win.

**Comment by mattbasta** [comment]
I'll respond inline:

> Rather than suggest specific optimizations, I'd prefer we take a more holistic view. What's the current page load time delay due to include.js?

On my cable connection at home, it's clocked at 200-250ms. On a B2G device at the office on wifi, this can be up to 800ms. We don't have SIM cards at the moment, but similarly sized assets on Edge have taken upwards of two to three seconds at best (DNS lookup, connection, SSL handshake, etc.).

The biggest concern that we have is the communication iframe, which is very heavy.
- We can't set the user off and running until the page has loaded, which is denoted by the `onload` event firing.
- iframes block onload
- communication_iframe.js blocks the communication iframe

> How can we measure that in a repeatable, rigorous way (maybe webpagetest.org)? Once we know the delta, I'd propose the front-end folks will figure out how best to reduce the page load impact--again, by choosing optimizations and measuring them rigorously. Sound good?

One of the biggest issues is, perhaps unintuitively, bytes on the wire. The majority of our users are on or will soon be on mobile networks and live in parts of the world that get sub-optimal internet speeds in general. Decreasing the number of things that physically need to load before we can get them started is paramount.

You can check out a tool that we've built on our end:

http://marketplace-size.appspot.com/

It measures all of the CSS and JS that our code loads directly (it doesn't run the JS, so that's not accurately measured). What's concerning is that include.js + communication_iframe.js is only 10kb less (on the wire) than all of the rest of the JS for our consumer pages combined.

> The good news is that fixes have already begun landing in the persona dev (effectively our master) branch, which we are now working to merge with the b2g branch.

Is dev pushed to login.persona.org regularly? What is your release schedule? I'd be interested in tracking your changes.

**Comment by shane-tomlinson** [comment]
@mattbasta - Thanks for bringing this up. The optimizations you suggest are very valid, but there are some other things we should do first.

There are two issues affecting users on 2G connections - latency and bytes over the wire.

First, let's talk purely bytes over the wire, then about the number of connections.

To understand why communication_iframe is so large, you have to understand what it is doing and what is included to get that done. communication_iframe takes care of generating certificates and assertions for users who are signed in. The assertion that is created is passed to your site, which allows you to sign the user in. To create the assertion, we need crypto code. bidbundle.js (the crypto code) makes up the largest portion of the communication_iframe.

The crypto code is huge. Un-minified, it comes in at 128KB. Minified, 73.6KB. Minified & gzipped - 25KB.

My opinion is that including the crypto code in the initial load of communication_iframe is somewhat naive, on a 2G connection, the crypto code alone can add several seconds to load time.

This exact same code is included in 3 places - in the communication_iframe, on the main site, and in the dialog. A first time user who visits Persona _does not need_ the crypto code. They only need the crypto code once they have opened the dialog and signed in. The crypto code should only be requested, as a separate module, once we know the user needs a certificate or assertion. 

This approach reduces the burden to first time Persona users on RPs such as marketplace in two ways. First, users download less code. Second, there is less initial Javascript parse time. Repeat visitors to the marketplace would request the crypto code only when it is needed. Since it will request the same version of the code that was requested in the dialog, it will be fetched from the HTTP cache and incur no extra cost.

I have experimented with on-demand loading of crypto code on https://checkmyidp.org and it works well. I'd like to port this idea over to the Persona mainline code.

Mentioning underscore is actually very valid, we use only an extremely small subset and could easily replace our calls with standalone functions. Removing underscore would save us 4.3KB over the wire.

There are large optimizations we could do to network.js and user.js for embedding. These two combined come in at about 78KB unminified, uncompressed. Minified they come in at 15.5KB. Gzipped: 5KB. Only a small subset of the functionality is needed for communication_iframe and the rest should be separated into a separate module.  We could probably save 3 or 4KB over the wire with smart optimizations

Finally, looking over the list of includes in communication_iframe, WinChan is included, which I do not understand. It shouldn't be, this looks to be a leftover from a past era but I have to check to make sure. Removing this saves 1.4KB over the wire.

I would prefer to not serve up distinct versions of include.js for different browsers, but again, we may be able to make some optimizations. Very little is actually IE specific, most of the hacks you mention are to allow easy cross domain messaging for all browsers. There are two types of cross domain messaging going on. First there is messaging between the communication_iframe and the RP - JSChannel takes care of this.  Second, there is messaging between the RP and the dialog. WinChan takes care of this. Because native versions of Persona perform the functionality of WinChan, we may be able to whitelist browsers with known native support and offer up a slightly reduced set of code. Minified and gzipped, include.js is only 5.8KB, so I'd rather get larger wins out of communication_iframe first.

Now, onto the number of connections and network latency.

You bring up total bytes on the wire, but connection latency on 2G networks is a performance destroyer. 2G connections can have 400+ms of latency per connection.

A Persona user who is not authenticated to Persona makes 4 requests.
1) include.js
2) communication_iframe
3) communication_iframe.js
4) session_context

Only the first 3 resources will block onload from firing, session_context is called once communication_iframe.js is initialized. Still, user who is not logged in can see 1.6 seconds of latency, without counting the time it takes to transfer the bytes, just to find out the user is not signed in.

A return user will fetch a fresh copy of include.js and etags will be checked for communication_iframe. communication_iframe.js will be cached. session_context has to be made.

Short of embedding the JS and the info provided by session_context, it is going to be difficult to but the number of requests on a diet. Embedding the JS will prevent us from using CSP, which isn't great.

**Comment by mattbasta** [comment]
Thanks for the really comprehensive response. I'd be interested in helping out if I can. Is there anything that I can get our team to help with?

One optimization that we landed last night is using `rel="dns-prefetch"` link tags on our homepage to prefetch the DNS for login.persona.org and static.login.persona.org. Can you think of anything else that we could do that might help kill some latency in the short term?

**Comment by seanmonstar** [comment]
On FirefoxOS devices, `navigator.id` is native, and it currently uses the resources from https://native-persona.org... but @jedp would know if theres a way you can improve that from marketplace

**Comment by jedp** [comment]
On FirefoxOS, we use both the sign_in iframe and the communication_iframe.  They are injected into the system app, not the marketplace pages.  This is done because of the FirefoxOS security model, which silos all apps and makes it impossible to share cookies and localStorage across them.

**Comment by seanmonstar** [comment]
Which frankly, would mean that the entire request to get https://login.persona.org/include.js is wasted. Maybe it could be solved like this?

``` html
<script id="persona-check">
if (!navigator.id) {
  var s = document.createElement('script');
  s.src = 'https://login.persona.org/include.js';
  document.getElementById('persona-check').parentNode.appendChild(s);
}
</script>
```

**Comment by mattbasta** [comment]
The marketplace CSP prevents us from doing inline scripts, though we could
put it in our asset bundle.

The downside then is that we're increasing latency because our entire JS
bundle needs to load before we can even begin loading include.js, which is
even worse.

**Comment by andymckay** [comment]
"A Persona user who is not authenticated to Persona makes 4 requests.
...4) session_context"

We are also seeing a request to list_emails so that's 5. Is that just for logged in users?

**Comment by shane-tomlinson** [comment]
@andymckay - Indeed, a signed in user also calls list_emails. @fmarier and I discussed combining list_emails with session_context for signed in users to eliminate this extra request, but we have not yet done so.

**Comment by jaredhirsch** [comment]
I'm concerned that there's no specific goal in this bug, so we can't ever close it. @mattbasta & @jedp, what's the performance situation with Persona on Marketplace at this point? Are you guys comfortable with closing this bug? If Persona is still a problem, maybe we can figure out some way to get performance numbers and quantify what's going on, and sharpen what this bug is all about?

**Comment by mattbasta** [comment]
I think things have improved since the bug was filed. Unless you think
there's still work to be done, I'd say that this is safe to close

**Comment by jedp** [comment]
Good!  I'd also like to close this.  We have other bugs where we continue to track specific performance issues on mobile (e.g., #3579 and #3602).
