### ISSUE TITLE
Normal CSRF protection mechanisms interfere with onlogin callbacks

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3074]
@wbamberg has done a great job of documenting the problems that @benw identified with CSRF protection mechanisms: https://github.com/wbamberg/persona-mdn/blob/master/csrf-problems.md

Given that it's a fairly common race condition / corner case with web frameworks and that the work-around is pretty ugly (an extra GET before a POST), it would be great to find a way to either fix this through an API change or something else.

**Comment by shane-tomlinson** [comment]
Link to https://bugzilla.mozilla.org/show_bug.cgi?id=919472

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
