### ISSUE TITLE
placeholder issue - remove lowercasing in automation-tests/lib/restmail.js when GH-2551 is fixed

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3082]
Putting this as an explicit bug, instead of a comment buried in the code. 

When GH-2551 is fixed, that will need to include removing the workaround at
https://github.com/mozilla/browserid/blob/d0f8ef43a74b110d4f91a991d4a42a7d6ca7afc5/automation-tests/lib/restmail.js#L16

**Comment by jrgm** [comment]
Also here: https://github.com/mozilla/browserid/blob/dev/automation-tests/tests/returning-user.js#L54

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
