### ISSUE TITLE
patch etherpad to use the Observer API

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3086]

**Comment by ozten** [comment]
Codebase: https://github.com/mozilla/pad

You can ping me and rhelmer for dev questions.

You will work with Jake (nmaul) to get this shipped. Deployment bug: you can clone https://bugzilla.mozilla.org/show_bug.cgi?id=766213 after discussing this work with Jake.

Thanks @6a68

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
