### ISSUE TITLE
improve dev ergonomics and code readability around raising more specific error messages in dialog

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3087]
Relate to #3081.

The code to raise specific error messages in the dialog is pretty whack.

```
    onFailure($.extend(info, { action: { message: error }}));
```

Pretty bad, eh?

**Comment by lloyd** [comment]
I suggest

```
onFailure($.extend(info,  { errorMessage: "the specific error that will help us diagnose and FIX IT" }));
```

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
