### ISSUE TITLE
improve escaping of untrusted IdP values

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3088]
Right now we are relying on EJS to do the escaping. To be consistent with dialog.js, all untrusted IdP values should be escaped when they enter the system.

Relate to #3081

**Comment by lloyd** [comment]
namely, that's in `resources/static/common/js/provisioning.js`. /cc @fmarier cuz this is a security architecture sorta thing.

**Comment by lloyd** [comment]
@fmarier would you have time to look at this?

**Comment by fmarier** [comment]
@lloyd Yes, I can certainly take a look at that if it's not too urgent (i.e. if it can wait until after Easter).

**Comment by lloyd** [comment]
works for me!  Thanks francois!

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
