### ISSUE TITLE
private browsing on Safari fails to display sign in button on 123done.org

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3094]
steps:
1. on mac or win safari - goto menu and select 'private browsing'
2. goto beta.123done.org or http://123done.org

results: animated spinning wheel displays forever where the sign in button should be

repro'd on:
123done.org and beta.123done.org
mac 10.8 Safari 6.0.2 and VM Win8 Safari 5.1.7

No repro in private browsing on:
mac/win Firefox Beta, Mac Chrome, Win8 IE10

**Comment by shane-tomlinson** [comment]
This will be the same as cookies disabled behavior because the user has not yet visited the Persona dialog.

#982, #989, #2999

**Comment by edwindotcom** [comment]
Just want to add 
1. going to this https://login.persona.org
2.  entering an email click submit

results in loading this: 
https://login.persona.org/signin? with no other visual indication that anything changed.  The user has no idea what happened.

**Comment by jaredhirsch** [comment]
@edmoz yeah, login.persona.org is busted because it shows the login form without doing a cookie check.

Here's the error message I see in the console: QUOTA_EXCEEDED_ERR: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.

This should also affect private browsing on MobileSafari. Moving this bit (the login.persona.org site bug) to a separate bug.

**Comment by jaredhirsch** [comment]
@shane-tomlinson So, it seems like this is actually a bug in 123done's implementation? Do we need to fire an event if third-party cookies are disabled, so RPs can do the right thing?

**Comment by shane-tomlinson** [comment]
Closing as dup of #1835
