### ISSUE TITLE
allow site to manage session length via BrowserID

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#312]
adding issue here to track discussion thread:

https://groups.google.com/group/mozilla.dev.identity/browse_thread/thread/251862126d72cc58/72ff215d86644063

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
