### ISSUE TITLE
Need to know which software versions are running at the webhead, signer and dbwriter in each datacenter

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3122]
placeholder... in middle of push.

**Comment by shane-tomlinson** [comment]
@jrgm - can you explain a little more what you would like to see? It should be straight forward to add more info. Right now it shows the git and svn SHAs, which while minimal, have generally been enough for us to `git log` and find the info that we need.

**Comment by jrgm** [comment]
So, the goal is a way to know that the correct version is running on webhead, signer and dbwriter.
Changing the current /ver.txt isn't likely the best way to do this. Perhaps some other tool or monitor in the datacenter.

**Comment by shane-tomlinson** [comment]
@lloyd, @gene1wood, @jrgm - Are there any ideas on how we can make this happen?

**Comment by lloyd** [comment]
I think we can make this happen in AWS and I think it would be worthwhile to do so.  It seems like a single node that can interact with ELBs and tell you current number and versions of each node would be the best way to realize this.

I think we should roll up this into a slightly larger task to land in AWS from the start with holistic, minimialist, high value dashboards and monitoring...  It's gotta be minimalist to start tho, lest it never get done.

**Comment by gene1wood** [comment]
@jrgm so you're talking about monitoring the ver.txt maybe? Can you talk about the problem you're trying to solve? Is it related to heterogeneous versions running within a cluster? Or something else?

**Comment by jrgm** [comment]
@gene1wood - so right now, I can use /ver.txt on a production url to know what the version running on the webhead is (router, static, verifier, browserid), but I don't have a way to see the backend tier: sweb (dbwriter), sign (keysigner).

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
