### ISSUE TITLE
Firefox doesn't save my new password when I change it.

### ISSUE THREAD

**Issue by erikrose** [mozilla/persona#3123]
1. Go to https://login.persona.org/
2. Click "Sign Out"
3. Click "Sign In"
4. Enter email address; hit Return.
5. Enter (recently changed) password; hit Return.

I would expect it to prompt me to update my stored-in-Firefox password. Instead, no prompt happens.

I'm on the 2013-3-11 nightly and have 4 previously stored Persona passwords, each under a different email address.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
