### ISSUE TITLE
Persona doesn't work with the LibreJS extension

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3126]
The [LibreJS](https://www.gnu.org/software/librejs/) Firefox extension exists to block proprietary Javascript code.

Since our code is not proprietary, there's no reason it shouldn't be able to work with that extension (which is enabled by default in [Icecat](https://www.gnu.org/software/gnuzilla/).

Freaky Friday project for me to figure out [what we could do to unblock these scripts](https://www.gnu.org/software/librejs/free-your-javascript.html).

**Comment by fmarier** [comment]
Here's a starting point for this:

https://github.com/fmarier/123done/tree/add_licensing_info
https://github.com/fmarier/browserid/tree/add_licensing_info

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
