### ISSUE TITLE
Figure out password policy when all of user's secondary addresses are converted to primaries.

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3128]
moved from: https://github.com/mozilla/browserid-bigtent/issues/158

0.0 login with a non yahoo.com email address
0.1 goto https://login.anosrep.org/ and remove specific email accounts manually (don't cancel account)
1. login via bigtent (yahoo.com acct)
2. goto: https://login.anosrep.org/
3. click 'edit' on password

result: edit password doesn't make sense, old password doesn't exist. it's complicated for us but should we hide it if you have only bigtent accts?

@ozten This is true of any primary, I think.

**Comment by jrgm** [comment]
This can be done with any primary, so, for example:
1) On beta.123done.org sign up as a new secondary address
2) On beta.123done.org use the dialog to add an address @eyedee.me
3) Go to login.anosrep.org and remove the secondary address to the account
4) Reload or signout/signin; a password change field is presented despite the fact the only email on the account is a primary email address.

**Comment by jrgm** [comment]
There's an interesting implication for bigtent. As any existing yahoo.com email address is converted to be a primary email address, those users will all see this UI to change the password. (This is because session_context returns has_password: true, because the passwd column in user non NULL for that. It should be non-NULL if the user still has both primary and secondary email addresses on the account. But for many users, as they get flipped to be primary, it's not right; probably code should set the password column to NULL if none of the addresses remaining on the account are secondary).

I'm slightly morphing this issue (which I don't like to do) but it seems right to do in this case. Anyways, when an IDP stops being a primary (or we disable bigtent), the UI presented is (of course) different depending on whether passwd column is not null.

not NULL

![back-to-secondary](https://f.cloud.github.com/assets/758162/305364/48dc965e-9657-11e2-9268-eb7816e03da9.png)

password column is NULL

![back-secondary-if-no-password](https://f.cloud.github.com/assets/758162/305370/554db0c6-9657-11e2-8868-4cc6cde3a4a9.png)

**Comment by shane-tomlinson** [comment]
@jrgm, @skinny97214 - What is the ideal behavior here as this becomes more common.

Should we remove the Persona password when the last of a user's email addresses converts from secondary->primary? If the user adds a new secondary or a primary turns off support, those users will have to set a password again.

**Comment by skinny97214** [comment]
I'm in favor of deleting the vestigial passwords. Note that if they are using PiCL, they will still need that password bc of force issuer.

**Comment by callahad** [comment]
+1. When we don't have to store hashes, let's not store hashes. :)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
