### ISSUE TITLE
[bigtent] If dialog is up for >~5 minutes then using the dialog to sign in fails with alert

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3145]
Haven't fully investigated this, but gist of STR

1) Use beta.123done.org to signin as a yahoo.com address
2) Now that  you're signed in, sign out and bring up the /sign_in dialog again
3) Wait for something more than five minutes (to let the cert expire)
4) Try to complete signin

Expected: normal completion of signin
Actual: alert with 'failed to verify assertion: assertion has expired'

Done with opera and firefox. And sorta safari, but it has a js error that prevents the alert. 

This is not a common use case, but it will happen. Not really specific to bigtent, except it is the one with 5min expiry, as opposed to hours.The user can recover from this and signin again.

**Comment by jrgm** [comment]
Link to GH-3153. This is its cousin, but I don't think fixing GH-3153 will fix this one. I'm guessing, but I think we might not recheck the certificate immediately before creating the assertion.

To clarify "Not really specific to bigtent..." I meant that this can probably be duplicated with login.persona.org  if you had the patience to bring up the dialog and wait for 24 hours ;-)

**Comment by shane-tomlinson** [comment]
We check to see if a certificate expires within the next 2 minutes, with the assumption that users will complete the flow within that time.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
