### ISSUE TITLE
Unclear when you already have an account

### ISSUE THREAD

**Issue by rikkiprince** [mozilla/persona#3151]
There is a slight usability kink when returning to persona.org to login, whilst forgetting that you already have an account:
1. You click the button to "Sign Up".
2. You enter your e-mail address.
3. It asks you for a password.
4. You choose a new password.
5. It says you got it wrong.
6. You wonder how given you're creating an account.
7. You realise it means you already have an account and go through all the passwords it could possibly be until you login or give up.

This really needs a notice banner (y'know, one of those big yellow bars at the top) at stage 3 that says "you already have a persona, please login with your password".

**Comment by shane-tomlinson** [comment]
Hey @skinny97214, care to weigh in here? Do we have some room to improve our returning user flow?

**Comment by shane-tomlinson** [comment]
A good suggestion from @edmoz - "A welcome back message would be helpful"

**Comment by shane-tomlinson** [comment]
@rprince - so we have a bit more context here, is this confusion from the main site at https://login.persona.org/signin or from the popup dialog?

**Comment by rikkiprince** [comment]
@shane-tomlinson Not sure I've seen the popup dialog. I think I was redirected to https://login.persona.org/signin, and I have definitely experienced it visiting https://login.persona.org/signin directly (just tried it now).

**Comment by skinny97214** [comment]
This is great bug, thanks to @rprince for opening it. I agree we could give much better feedback on whether an account exists. We will get some flack for leaking which accounts are valid, but we do that anyway with the forgot password screen, I believe. It's a minor security cost for a major UX win. @benadida pls explicitly sign off on that if you agree.

![Screen Shot 2013-03-28 at 1 32 36 PM](https://f.cloud.github.com/assets/41135/315409/b3fc0c22-97e6-11e2-8958-60ac23dcc707.png)

We'll need a cancel button here that I'm not showing. I'm thinking we can drop the TOS/PP to make room for it, since we know we have an account for this user.

Additionally, the error message for forgetting password could give more context that we do, in fact, have an account for that email address. "Invalid credentials" can be changed to "Incorrect password, please try again."

**Comment by rikkiprince** [comment]
Thanks to @graingert for telling me to submit it rather than just complain on Twitter :-)

You're completely right that the behaviour already gives away that an account exists, you're just not making it explicit to a human looking at it with their eyes or screenreader.

Many thanks for responding to my comment with such care and consideration.

**Comment by benadida** [comment]
@skinny97214 I don't believe this opens up any new security issue, as it is already trivial to determine if a user's account already exists with the current UI. So this looks to me like a UI issue entirely, which means it's up to you Crystal :)

**Comment by edwindotcom** [comment]
Lowering this to 3 star - as it's UX/Cosmetic.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
