### ISSUE TITLE
login.persona.org doesn't have a clear link to account manager page

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3152]
1. go to 123done.org and sign in
2. go here: https://login.persona.org/about 

actual: you're signed in, indicated by the button, but there's no clear way to get to 'account manager' page.  If you click on the persona badge, it takes you there but as a new user, that's not clear.

expected: There should be some clarity to how to manage my accounts.  I would expect that the persona badge just take me to the main product page not the account manager
![Screen Shot 2013-03-28 at 10 39 34 AM](https://f.cloud.github.com/assets/3698618/314572/7e702cea-97ce-11e2-8d25-c113d497846a.png)

**Comment by callahad** [comment]
@skinny97214 Care to weigh in?

**Comment by skinny97214** [comment]
@edmoz I'm confused on step 2. Where did you get find the /about link?

The current flow is clicking on the logo in the upper left of the popup takes you to the account manager page. Is that what you saw?

I agree that the navigation is confusing. If there's not already a bug open for different navigation, I'll open one. I have really old mocks for a new one kicking around somewhere. /me digs.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
