### ISSUE TITLE
eot and ttf should be transferred with gzip encoding

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3166]
@gene1wood noticed a discrepancy between production and stage configuration where stage had an nginx rule to do gzip for 'application/x-font-ttf', but production did not.

Stoyan Stefanov sez yes, gzip them (but not woff):
http://www.phpied.com/gzip-your-font-face-files/

@shane-tomlinson can you decide the official word for @gene1wood about what the correct set of mimetypes for webfonts should be gzip'd in AWS production?

**Comment by jaredhirsch** [comment]
Fonts to compress: ttf, eot, svg, otf. We don't serve otf at the moment,
but you might as well set it up while you're in there.

The trick with font files is that you have to manually add the MIME types
to your server config. In the case of nginx:

http://blog.bigdinosaur.org/gzipping-at-font-face-with-nginx/

Edit: that article mentions that svg already has a MIME type defined.
Edit: that article has a typo, refers to opentype as ott, not otf. But it is otf: http://caniuse.com/otf

**Comment by shane-tomlinson** [comment]
@gene1wood - gzipping all but .woff files would be a good win for users. @6a68's link has the info needed to make it so. If you need a sounding board while doing this, ping me on IRC.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
