### ISSUE TITLE
After verifying email addition, original dialog does not sign user in and close

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3172]
STR

1) Open dialog with account with one secondary email address
2) Add a second secondary email address
3) Open verification link in new tab of same browser
4) Original dialog never closes.

This affects the current beta.

Why didn't Selenium catch this?

**Comment by jaredhirsch** [comment]
ugh, another 5-star. confirmed.

Selenium doesn't check that the dialog has closed, I don't think--our tests just focus on the happy path.

**Comment by jaredhirsch** [comment]
gotta run for a bit but found where to plant the debugger breakpoint and thought I'd document my steps so far:
- dialog polls to see if user clicked verify link yet at wsapi/email_addition_status.
- inside the code, this is Network.checkEmailRegistration
- which is called by User.waitForEmailValidation
- whic his called by dialog.doConfirmEmail
- after which dialog/misc/state responds with handleEmailConfirmed
- which **should** call redirectToState('email_chosen'). so, why isn't this happening?

Need to set a breakpoint in handleEmailConfirmed and see what happens.

**Comment by jaredhirsch** [comment]
Well, I set that breakpoint and traced through it a couple of times.
- handleEmailConfirmed does the right thing & fires the email_chosen signal.
- the anonymous email_chosen handleState call does the right thing & calls user.checkAuthentication
- checkAuth returns authentication := "email_valid_and_ready", fires email_valid_and_ready signal
- User.shouldAskIfUsersComputer fires the onFailure callback, which is missing.

So, I guess the bug here is that the handler for email_valid_and_ready doesn't pass an errback to User.shouldAskIfUsersComputer at [line 433](https://github.com/mozilla/browserid/blob/dev/resources/static/dialog/js/misc/state.js#L433).

Next, going to look at when this changed last. I suspect the user/network refactor.

**Comment by jaredhirsch** [comment]
Large refactors are tricky. Lot of code to read through here.

https://github.com/mozilla/browserid/commit/1a44d48

**Comment by jrgm** [comment]
Should  be fixed via PR-3177.
