### ISSUE TITLE
replace all instances of "sign up" with "sign in"

### ISSUE THREAD

**Issue by skinny97214** [mozilla/persona#3200]
Our copy guidelines are that it's always "sign in". 

See #3189

**Comment by skinny97214** [comment]
If someone would do a find in our codebase and flag all the places it shows up, I will review each.

**Comment by shane-tomlinson** [comment]
This is quick and dirty:

```
./error-messages.js:      title: gettext("There was a problem with your signup link. Has this address already been registered?")
./error-messages.js:      title: "Signup Failed"

./index.ejs:                <%- format(gettext('<a %(aboutLink)s>Take the tour</a> or <a %(signupButton)s>Sign Up &rarr;</a>'),

./verify_email_address.ejs:            <p><%- gettext('Thank you for signing up with <strong>Persona</strong>. You can now use your Persona account to <em>Sign In</em> or <em>Sign Up</em> to websites all across the web!') %>

```

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
