### ISSUE TITLE
Need a way to supress alert dialogs to reduce webdriver test failures

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3202]
There's a known issue with alert dialogs on opera and safari (possibly more).  If we could have a query string param such as: 123done.org?noAlert=true that would suppress these errors, it would greatly improve our test stability.  Not sure of the implementation or security issues involved.

I'm on mac10.8 with safari installed:
1. run java -jar selenium-server-standalone-2.31.0.jar
2. run this from automated_tests/
scripts/run-all.js --local --platform=safari --tests=remove-email -e stage

result: safari eats the alert dialog
on saucelabs:
https://saucelabs.com/tests/bb1d9d74805549ecbd971e56a070a9c6

On my local isolated click alert test, i get this in stdout:
selenium.common.exceptions.WebDriverException: Message: u"A modal dialog was opened. The SafariDriver does not support interacting with modal dialogs. To avoid hanging your test, the alert has been dismissed. For more information, see http://code.google.com/p/selenium/issues/detail?id=3862

**Comment by jaredhirsch** [comment]
Maybe try hacking on this a bit
https://github.com/mozilla/browserid/blob/dev/automation-tests/lib/urls.js

**Comment by edwindotcom** [comment]
I'd be happy with crew:automated-tests, there are only 3 open and 34 closed so there won't be too much collision.

**Comment by shane-tomlinson** [comment]
@skinny97214 says that using alerts is bunk. We should create our own lightbox with a [Sandstone](https://www.mozilla.org/b/en-US/sandstone/) style.

**Comment by edwindotcom** [comment]
for a one two punch, I'm going to work on adding another option to run-all.js --ignore-test=remove-email that way we can omit tests per browser/os config.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
