### ISSUE TITLE
Packaged apps cannot authenticate with Persona

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3205]
Assertion verification fails in any manner of ways:

Result: `{u'status': u'failure', u'reason': u'audience mismatch: port mismatch'}`
Audience: app://{8fadbfca-d3e7-304d-b364-854d11695f8b}

When the audience is running on the `app:` scheme, port should not be checked as part of the audience verification process.

**Comment by jaredhirsch** [comment]
@jedp care to triage this puppy?

**Comment by jedp** [comment]
Yes, the verifier does not like addresses that are not proper http or https urls.  One solution would be for us to open up the verifier to accept `app://` (or `chrome://` or `resource://` or whatever); another would be to find a pattern for apps to use that would send the origin of the server behind them to the verifier, since that's what's really interested in the identity.

I understand that we should get something patched asap for QA on apps to proceed asap, so I can assign this to myself to work on that.  But I'd also like to talk with @benadida et al. to find the right long-term solution for this.

**Comment by mattbasta** [comment]
It should be noted that this blocks the Marketplace.

cc @cvan

**Comment by benadida** [comment]
@mattbasta sounds like we should pow-wow quickly to understand what you need.

In my opinion, logging into a local app makes little sense... the user typically logs into a networked service with an http or https origin. But I'm open to discussion! Would be good to discuss your packaged app approach, the options you're looking at, etc. Maybe a quick chat tomorrow (Friday)?

**Comment by mattbasta** [comment]
Sounds good, are you in MV?

**Comment by benadida** [comment]
We discussed this in person and concluded:
- the packaged app includes an IFRAME to a hosted static page at https://marketplace, which includes the shim and invoke the navigator.id calls.
- the packaged app uses .postMessage() to send a "I'm ready" message to the hosted IFRAME, so the IFRAME can get the packaged app's origin from the message event.
- the hosted app sends the assertion back to the packaged app via postMessage() to its parent with the right origin based on the previous step.

Eventually, once packaged apps have stable origins, the hosted app can check that it's getting a message from its correct packaged counterpart.

**Comment by jedp** [comment]
Awesome.  Since a solution has been agreed upon, I'll close this.

**Comment by jedp** [comment]
@guilherme-pg has used the recipe described above, and is able to get a persona assertion, but his server is unable to set cookies in a package app :(  Bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=901697
