### ISSUE TITLE
Investigate switching to UTC on all systems

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3218]
Historically, our production systems have been on PDT and that will continue in AWS. 

But we really should look into changing to UTC, especially since DST Fall back and mysql (if we continue to use mysql) is not simple to get correct.

**Comment by jaredhirsch** [comment]
+1. tis a recipe for failsauce

**Comment by vmunix** [comment]
See also: https://github.com/mozilla/identity-ops/issues/16 and avoid the 1 MILLION YEARS DUNGEON.

**Comment by benadida** [comment]
oh man, I didn't catch that way back when? That is not cool, Ben, not cool. I need an explanation re: this dungeon, though.

**Comment by vmunix** [comment]
@benadida that would be lemongrab: http://www.youtube.com/watch?v=9BbRffBCeYw

**Comment by callahad** [comment]
We need to make sure we can make the switch without breaking anything.

Namely, how is MySQL handling timestamps?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
