### ISSUE TITLE
navigator.id.request needs an "onsuccess" callback.

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3228]
You can use `navigator.id.watch`, but it's frustrating and difficult to use if you have a particular set of methods on individual objects that need to change. The lack of callback support makes using Persona with promises difficult at best.

**Comment by jaredhirsch** [comment]
Can you explain a little more about your current use case?

**Comment by mattbasta** [comment]
We're looking to create deferreds around Persona. That means being able to reject and resolve deferreds, but we can't use lexical scope because you don't have your `onlogin` handler for `navigator.id.watch` in that scope.

The workaround we have is that we're basically creating a queue of deferreds for outstanding login attempts, and resolving or rejecting all of the deferreds in the queue when we verify the assertions. Obviously this isn't ideal, and failed logins that don't generate errors (i.e.: Persona never returns a response, an unexpected exception happens, etc.) cause garbage to accumulate and lots of defunct deferreds to end up in the queue.

**Comment by mattbasta** [comment]
cc @cvan

**Comment by jaredhirsch** [comment]
@mattbasta I think I see what you're getting at, but I'd love to see some code. Is there anything I can poke at?

**Comment by mattbasta** [comment]
Here's the code that I've been working on:

https://github.com/mozilla/fireplace/blob/dfa974ea397419478584a944380db9535fb2d47c/hearth/media/js/login.js#L24

**Comment by callahad** [comment]
@shane-tomlinson and @lloyd to think more about this...

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
