### ISSUE TITLE
`navigator.id.watch()`'s `onlogout` does not get fired when `navigator.id.logout()` is called.

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3229]
I think this happens when there is no logged in user. If the site thinks, though, that the user is logged in and calls `navigator.id.logout()`, it's not misguided to assume that the site expects to know when the logout has completed.

Another ideal option would be to add a callback to `logout()` which would indicate when the user has been logged out.

**Comment by shane-tomlinson** [comment]
@callahad - this has been discussed before.

@mattbasta - the onlogin/onlogout callbacks are only supposed to be fired when Persona believes the state of the world is different than the site believes OR if Persona's view of the state of the world changes. Since Persona believes the user is already logged out, no onlogout is fired.

To try and get some context into what you are trying to achieve, if you already believe the user is signed out when you call navigator.id.logout, what are you doing inside of the onlogout function that must be called?

**Comment by mattbasta** [comment]
I'm not sure what the cause of the state discrepancy is on our end (i.e.: our app believing that the user is logged in when Persona doesn't think so). The way we structure our code is to put full faith in Persona and use `onlogin`, `onlogout`, and `navigator.id.request`'s `oncancel` to determine when each operation has finished. It may be that there is a deeper issue higher up in the Marketplace/Persona stack that's causing grief.

In the short term, though, I believe that if the app is calling `navigator.id.logout`, they don't expect that the user is already logged out (or they wouldn't have called it to begin with). Firing off `onlogout` would at least let these applications get back into a good state.

You can check out what we're doing here:

https://github.com/mozilla/fireplace/blob/master/hearth/media/js/login.js

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
