### ISSUE TITLE
reset password api call needed

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#323]
An api call is needed to reset the password of an account, which causes an email to be sent to the account holder which allows them to reset their password.

**Comment by lloyd** [comment]
The feature is easy to address, but the open issue here is transient email compromise...  That is specifically if I compromise one of your email addresses should I then be able to change your password, and go use your other identities.

It seems like there are several proposals to let us change email reset safely:
1. upon email reset send emails to all of a user's addresses with a note "if you didn't do this, click here".  This way a user can detect account compromise and react.  Until the user does this, there is a window of vulnerability.
2. upon email reset, _unverify_ all other emails for the user and require them to be verified again the next time they're used.

@benadida might hit me, because once upon a time I agreed to #1, then left and decided I didn't like it anymore :/

**Comment by ghost** [comment]
The case when the user tries to reset the password for an email not registered with BrowserID should also be considered:

STR:
1. Go to "https://diresworb.org".
2. Click on the "forgot your password?" link.
3. Enter an email address that is not associated BrowserID.
4. Click on the "reset password" button.

Expected Results:
 An error message is displayed letting the user know that his email address is not registered with BrowserID.

Actual Results:
 A confirmation link is sent to the entered email address.

**Comment by shane-tomlinson** [comment]
Reopened under #759
