### ISSUE TITLE
Tighten up redirect rules on browserid.org and *.persona.org

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3233]
This is a meta-bug to track the resolution of all of these bugs:
- [ ] https://github.com/mozilla/browserid/issues/2420
- [ ] https://github.com/mozilla/browserid/issues/2419
- [ ] https://github.com/mozilla/identity-ops/issues/113
- [x] https://github.com/mozilla/browserid/issues/2038
- [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=779710

We have a test script which encodes the correct redirections: https://github.com/fmarier/checkurl/blob/master/check-persona-url.py

For some of these changes (the ones that break RPs), we need to close #3771 first.

**Comment by fmarier** [comment]
This is currently blocked on the AWS migration as well as the [third-party library review](https://id.etherpad.mozilla.org/3rdparty-lib-reviews) since we should minimize the number of RPs we break when we roll out this change.

**Comment by callahad** [comment]
/me ninja-edits Francois' bug to add checkboxes.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
