### ISSUE TITLE
Documentation for new contributors

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3239]
We might have a section in the README explaining how best to contribute

**Comment by jedp** [comment]
Some good advice from callahad to a new contributor: http://irclog.gr/#browse/irc.mozilla.org/identity/242905

**Comment by quack1** [comment]
I am the guy who received these advices from callahad on IRC, and they are very usefull! I'm currently learning how Persona works from an end-user developer side, and then I will start contributing to the project.

Afer that, I will write a blog post in French and English about how I started contributing to Mozilla project, and more precisely to Identity. Of course, I will share it before on the IRC chan and here for review, and maybe it could be the README section you are looking for if no one has written this part when I will write my post!

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
