### ISSUE TITLE
clicking Add button goes disabled (grey) then enabled for a second before redirecting to 'yahoo makes this easy' page'

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3242]
moved from https://github.com/mozilla/browserid-bigtent/issues/190

logging for @graingert , he's on ubuntu with Firefox 20

you can watch it here at the 14sec mark:
http://www.youtube.com/watch?v=6tXcWmNC0u0#t=14s

```
1. goto 123done.org, click sign in and enter a few primary and secondary email address
2. click sign in again, then 'add another user'
3. enter a @yahoo.com
4. click 'Add'
```

result: the 'Add' button becomes disabled/greyed/alpha 50%, then becomes enabled/alpha 100% then after 1-2 sec on a slower connection, then redirects to 'loading yahoo' page

expected: The 'Add' button should not go back to enabled/alpha 100% state.

**Comment by callahad** [comment]
stomlinson: "There are actually lots of buttons that act like this, unfortunately."

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
