### ISSUE TITLE
cert_key wsapi err handling question

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3243]
https://github.com/mozilla/browserid/blob/dev/lib/wsapi/cert_key.js#L35

Are we missing an `if (err) handleErr` here or am I missing something?

_meta: better to ask specific code-related questions here or on mailing list?_

**Comment by jrgm** [comment]
Yes, possibly. But be aware that `err` could mean two things: a database error from `client.query` or the string 'no rows found'.

https://github.com/mozilla/browserid/blob/dev/lib/db/mysql.js#L260

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
