### ISSUE TITLE
UI treatment needed for 500 pages

### ISSUE THREAD

**Issue by gene1wood** [mozilla/persona#3247]
Currently when node services a 500 Internal Server Error due to some internal code problem the user is presented with a persona UI consistent page. When nginx serves a 500 the user sees an inconsistent default nginx 500 page.

Please 
1. modify the UI treatment of the node error page to encode the fact that the error is being presented by node, and possibly some details of the cause of the error. This could be taking whatever additional information that node has about the cause and encrypting it with some secret on the server. This is so that a user could potentially report the error string safely
2. create a similar UI treatment to be used by nginx, also with the fact that it's nginx serving the page encoded in the page. Convey this page to Gene so he can load it into our nginx provisioning logic

**Comment by jaredhirsch** [comment]
@callahad's solution: _never serve 500s_

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
