### ISSUE TITLE
Verifier compliance test suite

### ISSUE THREAD

**Issue by wrr** [mozilla/persona#3261]
An idea discussed on dev-identity mailing list is to create a set of language independent (probably JSON encoded) test cases that verification libraries could use to make sure corner cases are handled correctly. The format would need to encode a time stamp to be mocked during verification and an expected outcome. Something like:

```
[
 {
  "testName" : "assertion from a past",
  "assertion" : "xyz...",
  "timeToMock" : 4838329,
  "siteURL" : "https://example.org:8080",
  "valid" : false,
  "reason" : "assertion expired"
},
...
]
```

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
