### ISSUE TITLE
Split verifier into its own repo

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3263]
A baby step on the road to better verifier docs.

If split out from the main browserid monolith, this would be way less code to grep through, if folks just want to look at our implementation as a starting point. Also it'd give us a natural place to host relevant info like the test suite, specs/data formats (or links to them), etc.

For more context, see the [verifier docs discussion](https://groups.google.com/d/msg/mozilla.dev.identity/ByMcA5k7tFw/fJYUeRi2_6gJ) on the dev-identity mailing list.

**Comment by callahad** [comment]
There is some shared code that we'll want to extract out (which is going to be awesome) around authority discovery.

Or move that into the verifier and have the mozilla/browserid repo depend on the verifier? Ooh! I like that!

**Comment by fmarier** [comment]
I like the idea. In theory, the verifier should be a different project from the shim and fallback IdP because it's a separate service. It could be deployed separately from the rest (and likely much less often).

The fact that there is shared code suggests that perhaps we could extract a node module that both of these could depend on?

Of course, while I think this might be the right way forward, the downside is that it's a bit of extra work for us.

**Comment by seanmonstar** [comment]
I definitely feel this is the right way forward. People can currently try
to host their own verifier, but doing so requires getting the full
browserid system installed and working. And pointing them at the code is
hard as well, since it has express and compute-cluster stuff in the way,
that doesn't need to be part of the base verifier.

**Comment by lloyd** [comment]
Heh.  I'm a broken record.  

Are we sure we want to do this?  How will we manage code duplication in Idp lookup - aka primary.js.

My meta point here is with over 400 open bugs, I'm unsure we should file anything that isn't urgent actionable, and agreed upon.  How do others feel?

-- lloyd (thumb-typing)

**Comment by fmarier** [comment]
I'd say yes, we want do this, but probably not right now. It's a worthwhile thing to do, but I don't see it as a priority.

Regarding your meta-point, if we're not filing these in the bug tracker, how else should we keep track of non-urgent things that we should do at some point?

**Comment by lloyd** [comment]
I agree we should do this, and have argued for it many-a-time.  Also, we should be using the certifier instead of keysigner, a very related project.

But I'm struggling with the > 400 open issues.

Maybe a formal backlog?  And a clearer definition of what belongs in the bug tracker?  would this just be a placebo, or would it meaningfully improve the visibility of community reported issues and actual defects?  Am I proposing that we differentiate between software defects and new features?

More questions than answers.

**Comment by seanmonstar** [comment]
So, we agree we should do this.

The other part, having too many issues, seems like it's trying to hijack
this issue. Maybe move to the mailing list?

**Comment by SamPenrose** [comment]
I spent my Friday on this as follows:
- copied browserid/, post npm install, to a new directory
- hacked out a new test script that just runs tests/verification-test.js
- started deleting files and looking to see what breaks the tests

Eventually I wrote a script to speed the last bit up, which meant discovering lots of tests that hang forever if a module is missing. Good news: I deleted some stuff and kept the verification tests passing. Bad news is I couldn't delete _much_, though I suspect that of these categories:

  1) verification proper
  2) verification HTTP interface
  3) test harness and miscellaneous unneeded require() targets

the first is probably pretty small, and the second can probably be factored out. Notably, in (3) we run tests/lib/start-stop.js, and I don't know how much extraneous material that pulls in. If anyone who actually knows their way around this repo thinks that they could help me attack (3), that would be a big help.

**Comment by SamPenrose** [comment]
OK, browserid is about 50MB, not counting node_modules. My dismembered copy that still passes the 91 checks in verification-test.js is down to about 6MB and something like 200 files. I'm sure I cut some files that would be needed to run a verification service for real. Conversely if I understood the test harness I could probably cut more. If @chilts or anyone else thinks they might find this useful, let me know and I will try to clean it up enough to stick on github.

**Comment by SamPenrose** [comment]
I've got my mangled thing down to ~13K LOC. I'm going to start getting it ready for github. Also, it looks to me like start-stop.js adds a dozen counted asserts to verification-tests (and presumably each of the other 40+ suites in browserid/tests/ that use it), which would mean that the 1900 vows that npm test claims to pass in browserid is really about 1500.

**Comment by ozten** [comment]
Post your branch here, when it's up. I'd love to take a peek.

**Comment by SamPenrose** [comment]
https://github.com/SamPenrose/browserid-verify-assertion (no create repo perms in mozilla/). What would help me is for someone to take a quick look, notice that "hey, this is completely wrong you should/should not have included XYZ", and comment accordingly. Also I didn't include any of the browserid git history, which is presumably a major foul. Happy to redo via fork or whatever.

**Comment by ozten** [comment]
Great stuff!

If you have the same architecture as Persona, then you need `bin/router` and `bin/verfier`, but you don't need the other files under `bin`.

You don't need `l10n-all.json`, `l10n-prod.json` config files. You may need some of aws.json, local.json, and produciton.json, but it will only be the settings that affect the verifier.

Unless the tests require it, you don't need the top level `example` directory.

You don't need `resources` this is frontend code.

Aside from `scripts/test_verifier`, I doubt you need any of the other scripts.

**Comment by SamPenrose** [comment]
Excellent, thanks for the feedback. I'll look into excising the parts of the test suite that rely on those files. Also, I realized that I could extend this approach to each of the files in test/ and record the results, which could give us a DAG for browserid as represented by the tests. Not sure if anyone would find that useful, but it might be interesting to see where the cleavage lines are. Value will be limited by the coverage of the tests

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
