### ISSUE TITLE
b2g: hyperlinks don't work inside of native UI

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3279]
on romaer2 , b2g 1.1.0.0-prerelease: build id 20130418070205
1. goto native.123done.org
2. click sign in
3. click on any hyperlinks in the native UI

result: hyperlinks don't jump to any other pages.

actual: you'd expect it to switch browser tabs to the link that's clicked.

**Comment by shane-tomlinson** [comment]
@edmoz - When opening Persona from Marketplace, a single, isolated tab is opened, this tab cannot open new tabs. Because of this, we have to open links in an IFRAME that is overlaid on top of the page (see #3236). #2905 is a bug about removing the header and footer from the Persona TOS/PP when opened in this iframe because users should only be able to view TOS/PP links in the embedded IFRAME, they should not be able to browse away.

**Comment by callahad** [comment]
@shane-tomlinson please link to the open PR

**Comment by jedp** [comment]
That PR looks lovely on desktop and on b2g device.  Beautiful work, @shane-tomlinson

**Comment by shane-tomlinson** [comment]
This should be fixed with the merge of #3236. TOS/PP links are opened in an iframe and are only allowed for sites served up using https. The header and footer are no more.
