### ISSUE TITLE
https://native-persona.org/ is not loading

### ISSUE THREAD

**Issue by kumar303** [mozilla/persona#3282]
It appears that https://native-persona.org/ is not loading. Jed, I know you mentioned something about merging and replacing the server instance. Do we need to use a new URL now? This is blocking FxOS payments from happening so let us know how we can work around it.

**Comment by jedp** [comment]
The URL did not change, but it's certainly unavailable.

**Comment by jedp** [comment]
Huge thanks to @shane-tomlinson for jumping onto the aws console and helping out.

The recently-deployed b2g server, `2g_2013-04-16-738ece2e {i-61536d0c}` seems to have gone up in flames.  Since aws can't even stop/start it, I'm not optimistic about getting at the logs :(

So we've repointed the IP back to the older server, `native-persona {i-211a4c50}`.  We can try a fresh deploy on Monday and see if we can get any clues as to what went wrong.

Thanks for the report, @kumar303, and sorry about the outage.

**Comment by kumar303** [comment]
Thanks Shane, thanks Jed. Please check with me before you switch it back to AWS because we're in Spain right now (on an awkward time zone) testing payments; we're trying to keep everything as stable as possible.
