### ISSUE TITLE
interaction_data should have improved decoupling of incoming and outgoing requests

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3295]
interaction_data should have improved decoupling of incoming and outgoing requests

**Comment by jrgm** [comment]
Maybe by (ab)using compute cluster.

**Comment by lloyd** [comment]
The underlying problem here is that our servers are not sufficiently resilient to our kpi collector falling down.

KPI is important, but our service staying up is more important.

The fix is to make it so that when we fail to pass KPI data to kpiggybank, we drop it on the floor.

The easiest possible fix is to leverage (or abuse) compute cluster which already has the ability to perform only some small number of actions simultaneously, and to fail when the backlog gets too big.  We should compliment this with logging and statsd information.

I'm happy to take this.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
