### ISSUE TITLE
b2g: account manager is not signed in after you sign into native.123done.org

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3300]
This is touches on the security model of b2g, in that each tab is a different sandbox. However, the behavior is different than desktop, so it should be logged.
1. goto native.123done.org on b2g and sign in
2. goto login.native-persona.org

acutal: you are not signed into account manager
expected: you should be sign in just like the desktop experience.

**Comment by callahad** [comment]
@jedp thinks this is a misconfiguration on native-persona.org. Jed, take it away.

**Comment by jedp** [comment]
@edmoz is exactly correct.  I didn't realize until checking just now that there's no navigator.id.\* action on the landing page at (native-)persona.org.  So yes, due to the b2g security model, in which cookies and localStorage are siloed in each app (incl browser), this is not going to work on b2g.

On b2g, we work around the siloing by storing the state in the system app's context, and having all navigator.id.\* methods actually operate on iframes owned by the system app.  There's no useful browserid state in the browser or any other app on b2g.

fwiw, the b2g policy is also going to affect other auth systems in a simliar way (facebook connect, for example, won't be very connecty).

I wonder whether we could make navigator.id.wsapi.\* wrapper functions?  That would let us solve this problem on b2g, and it could also provide a simpler interface for clients.

**Comment by jedp** [comment]
Actually it sounds like @shane-tomlinson, by updating the persona.org landing page to do some navigator.id calls, may have fixed this already!  Looking for the relevant commits to cherry-pick into b2g for testing.

**Comment by shane-tomlinson** [comment]
@jedp, @edmoz - FWIW, we changed all the landing pages to now include the JS shim, so navigator.id.\* should be available to you.

**Comment by shane-tomlinson** [comment]
@jedp, @edmoz - though even in the mainline branch, if you are chilling at the landing page in one tab, open 123done in another tab and sign in, the original landing page _will not_ transition to the account manager.

**Comment by shane-tomlinson** [comment]
@jed - I just got to the comment about cherry picking. Oh man, this was a HUGE change. https://github.com/mozilla/browserid/pull/3253 is the PR.

**Comment by edwindotcom** [comment]
@shane-tomlinson - yeah - i know existing tabs will not redirect to account manager.  But on desktop, navigating to account manager will be in signed in state.

also cancelling acct, does not logout on b2g phone.  I believe it would on desktop.

**Comment by jedp** [comment]
@shane-tomlinson wow, 96 additions and 957 deletions is a thing of beauty! 

I'm inclined to hold off on cherry-picking this over to native-persona for now.  I'd prefer to wait until our merge is done and I can just push dev to native-persona in one swell foop.

**Comment by jedp** [comment]
Edits - we don't use the special url `native.123done.org` anymore, and we don't use `native-persona.org`.

So for folks trying to reproduce this, just go to `123done.org` and `persona.org`

**Comment by ozten** [comment]
The account manager page uses `user.checkAuthentication` to see if you are logged in (not a localStorage hack or anything like that).

The page on https://firefoxos.persona.org/ includes https://login.persona.org/include.js. I don't see from `adb lolcat` enough context to understand why we don't have an active session on login.persona.org. Would it be that the Account Manager's JS isn't running in the System App sandbox? ([start.js](https://github.com/mozilla/browserid/blob/dev/resources/static/pages/js/start.js), [manage_account.js](https://github.com/mozilla/browserid/blob/dev/resources/static/pages/js/manage_account.js))

**Comment by ozten** [comment]
Changing to 2 stars. I think the real fix is to create a widget in FirefoxOS Settings which allows you to do account management. This would be executed in the system app sandbox.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
