### ISSUE TITLE
Persona login with available https siteLogo not working if request is from http page

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3314]
Reported by Olav Nymoen in https://bugzilla.mozilla.org/show_bug.cgi?id=866016

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1488.0 Safari/537.36

Steps to reproduce:
1. Included login.persona.org/include.js shim
2. Entered navigator.id.request({siteLogo: '/img/logo.png'}); from a site on normal http, when the logo was available both on http and https.

Actual results:

Error saying: improper usage of API: Error: only https sites can specify a siteLogo

Expected results:

Should have tried retrieving the https logo.

**Comment by jedp** [comment]
We do restrict siteLogo to sites whose origins are served via https.

https://github.com/mozilla/browserid/blob/dev/resources/static/dialog/js/modules/dialog.js#L244

Olav, are you trying to serve a logo from a different site?

/cc @fmarier

**Comment by callahad** [comment]
As a separate question, is this common?

We can't allow HTTP logos into the popup's HTTPS origin, otherwise mixed content warnings make a mess of everything.

I don't think we can blindly try HTTPS, either, because at that point we don't have any evidence that the site supports HTTPS or that the user agent would trust the site's certificate.

So... if a site can serve its logo over HTTPS, why isn't it serving the rest of the site over HTTPS?

**Comment by callahad** [comment]
Tagging as 2-stars. We have some existing bugs open to loosen siteLogo restrictions, possibly by allowing data URIs, which might be a better solution than trying https for http origins.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
