### ISSUE TITLE
 [Trusted UI] Native persona (navigator.id) stops responding during beginning of payment

### ISSUE THREAD

**Issue by jds2501** [mozilla/persona#3317]
Migrated from https://bugzilla.mozilla.org/show_bug.cgi?id=864760.

There's no easy way to reproduce this but we've seen it multiple times on today's build.

What we see:
- the TrustedUI opens to WebPay
- the TrustedUI remains open but the login never completes, it just hangs

Build info, tested on Unagi:
  https://git.mozilla.org/?p=releases/gecko.git;a=commitdiff;h=e729e5a826d4accc3a75062c3c29268d1b595980
  https://git.mozilla.org/?p=releases/gaia.git;a=commitdiff;h=29c51d4c0101cf6509dff9685a6a83840550c803

I'm attaching the full logcat and HTTP requests/responses but this looks suspicious (this is the end of the logcat):

Identity SignInToWebsiteController: received delegate finished; telling content to close the dialog
XXX FIXME : Got a mozContentEvent: undefined
Identity SignInToWebsiteController: No more watchers; clean up persona host iframe
Identity SignInToWebsiteController: telling content to close the dialog
NOTE: child process received `Goodbye', closing down

**Comment by jedp** [comment]
The "today" in "today's build" was April 23.

We had been having an issue with certificate expiration causing verification failures.  That has been fixed (it was the 3.29 train hotfix, if I recall correctly) and pushed to b2g on the 24th.  I am hopeful that this fix has solved this problem.  The last verifier error I saw in the logs was from april 24, before we pushed the fix.

To be sure, I need to check with @kumar303 and see if they're still running into this.

The lines at the end of the logcat may look suspicious (most logcat lines do, to me), but these are completely healthy.  They are indicating that the persona flow is complete, the dialog can be closed, and the OS can clean up the process it's running in.  The mozContentEvent undefined warning is ok.  It's alerting us that we didn't add a `type` parameter to our content message, which turns out to be against gaia style.  We will fix that, but it's not hurting anything.

**Comment by jedp** [comment]
I spoke with @kumar303; he said he'd try to reconfirm.

@jds2501 I believe we've fixed the bug that was causing this (cert expiration), and would like to close this.  But can you tell me if the _symptoms_ are persisting?  Is there something else afoot that we need to address?

**Comment by jds2501** [comment]
@jedp I think you are looking for @kumar303 with the question to me. He was the original filer of the bug.

**Comment by kumar303** [comment]
@jedp it sounds like you fixed it server side. What day/time do you think it was fixed on? I haven't seen the symptoms recently but I have not been testing payments for a couple days. Krupa would know. I don't know what her github account is to ping her about it.

**Comment by jds2501** [comment]
cc @krupa

**Comment by krupa** [comment]
I haven't seen this bug all this week.

**Comment by krupa** [comment]
I spoke too soon. I just hit this bug on 2g. However closing the trustedUI and starting over worked.

**Comment by jedp** [comment]
@kumar303, @krupa: It sounds like this is no longer biting.  Please re-open if it's still a problem.

**Comment by kumar303** [comment]
Correct. I have not seen it. Thanks!
