### ISSUE TITLE
Persona should work with file://

### ISSUE THREAD

**Issue by mounirlamouri** [mozilla/persona#3323]
I tried to use Persona locally via a third-party library and I was surprised to see a cryptic error regrading the scheme. After trying the same library online in the example page, I realised that I was testing locally from file://.

Not being able to use Persona from file:// scheme is breaking some use cases.

**Comment by shane-tomlinson** [comment]
Dup of #39 (yes, #39)

**Comment by seanmonstar** [comment]
@mounirlamouri what use cases is that? are there some, besides testing locally?

**Comment by mounirlamouri** [comment]
Why wouldn't I be able to send an HTML file or a ZIP file to someone with a web application inside? Why should the web application be hosted somewhere?
That could also be used by Android/iOS applications: they could simply use a webview on local files (bundled).

**Comment by callahad** [comment]
If you're sending the application as a ZIP file, what are you trying to do with authentication? It would be trivial to circumvent it, right?

**Comment by mounirlamouri** [comment]
On 01/05/13 13:14, Dan Callahan wrote:

> If you're sending the application as a ZIP file, what are you trying to
> do with authentication? It would be trivial to circumvent it, right?

Isn't the base idea of Persona that you can't circumvent auth? I mean,
you can't fake to be logged in. The user would be able to remove the
code that checks that you are identified but then you just need to make
sure that the server never sends data if you are not logged in. Which is
something you anyway need to do.

**Comment by callahad** [comment]
Ah, okay. So you're sending the frontend in a zip file, but that frontend still talks to a remote backend that is _not_ under the client's control?

How urgent is this need for you? Out of curiosity, may I ask why sending people a link to a hosted frontend isn't ideal, given that you're hosting a backend either way?

**Comment by lloyd** [comment]
because the origin cannot be used here, this use case would mean any locally issued assertion would be able to authenticate to your server.  

Concretely, I can write a local application, users sign into it, and then I can use issued assertions to authenticate to your server and impersonate the user without you knowing.  is this acceptable risk for you?

**Comment by mounirlamouri** [comment]
> How urgent is this need for you? Out of curiosity, may I ask why sending people a link to a hosted frontend isn't ideal, given that you're hosting a backend either way?

It's not terribly urgent, I will just use something else as a login system.

> because the origin cannot be used here, this use case would mean any locally issued assertion would be able to authenticate to your server. 

Why the origin can't be used? This should probably send a null origin or something similar, right? Couldn't that information be used somehow?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
