### ISSUE TITLE
Developer FAQ on mozilla.org should link to MDN

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3326]
The Developer FAQ here: ttps://www.mozilla.org/en-US/persona/developer-faq/

doesn't have any links to our developer documentation on MDN.

**Comment by callahad** [comment]
The upstream repo is mozilla/bedrock, and they prefer to have Bugzilla tickets for pull requests. :)

I'd also suggest changing it from "Developer FAQ" to "Developer Docs" and point directly to the main MDN page...

**Comment by callahad** [comment]
(Whoops, missed the comment button)

It's 8 PM here; I'll whip up a fix in the morning, but feel free to preempt me.

**Comment by callahad** [comment]
Bugzilla Issue: https://bugzilla.mozilla.org/show_bug.cgi?id=867773
mozilla/bedrock Pull Request: mozilla/bedrock#818

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
