### ISSUE TITLE
Errors thrown inside `navigator.id.watch` callbacks get swallowed

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3374]
If an error is thrown inside the `onlogin` or `onlogout` callbacks (and presumably `navigator.id.request`'s `oncancel`), it is not reported in the error console. This means that login seems to mysteriously stop working in these cases for no apparent reason. Tracing the code in Firefox's dev tools and Firebug produce no useful debugging information since they don't report exceptions as they happen.

**Comment by seanmonstar** [comment]
Indeed, this seems true of `onlogin`: https://github.com/mozilla/browserid/blob/dev/resources/static/include_js/_include.js#L405

It seems like we didn't want errors in user provided scripts to stop our code from finishing up the event. Which makes sense... but it also sucks that you can't see the error.

Also worth noting that this behavior only happens when `onlogin` is called from the return value of the dialog. `onlogout`, `oncancel`, and `onmatch` aren't surrounded by try/catch, and the automatic login that would happen after redirecting once you completed email verification also isn't wrapped up.

**Comment by mattbasta** [comment]
For what it's worth, you shouldn't need to wrap your code in a try/catch block anyway. If there's an internal problem with Persona, wouldn't you want that exposed so you can correct the issue? You'll get exactly zero feedback about broken internals if you swallow your own errors.

**Comment by seanmonstar** [comment]
Ah, we don't swallow our own errors. That catch block is to protected the
internal code from errors written by the user in the `onlogin` callback. We
didn't want their errors stopping all our internals, methinks.

**Comment by mattbasta** [comment]
Perhaps you can catch the error, assign it to a variable, and throw it once you're out of the critical code path?

**Comment by deepak1556** [comment]
you can use domain feature of nodejs to solve the problem. put the code in the critical path to emit an event if error occurs and handle them in the listener.

**Comment by seanmonstar** [comment]
@deepak1556 this is code that executes in the browser, when you call `navigator.id.watch()`

**Comment by deepak1556** [comment]
a possible solution can be to them in a try-catch-final block without affecting code path and at same time throw the error to users.. 

``` javascript
  try {
   if (observers.login) observers.login(r.assertion);

 } catch(e if options.error = e ) {

            // client's observer threw an exception

 } finally { 

    console.log(options.error);
}
```

**Comment by jedp** [comment]
@lloyd suggesting we catch it, console.log it, and re-throw it.  Sounds like a great feature.

**Comment by lloyd** [comment]
this is a great idea to help developers when integrating persona, I :heart: it.

**Comment by jaredhirsch** [comment]
PR merged but bug was left open, closing.
