### ISSUE TITLE
b2g: unable to scroll when signing in to primary idP

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3376]
1. goto dev.123done.org
2. sign in with a user@yahoo.com or user@eyedee.me acct
3. go through flow to yahoo branded sign in page

result: unable to scroll around, i have to get out of keyboard mode, then tap on the password field.

**Comment by jedp** [comment]
Current plan is to disable primaries for v1 on b2g, so closing for now.

**Comment by edwindotcom** [comment]
I'm going to reopen as primaries are currently enabled

**Comment by jedp** [comment]
I can scroll around in eyedee.me, but not yahoo.com.

@shane-tomlinson do you think this is an issue to be addressed in browserid?  Or is this something that the primaries themselves have to fix?

**Comment by callahad** [comment]
Sounds like an upstream issue, potentially in B2G?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
