### ISSUE TITLE
Document prefixed experimental features

### ISSUE THREAD

**Issue by kumar303** [mozilla/persona#3384]
There was a thread here where we discussed documenting experimental, prefixed options to Persona APIs. Let's do the documentation part!

Thread: https://groups.google.com/d/msg/mozilla.dev.identity/JzDcePzAs4c/kRN5GL05l4QJ

This would be helpful for Firefox OS payments bugs [like this](https://bugzilla.mozilla.org/show_bug.cgi?id=850084#c11) but also for other community members who want to weigh in on the design of said features.

As of this writing, these are probably the only experimental options to document: https://github.com/mozilla/browserid/pull/3370/files

**Comment by ozten** [comment]
+1

I would document forceIssuer's only valid value as a hostname (or whatever). there is some discussion about `undefined` to disable the API in `request` and via the `verifier`.

**Comment by kumar303** [comment]
Can we please get some documentation here? It's hard for the Marketplace team to collaborate on features because no one besides me and a few others know how things work and what's going on in Persona.

**Comment by seanmonstar** [comment]
Ah yea, these experimental features... they're going to go away (from Persona) as soon as Firefox Accounts is deployed and being used by FxOS/Marketplace...

**Comment by kumar303** [comment]
Heh, ok. Well, in the short term the `experimental_allowUnverified` is really important to document because it produces unverified assertions which are different.

**Comment by kumar303** [comment]
I guess I'll continue to take time out of what I'm doing to explain it to everyone else

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
