### ISSUE TITLE
Services should return a 400 when unknown params are included in requests

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3402]
For example, if marketplace sends a request with `allowUnverified` instead of `experimental_allowUnverified`, persona should return a 400.  Currently, it just ignores the unfamiliar parameter.

/cc @kumar303

**Comment by seanmonstar** [comment]
Ew...

**Comment by jedp** [comment]
@kumar303 and I grossed @seanmonstar out

**Comment by jedp** [comment]
@lloyd is intrigued and will follow-up with @seanmonstar

**Comment by lloyd** [comment]
@seanmonstar you don't like this?  seems like it could help people find problems.  Seems like we would never want to remove non-required experiemental parameters.  Also seems like this could break people in the wild.

When we've discussed this in the past with @warner we've talked about returning an array in the verifier that are "warnings" which a client can look for and log in their server.

thoughts?

**Comment by seanmonstar** [comment]
Oh, this is meant more for the verifier? That sounds less gross. It sounds
possibly mean, if we deprecate experimental parameters.

I was worried this meant that if I do `navigator.id.request({ foo: 'bar'
})`, the dialog would 400.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
