### ISSUE TITLE
[B2G] Verify password page is too wide for the frame

### ISSUE THREAD

**Issue by zacc** [mozilla/persona#3409]
For the unverified user workflow at the step for create/verify password the input fields are too side. Also the footer text does not seem right, or at least to the precision standards of the Identity team.

The second screenshot shows panned to the right side; there is a grey border on the side.

![2013-05-15-07-13-10](https://f.cloud.github.com/assets/966053/507174/c851d938-bd69-11e2-8f9b-bd349eca9f28.png)
![2013-05-15-07-16-11](https://f.cloud.github.com/assets/966053/507196/24341400-bd6a-11e2-9459-1e0e8a911e6d.png)

**Comment by zacc** [comment]
Actually this appears to be specific to the Firefox OS version I am using.

b2g18/v1.0.1 -> As above
Gecko  http://hg.mozilla.org/releases/mozilla-b2g18_v1_0_1/rev/d40d1831ff41
Gaia   e2187565da22df0c85b2eb501ced4efd342b7bc2
BuildID 20130514230202
Version 18.0

b2g18/v1-train -> Works fine
Gecko  http://hg.mozilla.org/releases/mozilla-b2g18/rev/ad04d81b3eeb
Gaia   f4a59b245ea762eea2e9a30fc136229c0fe6f73f
BuildID 20130514230207
Version 18.0

**Comment by shane-tomlinson** [comment]
This looks to be some discrepancy in the renderer, on desktop it looks like:

![screen shot 2013-05-15 at 15 38 54](https://f.cloud.github.com/assets/848085/507337/8279ea82-bd6d-11e2-8034-5dd02fcd4775.png)

Which of the versions you quoted is going to ship? 0202 or 0207?

**Comment by zacc** [comment]
Unfortunately the 'bad' one, v1.0.1.

**Comment by jedp** [comment]
@zac interesting - i tested on yesterday's v1.0.1 build from pvtbuilds and didn't get that wide input issue.  I'll try today's build now

And, ugh - v1.0.1 has different css behavior than v1-train? That makes it exceedingly difficult to design and test this.  @shane-tomlinson i'm trying to figure out more.

**Comment by AutomatedTester** [comment]
can someone ping me before pushing this out as it's uncovered a nasty Marionette bug

thanks ❤

**Comment by shane-tomlinson** [comment]
This has made its way into stage and is due to the changes for B2G. @zacc did an awesome job coming up with STRs

STR
1) Open dialog in B2G (or on a desktop browser resized to ~B2G size), if signed in, sign out
2) Enter in an unknown secondary email address > 31 characters long
3) Check out the width of the input boxes

Diagnosis:
Above the first input element, we write the email address to a label. This is shown to desktop users. Mobile users do not see it. Instead of doing a `display: none` on the label, it is hidden using `visibility: hidden` so that screen readers still read the label. No max width/overflow is set on the label, allowing it to expand to infinity, which also cause the input boxes to continue expanding.
