### ISSUE TITLE
Update new design to work with mobile

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#341]
There is an m.css, but since I changed the markup, the css needs updated.

**Comment by shane-tomlinson** [comment]
merge 4e9883bd3d857528821f0a583aefcbf794c61587 addresses a lot of this, but more can be done.

My basic changes are to make buttons larger, space out the email addresses more, make things easier, but I feel the relative font sizes could use some UI genius know how work.

**Comment by ghost** [comment]
@shane-tomlinson - here are some more UI changes that need to be done for mobile:
1. on diresworb.org, the BrowserID image should be moved to the right of the "Connect with..." text, as on desktop (more efficient use of space, less scrolling).
2. footers should be at the bottom of the page no matter how large or small the page content is (on most Signing in pages/dialogs it occupies somewhere around a half of the page).
3. The "We sent ..." text on the Check your email pop-up should be centered (portrait view).
4. Dialogs on tablets should be smaller - currently they occupy almost all the screen although there is little data on them.
5. The area the user can tap to perform an action should be well defined - currently it is very difficult to tap on the "forgot your password?" link since the device sees it as if the user tapped on of the the textboxes above/under it.

**Comment by shane-tomlinson** [comment]
Did some experiments for footers today using position: fixed.  All of the mobile browsers fail miserably.  We could do this with Javascript, but it seems like a hacktastic hack.

**Comment by ghost** [comment]
When in landscape mode on Android phones (native browser), the user has to scroll horizontally BrowserID Signing In dialogs in order to see their whole content. Horizontal scrolling doesn't make a good user experience, especially when there is still space on the page to rearrange items so it wouldn't be needed.

**Comment by shane-tomlinson** [comment]
Closing in favor of #882
