### ISSUE TITLE
New person UX changes do not fully match the mocks

### ISSUE THREAD

**Issue by krupa** [mozilla/persona#3410]
## Steps to reproduce
1. Launch marketplace-stage app on your unagi phone (1.0.1)
2. Start the purchase flow 
3. Check the new Persona screens and make sure they match the mocks by Maureen
## Observed behavior

The following things don't match the mocks-
1. Header says "Sign in" instead of "Firefox Marketplace"
2. There is a section for Marketplace Terms and privacy policy. We need to move this to diff screen (Sign in) or make it pretty (I file a separate issue for that)
3. The email input field is missing Persona styling (see screenshot)
4. The button says "Next" when it should say "Continue"
5. Button is enabled when the formfields are empty.
![ux changes to persona](https://f.cloud.github.com/assets/301317/508865/8b40325e-bd93-11e2-9b10-54e51db57c3b.png)

**Comment by mhanratty** [comment]
Let's add the Terms and Privacy Policy for Marketplace directly underneath the Persona terms.

![screen shot 2013-05-15 at 3 28 08 pm](https://f.cloud.github.com/assets/4432402/509769/e541868e-bdae-11e2-9c99-0d004e92f921.png)

**Comment by jedp** [comment]
Tracking the location of the tos/pp links in issue #3413

**Comment by jedp** [comment]
To give some context for the title: It says 'Sign In' because [bug 829355](https://bugzilla.mozilla.org/show_bug.cgi?id=829355) made localization of the 'Sign In' title a tef+ blocker.  [Comment 22 in bug 813811](https://bugzilla.mozilla.org/show_bug.cgi?id=813811#c22) instructed that inheriting the title was not a v1 blocker.  So we will certainly fix this, but it will be v1.1.  (Note that it requires a platform change in gaia; this isn't server-side.)

**Comment by edwindotcom** [comment]
@skinny97214 is looking into this and will contact marketplace UX to resolve

**Comment by edwindotcom** [comment]
Maureen has reviewed and is ok to go live minus a few tweaks.

**Comment by shane-tomlinson** [comment]
@mhanratty, @jedp, @skinny97214 and I had a pow-wow about the current state of the UI. There are some slight discrepancies, but no known blockers. 

Opened #3457 about inlining the tooltip text.

Closing as signed off as being "good enough for V1.01"
