### ISSUE TITLE
[IE] /sign_in dialog flips behind the opener window

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3423]
STR
1. Use either IE8 or IE9 and go to http://dev.123done.org
2. Click sign in to bring up the dialog.

Expected: dialog opens and stays above the RP's window
Actual: dialog initially opens above the RP's window, but then the RP window moves above the dialog (potentially hiding it completely). 

Notes:
1. The does not happen on beta.123done.org (stage train-2013.05.08).
2. This does not happen with opera, safari, firefox or chrome on WinXP

Five star.

**Comment by jrgm** [comment]
To be clear that is IE9 on Windows 7, and IE8 on Windows XP, aand IE10 on Windows 8.

**Comment by jaredhirsch** [comment]
looking now

**Comment by jaredhirsch** [comment]
@jrgm I can't repro this on IE9/win 7 or IE8/xp. I don't have a Win 8 VM.

The STR are dead simple, so I'm not sure how I can twiddle VM settings to reproduce this.

**Comment by jaredhirsch** [comment]
OK, so I can't repro, but I have a theory around how this could happen. cc @shane-tomlinson 

If you open a window, then blur it (window.blur()), you get the popunder effect.

Our new dom.focus code (changed in 30e3f84) blurs the currently-focused element before focusing a new element. If the currently-focused element is the popup window itself, then we're effectively calling window.blur(), causing the symptoms @jrgm observed.

So, provided this can actually be reproduced, the fix is to do the search for focused elements lower than the document, maybe starting at document.body, instead of just doing $(':focus').blur() as seen [here](https://github.com/mozilla/browserid/commit/30e3f#L0R332).

_edited for clarity_

**Comment by jrgm** [comment]
Actually, I can no longer reproduce this with the IE's that I used before -  IE9 on Windows 7, and IE8 on Windows XP, aand IE10 on Windows 8.

**Comment by jaredhirsch** [comment]
closing. fingers crossed we don't have to reopen.

**Comment by shane-tomlinson** [comment]
@6a68 - NICE! I would have never thought of this, but it makes perfect sense. I can repro locally still. Theory testing time.

**Comment by shane-tomlinson** [comment]
I can reproduce this on IE8/Win XP after applying #3432, re-opening.

**Comment by shane-tomlinson** [comment]
@6a68 - your diagnosis was 100% spot on. The fix for IE8 was pretty simple, first, check if the focused element is the body. If it is, then skip blur.
