### ISSUE TITLE
development menu - show load screen is not hooked up

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3428]
Hey @shane-tomlinson I was looking at https://github.com/mozilla/browserid/pull/3396, and the development menu, and noticed that the 'Show Load' item does nothing, I think because the target div is not in the DOM.

This is probably on your todo list, so sorry if this is redundant or a duplicate issue.

**Comment by shane-tomlinson** [comment]
@jrgm - the load menu is hidden on desktop and only shown on mobile. I should probably change this, eh?

**Comment by callahad** [comment]
@shane-tomlinson to label this as mobile-only.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
