### ISSUE TITLE
diresworb/anosrep apache proxy must re-resolve DNS hostnames.

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3440]
With reference to https://github.com/mozilla/browserid/issues/3437#issuecomment-18091042. 

If I'm right, then the apache proxy for anosrep.org and diresworb.org was not re-resolving DNS hostnames. Since ELB can change the IP's it offers at any time, we need to be sure that the proxy is correctly honouring DNS TTL's.

**Comment by jrgm** [comment]
I think we need to set this On - http://httpd.apache.org/docs/current/mod/core.html#hostnamelookups

**Comment by gene1wood** [comment]
Just made this change https://github.com/mozilla/identity-ops/commit/04399fadbc5f9cea0b067255817ec69921c3ab52 and deployed. I think it should address this.

**Comment by callahad** [comment]
@jrgm Could you please verify and close if this is fixed?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
