### ISSUE TITLE
Create a Feedback Channel

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#3443]
[via the mailing list](https://groups.google.com/forum/?fromgroups#!topic/mozilla.dev.identity/xJslXiQX_-s)

If a user has a problem or wants to suggest an improvement, there are no
direct ways to give feedback.

Possible solution:
- Enhance login.persona.org with a link to support and feedback

I think we've worked hard to get developer insight and feedback, but are
missing the "end user" feedback loop.

**Comment by ozten** [comment]
@skinny97214 - Here you go.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
