### ISSUE TITLE
KPI: List of date/times that trains/changes are pushed to production

### ISSUE THREAD

**Issue by kparlante** [mozilla/persona#3447]
When graphing time series graphs of KPI data, we want to note milestones, in particular when trains get deployed to production.

I need a reliable/consistent way to get the list of recent pushes to production. A way to do this automatically would be great, but even a method that required some manual work on my part would be acceptable. (Right now I have no way to get these dates -- let me know if I'm missing something)

(I can re-file this in identity-ops if that makes more sense)

This request is important but not urgent; it would be fantastic to have this sometime in the next month.

**Comment by shane-tomlinson** [comment]
@kparlante, would it help to know which version of the code is running on the client when the KPIs are collected? We can send with the data package the current code version. I am not sure if this will require approval from data safety.

**Comment by kparlante** [comment]
@shane-tomlinson: Yes, I think we're going to want the code version with the blob -- it will also be useful down the road if we're doing bucket testing or A/B testing where different stacks with different code versions are sending blobs in the same time interval.

**Comment by kparlante** [comment]
@shane-tomlinson : @jrgm is working with me to get milestone data manually, which is good enough for this quarter. It is still probably a good idea to add the current code version, but we can batch that up with other changes that require approval later.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
