### ISSUE TITLE
refreshing bugzilla page after sign in and waiting 2 min results in assertion error

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3448]
Logging this just to describe the UX for some cgi or bugzilla users.
1. goto bugzilla.mozilla.org
2. click on 'sign in' and sign in with any user name, confirm email if necessary
3. leave your browser in a signed in state for at least 2 min
4. hit refresh
5. hit 'resend' in the alert dialog

actual: bugzilla says: Persona assertion has expired
expected: users should get an error when they refersh

John and I were discussing how this is an unfortunate behavior of resending and stale assertion, it would be good to explore work arounds or ways to avoid this.

**Comment by callahad** [comment]
This is because Bugzilla POSTs your assertion, so a refresh w/ "Yes, re-POST" results in re-sending a stale assertion.

**Comment by callahad** [comment]
Could be fixed with a redirect after POST?

**Comment by callahad** [comment]
@callahad to file upstream bug

**Comment by callahad** [comment]
@callahad to also annotate quick start guide

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
