### ISSUE TITLE
Safari error:'Viewport argument value "device-width;" for key "width" not recognized. Content ignored.'

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#345]
Does not affect usability.

**Comment by JohanStrandell** [comment]
This is due to semicolon instead of commas in the meta tag.

E.g. it should be
`<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, width=device-width">`

instead of 
`<meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">`

See: http://miniapps.co.uk/blog/post/make-sure-to-use-correct-meta-viewport-syntax/

**Comment by shane-tomlinson** [comment]
@JohanStrandell - thanks for the tip!  I fixed the syntax and no Webkit error.

**Comment by BachCN** [comment]
excellent solution @JohanStrandell
