### ISSUE TITLE
Canceling account on b2g phone should log you out

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3451]
@edmoz reported this in https://github.com/mozilla/browserid/issues/3300#issuecomment-17311567

**Comment by jedp** [comment]
I've opened a bug for creating a Persona component in the Settings app on FirefoxOS: https://bugzilla.mozilla.org/show_bug.cgi?id=892050

I don't think we're going to be able to really fix this kind of issue without that.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
