### ISSUE TITLE
Node modules installation on Ubuntu/Debian

### ISSUE THREAD

**Issue by quack1** [mozilla/persona#3472]
When I tried to setup my development environment on my Ubuntu 13.04 last week, I faces some issues :
- Wrong Node version in the Ubuntu repository (0.10.x)
- Some modules were not installed
- The help available in the documentation (https://github.com/mozilla/browserid/blob/dev/docs/SETUP_UBUNTU.md) was not up-to-date and didn't installed every necessary packet
- ...

@shane-tomlinson helped me out and I can get a complete running environment (http://irclog.gr/#show/irc.mozilla.org/identity/268299), and shane and I think that for more convenience it would be great if we could have a writeup and a script that do all the steps automatically.

**Comment by quack1** [comment]
My Pull Request #3474 is the script I talked about.
I also wrote a blog post to detailled it a little bit more in English and French : http://quack1.me/persona_setup_ubuntu-en.html

**Comment by lloyd** [comment]
fwiw, browserid now runs on node.js 0.10.x, the next person should have a better experience..  Thanks for your persistence and for blogging your experience!

**Comment by quack1** [comment]
I just updated the script I wrote (cf Pull Request #3474) to install the last 0.10.x version available in the `nvm` repository (0.10.9).
This way, the script ensures that we use a supported version of Node, even if the version available in the distribution repository is higher and/or not supported by Persona.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
