### ISSUE TITLE
compress JSON sent between client/server

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3475]
Reducing bandwidth will make a big difference for metered mobile accts. Not sure how the CPU cost of client-side compression will affect responsiveness.

**Comment by lloyd** [comment]
client side compression is nearly intractable - curious how much we'll actually win with this, but if we have free time it's worth quantifying server side compression if someone has time.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
