### ISSUE TITLE
Logo blurry on Retina

### ISSUE THREAD

**Issue by larrysalibra** [mozilla/persona#3490]
Mozilla Persona logo is blurry on Retina screens.

See screenshot:
[screen shot 2013-06-05 at 12 40 35 am](https://f.cloud.github.com/assets/597182/606862/af9a5d8a-cd35-11e2-92a1-422109df5e02.png)

**Comment by callahad** [comment]
Thanks! Seems like a good bug to tackle once we figure out a direction for #3286

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
