### ISSUE TITLE
The design of the dialog should respond to different window sizes

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3497]
There are circumstances that necessitate responsive design in the dialog, e.g., when the browser goes full-screen and opens the dialog in a separate tab, or when the user is on a tablet device.

**Comment by jedp** [comment]
For reference to firefox behavior, note [Bug 803675: Popup should always be opened in tab on fullscreen mode](https://bugzilla.mozilla.org/show_bug.cgi?id=803675)

And as gavin has clarified on IRC, where the comments say by "disable opening a new window", the meaning is in face "force new windows into tabs".

**Comment by shane-tomlinson** [comment]
@jedp - I am confused by this request. Can you give more information? The dialog already responds when opened as a tab instead of as a window, this behavior can be seen in Opera.

**Comment by shane-tomlinson** [comment]
@jedp - after reading over that Bugzilla bug, Persona will already take the appropriate action if platform decides to open dialogs in a full tab instead of a standalone dialog window. Another example browser is IE10 on Windows 8 Metro.

**Comment by jaredhirsch** [comment]
this happens on iPad as well

**Comment by jaredhirsch** [comment]
@ryanfeeley thoughts on how to gracefully puff up the dialog to tab-size?

**Comment by ryanfeeley** [comment]
Any possibilities to create a fully responsive approach from tiny Firefox OS mobile to wide screen? I also noticed that in my Safari browser (where new windows are tabs) how imbalanced it is. I'm all for tackling this.

**Comment by ryanfeeley** [comment]
BTW, that means I'll need to introduce a new column here, one for Desktop (full width) and one for Desktop (pop-up window) https://wiki.mozilla.org/Identity/Touchpoints

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
