### ISSUE TITLE
[b2g] Keyboard flashed with any touch in Trusted UI

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#3501]
In B2G 18.

Steps to Reproduce
1) Load UI Tests on Device, launch Identity tests
2) Wait for ready, then launch Cancel test
3) When we load in the trusted UI, click on the background of the page

Actual
Keyboard slides on screen, then slides away

Expected
No Keyboard

**Comment by shane-tomlinson** [comment]
@ozten - is this an issue in Gaia/Trusted UI code or the Persona code? Can you reproduce this on any other mobile device/browser? Does it happen in other applications in the trusted UI?

I am trying to pinpoint potential causes before taking wild guesses.

**Comment by shane-tomlinson** [comment]
@ozten - ahha. I believe the problem is we programatically focus the email field when the dialog opens. B2G ignores this. Whenever you click into the dialog, the forced focus takes effect, then the blur of where you clicked.

Wackity wack. I'd love a way of figuring out definitively if the user is on a mobile device and disable programatic auto-focus.  Unfortunately, checking for touch events is not sufficient with the advent of touch screen laptops.

**Comment by ozten** [comment]
I guess another way to look at it, is that the trusted UI isn't evaluating this focus, until the Trusted UI is clicked? It seems like the focus should happen immediately, no?

**Comment by shane-tomlinson** [comment]
@ozten - that is a great way of saying it. I do the focus as soon as the dialog opens, but the trusted UI does not seem to actually do the focus until the user clicks.

**Comment by ozten** [comment]
Filed [bug #881796](https://bugzilla.mozilla.org/show_bug.cgi?id=881796) to see if this is accurate.

**Comment by callahad** [comment]
I can repro. Suggest closing in favor of upstream bug?

**Comment by ozten** [comment]
Agreed. Closing.
