### ISSUE TITLE
move persona servers away from police state of USA

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#3505]
move persona servers away from police state of USA

**Comment by callahad** [comment]
Hi @ukaszg, thanks for chiming in. Please see [my comment](https://news.ycombinator.com/item?id=5855256) on Hacker News on [this topic](https://news.ycombinator.com/item?id=5854003).

Since moving our serves would only be trading one legal jurisdiction for another, I'm going to preemptively close this bug.

Instead, we need to double down on advancing Persona's promise of truly decentralized authentication. If we can deliver that, then each Persona user will be able to fully control who they choose to trust.
