### ISSUE TITLE
ephemeral instance resources are not gzipped

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3524]
This makes it difficult to run performance tests to see how we are doing.

**Comment by lloyd** [comment]
should we move this issue to awsbox?  @chilts are you interested in taking this along with a move to nginx on awsboxes?

**Comment by shane-tomlinson** [comment]
@lloyd - I could swear resources were gzipped on ephemeral instances at one point, have I been under a false impression the entire time?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
