### ISSUE TITLE
[kpi] Add email-verification-metrics.json

### ISSUE THREAD

**Issue by kparlante** [mozilla/persona#3528]
It would be great if we could count email verifications, aggregated by date. We're interested in knowing if new users are successful, and knowing the counts can help us validate the kpi data and count cases where users verify in a different browser, etc.

Similar to router-metrics.json and verifier-metrics.json.

cc: @shane-tomlinson, @lloyd

**Comment by kparlante** [comment]
UX is rightly worried about losing people in the email verification step. It could be that our kpi data currently shows a worse picture than we're really experiencing. We're doing our best to notice the case where people who close the window and then come back later after verification do succeed, but still have imperfect data. Would be great to double check this against # of successful email verifications per day.

**Comment by kparlante** [comment]
Depends on https://github.com/mozilla/identity-ops/issues/102 to get this in production.

**Comment by jaredhirsch** [comment]
The file that needs to be instrumented is [wsapi/email_for_token.js](https://github.com/mozilla/browserid/blob/dev/lib/wsapi/email_for_token.js).

**Comment by jaredhirsch** [comment]
We could generate an email-metrics file using [lib/metrics](https://github.com/mozilla/browserid/blob/dev/lib/metrics.js).

We could also use the new straight-to-piggybank logger I'm working on for mozilla/identity-ops#102. The lib is currently in a pull request [in my fork](https://github.com/6a68/browserid/pull/8).

We could do both, so that onboard debugging can verify the email verification link was visited, but also ship the data to our metrics collector for long-term trending.

**Comment by kparlante** [comment]
To solve the short term problem, not so important to generate email-metrics file if we're using the straight-to-piggybank logger. 

Longer term we have to work out our relationship with the metrics team (do we give them access to all of the kpi data? do we take on all of the pentaho responsibilities in the kpi dashboard?) We should have more clarity about this soon.
