### ISSUE TITLE
[b2g] db column 'type' conflict when user signs in with primary on desktop but secondary on b2g

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3530]
When we move all marketplace sign ins onto the main DB for all persona, there will be a conflict of what type of acct these are: primary or secondary.
1. user on desktop signs in with joe@yahoo.com acct.  In the db the type='primary'
2. user on b2g signs in with same joe@yahoo.com acct.  ForceIssuer causes the type to be 'secondary'

actual: db column will flip between types and desktop will stop using bigtent flow?

expected: db shouldn't have conflict.

**Comment by jaredhirsch** [comment]
more interestingly, what if joe@yahoo.com is logged into desktop persona (+bigtent) and fxos (-bigtent) at the same time?

**Comment by edwindotcom** [comment]
a few met and discussed, currently the belief is that updating the 'type' field's worst impact is adding one screen to the user experience when someone is switching between b2g and desktop.

**Comment by edwindotcom** [comment]
this is live and not many are running into this... FxAccounts may resolve this issue. - downgrading to 3 star.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
