### ISSUE TITLE
[b2g] with primary support - unable to logout of bigtent idp sessions in native UI

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3532]
logging as a placeholder of sorts as primaries aren't turned on firefoxos.persona.org right now.
1. sign into firefoxos.123done.org with user@yahoo.com
2. now try to sign in with a user_2@yahoo.com

actual: you've mismatched and there's no way to sign out of your existing yahoo.com session inside the native UI

expected: there should be a way to sign out.   The only way would be to clear local data, i think

**Comment by jedp** [comment]
For FirefoxOS, this will require the sign-out capability to be hosted in the dialog itself.  

This is a result of b2g's siloing of app data.  The browser tab has no access to any of persona's data (cookies, localStorage).

**Comment by jedp** [comment]
Changing the title to 'bigtent idp sessions', because I don't think this is going to be an issue in the general idp case (e.g., mozilla idp, sendmypin, gno.mn, eyedee.me, etc)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
