### ISSUE TITLE
Re-authentication?

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3539]
There are no docs for this that I could find, but we're going to need it in the Marketplace soon: what's the recommended way of having a "Please re-enter your password to perform this action" screen?

For instance, when you add and SSH key to Github, they ask you to re-enter your password. We'd like to do the same thing, but there isn't an apparent way to do it with Persona. Any thoughts?

**Comment by ozten** [comment]
I think the original design was that you'd include `forceAuthentication: true` to the request call. I think this landed 2 months ago.

I believe forceAuthentication is being moved to `experimental_forceAuthentication`.

See [Bug#808831](https://bugzilla.mozilla.org/show_bug.cgi?id=808831) and [Bug#811012](https://bugzilla.mozilla.org/show_bug.cgi?id=811012) for reference.

**Comment by mattbasta** [comment]
So the steps here are:
- Browser: `navigator.id.request` call with `forceAuthentication`
- Server: Verify the assertion
- Server: Return a one-time use, expiring token to the browser
- Browser: Pass token to the API endpoint of choice to confirm the action

Yes?

**Comment by ozten** [comment]
Yes, sounds good.

> Server: Return a one-time use, expiring token to the browser
> Browser: Pass token to the API endpoint of choice to confirm the action

I'm not up to speed on the design, but that sounds fine. Basically, if a user typed their pin wrong several times, one would set a flag server side to force a full re-authentication via Persona. This flag would not let the user type in a pin, until they had logged in via Persona. Once your servers validated the assertion, one would clear that flag and the user could re-try their pin.

Sounds like instead of a flag in a database, your passing around a token between distributed systems. Coolio.

**Comment by shane-tomlinson** [comment]
@mattbasta - you'll have to use experimental_forceAuthentication since this is still an experimental feature.

**Comment by shane-tomlinson** [comment]
@mattbasta - if experimental_forceAuthentication is what you are looking for, wanna close this down?

**Comment by mattbasta** [comment]
Yeah, this is fine. Do you guys have docs somewhere about `forceAuthentication`?

**Comment by shane-tomlinson** [comment]
@mattbasta - Not yet because it's not quite ready for prime time. It works for Marketplace that uses forceIssuer and primary IdPs are disabled and we can show the password field, but we have not yet figure out how we can surface this to primaries.
