### ISSUE TITLE
adjust jshint to catch ES3 reserved words

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3540]
One of this week's five-star bugs (#3522) was caused by using the ES3 reserved word 'native' as an object property. Android 2.2, our crappiest supported browser, apparently barfs on such words. Not even IE8, our other ES3-era browser, complains about `foo.native`.

It'd be great to sniff out these words as part of our jshint routine. I'm not sure the best approach to take. There's an [open pull request](https://github.com/jshint/jshint/issues/1139) against jshint to catch ES3 reserved words when used as object properties if you set `es3: true`. I'm not sure if that's the right approach, or when that patch will land.

@seanmonstar I'd love to get your thoughts here.

**Comment by seanmonstar** [comment]
That sounds solid to me.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
