### ISSUE TITLE
/wsapi/addressInfo returns `state: "transition_to_secondary"` after primary address is verfiied as a secondary

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3550]
It is marked as "transition_to_secondary" until the user has called /wsapi/cert_key.

This causes the fix for #3515 to go through some extra hoops.

STR)

1) Open local dev RP
2) Create new Persona account using example.domain
3) Disable example.domain primary support (add `"disabled": true` into .well-known/browserid)
4) Restart server
5) Open local dev RP
6) Open dialog, select address from #2
7) Enter in new password
8) Close dialog and RP
9) Open verification link in a new browser, enter in password from #7
10) Open dev RP
11) Open dialog
12) Open network console.
13) Select address from #2
14) The user's password is asked for even though they typed it in #9.
15) Check out the state in /wsapi/address_info - it is set to "transition_to_secondary"

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
