### ISSUE TITLE
[b2g] Signing into persona.org from FirefoxOS immediately signs out again

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3558]
Sorry, I'm pretty sure this is a dupe, but I can't find the other issue.

I think the problem is that the persona.org site looks for your login state in localStorage, but on FirefoxOS, that localStorage is far away in the system app.  (It's the siloing of data again)

**Comment by jedp** [comment]
This is probably a wontfix for Persona.  Instead, we should have account management in gaia itself.

I've opened [Bug 892050](https://bugzilla.mozilla.org/show_bug.cgi?id=892050)

Talking with @ozten, we think a good solution for this would simply to be to detect FirefoxOS visitors, not provide a sign-in button, and tell them how to reach the Settings app.

Demoting to three stars

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
