### ISSUE TITLE
[b2g] When wrong password is entered, no error is displayed

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3559]
(Reported by @kumar303)

Entering an incorrect password on FirefoxOS does not display an error.  A small triangle is visible, apparently part of a tooltip, but no tooltip itself can be seen.

(The page does function properly, in that it won't let you past with the incorrect password.  Retyping the password correctly allows the user to login.  So this is probably not a logic bug.)

**Comment by kumar303** [comment]
This is more or less what the screen looks like: 

![2013-06-19-11-11-33](https://f.cloud.github.com/assets/55398/675932/6bc2e190-d8fc-11e2-9cde-00f22f0bfb8a.png) 

The screenshot didn't capture the small triangle but that's all I saw, no tooltip and no error message. Pressing the signin button essentially did nothing until I entered the correct password.

**Comment by shane-tomlinson** [comment]
@kumar303 - I am testing with my FFOS phone pointed at "https://tooltips.personatest.org" and am seeing the tooltips as expected. Which server are you working against?

**Comment by shane-tomlinson** [comment]
@kumar303 - The fix for this was merged into train-06.05.2013 on 06.12, commit 5465483c05a121e0f1b1e30261002b69c9daa165 (tracking issue #3496). This code is currently on https://login.anosrep.org and is set to go into prod tomorrow (06.25). login.anosrep.org is not accepting new users at the moment, so I pushed the same code to tooltips.personatest.org and am seeing the tooltips there, though the behavior could be a bit better. Can you point your device's Persona host to https://tooltips.personatest.org to see whether the problem still manifests?

Which version of FirefoxOS are you running?

**Comment by shane-tomlinson** [comment]
@kumar303 - are you still seeing this problem? If not, could you shut this issue down?

**Comment by kumar303** [comment]
Go ahead and close it. I'll comment if I see it again. I don't seem to have access to close issues.

**Comment by shane-tomlinson** [comment]
Thanks @kumar303!
