### ISSUE TITLE
[b2g] When tooltip is displayed, input element loses focus.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3574]

**Comment by jedp** [comment]
Good catch.  A good one to fix, but the right action should be obvious to the user.  Added to the b2g milestone so we won't lose it when we eventually do a final sweep of b2g issues.

**Comment by shane-tomlinson** [comment]
This is the same cause as #2294

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
