### ISSUE TITLE
password field is not autofocused when verifying email address in second browser

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3575]
STR

1) Sign up as new user in Browser A
2) Verify email in BrowserB

Expected:
The email address should be focused.

Actual:
The email address is not focused.

![screen shot 2013-06-24 at 14 06 29](https://f.cloud.github.com/assets/848085/695391/e88e50e4-dcce-11e2-82db-6fd474a9da6d.png)

**Comment by yesyayen** [comment]
Why the email address should be focused. Its not even an editable textbox.   :)
or do you mean password filed is not auto focused (as mentioned in the title)

As of now, password field is getting auto-focused when verification link is opened in a different browser. I think you can have a look at it again and close this issue.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
