### ISSUE TITLE
iphone4 screens are jumbled

### ISSUE THREAD

**Issue by dianel** [mozilla/persona#359]
I could sign in, but it wasn't formatted properly for my screen.  I also couldn't resize the screen with two fingers, which is what I expect to do when screens aren't formatted properly.

**Comment by shane-tomlinson** [comment]
@daniel, which screens are jumbled?  We have just done a ux redesign addressing most of this.

**Comment by daniel** [comment]
I think you meant @dianel :)

**Comment by shane-tomlinson** [comment]
@daniel - you are correct - @dianel - which screens are jumbled on the iphone 4?  We just did an entire site redesign, you can see what we have done on dev.myfavoritebeer.org and dev.diresworb.org - using the dev server requires you to re-register because the databases between the two machines are not shared.  We spent quite a bit of time making this work on mobile and things were looking pretty good yesterday on my iPod Touch.
