### ISSUE TITLE
Phishing attempts are insufficiently distinguishable

### ISSUE THREAD

**Issue by callahad** [mozilla/persona#3600]
Based on the screenshot below, what are you going to log into?

![screen shot 2013-06-28 at 10 23 12 am](https://f.cloud.github.com/assets/24193/722723/4ba52776-e007-11e2-8cf3-7e7c82fd26e8.png)

**Comment by callahad** [comment]
Via email from Ben:

> Yeah, this could fool someone, but what is the incentive for an attacker to do this? So they can get your email address? It's not nearly as valuable an attack as typical phishing, which gets your password and thus all your data. So my feeling is that the risk is low.
> 
> Could be worth a few simple tricks, e.g. disallowing siteNames that look like domain names or origins that are not the suffix of the actual origin/domain name. But beyond that, my sense is that the risk is low.

**Comment by fmarier** [comment]
Unless I'm missing something, the only thing that `123done.org` would get out of this is the user's email.

The evil RP might trick the user into signin into `123done.org` by making it look (via `siteName` and perhaps more easily with `siteLogo`) like Google, but it can't use the resulting assertion for anything useful because the assertion's audience will be `123done.org` and will not allow that RP to impersonate the user on `google.com`.

**Comment by callahad** [comment]
Hrm. I still wish it was a little easier to figure out which item is what the site says it is, and which item is the domain you're actually going to sign into.

Still, with both Ben and Francois in agreement that this is not a problem, I'll close the bug.
