### ISSUE TITLE
communication_iframe pulls in a lot of images

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3602]
The first-time load of the communication_iframe is pretty heavy on desktop.  If we can, it would be a big help to our speed on mobile if we we could keep these things from loading.

Here's desktop firefox loading the communication_iframe from an m1.small ephemeral instance:

```
[09:26:10.655] uncaught exception: target window is same as present window -- not allowed
--
[09:26:21.702] GET https://webrtc.personatest.org/communication_iframe [HTTP/1.1 200 OK 528ms]
[09:26:22.258] GET https://webrtc.personatest.org/v/87236fe55a/production/communication_iframe.js [HTTP/1.1 304 Not Modified 345ms]
[09:26:22.563] uncaught exception: target window is same as present window -- not allowed
[09:26:22.631] GET https://webrtc.personatest.org/v/2e087b05eb/production/en/dialog.js [HTTP/1.1 200 OK 1069ms]
[09:26:23.710] GET https://webrtc.personatest.org/v/2189985728/production/en/dialog.css [HTTP/1.1 200 OK 352ms]
[09:26:24.078] GET https://webrtc.personatest.org/v/4c35c324fb/common/i/grain.png [HTTP/1.1 200 OK 496ms]
[09:26:24.597] GET https://webrtc.personatest.org/v/3ffe5e62d2/dialog/i/persona-logo-transparent.png [HTTP/1.1 200 OK 641ms]
[09:26:25.223] GET https://webrtc.personatest.org/v/b0e1d34973/dialog/i/arrow_grey.png [HTTP/1.1 200 OK 383ms]
[09:26:25.654] GET https://webrtc.personatest.org/v/ace06c36a7/common/i/button-loader.gif [HTTP/1.1 200 OK 449ms]
[09:26:26.107] GET https://webrtc.personatest.org/v/ccd9128527/common/i/button-arrow.png [HTTP/1.1 200 OK 294ms]
[09:26:26.407] GET https://webrtc.personatest.org/v/aa7b97aed0/common/i/button-arrow-hover.png [HTTP/1.1 200 OK 339ms]
[09:26:26.761] GET https://webrtc.personatest.org/v/043be45f4d/common/i/button-arrow-active.png [HTTP/1.1 200 OK 443ms]
[09:26:27.244] GET https://webrtc.personatest.org/v/0a9faad451/dialog/i/persona_watermark.png [HTTP/1.1 200 OK 353ms]
[09:26:27.595] GET https://webrtc.personatest.org/v/77e5d5d4c5/dialog/i/persona_watermark_sm.png [HTTP/1.1 200 OK 322ms]
[09:26:27.921] GET https://webrtc.personatest.org/v/29d9e089cb/dialog/i/persona_watermark_dark_sm.png [HTTP/1.1 200 OK 346ms]
```

**Comment by seanmonstar** [comment]
I believe that's from the prefetch links in the header. It's trying to
improve the load of the dialog by having things cached.

We had discussed this, and there was hope that the browser could determine
whether to prefetch or not.

**Comment by jaredhirsch** [comment]
@seanmonstar @jedp I did a bit of digging, this is funky.

Link prefetching is [only supported by FF](https://developer.mozilla.org/en-US/docs/Link_prefetching_FAQ), and that does include mobile firefox 21 on Android, but not B2G on my Keon (running 1.0.1.0), according to [this test page](http://browserspy.dk/prefetch.php). So, mobile FF users will experience weird sluggishness when they hit every RP site, it seems.

Chrome has [its own version](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/ksrOyFDKZo4), but it uses `rel="prerender"`, not Mozilla's `rel="prefetch"`, and cachify [doesn't add prerender](https://github.com/mozilla/connect-cachify/blob/master/lib/connect-cachify.js#L240). Beyond that, Chrome's heuristics don't allow https pages to be prerendered.

So, prefetching introduces complexity (in a separate library, but still), only helps one browser, and is bad for users and RPs on mobile versions of that one browser. I'd probably prefer removing prefetching completely, rather than add in even more complexity to sniff for a mobile UA to disable prefetch in that case. Thoughts?

**Comment by seanmonstar** [comment]
@6a68 Fennec experiences sluggishness from prefetch? I was originally afraid of that, but would have hoped that the browser would load those resources async, and after the rest of the site is loaded.

**Comment by jaredhirsch** [comment]
@seanmonstar: Hmm, you're right--I've tried a few RPs and can't find any jank/sluggishness. I'm on a pretty meaty Nexus, though, and I'm not sure how to throttle the connection (I guess I could tether to my laptop & find some application that can monkey with connectivity?).

Another concern is that mobile users have metered plans, and might download resources but never open the dialog on a given RP's page. /me shrugs

**Comment by seanmonstar** [comment]
That was my concern as well. They said that a good browser should hopefully
keep that in mind, being able to ask the operating system or something. I'm
skeptical that that's true, but that removed me r- earlier.

**Comment by jaredhirsch** [comment]
@jedp this seems like it's edging into wontfix territory, thoughts? Wanna push harder?

**Comment by shane-tomlinson** [comment]
@fmarier, @jedp, @6a68 - we were hoping to make the dialog load _faster_ on FirefoxOS by pre-fetching the resources. The theory is the browser pulls in the extra resources while the browser/network is idle so that resources are in the HTTP cache when the dialog opens.

**Comment by fmarier** [comment]
@6a68 That MDN page isn't up to date anymore, prefetching now works on Chrome (desktop) too. I found out by looking at the contents of the cache (about:cache) when testing that pull request.

In terms of sluggishness, it's up to the browser to determine whether or not to prefetch anything once the network is **idle**. In my testing, I've found that Firefox has some limit on the number of resources it will prefetch and will also only do so when the connection is fast enough (it didn't prefetch when slowed down to dialup speeds). But basically, it's entirely optional and if the browser has a good reason not to prefetch, then it can decide to delay it or not to do it at all. (If that's not working, then we should think about filing a bug against gecko because we're not the only using that feature.)

Finally, in terms of mobile data plans, it's tough because there are two cases which have opposite requirements:
1. If you have a metered plan where you pay per megabyte, you would prefer not to load the dialog if you don't plan on logging in. (If you're going to login then there's no difference of course.)
2. If you have a large enough plan (e.g. if I have 1 GB of data / month, I'm never going to reach that), then you do want to prefetch as much as possible because the slower your connection is, the more impact prefetching has.

Case 1 should ideally be handled by the mobile browser. Chrome for Android has an option that restricts prefetching to wifi connections and that's great because there's no way for the browser to distinguish between these two cases. However to minimize the impact on case 1, Shane and I decided to wait before merging the prefetching stuff until we had reduced the size of the resources that we pull in (e.g. bidbundle).

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
