### ISSUE TITLE
KPIs data does not contain whether an XHR response was non-200

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3610]
This makes it difficult to tell if there are responses that are regularly failing and to track down why certain error screens may be shown.

Link to #3466

**Comment by seanmonstar** [comment]
These lines will try to collect the response code if an error screen is shown from a failed request: https://github.com/mozilla/browserid/blob/dev/resources/static/common/js/modules/interaction_data.js#L55-L57

**Comment by shane-tomlinson** [comment]
Thanks @seanmonstar - those only collect status > 399, why aren't we collecting the others? The context of that magic number is forgotten.

**Comment by seanmonstar** [comment]
Thinking back, that function is called when an error screen is shown. It would include any network request error data if it was an request error. Less than 400 means the error happened client-side.

Ignore this, we should record include every response code as a separate piece of data, regardless of future error screens.

**Comment by shane-tomlinson** [comment]
As @seanmonstar notes in https://github.com/mozilla/browserid/pull/3620/files#r5071514, we should also record aborted XHR requests to make sure they only happen after window.unload.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
