### ISSUE TITLE
android 2.x with firefox has strange horizontal scroll bar blinking when signing in

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3612]
1. on android 2.x firefox release - goto beta.123done.org
2. attempt to sign in.

actual: horizontal scroll bar keeps blinking like it's trying to scroll, nothing else is scrolling

**Comment by shane-tomlinson** [comment]
@edmoz - is this a problem with 123done or with the dialog?

**Comment by edwindotcom** [comment]
in the dialog

**Comment by edwindotcom** [comment]
No repro on Android 2.x Stock Browser and Android 4.x FF and Stock Browser

**Comment by edwindotcom** [comment]
This is about to go live with the train - I don't want to block it as it's only 1 config, but It would be good to understand the issue?  @jrgm any thoughts on it's severity?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
