### ISSUE TITLE
[ie8][3554] add another email address; #newEmail not focused

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3616]
From #3554

STR
1. Sign in with and existing user.
2. From dev.123done.org, bring up the dialog and then 'add another email address'.
3. On IE8, the input with id #newEmail is not focused

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
