### ISSUE TITLE
[ie8][3554] add another email address to primary-only account; input#password not focused

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3617]
From #3554

STR
1. On IE8, sign in with an existing primary email address that is not in an account that contains any secondary email addresses.
2. From dev.123done.org, bring up the dialog and then 'add another email address'.
3. enter a new secondary email address. Set focus when you need to enter this password (GH-3616).
4. You will be prompted to choose a password for this account with text like 'Your email address is new to us...'. (resources/static/dialog/views/set_password.ejs it seems).
5. The input#password in that screen will not have initial focus set.

**Comment by callahad** [comment]
@6a68 to set up a meta-bug to track the collection of ie8 focus issues.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
