### ISSUE TITLE
fx-primaries.personatest.org is not responding

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3623]
I'd like to test the primaries fix on b2g and was informed to set pref to this:
https://fx-primaries.personatest.org/

but it's down

curl -v http://fx-primaries.personatest.org
- About to connect() to fx-primaries.personatest.org port 80 (#0)
-   Trying 54.243.17.165...

dig fx-primaries.personatest.org

;; ANSWER SECTION:
fx-primaries.personatest.org. 60 IN CNAME   primaries.personatest.org.
primaries.personatest.org. 60   IN  A   54.243.17.165

**Comment by jedp** [comment]
Looks like it got torn down and amazon recycled the static ip.

I'm launching https://train0619.personatest.org/ right now, and pushing ... the 06.19 train to it.

I'll cname `fx-train0619.personatest.org` to it

**Comment by edwindotcom** [comment]
i'm slightly confused, if you're just pushing 06.19 train, why not just cname fx-primaries.personatest.org to login.anosrep.org ?

**Comment by jedp** [comment]
Because the "normal" persona site (in this case, `login.anosrep.org`) needs to know what the firefoxos cname is.  It uses this to rewrite urls when determining the right postmessage origin.

Hence the only way to do it is to launch a new service with its own exclusive cname.

That said, `fx-train0619.personatest.org` is live and working with primaries.

Note that it will not work with bigtent, because there's no corresponding bigtent instance.

(I'm feeling more and more every day that as soon as we have the cname working completely, we should un-pref it from the phone, and let it provide backwards compatibility for the v1.0.1 phones.)

**Comment by shane-tomlinson** [comment]
@jedp - Do you think we should get rid of the CNAME? If so, +1

**Comment by shane-tomlinson** [comment]
@edmoz - you should be able to test using firefoxos.anosrep.org as your Persona source. This was only a test instance for development. Closing.

**Comment by jedp** [comment]
@shane-tomlinson  i do think we should get rid of the cname, yes :)
