### ISSUE TITLE
b2g: account manager doesn't show accounts on b2g browser

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3624]
description: there's no way to manage accounts on b2g, the security model prevents the browser being aware of native UI cookies
1. on b2g sign into 123done.org
2. after signing in goto login.persona.org

result: no accounts are displayed in account manager

expected: you should see accounts

**Comment by jrgm** [comment]
See also https://github.com/mozilla/browserid/issues/2914

**Comment by jedp** [comment]
And see #3558 

I think this is due to the way the account manager works; it reads from localStorage, which is not in the right silo in FirefoxOS.  It will need to use the api to sign people in.

Also, the cname will screw things up.  If you go to firefoxos.persona.org and sign in, it will appear to sign you right back out.  Then go to login.persona.org and you will be signed in.

**Comment by shane-tomlinson** [comment]
Dup of #3300, closing.

**Comment by jedp** [comment]
I've opened  [Bug 892050](https://bugzilla.mozilla.org/show_bug.cgi?id=892050) for an Account Manager on FirefoxOS
