### ISSUE TITLE
/wsapi/cert_key called in communication_iframe for Yahoo! addresses that have expired cert

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3625]
I am signed in to Persona using an account with a Yahoo! address and several other addresses. The Yahoo address was used to sign in to Persona. The Yahoo! address cert has since expired.

navigator.id.watch was called with a signedInUser of "null".

/wsapi/session_context returns:

```
{.....,"authenticated":true,"auth_level":"assertion","has_password":true,....}
```

/wsapi/list_emails returns my list of emails.

then /wsapi/cert_key is called for the Yahoo! address, without calling /wsapi/address_info to find out that a new cert should be fetched from Yahoo! BigTent instead of the fallback IdP.

Basic STRs as far as I can tell:

1) Sign into an RP that uses .watch with a Yahoo! address
2) Wait 10 minutes
3) Open up the network console
4) Refresh the RP - what's up with the call to /wsapi/cert_key?

**Comment by peder541** [comment]
I've encountered this issue with my implementation. The Yahoo address cert expired and navigator.id.watch was called with a loggedInUser of null. Then the sign in failed with a 400 to POST /wsapi/cert_key

I can't seem to replicate on 123done.org though.

In fact, it seems that 123done.org doesn't generate a new cert after a Yahoo cert expires but keeps generating acceptable assertions somehow. I say this because once the Yahoo cert expires, 123done.org logs in successfully on refresh. If I refresh my site after refreshing 123done.org, I still encounter the above error. However, if I sign out of 123done.org and sign in again, it generates a new Yahoo cert and my site signs in properly on refresh.
