### ISSUE TITLE
etherpad.mozilla.org : "Systems error, please insert another quarter."

### ISSUE THREAD

**Issue by gene1wood** [mozilla/persona#3627]
When visiting this page :

https://svcops.etherpad.mozilla.org/53

And clicking "Sign In" I got this error message

http://img713.imageshack.us/img713/874/9dz.png

I clicked sign in a second time and it brought up the persona pop up window just fine.

**Comment by ozten** [comment]
This would be an Etherpad integration bug, not a browserid bug.

That codebase is pretty gnarly and we punt on some corner cases.

I'm going to close this bug and I won't open a new bugzilla bug to track this, because the internal tools team is porting the new etherpad engine to Persona to replace Etherpad.
