### ISSUE TITLE
Cannot use .get and .watch APIs together

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3637]
This would be super useful for situations like mozilla/browserid-roadmap#9.

Context:

In  the wordpress plugin, I want to use .watch for session management.

But, for users who are not signed in, I want to use .get to get a one time assertion for users who wish to leave a comment and should not be signed in.

**Comment by shane-tomlinson** [comment]
link to #2152

**Comment by callahad** [comment]
I wonder if the "right" thing might be somehow unifying the normal and observer APIs, per this dev-identity thread from June: https://groups.google.com/d/msg/mozilla.dev.identity/cTN4ik4vHGQ/mBjVIcG56B4J

One of the proposals was: if you pass a function as the first argument to `.request()`, then it disables session management and uses that function instead of the registered `onlogout` callback.

**Comment by callahad** [comment]
(Which is functionally the same thing as just allowing get and request to coexist, but maaaaybe also gives us a unified way to present the API?)

**Comment by Osmose** [comment]
FWIW I feel like making request not always call the `watch` callbacks makes it unnecessarily complex. IMO it'd be clearer to keep them separate. 

Also from a user's perspective I'd prefer just enabling `get` for now and introducing API changes later. It helps me in the shrot term. :D

**Comment by callahad** [comment]
Closing this down, moving to the roadmap repo.
