### ISSUE TITLE
L10n environment down

### ISSUE THREAD

**Issue by mathjazz** [mozilla/persona#3646]
Both,

http://translate.123done.org/
and
https://translate.personatest.org/

are down and needed for localizers to test their translations.

**Comment by jaredhirsch** [comment]
hey @mathjazz, looking at this now

**Comment by ozten** [comment]
This has been something we've neglected for other high priority issues.

We should really get a solid L10n preview environment nailed down that has Bigtent, Sideshow, and Mozilla IdP support. It should update frequently.

@6a68 thanks for looking at this! I'd love for it to be a fully supported environment (whatever that means, maybe Ops instead of awsbox?)

**Comment by jaredhirsch** [comment]
@mathjazz This should be fixed. The translate environment ran out of disk space, I spun up a new one, and both en and es look correct to me. Reopen if this recurs.

@ozten that's a great idea, I've opened an issue (mozilla/identity-ops#107) to track that ops work.

**Comment by mathjazz** [comment]
@6a68 Thank you very much for taking care of this so quickly! 50+ localizers will really appreciate it.
