### ISSUE TITLE
Add the Persona icon to the Zocial button set

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3648]
Sites like bbs.boingboing.net are not using our Persona icon.

Let's get our icon added to http://zocial.smcllns.com/

**Comment by jedp** [comment]
I realize there are other sites like zocial.  I think the ones we want should all have separate issues to track.

**Comment by callahad** [comment]
This is a symptom of Discourse using the Zocial webfont, and BoingBoing using Discourse.

Here's the upstream bug: https://github.com/samcollins/css-social-buttons/issues/17

**Comment by zimbatm** [comment]
Just submitted a PR to zocial:  samcollins/css-social-buttons#70
I had to convert the AI doc into SVG. Here is the rendering that it gives in the browser: 
![screen shot 2014-02-13 at 12 47 54](https://f.cloud.github.com/assets/3248/2159856/2403e0fc-94ae-11e3-91d7-0d61e308cdb5.png)
If the design is acceptable it could be added to IcoMoon.io or other services to make it more widely available.

**Comment by callahad** [comment]
That's awesome! Thanks, @zimbatm! I'm not familiar with IcoMoon or other services, but you've got my permission to submit that more broadly.

**Comment by zimbatm** [comment]
@callahad are you the designer that did the UX ? Edit: thanks. Not sure if we can submit to IcoMoon but I'll have a look.

**Comment by callahad** [comment]
Nope. Sean Martell, Stephen Horlander, Crystal Beasley, and Ryan Feeley are predominantly responsible for our UX and design. :)

**Comment by zimbatm** [comment]
@callahad i was wondering if the rendering was up to standard. the little person looks a bit squished to me but i'm not good with design.

**Comment by callahad** [comment]
He does look a little squished (at least, his neck does), but an ever-so-slightly squished icon is better than no icon in those sets.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Comment by zimbatm** [comment]
This has finally been merged !
