### ISSUE TITLE
Dialog footer code is illegibly small on a single line.

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3675]
The dialog footer-shrinking hack produces lots of tiny text, which is hardly an improvement over multiple lines of legible text.

Looking at the translate environment today, I saw that the "negative space man" icon depends on the line-height, and so it's partly obscured, which makes the footer look less than beautiful:

![screen shot 2013-07-17 at 1 57 54 pm](https://f.cloud.github.com/assets/96396/815195/c3db710c-ef23-11e2-863a-0de2fb8e5bd3.png)

This is Spanish, btw. So, I'm happy to get rid of this hack, but we'll have to rethink how we solve #3129.

**Comment by shane-tomlinson** [comment]
Yeah, that's not so awesome.

**Comment by callahad** [comment]
Is there any way we can force a line break before the "More Information" bit, if we have to break anywhere? Give the link style `display: inline-block`, maybe?

Two lines of text fit just fine, the only problem is that we're wrapping in awkward places.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
