### ISSUE TITLE
Remove legacy L10n scripts

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#3686]
I need to work with @mathjazz to remove
- scripts/extract_po.sh
- scripts/merge_po.sh
- scripts/compile_mo.sh
- locale/compile-mo.sh
- locale/compile-json.sh
- locale/po2json.js
- locale/po2json.pl

Why remove these? We are using the new i18n-abide scripts for extract, merge and compile.

We don't use .mo files anymore, so anything mentioning those.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
