### ISSUE TITLE
browserid development dashboard

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#370]
we should have a page that gives us, at a glance, a view of current development, open issues, etc.

**Comment by lloyd** [comment]
it's suggested by @benadida that we have some view which lets you understand which devs are drowning in issues.  we need to be creative in a very fast/low cost way to display this.  it could be something like a score which considers closed issues in the last two weeks, new issues in the same period, and total open bugs.

**Comment by ozten** [comment]
via email:

The bug dashboard - We have a fairly lightweight process for tracking issues.  We use github issues almost exclusively for our issue tracking.  We need a quick view of product health, in terms of how many high priority issues are open.  This view into our issues tracking would help instruct the team when we need to buckle down and start focusing on closing open issues, vs implementing new features.

Here's the process: https://github.com/mozilla/browserid/wiki/The-BrowserID-Bug-Process

This task would be about creating a web app that interacts with github via their API and renders a view.  This view should give a viewer an idea of how many issues we have open and our recent trending.  It maybe includes:
- Issues open
- a weighted issue score, rolling up issue and priority into a concrete "risk" number
- a graph of the above two over the last month
- issues by assignee, perhaps by weighted score (the "who's drowning view").

Whatever it is, there should be a small amount of high quality information that gives you an idea of how we're doing in responding to community reported problems with browserid.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
