### ISSUE TITLE
forgot password link is too large on assertion->password upgrade

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3709]
STR (against dev))

1) Create account with one primary, one secondary
2) Sign out of Persona
3) Open Persona dialog
4) Sign in using primary address
5) Re-open Persona dialog
6) Select secondary address and sign in
7) That "Forgot Password" link is pretty big.

![screen shot 2013-07-25 at 12 09 16](https://f.cloud.github.com/assets/848085/855192/b06a06b8-f51a-11e2-9ea2-cb2fa87cf869.png)

**Comment by callahad** [comment]
If you're using a primary address, and then select a fallback address, you have to enter a password.

This is that screen.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
