### ISSUE TITLE
Add jenkins job to run qunit-frontend-tests

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3745]
from @jrgm's comment in #3740:

We should set up a jenkins job that runs:

```
./scripts/run-all.js -e dev --parallel 12 --platform all -i 1 -t frontend-qunit-test
```

Yes, the deployer/jenkins asynchronous issues are a problem, but perhaps a little preflight check and retry script would dampen out false noise; the frontend-qunit-test itself is not noisy to my knowledge (aside from occasional timer-based test failures on the slow IE8 JS engine).

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
