### ISSUE TITLE
differing colours on some screens in dialog

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3757]
Probably missed this screen in recent changes. It's not a big difference in colour but I happened to notice it.

![two](https://f.cloud.github.com/assets/758162/925798/6752d5f8-ff7f-11e2-9eb5-3d5146ef86b0.png)

![one](https://f.cloud.github.com/assets/758162/925799/6d86f88c-ff7f-11e2-830c-e7a18310ef5a.png)

**Comment by jrgm** [comment]
![three](https://f.cloud.github.com/assets/758162/925863/976e4de8-ff80-11e2-9368-4ef431495a67.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
