### ISSUE TITLE
The "Address Verified" screen can take upwards to 10 seconds to go away

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#3763]
It seems that sometimes after logging in with a Gmail or LDAP email address, the "Address Verified" screen sits for a very long time. Not sure if this is general slowness or an actual perf issue, but figured I should file it for the sake of getting it in the system.

Let me know if there's anything I can do to help.

**Comment by mattbasta** [comment]
I should note that this doesn't happen every time. On average it takes 3-4 seconds for me, but that still seems incredibly long. At least once per day it gets up to 10 or more.

**Comment by callahad** [comment]
What browser / platform are you seeing this on?

**Comment by mattbasta** [comment]
I've seen this on Chrome stable and beta on os x and Canary on Windows.
Also on fx nightly, but don't use other release channels enough to know
whether it happens there as well.

**Comment by shane-tomlinson** [comment]
@mattbasta - FWIW, we dropped the ridiculous 3 second delay post-IdP-verification to 500ms. The common case should be much faster. The 10 second occurrences should be ~ 7 seconds, I'd like to see what is going on here. My gut feeling is that it involves XHR chatter on both Persona and the IdP, as well as certificate generation and signing.

**Comment by mattbasta** [comment]
Just tested on our Ashes server and it seems to be taking ~5 seconds or so
on average. That's certainly a bit of an improvement.

**Comment by zaach** [comment]
@shane-tomlinson Is that in production or just stage? beta.123done.org is _much_ faster now, though once the arrow has slid across the dialog, there's a noticeable delay til the window closes. Is that lag or an explicit delay?

**Comment by shane-tomlinson** [comment]
@zaach - We delay the start of the animation by 750ms, the animation takes 1s, and delay 750ms post-animation or else the motion feels very jerky. Let's have another look at this.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
