### ISSUE TITLE
When you get a sign in error on B2G you cannot scroll the error message

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3764]
I was getting the following error when trying to log in to some staged Marketplace instance using a bad value in my B2G prefs:
![2013-08-08-11-21-48](https://f.cloud.github.com/assets/557895/933814/a35d134a-005d-11e3-8470-a4bae89cadf5.png)

If I click the "See more info" button, I get this dialog, but you cannot scroll the error message vertically, it seems to be scrolling the content BEHIND the dialog (my persona ids):
![2013-08-08-11-22-24](https://f.cloud.github.com/assets/557895/933798/34f553c2-005d-11e3-8367-e6e56d18486c.png)

**Comment by pdehaan** [comment]
It doesnt show in the screenshot, but the modal dialog has a semi-transparent background, so you can see the content behind the error message scrolling.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
