### ISSUE TITLE
email address management

### ISSUE THREAD

**Issue by alisonw** [mozilla/persona#3766]
Persona is a great idea _but_ there are a number of issues becoming more problematic as the user base expands.
1. Inability to change email address being used. Published response is "file a bug" but that really doesn't scale, and for non-techie types it is a complete non-starter. "https://login.persona.org/" lets you delete an address, but not add a replacement first, and although there is an "edit" button it doesn't actually permit editing (!). Not a good UX.
2. If you have created multiple accounts - intentionally or unwillingly - you can't amalgamate them. (This is a related facet of #1 in some ways)
3. Something which came up during an IRC discussion was that many people wanted the ability to publish a different address to the stored one, ie one for secure sign-in, one for open publishing. One could also extend this to additional addresses for different personas on Persona.

**Comment by callahad** [comment]
Thank you! Next steps for the team:
- [ ] Get this into user story repo.
- [ ] Link related bugs.
- [ ] Link mailing list discussion about passwords / fallback / etc.
- [ ] Track the need for a SUMO article explaining address management with Persona.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
