### ISSUE TITLE
Fallback IdP cookie should be a session cookie when user clicks "For this session only"

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3769]
The cookie that the fallback IdP sets when it creates a session for a user should be:
1. a regular cookie with a **long expiry** when the user clicks "This is my computer"
2. a session cookie (which expires when the browser is closed) when the user clicks "For this session only"

This is not a security bug per se because the expiry that matters is the one that's inside the client-sessions cookie and that one is set correctly to 1 hour in the second case.

However, a user that closes the browser early would reasonably expect the cookie to be gone given how we advertise that feature.

Also see issue #3770.

**Comment by shane-tomlinson** [comment]
YEEEEEES! I have wanted this for so long! Do the cookie middleware libraries already support session cookies?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
