### ISSUE TITLE
Review third-party libraries and plugins

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3771]
This isn't a bug on our codebase, but it doesn't really fit anywhere else, so I'm tracking it here for now.

Instructions and TODO list here: https://id.etherpad.mozilla.org/3rdparty-lib-reviews

(This will unblock #3233.)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
