### ISSUE TITLE
error message is low contrast red on blue background

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3777]
Minor UX case: On the /reset_password screen on main site, an invalid or mismatched password pair will show an error, but it is red text on a blue background, which is not the most readable.

![red-on-blue-error-password](https://f.cloud.github.com/assets/758162/950479/df902ac0-038f-11e3-822c-fee2ffb1b0b0.png)

**Comment by shane-tomlinson** [comment]
@ryanfeeley - can we get some input here?

**Comment by ryanfeeley** [comment]
@shane-tomlinson  How about match the other parts of the site by using the white background template? Some quick firebugging.
![screen shot 2013-08-13 at 10 27 21 am](https://f.cloud.github.com/assets/68213/955128/cd605952-0424-11e3-8dce-8dbd4c8c8f77.png)

**Comment by callahad** [comment]
+1 to the idea of a white background, but there's not a ton of contrast between what is a label and what is an input there :)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
