### ISSUE TITLE
[train-2013.07.31 and dev] consistent FE test failures with IE8 and IE9

### ISSUE THREAD

**Issue by jrgm** [mozilla/persona#3779]
There was a flaky test in train-2013.07.17, producing the message

```
"common/js/modules/interaction_data: addEvent with eventTime and duration - eventTime used as basis to calculate offset, duration is third item in event (1, 3, 4)"
```

in 2 of 5 runs against an ephemeral instance with IE8.

But in train-2013.07.31 and dev against respective ephemerals, I'm seeing consistent failures, summarized as:

```
{
  "IE9": {
    "6/10": "common/js/network: serverTime (1, 0, 1)",
    "10/10": "common/js/modules/interaction_data: start_time message sets the startTime to calculate event time offset (1, 0, 1)",
  },
  "IE8": {
    "10/10": "common/js/network: serverTime (1, 0, 1)",
    "10/10": "common/js/modules/xhr: xhr_delay not called for completed request (1, 1, 2)",
    "10/10": "common/js/modules/interaction_data: start_time message sets the startTime to calculate event time offset (1, 0, 1)"
  }
}
```

The js/network and js/modules/interaction_data are timing related on slower JS engines. 

But js/modules/xhr looks like a basic 'IE8 JS/DOM is not like the other ones' failure:

```
modules/xhr: xhr_delay not called for completed request (1, 1, 2)
Expected:  "undefined" 
Result:  "object" 
Diff:  "undefined" "object"
```

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
