### ISSUE TITLE
mobile: "Address Verified" screen not centered - looks ugly

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3782]
This shows after the "signing in" screen goes away.

![screen shot 2013-08-13 at 13 19 29](https://f.cloud.github.com/assets/848085/954349/b6b81742-0412-11e3-921e-09b0497d9ab3.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
