### ISSUE TITLE
The repo contains multiple copies of jschannel.js

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3800]
One in include_js, one in common/lib The one in include_js should be the canonical version (if it's not already) and used in include.js

**Comment by shane-tomlinson** [comment]
Link to #3759 which relates to duplicate WinChan's

**Comment by callahad** [comment]
Pretty sure this is a dupe somewhere.

**Comment by callahad** [comment]
(Also, diff the jschannels to make sure they're identical)

**Comment by jaredhirsch** [comment]
note that there's an ie8 bug in upstream jschannel's head. i had to back out some jschannel changes 2 trains ago because of this, but haven't had time to fix the upstream bug and pull the changes downstream to browserid.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
