### ISSUE TITLE
Odd HTML escaping in sign-in window when there is an error.

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3804]
I tried setting an invalid color (salmon; it's a lovely and valid color name), and the error messge reported is:

Action: error in http:&# x2F;&# x2F;blahblahblah.

I would have expected the &# x2F; bits to be properly converted. I'm guessing EJS is escaping them for us, or possibly double escaping them.

![mozilla_persona__a_better_way_to_sign_in](https://f.cloud.github.com/assets/557895/977854/31b9f6ca-06ae-11e3-833e-47170f9e916b.png)

**Comment by shane-tomlinson** [comment]
We discussed this when @warner and @fmarier were doing the internal security review. I forget the exact reasons why we continued with the double escaping of the RP name. Agreed, this is super ugly.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
