### ISSUE TITLE
"Add another email address" button label changes when resizing the browser

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3810]
When you log in to 123done.org, the default popup width (700px-by-425px) displays three buttons:
- Add another email address
- This is not me
- sign in

When you resize the window narrower (640px) the first button's label changes to:
- Add an email address

**Comment by shane-tomlinson** [comment]
@ryanfeeley - Let's get your input here!

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
