### ISSUE TITLE
'cancel' link sometimes does nothing in dialog

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#3812]
Related to #3811--I can't find STR outside of that case. Fixing it may fix this as well.

STR:
- trigger the #3811 bug (the simplest way is, right now, to enter webqa.browserid@aol.com & hit 'next' & wait for nothing to happen)
- edit the email address in any way, causing the password fields to be hidden
- click 'next'
- when the password fields appear, click 'cancel'
- nothing happens

@shane-tomlinson explained that this is because the dialog thinks it's gone forward to the next state already, so that hitting 'cancel' takes you back to the password state. Or something, my brain is melting at this point.

There might be simpler STR, but I haven't found 'em yet.

**Comment by shane-tomlinson** [comment]
Labeling 3\* because this only manifests with the issue with #3811, BUT, there is still an issue where the error handler  to user.stageReverifyEmail is not printing an error screen.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
