### ISSUE TITLE
KPI timing data sometimes contains negative values

### ISSUE THREAD

**Issue by kparlante** [mozilla/persona#3815]
In < 1% of the blobs, the timings up through `user.can_interact` have negative values. The percentage of blobs is small enough that we may not much care, but capturing this while I have the data in front of me.

https://id.etherpad.mozilla.org/kpi-issue-3815-data

**Comment by kparlante** [comment]
And occasionally the blobs have unexpectedly large timing values for a set of events. (This happens very rarely -- I only noticed when looking at the large max times for `user.can_interact`).

https://id.etherpad.mozilla.org/kpi-issue-3815-data-2

**Comment by kparlante** [comment]
And to round out the picture, sometimes the timing information is null for some set of events:

https://id.etherpad.mozilla.org/kpi-issue-3815-data-3

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
