### ISSUE TITLE
Sign in to Persona with assertion failure message is very unhelpful

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3818]
It show more info, it says "Action: Authenticating with Assertion".

If you check out the call to /wsapi/auth_with_assertion, it gives info that is helpful to debug, especially when developing an IdP.

I think it would be handy to show the "reason" field from the call to /wsapi/auth_with_assertion so IdP devs know _why_ the login failed.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
