### ISSUE TITLE
cancel button displayed but does nothing post-password reset if verifying in a different browser.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3822]
STR

Requires 2 browsers

1) Create an account using a secondary address
2) In browser 1, open dialog, if signed in, sign out.
3) Enter address, click "forgot password?"
4) In browser 2, open verification link
5) Enter new password.
6) In browser 1, go back to the dialog to enter the newly updated password
7) Why is that cancel button there? It doesn't do anything.

Link to #3812

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
