### ISSUE TITLE
browserid examples should use jQuery builds from a CDN instead of duplicating jQuery multiple times in the repo

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#3826]
It looks like we have multiple copies of jQuery in our repo: _example/primary/jquery.js_ and _/example/rp/jquery-min.js_ which are both jQuery 1.5.2 (Mar 31, 2011).

We should probably remove both of these from the repo and use the official jQuery CDN: http://code.jquery.com/jquery/ (for example, code.jquery.com/jquery-1.10.2.min.js supports both http:// and https://).

./browserid/example/primary/jquery.js
./browserid/example/rp/jquery-min.js

I think the only reason to keep these files in our repo would be if they are modified/custom versions of jQuery.

-peter

**Comment by ozten** [comment]
I don't think this is a problem.

1) example are static websites/services that are useful for testing and development
2) having jquery means you can hack on the Persona server without an internet connection

Of course we could upgrade jquery and keep a local copy of an upgrade version, but this just seems like busy work.

**Comment by ozten** [comment]
Just in case this conversation bleeds into `/common/js/lib/jquery-1.7.1.min.js` and CDNs... We should not rely on 3rd party hosting of jquery as we lose control of vetting it's contents.

**Comment by shane-tomlinson** [comment]
@pdehaan - @ozten has this right, we can only include content that we control, severely restricting 3rd party inclusions to CDNs that we trust.

To avoid any cross-functionality pollution, the projects under `/example` are treated as distinct repos. Instead of trying to create one jQuery to rule them all, we could try to actually make `/example` into a git submodule. Is it worth the effort?
