### ISSUE TITLE
Add a label to the email input field on mobile devices

### ISSUE THREAD

**Issue by chemistrydioxide** [mozilla/persona#3828]
I just tried to use Persona from my smart phone and I noticed that there is a huge UX issue.

On the first screen, you are shown an input box. NOTHING, absolutely NOTHING indicates what I am supposed to enter into that box. I am taking care of a site that has recently moved from username/password authentication to Persona, so most of my users will expect that they have to enter their user name. So please add a label to that field.

**Comment by pdehaan** [comment]
Mobile experience:
![mozilla_persona__a_better_way_to_sign_in](https://f.cloud.github.com/assets/557895/1013196/7ce3640c-0b80-11e3-96ee-d884eb411a05.png)

Desktop experience:
![mozilla_persona__a_better_way_to_sign_in](https://f.cloud.github.com/assets/557895/1013201/9fb00c74-0b80-11e3-9f93-c997b393a7c6.png)

**Comment by shane-tomlinson** [comment]
@chemistrydioxide - Thanks for the issue report. We actually do have labels, they are 0px tall and read out to screen reader users.

@mhanratty, @ryanfeeley - Your input here would be appreciated. What do you guys say to unifying the labels at a minimum (to make the L10N community's life simpler), and an indication of an email address on mobile? Could we use the placeholder text like we do on desktop?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Comment by callahad** [comment]
This is still an issue, and it's still really crappy, but I'm going to leave this closed until we re-review the cleanup-2014 tag. This comment will help it bubble to the top (we'll sort by last-updated) during the review.
