### ISSUE TITLE
desktop dialog text is quite compressed, especially the site name and "sign in to..." text.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3838]
The text in the RP name around "Relying" is especially difficult to read.

![screen shot 2013-08-28 at 15 27 36](https://f.cloud.github.com/assets/848085/1042164/c85b9bd4-0fe5-11e3-86f1-4d690da27786.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
