### ISSUE TITLE
Marketplace on Android unable to use unverified emails

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#3841]
Krupa reports that Marketplace is unable to sign in using unverified emails on Android.

**Comment by jaredhirsch** [comment]
@jedp @krupa can we get some more context here?

**Comment by jaredhirsch** [comment]
four stars to investigate

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
