### ISSUE TITLE
Error creating unverified user if email used before with primary

### ISSUE THREAD

**Issue by kumar303** [mozilla/persona#3842]
To reproduce:
- Log into https://marketplace.firefox.com/ using desktop Firefox with a Gmail account
- Walk through the oauth verification
- On the Firefox OS Marketplace app, attempt to log in with the same Gmail account
- It asks you to create a password, enter the new password

This results in the following error:

![2013-08-28-17-31-19](https://f.cloud.github.com/assets/55398/1046104/4abade54-1032-11e3-860d-ad978842bf7e.png)

It happens every time but other emails work ok so I think the error message is wrong.

Under the hood, the Firefox OS Marketplace does `forceIssuer=firefoxos.persona.org` and `allowUnverified=true` but desktop Marketplace _does not_.

I'm not sure what the right thing to do here is but we definitely don't want someone to be able to hijack a verified account by typing in that person's email for the first time on Firefox OS.

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=805608

**Comment by kumar303** [comment]
I didn't see anything useful in the logcat, let me know if you need it. Hmm, github doesn't let you attach text files.

**Comment by jedp** [comment]
Interesting.  This hit me today as well when using FirefoxOS on Unagi to sign in with a mozilla.com address, so we have identity bridging in common.  (Though it worked when I tried a second time.)  Yeah, logcat will have nothing to report in this case.  There's no error on the client.

**Comment by jrgm** [comment]
This error message is shown on a 503 response from POST /wsapi/stage_user. I think possibly when it calls db.createUnverifiedUser.

**Comment by seanmonstar** [comment]
An error from `db.createUnverifiedUser` will log to CEF with a `DB_FAILURE`.

If it was before that, we should be able to see the error message in the logs.

**Comment by jaredhirsch** [comment]
five stars to investigate immediately, @gene1wood will pull the logs

**Comment by gene1wood** [comment]
I've 13 instances of this failure over 24 hours yesterday. I'll try to correlate the nginx 503's with an underlying app log entry

**Comment by gene1wood** [comment]
Here's what's happening on the dbwriter : `{"level":"warn","message":"unexpected database failure: Error: Duplicate entry 'foo@gmail.com' for key 'address' -- at exports.createUnverifiedUser (/opt/browserid/lib/db/mysql.js:733:13)","timestamp":"2013-08-21T20:47:05.800Z"}`

@jrgm will be here shortly to explain what's causing this

**Comment by jrgm** [comment]
Yeah, so it's pretty clear what this issue is from the log line above (which I'll repeat with a line break for easy reading).

{"level":"warn","message":"unexpected database failure: 
Error: Duplicate entry 'foo@gmail.com' for key 'address' -- at exports.createUnverifiedUser 
(/opt/browserid/lib/db/mysql.js:733:13)","timestamp":"2013-08-21T20:47:05.800Z"}

The row for that key already exists (created initially on the desktop for the STR steps 1 and 2).

(By the way, a useful tip for debugging is to enable NSPR logging (https://gist.github.com/jrgm/4490638) and run this script to extract only the HTTP request/response -- https://gist.github.com/jrgm/4490664).

**Comment by kumar303** [comment]
I think we have a workaround in Marketplace which will deploy on Tues 9/3: https://bugzilla.mozilla.org/show_bug.cgi?id=910938 The workaround (which is a bug fix) is to always do `forceIssuer` -- i.e. on desktop and Firefox OS. In our testing, this lets Gmail users log in on Firefox OS, however they may have to create a new password on desktop first.

**Comment by kumar303** [comment]
For anyone reading this who is stuck trying to log in to Marketplace on Firefox OS, here's how the fix will work. On Sep 3rd around 12pm PST we'll release the aforementioned fix. After it has been deployed, you'll need to clear your cookies (persona.org and marketplace.firefox.com). Using a desktop browser you can then log in to Marketplace with your Gmail (or other bridged account). It will prompt you to create a new password. Your account will now work in Firefox OS with the new password you created.

**Comment by seanmonstar** [comment]
@kumar303 sounds reasonable, it's a bug on our side, and you're trying to fix your users faster. don't mind me ranting on the next lines, it's not you at all :)

@lloyd WUH! SEE? `forceIssuer` is the devil. and it's growing.

must. kill. H̸̡̪̯ͨ͊̽̅̾̎Ȩ̬̩̾͛ͪ̈́̀́͘ ̶̧̨̱̹̭̯ͧ̾ͬC̷̙̲̝͖ͭ̏ͥͮ͟Oͮ͏̮̪̝͍M̲̖͊̒ͪͩͬ̚̚͜Ȇ̴̟̟͙̞ͩ͌͝S̨̥̫͎̭ͯ̿̔̀ͅ

**Comment by shane-tomlinson** [comment]
Kill forceIssuer. Kill with a spoon so it's more painful.

**Comment by seanmonstar** [comment]
updated title to reflect underlying error

**Comment by seanmonstar** [comment]
deep dived into this just now. Since forceIssuer is being used, and the email is typically a primary, it comes back from address_info as `transition_no_password`. However, in state.js, we say that if there's on password and forceIssuer, then it's a newFxAccount, which sends us off to stage_user. stage_user tries to create a new user with the email address, and errors because email already exists.

I think the proper answer is to not treat it as a newFxAccount, but I think that means we need to shove more `allowUnverified` nonsense in more places.

The other way would be to just allow stage_user to be called, and we check if the user exists already, and if so, then don't create it, but set verified to false.

Except now the user is `unverified`, when on all other sites when forceIssuer isn't used, the user totally IS verified. :facepunch:

**Comment by shane-tomlinson** [comment]
@seanmonstar - I have been looking at this too: whenever I use the local dev IdP, I see "invalid email" in the console, state.js:line 404 after setting the password. If I add `|| self.allowUnverified` to the check, I am allowed to pass, I set the email address, and call /wsapi/stage_user (which returns 200), but end up in an infinite loop to set the email address, because address_info keeps returning as the state `transition_no_password`.

Is there a discrepancy between the production db and the json db, why would /wsapi/stage_user return 200 locally, but error against prod?

**Comment by seanmonstar** [comment]
Because the JSON db has no concern with duplicate entries, but our mysql db has a unique constraint on `email`.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
