### ISSUE TITLE
Using a dark background color in request() makes the text white, and then the light grey arrow animation practically hides the text

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#3853]

**Comment by shane-tomlinson** [comment]
@seanmonstar - if we remove the animation, this won't be a problem. ;)

**Comment by ryanseys** [comment]
This issue could benefit from a screenshotty. :camera:

**Comment by seanmonstar** [comment]
It's no fun trying to screen cap an animation :)

Easily seen by going to 123done.org, opening console, and typing `navigator.id.request({ backgroundColor: '#000' });`, then log in.

**Comment by ryanseys** [comment]
![test](https://f.cloud.github.com/assets/163873/1090277/d28a1404-1653-11e3-92b8-93fa83c65caa.gif)

**Comment by ryanseys** [comment]
:wink:

**Comment by ryanfeeley** [comment]
Thanks @ryanseys! @seanmonstar @shane-tomlinson I'm not okay with removing the animation, because it really makes sense in this content. It's a "waving bye bye" that is part of the experience. Isn't this just a z-index issue? Also could the shape not be made in HTML without an image? An inner DIV rotated 45°, possibly with a drop shadow?

**Comment by shane-tomlinson** [comment]
@ryanfeeley : w.r.t a div rotated 45 degrees - we would lose IE < 10 support. When you say z-index issue, do you mean that the arrow should be in front of the siteName and siteLogo?

**Comment by ryanfeeley** [comment]
@shane-tomlinson Oh yeah, OPB (other people's browsers :)

I was thinking that the arrow should go in front. So great that @ryanseys did that animation because it givess one pause to reflect on it.

I do like the rightward motion because it's dramatic, and appropriate in context. I'm not a very experienced motion graphic designer, but know a few. I'm going to ask.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
