### ISSUE TITLE
internal.setPersistent sets `remember` field instead of `logged_in` field to indicate user wants a silent assertion.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3856]

**Comment by shane-tomlinson** [comment]
This means users who sign in using the internal API are not getting the full goodness of silent assertions.

**Comment by shane-tomlinson** [comment]
Is internal.setPersistent actually used anywhere?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
