### ISSUE TITLE
Improve RP branded mobile view

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/persona#3868]
As promised @shane-tomlinson 

![mobile 001](https://f.cloud.github.com/assets/68213/1099864/b1660c7a-1742-11e3-83af-32288b62834c.png)

Questions: I still think we need to show Persona in here. Ideas? Also, where is the RP/Persona ToS?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - Like desktop, the TOS/PP agreements are only displayed to users who have not visited the RP before. Here's what they look like:

![screen shot 2013-09-10 at 10 18 21](https://f.cloud.github.com/assets/848085/1113341/27c37ab0-19fa-11e3-8193-93610924ab29.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
