### ISSUE TITLE
new users must sometimes re-enter password in dialog post-email verification

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3873]
This is intermittent, but sometimes users must re-enter their password in the dialog post-email verification.

STR (again, intermittent)

1) open dialog
2) stage user
3) in same browser, open a new tab and verify the user

I'm trying to get a network trace of this happening.

**Comment by shane-tomlinson** [comment]
`/wsapi/user_creation_status` returns `mustAuth`.
![screen shot 2013-09-10 at 13 40 54](https://f.cloud.github.com/assets/848085/1114286/46677842-1a16-11e3-922d-a2481a84e4d0.png)

Since the user typed their u/p in the dialog before staging the address, we attempt to authenticate them:

![screen shot 2013-09-10 at 13 39 48](https://f.cloud.github.com/assets/848085/1114293/65a91b5c-1a16-11e3-95ed-d06dd7e591f3.png)

Backend returns `no such user`

I unfortunately do not have a trace of the verification window to see the exact time that `/wsapi/complete_user_creation` was called.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
