### ISSUE TITLE
Four round trips to check login - ouch

### ISSUE THREAD

**Issue by richardcrichardc** [mozilla/persona#3879]
I'm in New Zealand 200-250ms from login.persona.org - responses come back in about 300ms. Round trip time is a big deal for us.

I'm looking at the load time of a website using persona to login. To avoid flickering from logged in to not logged in, the page is not displayed until the persona onready callback fires.

Page loads are taking about 3 seconds. The site is quite ajaxy, so there is scope for me to optimise out several round trips.

However almost 1.5 of these seconds can be attributed to Persona - there are 4 round trips to login.person.org and that is after include.js has been loaded.

Is there any scope for optimising this 'verify login' path from four round trips down to one?

Below is a screen shot showing the measurements - these are pretty typical.

![persona-round-trips](https://f.cloud.github.com/assets/885016/1126855/4259fcaa-1b2b-11e3-9591-024f9379b574.png)

Here is a more pathological case I came across, 7 round trips including the initial load of the communications iframe which is not in the screen shot. After logging out I could not reproduce this case.

![persona-round-trips2](https://f.cloud.github.com/assets/885016/1126905/bd7daf0c-1b2c-11e3-9b64-c070004fc3e1.png)

**Comment by jaredhirsch** [comment]
:-\

We've discussed implementing a CDN, seems like that would mitigate a lot of this latency

**Comment by seanmonstar** [comment]
Would it? 3 of the calls are wsapi requests.

**Comment by richardcrichardc** [comment]
I've spent 10 minutes looking at the spec and source code making me an instant expert - so I don't actually know what I am talking about ;-)

There appears to be a cookie browserid_state which presumably is the key to whether the user is logged in or not.

How about as soon as include.js is loaded a call is made to a new wsapi endpoint https://login.persona.org/wsapi/whos_logged_in which simply returns the email address of the logged in user. Then when navigator.id.watch is called it can trivially call onLogout or onReady depending on whether loggedInUser matches the response from the api call - all within one round trip to the server (after the load of include.js). 

This sort of approach should work if login.persona.org was the only identifying party, but it's not. I'm struggling to match what I am seeing happening on the network with the documentation of how browserid is supposed to work. I did see something about 'requesting a single cacheable document', which suggest checking whether the logged in user matches could be done with 0 round trips to the server - that would be pretty amazing!

**Comment by shane-tomlinson** [comment]
@richardcrichardc, @seanmonstar - We talked about combining several of the `wsapi` calls into one so that when `/wsapi/session_context` is called, the user's list of emails is also returned. Combining `/wsapi/address_info` into this single call will be a bit more work, but should be possible as well. 

We have given this a lot of thought, but are holding off until we see what boosts a CDN give us with the static resources. If we are "good enough" when the CDN is introduced, going deep and spending time combining `/wsapi` calls can be deferred until we need to pull an ace out of our sleeves.

**Comment by richardcrichardc** [comment]
@shane-tomlinson. Thanks for the update.  

What sort of time frame do you imagine the CDN going live? I take it that include.js and communication_iframe would go on the CDN. You might be able to get the same benefit simply by tweaking the caching policy for static resources.

So of the four round trips (excluding include.js) that is going to shave off about 1/5 of a second (communications_iframe down to say 50ms from 250ms).

I'm trying to get my head around how what I am seeing corresponds to the specs. Specifically I am looking at the section "How browsers interact with IdPs" on [this page](https://developer.mozilla.org/en-US/docs/Mozilla/Persona/Identity_Provider_Overview?redirectlocale=en-US&redirectslug=Persona%2FIdentity_Provider_Overview). If you have a moment, it would be great to know if the communications_iframe corresponds to the provisioning page. This kind of makes sense, but when inspecting the code I thought I saw the communications iframe being loaded before `watch` had been called, which doesn't make sense as the provisioning page depends on the domain name of the email address being verified. Or are these specs out of date because of identity bridging?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
