### ISSUE TITLE
"Your browser is not supported" message should warn about dom.storage.enabled on Firefox

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3886]
Some users of the most recent Firefox version are being told by Persona that their browser is not supported. See https://bugzilla.mozilla.org/show_bug.cgi?id=916460 for an example. I've seen another case of that too.

Ideally, we should expose the actual reason for Persona not working (postMessage not working, localStorage not working, etc.) in the error message.

However, at the very least, we should have a warning for Firefox users when we detect that their `dom.storage.enabled` is set to `false` because it's an easy thing to fix.

**Comment by shane-tomlinson** [comment]
@fmarier - I think we could show a message for postMessage, localStorage, etc, but I am unaware of a mechanism to query `dom.storage.enabled`

**Comment by fmarier** [comment]
@shane-tomlinson Yes, I was a little sloppy there. I think we can only indirectly check for `dom.storage` by checking both localStorage and sessionStorage. That's what I do on https://people.mozilla.org/~fmarier/troubleshoot.html

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
