### ISSUE TITLE
Verifier accepts paths in the audience

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#3888]
Currently, the verifier that we run accepts audiences that include a path and discards the path. For example, these three audiences are equivalent:
- `http://example.com`
- `http://example.com/moodle/`
- `http://example.com/mahara/`

This could lead people to think that (as in the above example) web applications running on the same domain but separated by paths are separate in the browserid world, like they are with cookies.

Fixing this would of course break backwards compatibility so we would have to first of all check how widespread that practice is and then reach out to any RPs that are passing in the full URL.

**Comment by fmarier** [comment]
Also, this has implications for the libraries that @chilts is writing. In that case though, since nobody is using them at the moment, we can just have them enforce the stricter right from the start.

**Comment by warner** [comment]
Yeah, I think that's worth fixing. More certainty is better. APIs should encourage correct thinking instead of being misleading.

It'd be nice if we had some sort of messaging pathway, like if the verifier could return "ok, but something is a bit weird: XYZ" which would go into the RPs logs for them to look at occasionally.

**Comment by fmarier** [comment]
I love @warner's idea of a "warning" field in the JSON output. Like the "reason" field when validation fails, but for valid assertions.

**Comment by chilts** [comment]
Yep, we'll just throw/die/quit if they pass an audience which has a path. In general most libraries obtain the audience outside of the request and prior to doing the verify so this should work well.

**Comment by jrgm** [comment]
Should this be discussed on the list for what impacts it could have on existing RP (suggestion from triage).

**Comment by callahad** [comment]
This seems like a good idea. Let's go ahead and give persona-notices a heads up, and kill this in 6 months. Monitoring usage between now and then, obviously.

I'll draft that email. Assigning to me until that gets done.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
