### ISSUE TITLE
'Registration Failed' message displayed when registering email@yahoo.co.uk

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#3891]
Env:
Ubuntu 12.04 & Firefox 24 release
Win 7 & Firefox 25 beta1
beta.123done.org - stage
123done.org - prod

Steps:
1. Sign in with email@yahoo.co.uk
2. Open the email client and click on the confirmation link

Expected: The email is successfully signed in without any error message  

Actual: The email is logged in on login.anosrep.org but the sign in dialog displays this error message:  "Error. Please close the window and try again. Action: Registration failed"

This is not reproducible - on Win 7 & IE 10
                                   - when using email@yahoo.com

**Comment by jrgm** [comment]
Is this consistently reproducible?

**Comment by csuciu** [comment]
Yes, I can reproduce this issue consistently.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
