### ISSUE TITLE
Garbage collect IdP info in bulk

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#3897]
Currently the `address_info` wsapi [triggers a per domain cleanup](https://github.com/mozilla/browserid/blob/f05f038b3aca5f8171b62e6790d41130cb3a8b52/lib/wsapi/address_info.js#L72) of IdP information.

This is inefficient. We should have a cronjob or other mechanism which ensures we delete all stale data in bulk, periodically.

`DELETE FROM idp_cache WHERE created > NOW() + 50000` or whatever (psuedo code, not real table/column names).

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
