### ISSUE TITLE
Test fails on post-limiting-test.js (on some combinations of distro/kernel/nodejs version)

### ISSUE THREAD

**Issue by mohit-agarwal** [mozilla/persona#3911]
![screenshot from 2013-09-24 04 14 19](https://f.cloud.github.com/assets/2356369/1195993/e430dbdc-24a1-11e3-9111-4e908d875e2d.png)

node version v0.10.18
npm version 1.3.8

Linux mohit-Inspiron-5420 3.2.0-51-generic #77-Ubuntu SMP Wed Jul 24 20:18:19 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.2 LTS"

**Comment by jrgm** [comment]
Yeah, I install 12.04.3 to get a newer 3.x kernel than what travis is installing (2.x) (don't ask me why that version on travis), and I can see that sometimes (but not always) ECONNRESET is returned instead of 'socket hang up' . For purposes of the test, I think just changing the test to accept either failure message is fine. So, if you want create a pull request, that would be good; if not, we'll get this fixed. Thanks!

e.g., `assert.ok(/Error: (socket hang up|read ECONNRESET)/.test(err.toString()));`

Try just running `WHAT_TESTS=back npm test`; you'll need phantomjs installed and mysqld installed and configured to run the `front` and `back_mysql` targets.
