### ISSUE TITLE
login.persona.org/sign_in on samsung browser just spins with loading dialog

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3926]
I'm on galaxy s4, Android 4.2.2
1. with internet browser - goto 123done.org or beta.123done.org
2. click sign in with email

actual: dialog pops, and you see a spinning wheel "connecting to persona"
I've waited at least 2 mins and that's all you see.

expected: you should get form fields

**Comment by jaredhirsch** [comment]
:-( attack of the stock browsers, part 2? son of safari?

**Comment by edwindotcom** [comment]
on galaxy s4 - no repro FF, Chrome

**Comment by jaredhirsch** [comment]
edmoz: what's the version of the OS and browser?

**Comment by jaredhirsch** [comment]
whoops, @edmoz. i've got a galaxy nexus, i can try to repro

**Comment by edwindotcom** [comment]
this might be a Samsung browser - it says: Internet Browser 1.0 - the user agent is Mozilla/5.0(Linux;Android 4.2.2;samsung sch-I545 build/jdq39)AppleWebKit/1.0Chrome/MobileSafari/  - might be able to call this unsupported.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
