### ISSUE TITLE
login.persona.org looks terrible and is missing login button on Private mode Safari iOS7

### ISSUE THREAD

**Issue by ryanseys** [mozilla/persona#3929]
Note: only appears when in a Private tab. A non-private tab looks fine.

![img_9101](https://f.cloud.github.com/assets/163873/1232062/4ae56afa-2885-11e3-8509-74bef1c42c80.png)
![img_2658](https://f.cloud.github.com/assets/163873/1232063/4e57ba80-2885-11e3-960c-701158a77280.png)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
