### ISSUE TITLE
Going directly to login.persona.org/sign_in in iOS7 Safari private tab spins indefinitely. 

### ISSUE THREAD

**Issue by ryanseys** [mozilla/persona#3930]
STR:
Open Safari in iOS 7.
Turn private browsing on.
Direct a new tab at https://login.persona.org/sign_in

Actual result:
You will see a spinning icon and "Connecting to Persona" indefinitely. (see below for screenshot)

Expected result:
You should see an error related to establishing a relay, and it should allow you to close.

This was reproducible on:
- iOS7 Safari on iPhone 5s
- iOS7 Safari in XCode Simulator

![img_5369](https://f.cloud.github.com/assets/163873/1232065/8826bb30-2885-11e3-95cb-4d843fe096ce.png)

**Comment by ryanseys** [comment]
Sounds related to #3926

**Comment by mattbasta** [comment]
Safari private browsing bans localStorage usage (both Desktop and iOS). Accessing localStorage at all throws an error. :(

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
