### ISSUE TITLE
Going directly to login.persona.org/sign_in in iOS7 Safari tab does not allow you to close by pressing OK.

### ISSUE THREAD

**Issue by ryanseys** [mozilla/persona#3931]
STR:
Open Safari in iOS 7.
Turn private browsing OFF.
Direct a new tab at https://login.persona.org/sign_in

Actual result:
You should see an error related to establishing a relay, with an OK button. Pressing OK to attempt to close the window does nothing. (See screenshot)

Expected result:
You should see an error related to establishing a relay, with an OK button. Pressing OK to attempt to close the window should close the window.

This was reproducible on:
- iOS7 Safari on iPhone 5s
- iOS7 Safari in XCode Simulator

![img_3094](https://f.cloud.github.com/assets/163873/1232081/083c5ec8-2887-11e3-9787-2e4daad77a94.png)

**Comment by shane-tomlinson** [comment]
@ryanseys - if you manually open a tab and direct it to the /sign_in page, I do not believe there is any way we _can_ close that tab.

**Comment by ryanseys** [comment]
So should we be showing an 'OK' button then?

**Comment by ryanseys** [comment]
And why doesn't `window.close()` work?

EDIT: nevermind :dancer:

**Comment by seanmonstar** [comment]
Many browsers only allow closing a window with JavaScript if it was created
with Javascript.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
