### ISSUE TITLE
'We're sorry ......' dialog is displayed for a very short time when loading login.persona.org or login.anosrep.org

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#3932]
Please see the video: http://www.flickr.com/photos/99294146@N02/10018540186/

I was able to reproduce this issue only on:
- Samsung Galaxy SII (GT-I9100) running Android 4.0.3 
- Firefox 24 (release)
  when loading:
- login.anosrep.org
- login .persona.org  

'We're sorry, this is taking longer than it should' message is displayed for a very short time even if the server site is loaded without noticeable delays

I tried on other devices with android 4.0.x and I couldn't reproduce .

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
