### ISSUE TITLE
Cannot specify PUBLIC_URL

### ISSUE THREAD

**Issue by shuhaowu** [mozilla/persona#3943]
I would like to run a local instance of persona on something other than http://127.0.0.1:10002 (with a custom hostname). 

However, https://github.com/mozilla/browserid/blob/dev/scripts/run_locally.js#L81 seems to be thwarting the effort. Putting a "public_url" entry in config/local.json also does not help.

Any ideas?

**Comment by shuhaowu** [comment]
Furthermore, if we edit the run_locally script to allow passing of a router_url, the url will still be overwritten in common/js/user.js, which will give out the wrong assertion.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
