### ISSUE TITLE
Selecting an email from the form autocomplete popup does not enable the 'Continue' button

### ISSUE THREAD

**Issue by csuciu** [mozilla/persona#3944]
Env:
Samsung Galaxy SII (Android 4.0.3)
LG Optimus 4x (Android 4.1.2)
Firefox 24 (release)
beta.123done.org
123done.org

Steps:
1. open www.123done.org
2. press on sign in
3. make sure you have at least one form autocomplete popup entry available
4. tap on the email field
5. select an email from the form autocomplete popup

Expected: 'Continue' button should change his state to enabled

Actual: 'Continue' button remains disabled and will change his state only after entering a character

**Comment by callahad** [comment]
Note to self: is there an event we're not listening to that fires upon autocomplete, or is this an upstream Fennec issue?

**Comment by seanmonstar** [comment]
We listen for both `keyup` and `change`. I would expect `change` to have triggered in this case.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
