### ISSUE TITLE
changing to prefs after logged in results in inability to logout

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3947]
I'm on safari 6.0.5. This could be an issue while people try to troubleshoot an issue and change settings, they could get into this state -- which exacerbates the investigation.
1. in Safari > preferences menu dialog - set privacy > block cookies : 3rd party advertisers
2. goto 123done.org and sign in with a mozilla.com acct (not sure if that type of acct is important)
3. go to prefs, and change block cookies to 'always' and poke 'remove all website data'
4. go back to browser, click logout
5. refresh browser

actual: 123done.org says you're logged in

expected: you should be logged out and see sign in button.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
