### ISSUE TITLE
reset-password-test Selenium test fails frequently (> 50% of time)

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3956]
Always with the same failure

```
reset-password-test - win7_firefox_22 (1 failure(s), 0 warnings):
  5: add addressVerifiedAtSignIn, errors:
    * "timeout hit" undefined "undefined" // vows_harness.js:47
  >> https://saucelabs.com/tests/87c30567f1c64734967065081d3c6a8c
  >> https://saucelabs.com/tests/79610f49eaf946c9a08a647826770f1f
  >> https://saucelabs.com/tests/16461d3b2ca7496aa8cc5b4144e9326a
  >> https://saucelabs.com/tests/0f72c1c12ce240e8978a9923649df9e8
```

Link to #3873 - may be same root cause, I have not done a deep dive yet.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
