### ISSUE TITLE
Implement Golidlocks API

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/persona#3958]
Names for methods can change, but my understanding is this:

``` js
navigator.id.watch({
  onlogin: function(assertion() {}
  // woah, no onlogout? no problem.
});

navigator.id.request(options);
```

This will send an assertion over winchan if it can, but if it can't (redirect flow, user closed popup during email verification), it will keep around a `one_time` flag that the communication iframe should trigger `onlogin` once, and then wipe the bit.

The `one_time` bit still requires 3rd party cookies, but we can't live without them for the closing-the-loop feature. In cases where the user doesn't allow 3rd party cookies, the assertion should hopefully still be passed back by the dialog via WinChan.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
