### ISSUE TITLE
iOS 7 Homescreen web app failure

### ISSUE THREAD

**Issue by bryandonnovan** [mozilla/persona#3965]
Open safari and visit a site with:
<meta name="apple-mobile-web-app-capable" content="yes">

Save a shortcut to the home screen

launch from home screen shortcut

attempt persona sign in with observer api

empty persona window appears.  window is frozen and nothing else happens.

**Comment by bryandonnovan** [comment]
Sorry, markup was filtered.  Open safari and visit a site with:
&lt;meta name="apple-mobile-web-app-capable" content="yes"&gt;

**Comment by shane-tomlinson** [comment]
This is partially a dup of #2034

**Comment by davidguttman** [comment]
Just bitten by this issue. Just read up on #2034 -- would be great to specify redirection instead of popup.

**Comment by abritez** [comment]
Same problem, and a huge deal breaker for my app since it needs to work as both mobile web app and PhoneGap hybrid. Both done work for me.  Any word on this?

**Comment by seanmonstar** [comment]
I post about a discussion in #2034 regarding adjusting the api, here's the discussion link: https://groups.google.com/d/topic/mozilla.dev.identity/12PW2Z-YPps/discussion

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
