### ISSUE TITLE
b2g: launching persona from whereismyfox.com has uneditable username

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#3975]
1. on b2g 1.3 goto: whereismyfox.com
2. click the sign in button
3. tap in the username text field

actual: keyboard launches, then gets dismissed, then you're unable to enter text, eventually get a 'bad login' error

expected: you should be able to sign in

**Comment by edwindotcom** [comment]
I'm unable to repro on 123done

**Comment by pdehaan** [comment]
I can repro on whereismyfox on B2G 1.2 prerelease

**Comment by edwindotcom** [comment]
here's the JS

```
$("#persona-login").on("click", function(e) {
    e.preventDefault();
    navigator.id.get(mailVerified, {siteName:"where is my fox"});
});

$("#persona-logout").on("click", function(e) {
    e.preventDefault();
    $.get('/auth/logout', loggedOut);
});

function mailVerified(assertion){
    $.ajax({
        type: 'POST',
        url: '/auth/login',
        data: {assertion: assertion},
        success: function(res, status, xhr) {
            loggedIn(JSON.parse(res).email);
        },
        error: function(xhr, status, err) {
            alert("Login failure: " + err);
        }
    });
}
```

**Comment by callahad** [comment]
Ahhh! They're using .get! Not the Observer API!

**Comment by edwindotcom** [comment]
@jedp @callahad :  get() api shouldn't cause the keyboard to dismiss should it?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
