### ISSUE TITLE
RP name inconsistency in email picker

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#3978]
desktop shows the RP name, mobile does not.

![screen shot 2013-10-15 at 15 22 07](https://f.cloud.github.com/assets/848085/1334231/4eed5de2-35a5-11e3-9d28-fed5a06febdc.png)

![screen shot 2013-10-15 at 15 22 13](https://f.cloud.github.com/assets/848085/1334232/50b8cf08-35a5-11e3-8bfc-a83ed26d5c29.png)

What do you think @ryanfeeley, should we make these consistent? If not, close at will.

**Comment by ryanfeeley** [comment]
Please do! I thought I had fixed this already. In fact, didn't I see this fix on oauth version you pushed?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
