### ISSUE TITLE
Addon bar is visible in the Persona login dialog

### ISSUE THREAD

**Issue by fmarier** [mozilla/persona#4002]
![french_is-that-your-computer](https://f.cloud.github.com/assets/167821/1434885/2ff0ab82-412c-11e3-97cf-a51c0958105f.jpg)

Initially reported on https://bugzilla.mozilla.org/show_bug.cgi?id=742904

**Comment by callahad** [comment]
Aesthetic only. Tagging as 2-star + good first bug. Relevant docs from MDN: https://developer.mozilla.org/en-US/docs/Web/API/window.open#Note_on_status_bar

**Comment by dporru** [comment]
I'm new here, so if please tell me if I'm doing something wrong. I've been trying to fix this bug, but no luck.

In the window.open call, there is already a status=0, which seems to have no effect. The addon bar does disappear when the location=0 option is set. This will, however, also remove the location bar, which would be a security risk and this option is disabled in the about:config by default, so it wouldn't work anyway.

It also seems the addon bar will be removed in the near future anyway: https://developer.mozilla.org/en-US/Firefox/Australis_add-on_compat

So, unless I'm missing something, this bug should be closed.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
