### ISSUE TITLE
Verification link in email does not work on Firefox OS

### ISSUE THREAD

**Issue by atopal** [mozilla/persona#4003]
I don't know if there is already an issue filed for this, please dupe in case there is already one.

When we worked on Persona integration on support.mozilla.org we ran into a number of issues that blocked us from rolling Persona out on production:

When you get a verification email on Firefox OS, clicking the link will bring you back to the browser where the pop-up is still open. So you have to know that you have to close the browser. Then you are not sent to the actual page you wanted to log-in to, but persona.org. And on persona.org you are not automatically logged in, but have to type in your credentials.

The whole workflow can be seen here: http://www.youtube.com/watch?v=oDVHzmSqhpI

**Comment by edwindotcom** [comment]
This is definitely a broke workflow with persona on b2g.  bump to @jedp

**Comment by callahad** [comment]
Tagging as 4-stars; looks like an upstream bug related to BrowserID sandboxing on FxOS...

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
