### ISSUE TITLE
Email address picker display switches back to default address for an instant before verification 

### ISSUE THREAD

**Issue by gene1wood** [mozilla/persona#4004]
On what appears to be the first use of Persona in a given day, when I go to authenticate to a site, and I select a different email address than the one that the email picker defaults to, when I click submit, the radio box changes back to the default just before the page goes away.

This doesn't present a functional problem, it's just a UX bug.

![email-picker-bug](https://f.cloud.github.com/assets/1134034/1439554/f5d2e2ce-418c-11e3-8b87-600f19136f16.gif)

**Comment by callahad** [comment]
2-Stars (cosmetic + you'd have to be paying really close attention...)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
