### ISSUE TITLE
Unable to log into Persona on firefoxos marketplace

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#4006]
@krupa reports in [Bug 933394](https://bugzilla.mozilla.org/show_bug.cgi?id=933394):

firefoxos 1.1

steps to reproduce:
1. Launch marketplace on your firefoxos phone
2. Try to sign in using persona

observed behavior:
Sign in hangs with 'Connection to Persona'

```
10-31 11:50:03.967 E/GeckoConsole( 2474): [JavaScript Error: "Error: unknown email address" {file: "https://static.login.persona.org/v/3afab0b595/production/en/dialog.js" line: 5}]
```

Note that sign in is failing from webpay and fireplace. Reproducible on both stage and prod

**Comment by krupa** [comment]
I reflashed my phone which seems to have fixed this issue. Note that another person also hit the same issue on their 1.1 firefoxos phone.

**Comment by jedp** [comment]
Hm - reflashing is not going to be a solution for customers.  Perhaps some kind of localstorage issue here?

**Comment by edwindotcom** [comment]
something to check is if it's hitting firefoxos.persona.org vs the old native.persona.org

**Comment by jedp** [comment]
If there were a mismatch like that, I think you'd be getting CSP errors

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
