### ISSUE TITLE
Firefox Password Manager does not pre-fill username/password.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#4009]
A dup of the closed #314 - opening a new issue so that it is not forgotten about.

More context: 
- https://github.com/mozilla/browserid/issues/314#issuecomment-27631082
- https://bugzilla.mozilla.org/show_bug.cgi?id=906300

**Comment by shane-tomlinson** [comment]
Link to #1540

**Comment by callahad** [comment]
Tagging as 4-star; this is annoying.

**Comment by kornelski** [comment]
There's also https://bugzilla.mozilla.org/show_bug.cgi?id=759452

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Comment by flying-sheep** [comment]
please reopen, still a usability issue.

and since this project is all about usability, that’s important.
