### ISSUE TITLE
Recognize "google apps for domain"

### ISSUE THREAD

**Issue by k-bx** [mozilla/persona#4010]
Hi! I've heard that mozilla persona knows how to handle gmail accounts, but I wonder, is it possible to handle "google apps for business" accounts also?

**Comment by callahad** [comment]
Hi @k-bx,

Thanks for asking. Currently, it's not possible because some of the constraints we rely on in the Gmail bridge don't apply to Google Apps. For instance, it's possible to set up email aliases that are fully-functioning email address, but which aren't provable over OpenID, which the bridge relies on. :(

However, it _is_ possible for domains to independently and separately support Persona, even if their email is currently handled by Google Apps. This would require custom development, but the "Becoming and Identity Provider" documents on MDN should help.

**Comment by eduvik** [comment]
I think this is a major hurdle for uptake of openbadges (which relies on persona) in schools which use Google Apps for Education. Can there not be a 'login with google' button in the persona login page which then grabs the currently logged in google account?
