### ISSUE TITLE
box-shadow between left and right sides of dialog looks bad with certain RP background colors

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#4011]
In IE10 on Windows 8, this looks pretty bad:

![screen shot 2013-11-04 at 16 51 59](https://f.cloud.github.com/assets/848085/1466482/ea4be674-4571-11e3-81f5-1c5193ccba28.png)

**Comment by callahad** [comment]
Ugly -- Tagging 3 stars, good first bug.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
