### ISSUE TITLE
Goldilocks API breaks Desktop APIs

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#4019]
We are assigning variables to `navigator.id`, even if there is that object was provided natively and we skipped most of the shim code.

I think we either need to integrate the Goldilocks code deeper or add the same check as the overall shim uses, to the Goldilocks portion of the code.

Steps to Reproduce:
0) Optional - get the latest patches and build Firefox
1) In about:config set `dom.identity.enabled` to `true`
2) Use the default Test page in development (http://127.0.0.1:10001/) or any page which uses the new API

Actual:
In web dev console, note "uncaught exception: Error" or in Firefox debug `JavaScript error: , line 0: uncaught exception: Error`.

Expected:
Native code shows door hanger, as it still does on (http://127.0.0.1:10001/watch)

For background info, this is basically the same issue we ran into with B2G's navigator.mozId object a few months back.

**Comment by callahad** [comment]
@ozten Care to suggest a priority? Tagging as 3-stars for now, as Desktop isn't publicly available and will likely need some tweaks regardless of what happens with Goldilocks...

**Comment by ozten** [comment]
Perfect.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
