### ISSUE TITLE
Rename the private browserid repos

### ISSUE THREAD

**Issue by pdehaan** [mozilla/persona#4025]
https://mana.mozilla.org/wiki/display/Identity/Security_Bug_Fixing_Process

We should continue repo rename-o-rama by making sure we update all the _private repos to be consistent with their freshly renamed public counterparts.
- https://github.com/mozilla/browserid-exploits_private -> /mozilla/persona-exploits_private/
- https://github.com/mozilla/browserid-bigtent_private -> /mozilla/persona-yahoo-bridge_private
- ...

Finally, update the security wiki page above with the new, final repo names.

:shipit:

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
