### ISSUE TITLE
TOS/PP not available in German

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#4026]
When setting language to `de`, TOS/PP are in English.
- https://login.persona.org/de/embedded_tos
- https://login.persona.org/de/embedded_privacy

Initially reported by Vikas Nanda in [bug 938777](https://bugzilla.mozilla.org/show_bug.cgi?id=938777) as a b2g bug, but it needs fixing on desktop as well.

**Comment by fmarier** [comment]
This is not specific to:
- _the embedded versions of the pages_: https://login.persona.org/de/tos and https://login.persona.org/de/privacy are also in English
- _the German locale_: setting your browser to French also returns the English TOS/PP

While the page is in English, the `<title>` of the page is in German. Do we even have translations of the legal texts or do we just have translations of the titles?

**Comment by ozten** [comment]
TOS and PP are localized differently than our software. Instead of Gettext, legal documents are localized as an HTML document.

Very few of our locales are available for the TOS/PP. They are being localized one off in legal bugs as we target different launch locales for FxOS. We should give legal/L10n as much heads up as possible for a new launch market as possible. I don't think we're localizing all locales' legal documents.

**Comment by fmarier** [comment]
Austn is right, we only have `en`, `es` and `pl` at the moment: https://github.com/mozilla/persona/tree/dev/resources/views

**Comment by callahad** [comment]
Closing -- As I understand it, the es and pl localizations are there as a result of FxOS business requirements, and MoCo legal is uncomfortable with community-driven localization of legal documents.

**Comment by jedp** [comment]
I've opened [bug 947995](https://bugzilla.mozilla.org/show_bug.cgi?id=947995) to request a translation from Legal.  FirefoxOS is going to market in German-speaking countries, so we will need this soon.
