### ISSUE TITLE
processes no longer shut down cleanly

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#4031]
We updated to node-statsd `0.0.7` in sha 092eb6c.  This update causes our processes to no longer shut down cleanly.

STR:
1. ENABLE_STATSD=1 npm start
2. (in a separate console) ab -n 600 -c 300 http://127.0.0.1:10002/wsapi/session_context
3. `^C in npm start console

NOTE: this problem does not reproduce if you try only a single session_context call - thus the expectation is leaked references to open resources (or some such) is only triggered with concurrency.

**Comment by seanmonstar** [comment]
following your steps, when I hit ^C, it see all the processes shutdown and then a message "graceful shutdown complete..."

**Comment by callahad** [comment]
@lloyd What are you seeing when you say the processes no longer shut down cleanly?

Things _look_ clean to me, but maybe I'm crazy:

```
SIGINT recieved! trying to shut down gracefully...
proxy exited(1)
example exited(1)
example_delegated_primary exited(1)
example_primary exited(1)
browserid (31737): warn: SIGINT received.  closing 0 connections and shutting down.
browserid (31737): info: graceful shutdown complete...
router (31745): warn: SIGINT received.  closing 0 connections and shutting down.
keysigner (31731): warn: SIGINT received.  closing 0 connections and shutting down.
keysigner exited(0)
verifier (31730): warn: SIGINT received.  closing 0 connections and shutting down.
verifier exited(0)
dbwriter (31732): warn: SIGINT received.  closing 0 connections and shutting down.
static (31738): warn: SIGINT received.  closing 0 connections and shutting down.
dbwriter (31732): info: graceful shutdown complete...
static exited(0)
dbwriter exited(0)
```

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
