### ISSUE TITLE
Intermittent "server is too busy" response for include.js

### ISSUE THREAD

**Issue by mattbasta** [mozilla/persona#4039]
When requesting include.js, sometimes the server responds with the text "server is too busy":

https://login.persona.org/include.js

Ideally, a file as popular as include.js would never be served by a dynamic source and should always be (mostly?) cached at the outermost layer of the stack.

**Comment by shane-tomlinson** [comment]
See #2549, #3035, #3119 and mozilla/browserid-roadmap#47 and the conversation at https://groups.google.com/forum/#!topic/mozilla.dev.identity/jXhDsQsO-fQ/discussion

**Comment by callahad** [comment]
We suspect this is seasonal degradation in AWS's QoS. There's some ongoing discussion of that in #4027. Our current plan is to mitigate by temporarily disabling toobusy in production.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
