### ISSUE TITLE
Continue button enabled too soon in password screen

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#4040]
Vikas Nanda reports in [bug 944734](https://bugzilla.mozilla.org/show_bug.cgi?id=944734) that the _continue_ button is enabled when nothing is entered in the text box

steps to reproduce:
1. Start MP/Inapp Stage
2. Search and select to purchase any pricetier. 
3. Select reset pin. 
4. Enter login information

expected behavior:
The user is taken to the password screen, the continue button is disabled. 

observed behavior:
The user is taken to the password screen, the continue button is enabled even though text has not been entered.

@shane-tomlinson is this something you could take a look at?

**Comment by shane-tomlinson** [comment]
@jedp - I'm passing this off to @seanmonstar, @callahad and @fmarier

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
