### ISSUE TITLE
"Signing in" text appears in English, not local language

### ISSUE THREAD

**Issue by jedp** [mozilla/persona#4041]
Vikas Nanda reports in [bug 946290](https://bugzilla.mozilla.org/show_bug.cgi?id=946290):

If the user creates a new account they will notice the words "signing in" for a split second even though the device language is set to German

steps to reproduce:
1. Start MP in German language
2. Go to settings or attempt to purchase an app. 
3. Create a new account. 
4. Enter and confirm password

expected behavior:
All pop up messages 

observed behavior:
The user receives the pop up message "signing in" in English

**Comment by callahad** [comment]
As far as I can tell, it looks like we're calling gettext properly: https://github.com/mozilla/persona/blob/c8bbf013de28bd46536e908d7981ba8c0d23e095/resources/static/dialog/js/modules/complete_sign_in.js#L49

**Comment by jaredhirsch** [comment]
@mathjazz any thoughts on this one?

**Comment by mathjazz** [comment]
Looks like one of the merges removed the string from our l10n files:
http://svn.mozilla.org/projects/l10n-misc/trunk/browserid/locale/de/LC_MESSAGES/client.po

It is marked as obsolete:
#~ msgid "signing in"

I guess something must be wrong with extract/merge scripts.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
