### ISSUE TITLE
Email adress verification: foo+bar@example.com won't work for account foo@example.com

### ISSUE THREAD

**Issue by mweibel** [mozilla/persona#4046]
- I tried to signup with my gmail address on MDN with persona like this: `username+persona@example.com`. 
- I was being redirected to the gmail select account page (as I'm loggedin with 2 accounts).
- Returning back to Persona it stated that it couldn't verify me

After I signed up using `username@example.com` and set my username etc. I tried, for the matter of this issue, to sign out and login again with `username+persona@example.com`. It worked then and assigned the same account to it.

So it seems that the initial account creation doesn't work if the email address doesn't exactly match the account's email adress even if it's the same account but logging in after works with the other email adress too.

**Comment by callahad** [comment]
This _should_ work with the GMail bridge: If you type `foo+bar@gmail.com` into Persona, but select `foo@gmail.com` in the Google account picker, it should Just Work.

Is that not working for you?

**Comment by mweibel** [comment]
At least it didn't work back then. I'll try again in order to eliminate temporary problems :)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
