### ISSUE TITLE
automated tests failing locally with environment you requested was unavailable

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#4047]
1. name sure you npm install everywhere then run this:

```
    $:~/github/mozilla/persona/automation-tests$ PERSONA_ENV=prod scripts/run-all.js --local --platform=firefox -e prod --tests sign-in-test
    ignoring frontend-qunit-test.js
    ignoring public-terminals.js
    adding sign-in-test.js
    Running 1 suite(s) on 1 platform(s), 1 at a time against https://login.persona.org
    >.!.<
    3/4 tests passed, here are your failures:
    sign-in-test - firefox (1 failure(s), 0 warnings):
    2: create a new selenium session, errors:
    * {"message":"The environment you requested was unavailable."} undefined "undefined" // vows_harness.js:48
```

actual: @pdehaan and I are seeing this locally only.  Be careful to use Fx25 as Selenium doesn't fully support Fx26 (go live today)  Test passes on saucelabs.

**Comment by jrgm** [comment]
See  https://github.com/admc/wd/issues/167#issuecomment-22370195. Things work with selenium < 2.34.0, but we'll need to update wd to use versions above (which, last time I looked at upgrading, tests ran _way_ slower :--( ).

**Comment by edwindotcom** [comment]
jrgm nice find! - I'll downgrade for now till we can fix it.

**Comment by edwindotcom** [comment]
another work around is to us the current wd version fo 0.2.6 rather than lloyd's fork

**Comment by callahad** [comment]
Once #4042 is resolved, we can fix this by bumping the wd version, so long as the new version isn't prohibitively slow.

**Comment by jaredhirsch** [comment]
:warning:

we switched to a fork originally because wd's `browser.chain` behavior used caolan/async under the hood, which does not properly handle errors thrown within the sequence of calls, so tests were failing in unclean ways.

since that time, wd has added a promises-based API, and also added its own version of error handling for chained calls IIRC, though the syntax differs from ours.

moving away from our fork would require updating a bit of boilerplate across all the tests. see wd-extensions.js & the HEAD commits in lloyd's fork for a starting point. would be nice to take care of this, but could turn into a bit of a rabbit hole.

**Comment by jrgm** [comment]
@6a68 Yeah, thanks. That was on my mind, but hadn't stated it (had just mentioned the sluggishness).

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
