### ISSUE TITLE
Support GMail's 'Actions in the Inbox' for 1-click email validation

### ISSUE THREAD

**Issue by ryanseys** [mozilla/persona#4052]
It would be great to see Persona support GMail's 'Actions in the Inbox' which will provide GMail users (or I suppose only Google Apps users now considering the GMail bridge) with the option of verifying their email address with one click (you don't have to open the email).

See here for more details: https://developers.google.com/gmail/actions/

**Comment by callahad** [comment]
+1, this sounds neat. Would merge a pull request doing this.

**Comment by ryanseys** [comment]
Glad to hear about interest for this. For best results, a [Go-to Action](https://developers.google.com/gmail/actions/actions/actions-overview#go-to_actions) would likely be best. Simply use the same URL for verification that is used now in the body of the email.

**Comment by ryanseys** [comment]
I will happily take this one on. Doesn't seem too hard. Any pointers to docs for testing mail delivery?

**Comment by ryanseys** [comment]
After much fiddling and reading docs, I got something working! 

![screenshot 2013-12-21 00 07 47](https://f.cloud.github.com/assets/163873/1795293/2bed9ec8-69fe-11e3-9556-8a6b5f2735f0.png)

However, the button, when clicked, is then blocked by Firefox popup blocker (D'oh!)

Things learned so far: 
- only registered companies and products can use this feature right now. We can fill out [this Google form](https://docs.google.com/a/google.com/forms/d/1PA-vjjk3yJF7MLPOVKbIz3MBfhyma2obS8NIZ0JYx8I/viewform?pli=1) to request access.
- It will also work if you email yourself (at your @gmail.com) address with the schema-sauce, which is how I hacked my instance to work.
- popup blockers...

Next steps:
- Get a PR up here for new user's complete sign-in email + schema-sauce to start.
- Request access from Google?

**Comment by ryanseys** [comment]
MVP 1 in PR #4057

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
