### ISSUE TITLE
Login form implementation makes most password managers useless

### ISSUE THREAD

**Issue by kornelski** [mozilla/persona#4065]
#314 and #4009 seem to be focused on Firefox. However, Firefox-only hacks for Firefox's password manager are not satisfactory. Persona password saving is broken in Chrome, Safari and Opera as well.

I have configured my browsers to delete all cookies every time I quit them, which isn't problematic on normal websites where thanks to auto-saved passwords I can literally login with 1 or 2 clicks. 

However, Persona _always_ requires me to type my full e-mail address and password. To me this is a _dealbreaker_.

I admire your principles and fully support goal you want to achieve, but the fact is that every time I stumble upon the current stop-gap Persona implementation I'm annoyed. I can't recommend it to anybody in the current state and I dislike using websites that require it.

Please make this issue a priority. I see there are 2-year-old bugs filed for it, and it's still broken. That's quite disappointing.

**Comment by callahad** [comment]
Sorry about the delay -- we've been stretched pretty thin, but we are working. Any of these things would help speed this up:
1. Links to good documentation on how major browsers and password managers behave. What is Chrome expecting to see? LastPass?
2. Human-language explanation of what a patch would need to do.
3. A patch itself.

**Comment by callahad** [comment]
Triaging as 3-stars; most users authenticate via a bridge, avoiding the Persona password form altogether.

**Comment by fmarier** [comment]
Passwords managers should work better once sites start using the `email` option to `navigator.id.request` (which isn't implemented yet).

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
