### ISSUE TITLE
Popup does not show login form in Firefox if Selenium IDE is running

### ISSUE THREAD

**Issue by mattrco** [mozilla/persona#4072]
System is Ubuntu 12.04 with Unity. Firefox 26.0 with Ubuntu addon applied. Selenium IDE 2.5.0.

As you can see from the screenshot, the popup has launched but the login form is not visible. It works fine without Selenium IDE running.

![persona_popup](https://f.cloud.github.com/assets/207735/1942248/4a1d9ad0-7f96-11e3-8c86-6f5a8294a692.png)

(This was reported in IRC earlier).

Any input on why this might be happening would be appreciated, it could just be my error!

**Comment by mattrco** [comment]
Has anyone been able to reproduce this? No problem if not, happy to take a closer look myself.

**Comment by callahad** [comment]
I can reproduce this. It seems like Selenium IDE's click event is not a "real" click, as Firefox's popup blocker tried to stop the Persona popup on my end. We currently don't recover well if the popup is blocked (#4055). :(

Would the Selenium WebDriver work for you, instead?

**Comment by callahad** [comment]
(Initially triaging as 2-Star)

**Comment by mattrco** [comment]
We use WebDriver already in some areas, so this is more for making things easier for our QA.

No big deal, but it would be great to have this fixed at some point :)

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
