### ISSUE TITLE
Ability to have persona work in dev / offline mode

### ISSUE THREAD

**Issue by daleharvey** [mozilla/persona#4074]
Switching to a persona based login has given me a problem, its now a huge hassle to develop my application offline

I have some conditional code that works around the problem, but its rather unweildy, I can write a more elegant shim, but this seems like a problem for every person who will use persona and should have an easy path to degrading.

Not talking about a way to make browserid itself work offline, just a path to offline development where we pretend a user has logged in

**Comment by jaredhirsch** [comment]
doh! sorry @daleharvey, accidental click

**Comment by callahad** [comment]
(Triaging as 2-star)

@daleharvey Some sort of offline / dummy shim would be really useful, but it seems like it would be best served by a separate project.

Right now, our best suggestion is to build a dev-mode back door into your own app which sets your own session cookie appropriately.

**Comment by daleharvey** [comment]
maintaining a client side mock as well as the server side back door is fairly confusing, having the client lib just send a known fake assertion and letting the server pretend everything is ok is working, will try and get something working and see if it would be mergable

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
