### ISSUE TITLE
sign into marketplace results in 504 error

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/persona#4078]
1. with browserid 10.23 running on persona
2. goto marketplace.firefox.com
3. click sign in

result: pop up pops, then you see this:

![nsnuvbs](https://f.cloud.github.com/assets/3698618/1980795/01a7d69e-83c9-11e3-94e7-e9481a20cad0.png)

I also saw a timeout using user@hotmail.com

we've rolled back 10.23 till this is resolved.

**Comment by callahad** [comment]
(Triaging as 5-star, to ensure it does not recur before we roll 10.23 again.)

Likely related to this hotfix: mozilla/browserid_private@11e48d48b7eb75b674408a71159c696fe711368d

For testing, Marketplace has an environment that points to our staging and [updates nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=884606#c14). It's located at https://identity-stage-marketplace.allizom.org/

Unfortunately, it sends a CSP header that does not allow `https://login.anosrep.org` as a `script-src`, so we'll need to either flip `security.csp.enable` in `about:config`, or use something like [mitmproxy](http://mitmproxy.org/) to change the CSP before it hits Firefox.

**Comment by edwindotcom** [comment]
can someone cherry pick out that commit, then branch, then give us the SHA to get this on stage.

**Comment by callahad** [comment]
@edmoz In a meeting for the next half hour, will do that as soon as I'm out.

**Comment by callahad** [comment]
Why is @fmarier so fast?

**Comment by fmarier** [comment]
BTW, nobody has confirmed that removing this commit fixes the problem.

**Comment by callahad** [comment]
I am able to repro, this was introduced by mozilla/browserid_private@11e48d48b7eb75b674408a71159c696fe711368d

**Comment by callahad** [comment]
Steps to Reproduce:
1. Create a new Firefox profile and give it a [bright red theme](https://addons.mozilla.org/en-US/firefox/addon/adobe-flash/) so you know it's insecure
2. In `about:config`, set `network.stricttransportsecurity.preloadlist` to `false`
3. Spin up an awsbox
4. As the `app` user on the awsbox, set `~/config.json` to:
   
   ```
   {
       "public_url": "https://login.persona.org",
       "forcible_issuers": [
           "login.persona.org",
           "firefoxos.persona.org"
       ]
   }
   ```
5. Edit /etc/hosts to point static.login.persona.org and login.persona.org to your awsbox
6. Visit https://login.persona.org/ver.txt to ensure you're hitting your awsbox and accept the self-signed SSL cert.
7. Visit https://login.persona.org/ to make sure everything loads correctly.
8. Visit https://marketplace.firefox.com and attempt to log in (remember, you can check MockMyID inboxes at mailinator)

**Comment by callahad** [comment]
Furthermore, I can confirm that @fmarier's `train-2013.10.23-release` branch (currently mozilla/browserid_private@b710281) works properly.

**Comment by callahad** [comment]
Other notes:
- My awsbox was behaving oddly. While bisecting, I had to run `forever stopall && rm -rf code tmp/deploy* tmp/npm*` before each push to the awsbox. Otherwise, npm would fail and the service would be left in a weird state.
- Don't forget to visit https://login.persona.org and sign out before testing a new SHA.
- In the broken state, I don't see anything in the keysigner's log. It seems like the `cert_key` request is never forwarded to it. In the top-level browserid log. I see `"message":"wsapi.cert_key"`, but it is not followed by the expected `"message":"forwarding request: /cert_key -> http://127.0.0.1:62600/wsapi/cert_key"`
- Even in the broken state, Persona continues to work fine without `forceIssuer`

**Comment by callahad** [comment]
So, in summary, mozilla/browserid_private@11e48d48b7eb75b674408a71159c696fe711368d introduces a change that breaks `experimental_forceIssuer` on the web. Marketplace breaks because it's using forceIssuer. Normal Persona works as expected.

This can be verified by allowing popups on Marketplace and manually invoking `navigator.id.request()` from the browser console. Amusingly enough, Marketplace accepts federated Persona assertions, despite normally wanting to force the issuer.

**Comment by callahad** [comment]
I've [bumped the version in the RPM spec file](https://github.com/mozilla/browserid_private/commit/2be2d217c93e6a12e74bd59eb48edaa64601d797) and [re-opened the deployment ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=960284)

I left an awsbox up at 54.204.78.24 with the bad SHA, mozilla/browserid_private@11e48d4, if you'd like to take a shortcut toward re-verifying.

**Comment by callahad** [comment]
FWIW, I seem to be able to repro locally by simply trying to use the `forceIssuer` checkbox on the local testing pages, http://127.0.0.1:10001/watch.html

**Comment by seanmonstar** [comment]
Thanks for all the debugging @callahad, I can dig in after lunch

**Comment by callahad** [comment]
**EDIT**: I think this particular comment is a red herring.

Further investigation: Locally things seem to work fine with fallbacks; the problem may be limited to primaries + forceIssuer. Put another way, `foo@mockmyid.com` will fail, but `foo@mailinator.com` will work.

**Comment by callahad** [comment]
Also, for some reason the awsbox's verification emails aren't always making it to Mailinator. You can grab them from mysql directly with `mysql -e 'SELECT secret, email FROM staged;' -u browserid browserid` as the `app` user on the awsbox, then visit `https://login.persona.org/verify_email_address?token=<secret_goes_here>`

**Comment by callahad** [comment]
@jrgm suggests that this may be because the keysigner is attempting to do a well-known lookup, but isn't allowed to actually do that. I'm a little dubious because the diff for `/bin/keysigner` doesn't actually change anything: https://github.com/mozilla/browserid_private/commit/11e48d4#diff-0, but I may be dumb.

**Comment by callahad** [comment]
The awsbox at 54.204.78.24 is now running @seanmonstar's patch, https://github.com/mozilla/browserid_private/commit/e96317f22b6e0d6d992c6494a9b64f578b3985ff

Manual testing of Marketplace and 123done shows correct behavior with both primary and fallback addresses.

**Comment by fmarier** [comment]
We have reverted the offending commit.

**Comment by callahad** [comment]
For future reference, here's a simplified way to test Persona staging against production Marketplace.
1. Create a new Firefox profile.
   - Set `network.stricttransportsecurity.preloadlist` to `false` in about:config
   - Disable popup blocking
2. Edit `/etc/hosts` to point `static.login.persona.org` and `login.persona.org` to a Staging IP address
3. Visit https://login.persona.org/ver.txt to ensure you're hitting Staging, and accept the self-signed SSL cert
4. Visit https://login.persona.org/ to make sure everything loads correctly
5. Visit https://marketplace.firefox.com, open the JavaScript Console, and execute: `navigator.id.request({experimental_forceIssuer: 'login.anosrep.org'})`
6. Attempt to log in with `<something>@mockmyid.com` and `<something>@mailinator.com`. Both inboxes can be checked at `https://<something>.mailinator.com`

**Expected Results:**
- You should be prompted to create a password.
- You should be required to check a confirmation link sent via email for _both_ the Mailinator _and_ the MockMyId accounts.
- The Persona window should successfully close itself, but you should _not_ get logged into Marketplace.

**Expected Issues:**
1. Clicking the "Sign in / Sign up" button on the Marketplace homepage will not work.
   
   The Persona popup will show an error right before sending a backed identity assertion. This is because Marketplace sets the issuer to 'login.persona.org', which Stage does not recognize as itself. As a result, /wsapi/cert_key will fail and the popup will display an error.
2. Using `navigator.id.request` will not actually result in a successful login, though it will successfully _attempt_ to log in.
   
   This is because Marketplace's backend doesn't have your same `/etc/host` hacks, and it will try to verify your identity certificate with production Persona.
