### ISSUE TITLE
Persona broken with Seamonkey

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#4085]
Transferred from [https://bugzilla.mozilla.org/show_bug.cgi?id=967597](https://bugzilla.mozilla.org/show_bug.cgi?id=967597) on behalf of Tim Terriberry:

> When I try to login to http://benjamin.smedbergs.us/weekly-updates.fcgi/ to post my status, it redirects me to https://login.persona.org/unsupported_dialog.
> 
> User Agent; Mozilla/5.0 (X11; Linux x86_64; rv:25.0) Gecko/20100101 SeaMonkey/2.22.1
> 
> This worked as recently as two weeks ago.

**Comment by seanmonstar** [comment]
Is `localStorage` and `JSON` available? Or might they have been disabled?

**Comment by tterribe** [comment]
dom.storage.enabled is true, but http://dev-test.nemikor.com/web-storage/support-test/ reports "localStorage: not supported". Not sure why.

**Comment by seanmonstar** [comment]
Could cookies / website data be disabled?

**Comment by tterribe** [comment]
about:data says login.persona.org has permission "Set Cookies" set to "Allow for Session".

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
