### ISSUE TITLE
[B2G][Marketplace][Catalan]Marketplace persona sign in password screen buttons are not properly aligned

### ISSUE THREAD

**Issue by jds2501** [mozilla/persona#4089]
Users can sign into a persona profile on the marketplace. After entering an email address, the user is prompted to enter a password. At the bottom of this screen are 'Sign In' and 'Cancel' buttons. These buttons are not properly aligned/placed when the device language is set to Catalan.

Repro Steps:
1) Updated Buri to BuildID: 20140130004001
2) Set device language to Catalan(Català).
3) Launch Marketplace app.
4) Tap on 'Settings' gear icon.
5) Tap on 'Sign In / Sign Up'(Inici de sessió / Registre).
6) Type in a valid email address that is registered with persona.
7) Observe 'Enter Password' screen.

Actual:
The 'Sign In' and 'Cancel' buttons are both on the right side of the screen and aligned vertically on top of each other

Expected:
Both buttons are aligned to the bottom of the screen. The 'Cancel' button is on the left edge of the screen, the 'Sign In' button is on the right edge of the screen.

Environmental Variables:
Device: Buri v1.3 Moz RIL
BuildID: 20140130004001
Gaia: 8defa5bf0cbce290c649e564b7f3ebe708e19b23
Gecko: 6b12800e0e46
Version: 28.0a2
Firmware Version: v1.2-device.cfg

Notes:

Repro frequency: 100%
See attached: screenshot

**Comment by jds2501** [comment]
Cross post of https://bugzilla.mozilla.org/show_bug.cgi?id=968574

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
