### ISSUE TITLE
Fails to start a channel in IE10/Win7

### ISSUE THREAD

**Issue by gwalzer** [mozilla/persona#4097]
IE10 version:10.0.9200.16798
on Win7 professional 64bit

when making a call to navigator.id.request(), dialog.js' startChannel() fails and prints the relaySetup error: "Relay frame could not be found"

**Comment by callahad** [comment]
Hm. I can't reproduce that issue on Win 7 Enterprise (32-bit), IE version 10.0.9200.16721, which is the version that comes with the https://modern.ie/ VMs.

I was able to patch up to version 10.0.9200.798, which also worked as expected.

I suspect this may be an issue with your browser settings or a group policy.

On my local install's Internet Options, the Internet zone is set to "Medium-high" security, Protected Mode is enabled, and Privacy is set to "Medium."

**Comment by gwalzer** [comment]
I had the same security settings on my IE as well, with the exception I'm running on a 64-bit machine.

**Comment by jaredhirsch** [comment]
@gwalzer from your comment, it sounds like the bug is unresolved for you, is that right? I'm reopening just in case. If it's actually fixed, please do actually close it. Otherwise, we're happy to continue to diagnose.

You can let us know what you see when you load this page, for instance: https://people.mozilla.org/~fmarier/troubleshoot.html

**Comment by gwalzer** [comment]
Hi Jared - thanks for looking into this again.
At this point the issues has been resolved for me.
I'm going to close the ticket.
Gil.

**Comment by gabegorelick** [comment]
@gwalzer How did you resolve this issue? I think I'm running into a similar problem.
