### ISSUE TITLE
Send ETag response header for gzip'd responses

### ISSUE THREAD

**Issue by cvan** [mozilla/persona#4105]
Notice `ETag: "17318-1391802200000"` appears only when I omit the request header `Accept-Encoding: gzip`:

``` bash
%% curl 'https://login.persona.org/include.js' -H 'Accept-Encoding: gzip' -I 
HTTP/1.1 200 OK
Access-Control-Allow-Origin: https://login.persona.org
Cache-Control: public, max-age=0
Content-Encoding: gzip
Content-Type: application/javascript
Date: Thu, 13 Mar 2014 18:44:12 GMT
Server: nginx/1.4.4
Strict-Transport-Security: max-age=10886400; includeSubdomains
Vary: Accept-Encoding,Accept-Language
X-Frame-Options: DENY
X-Powered-By: Express
Connection: keep-alive
```

``` bash
%% curl 'https://login.persona.org/include.js' -I
HTTP/1.1 200 OK
Access-Control-Allow-Origin: https://login.persona.org
Cache-Control: public, max-age=0
Content-length: 17318
Content-Type: application/javascript
Date: Thu, 13 Mar 2014 18:44:19 GMT
ETag: "17318-1391802200000"
Server: nginx/1.4.4
Strict-Transport-Security: max-age=10886400; includeSubdomains
Vary: Accept-Encoding,Accept-Language
X-Frame-Options: DENY
X-Powered-By: Express
Connection: keep-alive
```

Regardless of whether I'm getting a gzip'd or non-gzip'd response, I should get an `ETag` response header. The value of the `ETag` should be different of course, but I should still get one if I'm getting a gzip'd response.

Also, if we're using `ETag`s, then we could remove the `Cache-Control: max-age=0` and just rely on the browser's `If-None-Match` request headers to make sure that we're doing the right thing.

/cc @clouserw @diox

**Comment by jrgm** [comment]
@cvan Sorry for a late reply. Hey, does marketplace run a fork of nginx, or use particular plugins?

**Comment by clouserw** [comment]
@oremj or @jasonthomas would know best

**Comment by oremj** [comment]
We're just using vanilla nginx 1,4

**Comment by jaredhirsch** [comment]
@cvan Just to be clear here, Marketplace is moving away from Persona, right? So, this is going to have limited impact for you guys?

**Comment by diox** [comment]
On the long run, it is, but right now we are still using Persona (we haven't started implementing Firefox Accounts yet) and we still need this for performance in the meantime.

**Comment by jaredhirsch** [comment]
@diox cool, good to know. we still haven't gotten a single release out post-drama, so I really can't tell you if/when this will be resolved. But I'll mark four stars, since it's likely a simple fix, and seems to impact you guys. (Do you have any stats around the performance impact? No biggie if not.)

**Comment by diox** [comment]
We have stats, but they are a bit scattered - there are some waterfalls on https://bugzilla.mozilla.org/show_bug.cgi?id=987895 , but basically just load marketplace in webpagetest, and you can see that because the client can't cache it, persona really hurts the repeat view performance.

Related: #3035 (having any of those bugs fixed would be great. having both fixed would be awesome :)

thanks

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
