### ISSUE TITLE
Fira Sans font not sticking

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/persona#4109]
![not-fira](https://f.cloud.github.com/assets/68213/2503205/fd56085e-b37f-11e3-8510-8f0d6b308985.png)

**Comment by krydos** [comment]
Hello. I sent the pull request which fixed this problem. Problem was in css fonts inheritance. 
I hope I did it right. 

Thank you.

**Comment by zimbatm** [comment]
not a core member here but it's looking good to me

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Comment by callahad** [comment]
(This has been fixed per https://github.com/mozilla/persona/commit/677bb87fae5a587889f17461eaaaf7d3c76dad0a)
