### ISSUE TITLE
Gather list of all outstanding security fixes

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/persona#4110]
@fmarier, we need to get together and figure out which private commits haven't been merged back to dev :neckbeard:

**Comment by fmarier** [comment]
I went through this a few months ago and found a few security fixes which had been lost, but that got fixed in the last hotfix in production and subsequently merged to dev.

Before I got pulled away from Persona, I made sure we didn't have any outstanding security bugs open and that all fixes had made it to both production and dev.

The only security-related bugs that aren't fixed are the minor ones which are on the public github tracker.

**Comment by jaredhirsch** [comment]
oh awesome man! thanks for the info, closing
