### ISSUE TITLE
Please kill backup IdP account for licensing@mozilla.org

### ISSUE THREAD

**Issue by gerv** [mozilla/persona#4128]
I am licensing@mozilla.org, but someone other than me appears to be in control of the Persona account for that email address on the backup IdP. Please verify my identity and claim, and then kill it.

Thanks,

Gerv

**Comment by gerv** [comment]
(See https://bugzilla.mozilla.org/show_bug.cgi?id=999401 for why I can't just reset the password, and the discussion in mozilla.dev.identity for how we got to this place in the first place.)

**Comment by jaredhirsch** [comment]
OK, I guess @relud will have to do this, since he has the keys to prod. Or maybe we can get @sheeri to do it, if she's not too busy.

Either way, the basic deal here is that we'll manually execute the SQL inside [db.emailToUID](https://github.com/mozilla/persona/blob/dev/lib/db/mysql.js#L567-L574), then pass that uid to the SQL used by [db.cancelAccount](https://github.com/mozilla/persona/blob/dev/lib/db/mysql.js#L711-L719):

```
// get the uid for 'licensing@mozilla.org'
SELECT user FROM email WHERE address = 'licensing@mozilla.org';

// delete all the things
DELETE LOW_PRIORITY FROM email WHERE user = uid;
DELETE LOW_PRIORITY FROM staged WHERE existing_user = uid;
DELETE LOW_PRIORITY FROM user WHERE id = uid;
```

Happy to help get this done, let me know if you have any questions at all.

**Comment by relud** [comment]
user deleted

**Comment by jaredhirsch** [comment]
:beers: thanks @relud!
