### ISSUE TITLE
When the user clicks on the BrowserID confirmation link from a yahoo mail inbox, the diresworb.org page is loaded in the same tab

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#414]
Device: Acer A500 (tablet)
Android version: 3.2
Browser: stock

When the user click on the BrowserID confirmation link from a yahoo mail inbox, the diresworb.org page is loaded in the same tab (over yahoo mail). This issue doesn't reproduce on other browsers nor on non-Android OSs.

**Comment by shane-tomlinson** [comment]
@lloyd, when I look at the email at mailinator, the email has a target="_blank" on it, which should be fine, is this the case for all email providers or has mailinator added this?

**Comment by lloyd** [comment]
we will probably address this when we improve the email that is sent (html+plain text)

**Comment by shane-tomlinson** [comment]
@lloyd - this should be re-tested now that we have HTML emails.

**Comment by csuciu** [comment]
The issue still occurs on mobile browsers. I tried stock browser, FF mobile and Chrome on Android 3.2 and 4.0.4

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
