### ISSUE TITLE
Case sensitivity in email addresses

### ISSUE THREAD

**Issue by JohnSmith-LT** [mozilla/persona#4157]
Hi,

I know similar things have been raised in other issues but these have mostly to do with logging in with a differently cased email address; i.e. registering with johnsmith@domain.com and trying to login with JohnSmith@domain.com

What I don't see as being addressed is badges that come from other places who downcase all email addresses. For example I have a backpack with ID J.J.Smith@ and have an account registered at Code School with the same email address. However they downcase to j.j.smith@ so I can never receive the badges in the other backpack. They have no way to reissue badges to the mixed case account.

I know the spec says that email addresses should be case sensitive but does any domain actually respect this and  allow two different users to use jsmith@ and JSMITH@ because to me that would seem to be pretty insane from a management point of view...

What can we do in this situation?

John

**Comment by jaredhirsch** [comment]
Yeah, this has come up a number of times; our judgment call was to err on the side of respecting the RFC, and leaving the interpretation of the user part up to the domain. We don't want to prevent someone from running their own IdP which is case sensitive. :-/

The real culprit here is code school opting to downcase email. You probably should open a bug for them to change this.

Another option might be to file a bug against the backpack repo--this is really a question for the wider badges ecosystem. cc @brianloveswords 

I'm really sorry this has stung you, but I don't think Persona is the right player to address this. Hope this makes sense.
