### ISSUE TITLE
Mozilla Persona not create account 

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#4158]
1. Sign in Mozilla Persona does not create account on new mail address
2. For gmail mail address, it throws error message
   Action: Authenticating with Assertion and 
   URL: https://login.persona.org/sign_in?AUTH_RETURN
3. For hotmail email addresses, it does not send confirmation mail for completing the creation process.

**Comment by vthunder** [comment]
I just repro'ed this. Can't make new accounts, at least with my Google-hosted domain address.

**Comment by interactiveblueprints** [comment]
We noticed the same problem.
New user is detected and asked to create his password (twice).
Then the login screen switches to login (no notification that an email was send).
The email is received, but when the "button" is pressed, the persona site shows up with an error ("There was a problem with your signup link. Has this address already been registered?")

Tried with FF 30 in linux and windows, Google Chrome on windows.
And on different locations and networks/providers

**Comment by shane-tomlinson** [comment]
> [10:35:22]  <Interactive>  From #persona: stephank> Getting errors: GET https://login.persona.org/include.js 503 (Service Unavailable: Back-end server is at capacity)

**Comment by gene1wood** [comment]
These symptoms from this last night were caused by an operational issue which resulted in one of our databases losing replication with it's master.

The timeline of the event can be seen here : http://personastatus.org/#1403754712

The root cause was that the systems ran out of disk space due to Percona MySQL default setting `relay_log_purge` to `0`. This resulted in binary logs never being deleted on the databases and slowly over its entire life, filling the disk.

I've got PR https://github.com/mozilla/identity-ops/pull/161 in to fix this (I fixed it manually last night to get the DB back up).

The reason for the long period of time during which this DB was out of replication was due to a mistake made in our operations team mis-identifying the production persona database as a staging Mozilla Marketplace database, resulting in the monitoring alerts not being escalated to me (the oncall tech). I've started conversations to make process changes to reduce the likelihood of this type of process failure in the future.

The issue which triggered the oncall escalation that identified this DB issue was an unrelated problem that took Persona down entirely ( see #4159 ). The timing of these two events were entirely coincidental.
