### ISSUE TITLE
encrypt cookie content

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#416]
right now cookie-sessions have integrity protection, not confidentiality. We should encrypt them.

**Comment by lloyd** [comment]
Addressing this issue would allow us to use the serial user ID to address issue #388 (and other issues related to the same underlying issue, that storing the email address that you authenticated is more fragile than a user id associated with the account you authenticated to - because in many attack scenarios email ownership can change).

I'd suggest we hijack this issue a bit and make it about a more holistic solution to the session implementation.  Another flaw that exists with the existing session implementation is that it sends Set-Cookie headers on every request.  This requires that any WSAPI call that can possible change session state must be serialized, and all other wsapi requests must be blocked until that completes.  

I'd suggest the following requirements on our session implementation:
- a standalone node.js module that we can independently test and reuse for many of our projects
- can be bound on a subset of the url space, and only performs processing when neccesary (current implementation doesn't support this and must be wrapped)
- encrypts cookies (we don't care about signed cookies, let's not even bother implementing support)
- lazy cookie decryption (on demand when .session is accessed?)
- well tested with standalone unit tests
- only sends set-cookie headers when needed (this mitigates inherent race conditions of client side sessions and also shaves a bit off the wire)
- self manages fixed durations (currently we implement a 2 week timeout inside our application)
- self manages inclusion of nonces or whatever random data is required to be cryptographically sound.
- can be used by other, higher level connect abstractions, like the in-development [connect browserid middleware](https://github.com/lloyd/connect-browserid)

I think this whole implementation can fit in a couple hundred lines of SLOC.  Have a look at jed's [cookies](https://github.com/jed/cookies) module for inspiration and/or code.  That might be a great starting point.

**Comment by benadida** [comment]
one correction:
- we have to sign the cookie, not just encrypt it. Otherwise this might allow someone to rejigger the ciphertext around and mess things up. In general, not good to encrypt without signing, it's typically asking for trouble. So we'll do both.

and one question:
- what do you mean by "self manages fixed durations?" Do you mean that it auto-updates the cookie expiration to expose effectively 2-week (parameterizable) sessions?

**Comment by lloyd** [comment]
I mean the mechanism itself embeds an original-issue-time from which point the "duration" of the cookie is calculated.  So you can say "this session is good for two weeks" and that means two weeks max, from right now.  not two weeks from the user's last visit.

**Comment by lloyd** [comment]
see 'authenticatedAt' here: https://github.com/mozilla/browserid/blob/dev/lib/wsapi.js

For the application level mechanism I'm suggesting we might push down into the session implementation

**Comment by benadida** [comment]
gotcha, right, because if it's just expiration time on the cookie, then resetting the cookie will extend the expiration time, which is not what we want.

I'm thinking proxies might be overkill, maybe JSON serialize and compare?

**Comment by lloyd** [comment]
Json serialize doesn't guarantee any order.  It's impl dependent, so you would need a deterministic serialization format and this would need to happen on every request.  Not a big deal, but if mutation detection were easy, it could be elegant

--lloyd

**Comment by benadida** [comment]
crud, I was under the impression that JSON serialize had an option for sorting keys. OK, I'll see if I can find existing mutation detection. Some hints of it here:

http://stackoverflow.com/questions/1759987/detect-variable-change-in-javascript

but of course we need to watch for property changes where we don't know the properties ahead of time. I'm sure there's some existing proxy code for this. I'll hold off on the temptation to cc /be

**Comment by benadida** [comment]
only missing feature right now is management of the duration, will work on that asap, so I'm going to reopen this issue actually.
