### ISSUE TITLE
Internet Explorer 8 not working

### ISSUE THREAD

**Issue by migurski** [mozilla/persona#4172]
We are seeing errors with IE8, despite it being in the list of supported browsers. We believe that we’re doing the right things with compatibility mode.

![image](https://cloud.githubusercontent.com/assets/58730/3807233/983be2f4-1c61-11e4-8ab3-859f93c4646f.png)

/cc @criscristina.

**Comment by jrgm** [comment]
Hi. Yes, IE8 is supported and it does work (I've used it just now).

Can you load this page and share the results? (It just checks for support of various DOM features like localStorage, XMLHTTPRequest, postMessage...). Thanks!

**Comment by migurski** [comment]
Which page?

**Comment by jrgm** [comment]
Sorry. Forgot this link - https://people.mozilla.org/~fmarier/troubleshoot.html

**Comment by criscristina** [comment]
Getting this:
![image](https://cloud.githubusercontent.com/assets/3180799/3818329/2cca680e-1ce0-11e4-8400-67b67cd424e7.png)

**Comment by Eagle3386** [comment]
IE8 was the last one to support Windows XP (which was abandoned in April this year). Its successor, IE9, is supported. Do you _really_ think, this issue shouldn't be resolved as "invalid" by now?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Comment by callahad** [comment]
Whoops, the mass-closing script misfired. Sorry about that.

@migurski, is this still an issue? The troubleshooting page makes it look like everything is working. Is it possible that your site is forcing IE8 into quirks mode, rather than standards mode?

**Comment by criscristina** [comment]
No, you should be able to close this.  You were right about forcing quirks
mode. Thanks for checking.

**Comment by callahad** [comment]
Awesome, thank _you_!

**Comment by migurski** [comment]
Not an issue!
