### ISSUE TITLE
FreeBSD setup document is outdated (at docs/SETUP_FREEBSD.md)

### ISSUE THREAD

**Issue by stevejarvis** [mozilla/persona#4186]
FreeBSD 10 [switched to Clang and does not include GCC in the base system](https://www.freebsd.org/news/status/report-2011-04-2011-06.html#Clang-replacing-GCC-in-the-base-system).

And with pkgng, ['add' assumes the application is available locally](https://wiki.freebsd.org/pkgng#add). The system suggests 'install' when it isn't found, which is probably the best way to go.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!

**Comment by callahad** [comment]
Whoops, the mass-closing script misfired. Reopening.

**Comment by callahad** [comment]
Fixed in https://github.com/mozilla/persona/commit/88212d654c9f326c00de2d80fc2ff44173d4e620
