### ISSUE TITLE
Keeping Mozilla Persona Alive

### ISSUE THREAD

**Issue by vote539** [mozilla/persona#4234]
Mozilla Persona is a good service.  It has its flaws, but I don't see a good reason why to take it offline.  Persona fills a void that no other service really provides (anonymous SSO logins), especially since traditional OpenID has been deprecated.

I run a site that has had on the order of 10k users sign in with Persona this year.  When I added Persona login as an option about 18 months ago, I put faith in Mozilla that I wouldn't have to see this day when I would need to move away to another service.

I would be willing to make contributions to keep the service online, and I imagine other web developers would as well.

**Comment by rfk** [comment]
Thanks for reaching out @vote539, but I'm afraid that ship has sailed.  We were able to keep the persona.org service active for several years in "maintenance mode", but it's clear that usage is declining and community-led efforts to maintain development have not be fruitful enough to justify an ongoing investment of resources from Mozilla.

> I don't see a good reason why to take it offline

To say a little more about this - running an authentication system is no small endeavor, and is not as simple as just keeping it online.    There is a certain level of operational and security support that is required in order to keep users of the system safe.  We simply can't justify dedicating those resources on an ongoing basis.

If you're interested in supporting a service in a similar vein to Persona, I recommend taking a look at https://github.com/portier - it's early days but the team there includes several people who were active in Persona development in the past.
