### ISSUE TITLE
Deal with deleted acounts when the dialog is open & authenticated

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#466]
Linking from issue #401.

We need a way of dealing with accounts that are deleted from the main site after the user has already opened the dialog and authenticated.

**Comment by csuciu** [comment]
Test case added https://moztrap.mozilla.org/manage/caseversion/23755/

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
