### ISSUE TITLE
/wsapi/cert_key is returning a string instead of a JSON response.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#471]

**Comment by benadida** [comment]
yes we should wrap this signature in a JSON object

**Comment by lloyd** [comment]
+1.  bump.  fist pump.  etc.

**Comment by shane-tomlinson** [comment]
@lloyd - this is still returning a string instead of a JSON response.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
