### ISSUE TITLE
Refreshing the Sign in dialog/tab closes it

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#475]
Device: Samsung Galaxy S
OS: Android 2.2
Browser: Firefox 7.0.1

STR:
1. Launch http://beta.myfavoritebeer.org in the above environment.
2. Tap on the Sign in button.
3. Refresh the newly opened Sign in tab.

The tab is closed.

OS: Windows 7 Professional
Browser: Firefox 7.0.1

STR:
1. Launch http://beta.myfavoritebeer.org in the above environment.
2. Tap on the Sign in button.
3. In the newly opened dialog, click next to the URL and press Enter.
4. Press F5.

Nothing happens at step 3. The dialog is closed at step 5.

**Comment by shane-tomlinson** [comment]
@ioanab - this is linked to #465.  The reason is because we have no way of establishing the communication channel because we remove the name of the iframe to link up with from the URL.  @lloyd, what do you think about this, should we say this is a feature and show an error message, or should we try and re-establish the comm channel somehow, perhaps by keeping the hash or store the iframe name info in localStorage.

**Comment by shane-tomlinson** [comment]
Incorrectly closed, should have been #465

**Comment by ghost** [comment]
Bug 465 has been fixed, but this issue (475) still reproduces:

If the user opens the signing in dialog and presses F5 (refresh) before the hash has been cleared, the page is still loaded ok. If the user presses F5 after the hash has been cleared, the dialog is closed.
