### ISSUE TITLE
improve handling of dropped database connection

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#482]
this might include:
- improving `__heartbeat__` to verify that the connection to the database is up.
- include in automated testing the above - both transition from health to sick and back again.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
