### ISSUE TITLE
browserid.org should show content with JS disabled

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#510]
a fade-in effect should not be required. Maybe do a .hide() in JS only?

**Comment by shane-tomlinson** [comment]
@benadida - which fade in effect are you referring to?

**Comment by benadida** [comment]
front page of browserid.org

**Comment by lloyd** [comment]
+1

--lloyd

**Comment by shane-tomlinson** [comment]
ok, we are going to lose the effect of the BrowserID "card" sliding in/out over the find out more/create account text for browsers that do not support CSS transitions.

**Comment by lloyd** [comment]
Oh, we're not talking about getting rid of _all_ the JavaScript, just making the content visible in a browser with JavaScript disabled...

--lloyd

**Comment by shane-tomlinson** [comment]
@benadida, @lloyd - I have updated so that the contents of all pages will display even if Javascript is disabled.  On the main page, the contents are shifted vertically because the original CSS depends on Javascript setting the height of an element to do vertical centering.  Fadein on each page still happens if Javascript is enabled because it looks better.

It brings up the question - what should happen on the sign in and sign up pages?  Right now I just have a "noscript" tag that displays at the top of the screen saying Javascript must be enabled for these features.  I experimented with not even showing the "sign in" and "sign up" buttons from the header and main screen, but then asked myself if non-Javascript users would ask themselves "well, how DO I sign up?" By enabling the pages but showing the message, at least we give them instructions.

Any input would be helpful.

**Comment by lloyd** [comment]
I think your approach is perfect here, shane.  I feel noscript is a non-starter for us, and is fairly fringe - as long as we fail clearly and gracefully I think we're good, and that's what you've done.

**Comment by benadida** [comment]
agreed with @lloyd: we can't solve the auth problem with noscript (at least not anytime soon), but we should explain why someone would want to enable JS for this feature.

**Comment by shane-tomlinson** [comment]
@benadida, @lloyd - alright closing this.

**Comment by ghost** [comment]
Verified on Windows 7 with Firefox 7.0.1. The page content is displayed with javascript disabled and the "We're sorry, but to sign up for BrowserID, you must have Javascript enabled.", "We're sorry, but to sign in to BrowserID, you must have Javascript enabled. " messages are displayed on the pages with Sign in/up text boxes.
