### ISSUE TITLE
include.js catches postMessages not intended for it

### ISSUE THREAD

**Issue by ianb** [mozilla/persona#534]
I have an iframe that itself includes https://browserid.org/include.orig.js and that iframe receives postMessages from its parent.  I'm sending some invalid JSON (the string "hello"), which browserid's include catches, but was not intended for browserid.

I get this (mostly harmless) exception:
  Uncaught SyntaxError: Unexpected token h (include.orig.js:110)

It seems like a check of event.origin could determine immediately that the message didn't come from browserid, before any JSON parsing.

**Comment by shane-tomlinson** [comment]
@lloyd - I gave this to you since you did the JSChannel work - is there a way we can have the JSChannel only listen for postMessage messages coming from the browserID relay iframe?  It seems like this should be possible, that way if @ianb's use case pops up again and include.js is included in an iframe, include.js is only catching messages from the inner relay iframe and not from the parent?
