### ISSUE TITLE
add a FAQ to end user docs regarding password handling

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#538]
we should document precisely how we handle passwords so folks can feel safe about sharing their must trusted random phrases with browserid.  This would be good as a FAQ that is end user and/or developer facing.  Maybe this means in SUMO?

**Comment by shane-tomlinson** [comment]
@callahad - I am reassigning this to you to do as you please.

**Comment by jaredhirsch** [comment]
@callahad bump. Leaving open for Beta 2 as it's "just docs" :surfer:

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
