### ISSUE TITLE
The "Communicating with server" dialog hangs when loosing the internet connection

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#568]
OS: Windows 7
Browser: Firefox 8.0

STR:
1. Open beta.myfavoritebeer.org.
2. Click on the Sign In button.
3. Loose your internet connection while the "Communicating with server" dialog is displayed.

The "Communicating with server" dialog hangs (regardless if the internet connection is re-established or not) until the user manually closes it. No error message is displayed.

**Comment by shane-tomlinson** [comment]
I am marking this as needs discussion because I think we need a decent plan of attack here on how to take care of opening the dialog with a loss of network connection before the relay frame is established.

**Comment by jedp** [comment]
Note that this also happens if the server crashes.  So if there were an outage, you'd get a misleading message.

STR:
1. Run browserid
2. Go to localhost:10001
3. Crash browserid
4. Click 'Get an assertion'

The login dialog appears and hangs, saying "Communicating with server"

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
