### ISSUE TITLE
Document the process for changing an email address

### ISSUE THREAD

**Issue by joshtriplett** [mozilla/persona#58]
Many users still rely on email addresses that may change in the future without the possibility of forwarding.  Those users may eventually need to change their email address.  This should not result in the user having to re-establish their identity with every site they use, nor should it compromise the user's security if someone else later gets access to that email address.

Please, document the process for a user to change their email address, including the involvement of the user's browser, the browserid.org fallback, any cryptographic keys the user may have, and how sites can transition to a new email address.

Please also consider extending the BrowserID standard to allow browsers to notify a site at authentication time that it needs to use a new email address; that way, users need only re-authenticate with all sites to change their email address, rather than having to find a site-specific "change my email" mechanism.

**Comment by vthunder** [comment]
Yes, agreed. We need to help users be able to switch email addresses as easily as possible. It's relatively easy when the user still has access to the old email (though even that requires some site support). I think our "session API" (which is still in the works, but essentially it's a way for the page to tell the browser about who is signed in, and for the browser to be able to send events like "sign in" and "sign out" to the page) would be a pretty good fit here: we just need to send a "change email" event that the page listens to.

Changing an email when the user no longer controls the old email is trickier, and probably more of an evangelism problem (we need to let sites know about this issue). There are use-cases where it would be undesirable to get the site to change the email in this case (e.g., I use my company email to access a partner company's site, then I get fired--I should not be able to change my email on the partner company's site).

Not sure how we resolve issues that we think will be part of the session API. Ben/Lloyd? Close here and add to the wiki?

**Comment by joshtriplett** [comment]
Github has issue labels now; you might consider leaving the issue open and adding a specific tag to it, so that you can ignore all session API issues until working on the session API.

**Comment by myers** [comment]
I think it might be done this way:

Start:
1. user creates BrowserID me@foo.com 
2. user creates new account on example.com and uses the site for months
3. user now wants to change email addresses
4. user creates BrowserID me@bar.com
5. user logins in to example.com and requests to change his email
6. example.com asks for a new BrowserID
7. user sends his new BrowserID me@bar.com
8. example.com replaces BrowserID me@foo.com with BrowserID me@bar.com it it's database
9. user repeats this with all other sites he's used me@foo.com 

This isn't that far off from how you change emails now.

**Comment by joshtriplett** [comment]
That looks about right, except that I'd suggest replacing steps 5-8 with:
1. User tells their browser (or browserid.org) that they want to switch from me@foo.com to me@bar.com.
2. Later, user logs into example.com using BrowserID.
3. During the login procedure, the site automatically gets told that the user wants to switch email addresses, without the user having to find a site-specific "change email" button.
4. example.com changes the email in its database, and informs the browser that it has done so, so that the browser stops reminding it on every login.

I think making this an automatic part of login would avoid the need for every site to handle it differently, or supply UI for it.

**Comment by davesann** [comment]
I have a suggestion on this matter that breaks current practice. I think that it could be considered a problem that persona uses a piece of data that may or will change as an identifier. Instead, use a permanent id that cannot change.
1. Persona should not provide the email address to the site when verifying
2. Persona should provide a permanent unique identifier only. Persona assigns and manages this id
3. Persona can still use email for login
4. Persona manages email aliasing and email address change flow centrally.
5. Persona allows client site to access current email. (under users control)
6. Optional - persona allows user to set name and possibly other details for provision to client sites.

This is also sort of nice because you could, if you wished, log in without providing any personal information to a site. 
For the site they can still track that user X logged in.

**Comment by callahad** [comment]
Thanks for the thoughts, @davesann. Any thoughts on how we could do that while still being decentralized and without locking sites into Persona?

**Comment by davesann** [comment]
that will require some more thought. maybe, maybe not.

**Comment by shane-tomlinson** [comment]
Link to #794, #852

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
