### ISSUE TITLE
issues with multiple RPs and relay frame

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#588]
This is a regression, originally raised in issue #580.  If you open an RP, then open a second, then click sign in on the first, the dialog will fail with the following message

"We are very sorry, there has been an error!
To retry, you will have to close BrowserID and try again. More info can be found by opening the expanded info below.

```
Action: Establishing Relay
Relay frame could not be found"
```

@shane-tomlinson and I expect that this is due to the localStorage mechanism introduced.

**Comment by lloyd** [comment]
we need to somehow correlate in time the setting of this localstorage thingy by the relay frame, and the reading of said thingy by the dialog...

**Comment by benadida** [comment]
## Yes, nice catch. Leave this one to me while you work on requiredEmail.

Ben

Lloyd Hilaiel reply@reply.github.com wrote:

This is a regression, originally raised in issue #580. If you open an RP, then open a second, then click sign in on the first, the dialog will fail with the following message

"We are very sorry, there has been an error!
To retry, you will have to close BrowserID and try again. More info can be found by opening the expanded info below.

Action: Establishing Relay
Relay frame could not be found"

@shane-tomlinson and I expect that this is due to the localStorage mechanism introduced.

---

Reply to this email directly or view it on GitHub:
https://github.com/mozilla/browserid/issues/588
