### ISSUE TITLE
Resolve issues around account consolidation.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#607]

**Comment by shane-tomlinson** [comment]
@jbonacci - I forget what the original issue is about!  For the questions you raise above, I defer to @skinny97214.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
