### ISSUE TITLE
The "If this is a mistake..." message on the verification dialog doesn't make sense

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#623]
On the email verification dialog, the following message is displayed:
" We sent a confirmation email to <email_address>
To finish signing in just click the verify link we sent to your email address.

If this is a mistake, just ignore the sent email and use another."

This message should be:
" ...
If this is a mistake, just ignore the sent email and use another email address."

**Comment by shane-tomlinson** [comment]
@jbonacci, @ioanab - I have made some small changes but would like some UX input here.  I have used James' suggested text of "use another email address" as well as made the font on the links bold so that they are more discoverable, but it now seems like the "use another" link stands out too much.  @clarkbw or crystal?

**Comment by skinny97214** [comment]
Black bolded text is used in a lot of places where it's not a link. In the name of having a consistent visual language, I changed the link to be the regular blue. I also reworded slightly so if a user only scans the text of the link, it's clear what clicking it does: "sign in with another address"

http://cl.ly/2D0l433J1q0A0E1C2R2k

**Comment by shane-tomlinson** [comment]
Skinny's suggestion has been merged for quite some time, wording and all.  Closing.
