### ISSUE TITLE
Structure of browser JS

### ISSUE THREAD

**Issue by jrburke** [mozilla/persona#660]
I expect this is a low priority item, and it may not be the right time to consider this, or you already may have this worked out. So feel free to discard or delay a response until much later:

I would like to help with the structure of the browser code in browserid. While trying to trace the code to modify for allowing appscheme: flows for mobile devices, I noticed the following things:
- sometimes it was hard for me to map what objects were being created by which files.
- there is an implicit dependency order for some scripts, and that order needs to be reflected correctly in the ejs template for dev and the compress.sh for building for production.
- vepbundle.js using a require()-type system that is not used by the rest of the code.

I have helped another mozilla project, [gladius](https://github.com/alankligman/gladius) with a modular approach using AMD modules, which are friendly to CommonJS-style modules but works well in the browser, and I can see that approach working here too. 

gladius use fine-grained modules in dev that get separate script loads for each module via RequireJS, allowing easier debugging, but then for deployment do a build that wraps up all their modules into one file and just includes a small define/require shim via [almond](https://github.com/jrburke/almond).

Another nice feature with AMD modules is the ability to use loader plugins that can inline their resources as part of the build, like HTML templates and i18n bundles.

I could go into more detail how I structured the gladius code, but first wanted to see if this might be useful, and how to tie into the larger plans for the front end code.

You may have already sorted out a structure that works for you, and that is great too. The most important thing is delivering functionality to end users. Just offering to help if you do want to change your current structure.

**Comment by shane-tomlinson** [comment]
@jrburke - Thanks for the issue - you are correct, I have been trying to slowly clean up the directory structure to make discoverability simpler. There is still a lot of work to be done here, especially in the area of storage, user, and network.  I'd like to further break these three up into more cohesive components.

As far as using a script loader, we just ripped out StealJS because it interfered with us more than I was comfortable with.  StealJS and other loaders like your RequireJS have some very nice benefits (dependency ordering), but StealJS did a lot of its magic using eval, which caused problems in IE under certain circumstances.  The most important problem we had is it caused problems when opening an HTTPS iframe inside of an HTTP page.  Secondly, even when all of the scripts were compressed, StealJS required two network calls, the first for the script loader, the second to load the compressed scripts.  Third, removing StealJS saved us ~10kb - this savings is due in part to two factors - 1) StealJS is no longer included, and 2) we are no longer declaring every file's dependencies at the top of the file.

In the end, it was my desire to have lower level control that made me rip out StealJS.

The biggest downside of doing this work so far is that the order of dependencies is now maintained in two places, the first for development, the second in the build script used to concatinate the JS together, and this alone is making me consider an alternative AMD library such as yours.

I am completely open to suggestions, your knowledge with RequireJS would be very useful in addressing a lot of my concerns.

As var as the vepbundle, @benadida would have further insight there.

**Comment by jrburke** [comment]
@shane-tomlinson: that makes perfect sense. I can see a lot of overlap with your desire for minimal code impact/funkiness and how I did the setup for gladius:

1) In dev, for each page, have one HTML script tag in the page at the bottom of the file, call it page/app.js. That page/app.js in dev would do a document.write for the script loader, and trigger the loading of the "main" script for that page. [Here is that dev version in gladius](https://github.com/alankligman/gladius/blob/develop/src/gladius.js) but I expect for browserid it would be an even simpler file for each page, probably just a simple document.write() call.

2) For production deployment building, run the requirejs optimizer that replaces that page/app.js with a built resource that includes just the page's scripts plus a small define/require shim. So, no dynamic script loader (no require.js) is delivered for production, and the define/require shim is small, around [750 bytes when minified and gzipped](https://github.com/jrburke/almond).

If the vepbundle was generated to use the same wrapping shim instead of its custom require shim, then I would expect the file size change to be near zero over what is bundled up now.

This would mean that you would still be only doing one JS script request per page, and there would not need to be a if (dev) branch for script loading in the HTML templates. And since the "dev" version of the file is not used, there is no document.write() going on in production.

I'm not sure what StealJS uses eval for, but requirejs does not use eval for loading JS modules. There is a helper functions for transpiler loader plugins, like the coffeescript loader plugin, and that uses eval, but for JS loading and simpler loader plugins like the text plugin, it is not used.

If you are interested, I could do a branch that would show a possible use. I would likely want to walk through the code with you a bit in realtime first, to make sure I understand your concerns and end design goal though. So if there is a time that works for you/the team let me know. I know there are higher priority items to get done though, so I appreciate you may not respond to this for a while. 

If I wrap up my appscheme branch sooner than expected, I may play around with it and just post back here if I get something going, if we do not get a chance to talk before then.
