### ISSUE TITLE
Apache BrowserID module

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#671]
We've got an Apache module that does BrowserID:

  https://github.com/mozilla/mod_browserid

It could probably use some tender loving care.

**Comment by samatjain** [comment]
The [OpenID module for Apache](http://findingscience.com/mod_auth_openid/) has some nice ideas. Some of the stuff I liked and is missing from the BrowserID module:
1. A default login page, built-in the module
2. Pass parameters (such as REDIRECT_URL) via GET, so the login page could be static HTML instead of a server-side script

**Comment by GHANONTEST** [comment]
I would absolutely LOVE to see this play out with come TLC and polish.  In the meantime I'm contemplating writing a PHP shim to achieve the same affect.  

BTW, wouldthis require any special permissions or root access to install and enable, orwould it work on a standard shared hosting setup?

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
