### ISSUE TITLE
The BrowserID dialog cannot be opened from multiple clients at the same time in Opera

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#714]
OS: Windows XP
Browser: Opera 11.6

STR:
1. Load 2 distinct clients in new tabs (e.g. http://beta.myfavoritebeer.org/ and http://beta.myfavoritebooze.org/).
2. Click on the Sign In button to open the BrowserID dialog from one client.
3. Go to the other client and try to open the dialog from there too.

The BrowserID dialog cannot be opened from multiple clients at the same time in Opera. It can be done in Chrome 15 and Firefox 8.0.

**Comment by shane-tomlinson** [comment]
@ioanab - nice find!  This is probably due to the fact that the name we give the new tab is always '_mozid_signin'.  To fix this, we are going to have to assign a new name for each dialog window.

**Comment by shane-tomlinson** [comment]
@lloyd - I am going to reassign to you and will offer my services where needed.

Now that WinChan is in, Opera acts even stranger.  If you have two RPs open, one with BrowserID open, and then in the other RP attempt to open BrowserID (making a second instance open), the original BrowserID window closes.  I theorize that this is due to the window name being null - I believe that window names need to be unique for Opera to behave in expected ways.

**Comment by csuciu** [comment]
Re-tested this issue on Ubuntu 12.04 + Opera 12.12 and I got the same result as in comment #0.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
