### ISSUE TITLE
Unresponsive script avoids Sign Up

### ISSUE THREAD

**Issue by lalluviamola** [mozilla/persona#741]
I'm trying to use OpenPhoto, but I cannot be identified successfully. After checking my email address and my passphrase, when I click on "Sign Up" after some seconds appears a windows saying:

A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete.
Script: https://browserid.org/dialog/production.js:51

Stop the script and refresh carries me to the same situtation. Also with private browsing.

I'm using iceweael 3.5.16 on debian running in a MIPSEL architecture (yes, my browser is probably very unique. ) I've get installed NoScript but it doesn't seem the problem.

**Comment by lloyd** [comment]
I think the problem here is that your computer is too slow to complete the generation of DSA keys in the time the browser allows scripts to hog the processor.

This is a very interesting case.  And I have some questions for you:
- What happens if you keep pressing "continue" to see if the script will complete?
- If the first step does eventually complete, approximately how long does it take in seconds?

/cc @benadida @shane-tomlinson Perhaps a robust solution here would be to run a quick client benchmark (200ms) to see how much work the client machine can complete in a fix amount of time.  Based on that result, either downgrade the keysize of the DSA key, or even just block the client (if it would take > 1minute or some threshold).

This would move us away from browser detection for performance (IE8) and would move us toward a more meaningful measure: holistically, how fast is the user's machine?

**Comment by lalluviamola** [comment]
It worked! Exactly as you described. As I hadn't success continuing scripts in the past I didn't think it could work, so after the second "Continue" I always chose "Stop the script". However, after the 3rd time it worked, but I had to refresh the page for noticing it (while I believe that NoScript was not blocking anything related to BrowserID).

Time it lasted was almost exactly 1 min.

My machine is the wonderful Lemote Yeeloong, which comes with a unique processor of 800 MHz and a free BIOS.

Feel free to ask for more tests if you want.

**Comment by benadida** [comment]
@lloyd we could try a smaller modexp, yes, I've wondered about that. I'm not sure if it will give us the right benchmark, but it's worth trying it out.

**Comment by lloyd** [comment]
let's close this down and focus on issue #762 which should address it.  please re-open if you feel like issue #762 won't solve it.
