### ISSUE TITLE
BrowserID fails to communicate with Chrome extension window.

### ISSUE THREAD

**Issue by asbjornenge** [mozilla/persona#75]
Calling navigator.id.getVerifiedEmail from a chrome-extension:// "protocol" will cause...

Uncaught Channel.build() called without a valid window argument - buildjschannel.js:201

I'd love to use BrowserID for my chrome apps too!

**Comment by lloyd** [comment]
@asbjornenge - this will take a _little_ bit of tweaking.  The key problem to solve here is the ability to post messages (using postMessage) between the addon and the content window that's spawned.  currently in channel.js, line 35 you can see we're using window.opener from the opened content (err, "dialog") window. 

I have to focus on other issues for a while, but would def be able to review and merge patches in the short term.  if not, I'll look into a fix just as soon as I can get to it.  I'd also like to build a chrome extension for "native" browserid support, so that might be the perfect way to figure out this issue, too.

**Comment by asbjornenge** [comment]
"Native" support seems like the way to go. Since chrome apps run sandboxed they are by design unable to communicate with spawned windows etc. But extensions can easily talk to other extensions, so that would solve the issue.

I can look into it and see if I can be of any help here. Haven't dug too deep in the code yet. Might get some time later today :-) Could you help by pointing me in the right direction...?

**Comment by asbjornenge** [comment]
Ok, so... I've been looking into what chrome extensions can do and digging a bit in the browserid source....

What I've basically done is made an extension based on your browserid/static files, and a little bid_ext_include.js that can talk to it. And when I say I've done this I mean in a way that its totally not working properly and looks like a mess :P.

What I think I should do is just to make my own UI bit and rather just work agains your restful api. Not being used to steal or .ejs templates makes using you code as a base for the extension a bit messy for me. I'd have to get into boring and non interesting stuff like learning frameworks, blahr :P

I'm not really sure how you guys intended browser vendors to integrate... I think you need something a bit more targeted at this kind of scenario. Or I might be totally off track... Care to elaborate?

**Comment by shane-tomlinson** [comment]
Closing in favor of #2034
