### ISSUE TITLE
BrowserID should allow login from N emails with user's 1 password

### ISSUE THREAD

**Issue by ozten** [mozilla/persona#750]
While trying to reset my password (Issue#114), I stumbled on a weird flow and a bug.

Steps to Repro:
1) Go to http://myfavoritebeer.org/
2) Click Sign In
3) In dialog click "This is not me..."

I did this because I was hunting for a password change flow

4) Enter email
5) Click "forgot your password"
6) Do verification dance in a completely different browser (new profile)
7) Go to http://myfavoritebeer.org/ (in new browse)
8) Click Sign In, input a secondary email, new password
Note: secondary email starts down registration flow
9) input primary email and password

Expected
I can log in with any of my previously verified email addresses along with my password
All my emails show up in the new browser

Actual:
Logged in, but only primary email show sup in the list

**Comment by ozten** [comment]
As a heavy user of browserid, I'm used to disclosing emailA at siteA and emailB at siteB.

If I have to log-in on a new browser or from "scratch" while on siteB, I tend to input emailB... since I'm on siteB. BrowserID doesn't recognize that as a valid auth credential and starts me down the registration flow... for an email it already knows about as a secondary email.

**Comment by vmunix** [comment]
I hit the same issue since I leave GMail running in a "dedicated" browser.

**Comment by shane-tomlinson** [comment]
@ozten, @vmunix - yes, this is indeed the case, we have discussed this several times and how to approach it.  Right now by design when you forgot a password, the reset password flow essentially creates a new account for that single address.  I believe this was to stop what @benadida and @lloyd were calling the "transitive identity" hack.  The essentials of this is that if a bad person has control of one of my email accounts, they cannot instantly get control of my entire set of ids in BrowserID by resetting the password.   Account consolidation is still possible by resetting the password on one account and then adding the emails using "Use a different address."

**Comment by lloyd** [comment]
all discussion moved to issue #757

**Comment by shane-tomlinson** [comment]
Issue #759
