### ISSUE TITLE
Bad SSL Cert for https://beta.myfavoritebeer.org

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/persona#751]
When going to https://beta.myfavoritebeer.org, I get a big old security warning in both FF8.0.1 and IE9.

Output from FF 8.0.1:

beta.myfavoritebeer.org uses an invalid security certificate.

The certificate is only valid for the following names:
  *.herokuapp.com , herokuapp.com  

(Error code: ssl_error_bad_cert_domain)

**Comment by benadida** [comment]
I don't think this is an issue, myfavoritebeer should be reached over plain HTTP, not SSL :) Closing.

**Comment by callahad** [comment]
Solution: Stop listening on 443.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
