### ISSUE TITLE
email reset / password recovery is not good

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#759]
No one is happy with how password reset works, we need to re-think it considering both security and UX.

**Comment by benadida** [comment]
UX + security agreement (sort of cause @lloyd not on phone) that blast all emails but keep account consolidated is the right approach. Ben will write up.

**Comment by ghost** [comment]
Currently, when performing the steps from @jbonacci 's last comment, the email used at step 4 is separated into a new account with the new password. The other emails stay in the old account.

If you decide to keep this behavior, the user will have to be notified about what happened since his impression will be that the emails from the old account were simply lost. Perhaps display a warning when he clicks the Forgot Password link and wait for a confirmation before sending the verification email?
