### ISSUE TITLE
Support for internationalized domain names

### ISSUE THREAD

**Issue by M66B** [mozilla/persona#78]
See here for an explanation: http://en.wikipedia.org/wiki/Internationalized_domain_name

On PHP $_SERVER['HTTP_HOST'] contains the ASCII version of the 'audience', while the server seems to expect the Unicode version. Unfortunately PHP has no native support to translate one into another. Few servers offer the function idn_to_utf8: http://php.net/manual/en/function.idn-to-utf8.php.

This class can be use as an alternative: http://idnaconv.phlymail.de

But it would be easier if the server support the ASCII version and maybe it even should.

**Comment by M66B** [comment]
UTF8 domain names seems to give 502 Bad Gateway always when verifying :-(
Sending the ASCII domain name results in 'Payload audience does not match provided audience'
So, no go for IDN.

**Comment by M66B** [comment]
Some more info:

PHP audience: www.xn--idyry-yua.no ($_SERVER['HTTP_HOST'])
PHP audience UTF-8: www.idyrøy.no
JS audience: www.idyrøy.no (window.location.hostname)

**Comment by M66B** [comment]
Even more info, the login dialog displays:

What email address would you like to use to sign into www.xn--idyry-yua.no?

So the ASCII and UTF-8 version of the domain name seems to be mixed up.

**Comment by M66B** [comment]
This issue is browser dependent:

FF:
Shows this in small popup window: www.idyrøy.no
Sign In ERROR:
Verification failed
Payload audience does not match provided audience.

Chrome:
Shows this in small popup window: www.xn--idyry-yua.no/iDyroy
Sign in OK.

IE9:
Doesn't work.

Verification of the assertion was done with the ASCII version.
Unicode version always results in 'Bad Gateway'.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
