### ISSUE TITLE
handle SIGHUP for log rotation

### ISSUE THREAD

**Issue by fetep** [mozilla/persona#793]
For better more reliable log rotation, it would be great if we could take a SIGHUP and re-open logfiles.  Specifically, the main process logs and the metrics JSON logs.

Without this, we have to use logrotate's "copy & truncate" method, which is prone to losing a few log messages during rotation.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
