### ISSUE TITLE
Error including browserid.org/include.js

### ISSUE THREAD

**Issue by interactiveblueprints** [mozilla/persona#795]
L.S.,

I'm new to browserid. Maybe I'm overlooking something but the sample code provided in the docs, see pastebin: http://pastebin.com/Xq1TFYSC, seem not to work.

Ran on a localhost server it leads to a javascript error on Chrome:
Uncaught TypeError: Cannot call method 'call' of undefined
Unable to post message to https://browserid.org. Recipient has origin http://localhost.

What am I doing wrong? It seems like a bug...

Thanks for the product, kind regards,
 Sjoerd

**Comment by lloyd** [comment]
It is a bug!  It's issue #555 and should be fixed in our development branch.  (but the console error message should be just cosmetic, and everything should work anyway).  Please try the fix out on dev by replacing `browserid.org` with `dev.diresworb.org` and confirm that the ugly log message goes away!

Thanks for the report!

**Comment by interactiveblueprints** [comment]
Thanks for answering so quick. What's the state of dev.diresworb.org? Will users be able to migrate from diresworb to browserid?. It's not an appealing option right now to choose for browserid....
Good luck with this wonderful tool!
