### ISSUE TITLE
make sure audience captures full origin

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#82]
scheme and port, in particular.

**Comment by lloyd** [comment]
ok, port is already in there, but it seems like we'll need to make sure we're normalizing (so that foo.com:80 and foo.com match).

I wrote a little library to do that once upon a time: https://github.com/lloyd/urlmatch.js - but I think that's overkill, because we can just use node's libs (normalization is work to be done inside the verifier): http://nodejs.org/docs/v0.4.12/api/url.html

More interesting to me is breaking our external contracts.  Here's my proposal:
1. change our code so that `origin` inside assertions includes scheme://host:port
2. change the verifier so that it handles either a partial origin or a full origin inside the POST request.
3. blog about the migration to full origins
4. wait
5. change the verifier to require scheme

sound sane?

**Comment by benadida** [comment]
the plan sounds very good.
