### ISSUE TITLE
if session expires in the middle of user using it, problems

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#829]
I haven't seen this yet, but I'm guessing that, with the existing session approach and even our new one, we get into trouble if the session expires while the user is using BrowserID. This is probably rare, but can happen because we have a hard expiration time based on when the user loggedin.

**Comment by shane-tomlinson** [comment]
@benadida - this is very very extremely similar to #374, should we merge?

**Comment by shane-tomlinson** [comment]
@benadida - which is also related to #835

**Comment by benadida** [comment]
@shane-tomlinson agreed! Merge as you see fit.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
