### ISSUE TITLE
sporadic test failures in verifier-test

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#833]
apparently when you remove the last char from an assertion, it might still parse ok.  

test failures get five stars!

**Comment by fmarier** [comment]
I've looked into this one a bit because it looked like another problem I was having with certain assertions failing to verify while others were working fine.

My problem turned out to be due to my custom verification script (https://github.com/fmarier/browserid-tools/blob/master/verify-assertion.py) leaving an extra newline character at the end of assertions (I was cat'ing it from a file saved with vi). It would send those off to browserid.org/verify which doesn't trim assertions before base64decoding them and the decoding would fail sometimes but not always.

Anyways, here's how far I got into debugging the sporadic test failure in tests/verifier-test.js:
- it only seems to happen with newstyles bundles when the assertion param ends with 'A'
- we expect to see a failure in sig_verification (jws.js:JWS._verify()) but it passes

I've got a collection of 9 "invalid" assertions that work as expected (i.e. they fail to validate when you remove their last character) and 9 "okay" assertions that fail the test (i.e. they still validate when you remove their last character). I put them here: http://people.debian.org/~francois/browserid_issue833/

**Comment by lloyd** [comment]
@fmarier This is extremely helpful!  thanks for the careful analysis!

@benadida, when the last char of the "crypto segment" of the assertion jws structure is an A, verification still succeeds.  does this base64 correspond to a little endian integer, such that a leading zero doesn't change the value? Why would we even bother encoding a leading zero if my understanding is correct?

**Comment by benadida** [comment]
OK, I finally got to the bottom of this. It's clear if you dig into how base64 encoding works.

It takes 4 base64 characters to encode 3 bytes, because each base64-character encodes 6 bits. A nice alignment graphic is here: https://en.wikipedia.org/wiki/Base64#Padding

We're encoding a 512-bit signature that gives 86 base64 characters (516 bits), where the last 4 bits are 0, which means the last base64 character is always one of our possibilities: A (000000), Q (010000), g (100000), or w (110000). When decoding such values, the 4 extra bits beyond the byte-alignment are ignored. Which means we could actually substitute 
'B', 'C', 'D', any of 15 possibilities for a trailing 'A', and still get a valid sig. Same for the other 3 legal trailing letters for our signature length, each has 15 alternatives whose last 4 bits will be ignored, and thus will yield valid signatures. Btw, if there are 2 extra bits beyond byte alignment, then those 2 bits are also ignored.

HOWEVER, when there are 6 extra bits beyond byte alignment, then base64url-decoding assumes that the 2 missing bits are 0, and fills them in. That's exactly what happens given that our signature length is 512 bits if you chop off the last character: that's 510 bits encoded, so it assumes the last 2 bits are 0. That assumption happens to be valid 25% of the time: chopping off the trailing 'A' chops off 6 0-bits, and the two most significant ones are recovered by the base64url-decoding procedure.

I suppose that, technically, the encoding could see: ahah, I'm about to encode an 'A' as the last char, and the byte alignment is such that decoding can recover. But that's not how the encoding is spec'ed as best as I can tell.

So there you go.

I don't think we should build this knowledge into our tests. Rather, I'm modifying the test to chop off two characters, which should _never_ yield a valid assertion.
