### ISSUE TITLE
reduce the cost of logging

### ISSUE THREAD

**Issue by lloyd** [mozilla/persona#860]
The next step in our performance tuning saga is logging!  If I run loadgen with a target of 3m users locally on a 4 core i5 proc, and bcrypt rounds turned down to 8, I see browserid settle back down to 201M res after 6 minutes on the proc and capable of running 1.87M ADU.

If I perform the exact same test and disable file logging, browserid settles back down to 45M and is capable of 2.1M ADU.

we should figure out a way to reduce the impact of logging on our most performance critical process, and we should do this before we consider clustering the browserid process to distribute compute load.

**Comment by vmunix** [comment]
110% agreed on reducing logging overhead (and in general, our single per-process memory and cpu footprint) before putting the cluster module into play.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
