### ISSUE TITLE
Wrong error message displayed under the described conditions

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#872]
OS: Windows 7
Browser: Firefox 12 (Nightly)

STR:
1. Launch a BrowserID client in the browser (except beta.myfavoriteshow.org).
2. Click on the Sign In button and sign in with an email address already associated to BrowserID.
3. Leave the Sign In dialog with the emails list open.
4. Launch another client in a different browser tab.
5. Click on the Sign In button, then click on the "This is not me..." link.
6. Sign in with a different BrowserID account.
7. Go to the Sign In dialog from step 3, select an email and click on the Sign In button.

The "The selected email is invalid or has been deleted." message is displayed, which is not ordinarily correct since the email is neither invalid nor has it been deleted.

**Comment by zaach** [comment]
Confirmed on 123done.org.

**Comment by shane-tomlinson** [comment]
@zaach - yeah, this will most definitely still be an issue.  The user's authentication cookie will have been reset and their localStorage will have been cleared.

**Comment by callahad** [comment]
Hi! To help us better focus, I'm "closing" all issues that have been open for more than six months. These have been tagged "cleanup-2014" so that we can go back and review them in the future.

For more information, check out this thread: http://thread.gmane.org/gmane.comp.mozilla.identity.devel/7394

If you believe this bug is still a major issue for you, please comment, submit a pull request, or discuss it on our mailing list: https://lists.mozilla.org/listinfo/dev-identity

Sorry for GitHub notification spam!
