### ISSUE TITLE
status.browserid.org

### ISSUE THREAD

**Issue by benadida** [mozilla/persona#896]
get it set up.

**Comment by lloyd** [comment]
Assign to me when folks are on board.  it should look like this somewhat: https://status.heroku.com/

it should syndicate from a twitter account.  and post updates into our IRC room. 

I can build the site on heroku set up custom dns, then going live is a matter of adding a dns record to browserid.org.

**Comment by ozten** [comment]
via email

The status page.  Github, heroku, all the popular services on the interwebs have a status page.  We need a channel that directly communicates service status with sites that depend on us.  We need to be able to give feedback to our most important community members (those who rely on us for auth) about ad-hoc events related to service status.

This may be just a page on heroku or amazon or whatever that is dns mapped to status.browserid.org that folks can visit/follow to understand what's happening _right now_ with browserid, and what events are coming up in the next week that might affect them.

This could be just a simple page that syndicates a twitter account.  The requirement is that it should rely on completely different infrastructure than the browserid service itself, so that we have a means of communicating with folks for whom browserid's servers are not reliable at the moment

**Comment by lloyd** [comment]
taking this

**Comment by lloyd** [comment]
```
12:38 < skinny> lloyd: yah know, if you follow the exact structure of status.github I wouldn't complain. they seem to have thought it out really well

12:40 < skinny> lloyd: if you start with Sandstone CSS, you'll be 90% of the way there in terms of the design.
```

**Comment by lloyd** [comment]
also this: 12:41 < ednapiranha> https://github.com/mozilla/tabzilla

**Comment by skinny97214** [comment]
Lloyd, you're clear for takeoff. I'll come in and wallpaper when it's built and post the CSS like we did with 123done.

**Comment by lloyd** [comment]
Roger, tower.  We,ll aim to get off the ground tomorrow.

--lloyd

**Comment by shane-tomlinson** [comment]
We now have personastatus.org, closing.
