### ISSUE TITLE
make verifier support POST only (turn GET off)

### ISSUE THREAD

**Issue by vthunder** [mozilla/persona#98]
as the title says.

this depends on doing all we can to minimize site breakage.

**Comment by shaver** [comment]
This.

**Comment by lloyd** [comment]
Bump the issue on twitter on monday morning, push a fix on tuesday morning?

**Comment by shaver** [comment]
Yeah, not worth shipping with a warning to bridge, IMO, because people choose when to upgrade.

**Comment by benadida** [comment]
@lloyd after continued thought on this, the right approach here seems to be for us to not log the information, at any layer, rather than encourage an incorrect use of POST (there's no side effect.)

@shaver what do you think?

Also, I'd like to _minimize_ the contract we have with the rest of the world. One endpoint for /verify, not two (/ and /verify). If we support /manage.html, we should redirect to /manage, not serve the file at .html which will cause folks to bookmark the URL and force us to support it forever.

**Comment by benadida** [comment]
so a new wrinkle has come up with the new cert infrastructure. Even though GET is the right web arch approach, our assertions are becoming long enough to start worrying about whether the URL querystring will become too long for certain libraries to handle, especially when we up the keysizes.

So I guess we probably should move to POST as initially proposed, even if the reasons have changed a bit.

Any additional thoughts, @lloyd and @shaver ?

**Comment by lloyd** [comment]
I don't see what you see.  I see about 4% of the requests we got yesterday were GET reqests:

```
lhilaiel@browserid1:/home/browserid/var/log$ zgrep -v ping.txt verifier.log-2011-10-28.gz | wc -l
323
lhilaiel@browserid1:/home/browserid/var/log$ zgrep -v ping.txt verifier.log-2011-10-28.gz | grep GET | wc -l
14
```
