### ISSUE TITLE
browserid doesn't seem to work if 3rd party cookies are disabled

### ISSUE THREAD

**Issue by ghost** [mozilla/persona#982]
I had third-party cookies disabled (like a lot of people will) and got stuck in a loop where I couldn't sign in to myfavoritebeer (either dev or beta) after creating an eyedee.me account.  There was no way to know what the problem was, just an endless signin loop with no indication of a problem -- I just had to guess.  Luckily I eventually guessed right and re-enabled third-party cookies and it worked.

**Comment by shane-tomlinson** [comment]
Thanks @dria.

Related to #835.  835 is for cookies in general disabled, this is 3rd party.  Keeping both open.

**Comment by lloyd** [comment]
thanks @dria!  

plenty of discussion from the dev team starting here:  http://irclog.gr/#show/irc.mozilla.org/identity/48330

We're going to need to figure out how to improve the experience of people with third party cookies disabled, ideally figuring out a way to make things Just Work.  This may involve re-visiting some aspects of the design of primary support.

**Comment by MichaelHackett** [comment]
I just ran into this (using Firefox 11) and was playing with some settings and found that, even with "Accept third-party cookies" enabled, the BrowserID dialog was still reporting that cookies were disabled _unless_ I added an exception for _both_ the originating site and `browserid.org`, or I switch "Keep until:" to something other than "ask me every time". (In the case of `browserid.org`, I'm not even given the opportunity to accept its cookies the first time, if I don't pre-add an exception.)

I realize that it may be less common to have "ask me every time" enabled than it is to have third-party cookies disabled, but the configuration works reasonably well for me for most sites. I would be happy if the test was more fine-grained and/or the error message was more informative (e.g. testing cookies for the originating site and `browserid.org`, and if only one fails, tell me to add an exception for the failing one). I know you don't want to overwhelm less technical users with too much detail, but it's also quite frustrating to be given a solution (e.g. accepting third-party cookies) that doesn't work because an interaction with another setting that you are assuming is set a certain way. Perhaps a link to more details would be a reasonable compromise. Or perhaps the Firefox help screen that comes up could be improved to cover additional scenarios.

**Comment by shane-tomlinson** [comment]
@lloyd - this is a problem on dev.123done.org with third party cookies disabled.  When signing in, the assertion is returned to the RP, the user appears to be signed in and then immediately signed out.

**Comment by lookfirst** [comment]
I think a Safari 5.0.6 on OSX 10.5 user of mine was bitten by this.

**Comment by csuciu** [comment]
Test case added https://moztrap.mozilla.org/manage/caseversion/23757/

**Comment by jaredhirsch** [comment]
As mentioned in the other long-lived 3p cookie bug, work is ongoing right now, but didn't make it into the final train before Beta 2. Bumping to Beta 3.

**Comment by shane-tomlinson** [comment]
We did a ton of work in #3116 to make Persona work with 3rd party cookies disabled, closing.
